.include "macro.inc"

.section .sbss

/* Generated by spimdisasm 1.27.0 */

dlabel D_80075668
/* 65E40 80075668 */ .space 0x04

dlabel g_CutsceneIdx
/* 65E44 8007566C */ .space 0x04

dlabel D_80075670
/* 65E48 80075670 */ .space 0x04

dlabel D_80075674
/* 65E4C 80075674 */ .space 0x04

dlabel D_80075678
/* 65E50 80075678 */ .space 0x04

dlabel D_8007567C
/* 65E54 8007567C */ .space 0x04

dlabel g_CutsceneLayout
/* 65E58 80075680 */ .space 0x04

dlabel D_80075684
/* 65E5C 80075684 */ .space 0x04

dlabel g_PreviousLevelIndex
/* 65E60 80075688 */ .space 0x04

dlabel D_8007568C
/* 65E64 8007568C */ .space 0x04

dlabel g_IsFlightLevel
/* 65E68 80075690 */ .space 0x04

dlabel D_80075694
/* 65E6C 80075694 */ .space 0x04

dlabel D_80075698
/* 65E70 80075698 */ .space 0x04

dlabel D_8007569C
/* 65E74 8007569C */ .space 0x04

dlabel D_800756A0
/* 65E78 800756A0 */ .space 0x04

dlabel D_800756A4
/* 65E7C 800756A4 */ .space 0x04

dlabel D_800756A8
/* 65E80 800756A8 */ .space 0x04

dlabel D_800756AC
/* 65E84 800756AC */ .space 0x04

dlabel D_800756B0
/* 65E88 800756B0 */ .space 0x04

dlabel D_800756B4
/* 65E8C 800756B4 */ .space 0x04

dlabel D_800756B8
/* 65E90 800756B8 */ .space 0x04

dlabel g_UpdateParticle
/* 65E94 800756BC */ .space 0x04

dlabel D_800756C0
/* 65E98 800756C0 */ .space 0x04

dlabel D_800756C4
/* 65E9C 800756C4 */ .space 0x04

dlabel D_800756C8
/* 65EA0 800756C8 */ .space 0x04

dlabel g_DeltaTime
/* 65EA4 800756CC */ .space 0x04

dlabel g_HasLevelTransition
/* 65EA8 800756D0 */ .space 0x04

dlabel D_800756D4
/* 65EAC 800756D4 */ .space 0x04

dlabel g_ActAvailable
/* 65EB0 800756D8 */ .space 0x04

dlabel D_800756DC
/* 65EB4 800756DC */ .space 0x04

dlabel g_CDMaxReadTime
/* 65EB8 800756E0 */ .space 0x04

dlabel D_800756E4
/* 65EBC 800756E4 */ .space 0x04

dlabel D_800756E8
/* 65EC0 800756E8 */ .space 0x08

dlabel D_800756F0
/* 65EC8 800756F0 */ .space 0x04

dlabel D_800756F4
/* 65ECC 800756F4 */ .space 0x04

dlabel g_CreditsTimer
/* 65ED0 800756F8 */ .space 0x04

dlabel D_800756FC
/* 65ED4 800756FC */ .space 0x04

dlabel D_80075700
/* 65ED8 80075700 */ .space 0x04

dlabel g_CreditsStage
/* 65EDC 80075704 */ .space 0x04

dlabel D_80075708
/* 65EE0 80075708 */ .space 0x04

dlabel g_ScreenBorderEnabled
/* 65EE4 8007570C */ .space 0x04

dlabel g_HudMobys
/* 65EE8 80075710 */ .space 0x04

dlabel g_DemoMode
/* 65EEC 80075714 */ .space 0x04

dlabel g_SurfaceBelowFlags
/* 65EF0 80075718 */ .space 0x04

dlabel D_8007571C
/* 65EF4 8007571C */ .space 0x04

/* The index of the selected item in the main pause menu, the options screen, and the post-flight menu */
dlabel D_80075720
/* 65EF8 80075720 */ .space 0x04

dlabel D_80075724
/* 65EFC 80075724 */ .space 0x04

dlabel D_80075728
/* 65F00 80075728 */ .space 0x04

dlabel g_GameTick
/* 65F04 8007572C */ .space 0x04

dlabel D_80075730
/* 65F08 80075730 */ .space 0x04

dlabel g_UpdateMoby
/* 65F0C 80075734 */ .space 0x04

dlabel D_80075738
/* 65F10 80075738 */ .space 0x04

dlabel D_8007573C
/* 65F14 8007573C */ .space 0x04

dlabel D_80075740
/* 65F18 80075740 */ .space 0x04

dlabel D_80075744
/* 65F1C 80075744 */ .space 0x04

dlabel D_80075748
/* 65F20 80075748 */ .space 0x04

dlabel D_8007574C
/* 65F24 8007574C */ .space 0x04

dlabel g_DragonTotal
/* 65F28 80075750 */ .space 0x04

dlabel D_80075754
/* 65F2C 80075754 */ .space 0x04

dlabel D_80075758
/* 65F30 80075758 */ .space 0x04

dlabel D_8007575C
/* 65F34 8007575C */ .space 0x04

dlabel g_UnprocessedFrames
/* 65F38 80075760 */ .space 0x04

dlabel D_80075764
/* 65F3C 80075764 */ .space 0x04

dlabel g_CreditsBuffer
/* 65F40 80075768 */ .space 0x04

dlabel D_8007576C
/* 65F44 8007576C */ .space 0x08

dlabel D_80075774
/* 65F4C 80075774 */ .space 0x04

dlabel D_80075778
/* 65F50 80075778 */ .space 0x04

dlabel D_8007577C
/* 65F54 8007577C */ .space 0x04

dlabel D_80075780
/* 65F58 80075780 */ .space 0x04

dlabel D_80075784
/* 65F5C 80075784 */ .space 0x04

dlabel D_80075788
/* 65F60 80075788 */ .space 0x04

dlabel D_8007578C
/* 65F64 8007578C */ .space 0x04

dlabel D_80075790
/* 65F68 80075790 */ .space 0x04

dlabel D_80075794
/* 65F6C 80075794 */ .space 0x04

dlabel D_80075798
/* 65F70 80075798 */ .space 0x04

dlabel g_StateSwitch
/* 65F74 8007579C */ .space 0x04

dlabel D_800757A0
/* 65F78 800757A0 */ .space 0x04

dlabel g_ActEnabled
/* 65F7C 800757A4 */ .space 0x04

dlabel D_800757A8
/* 65F80 800757A8 */ .space 0x04

dlabel g_CreditsSequence
/* 65F84 800757AC */ .space 0x04

dlabel D_800757B0
/* 65F88 800757B0 */ .space 0x04

dlabel g_MobyPodCount
/* 65F8C 800757B4 */ .space 0x04

dlabel g_DemoIndex
/* 65F90 800757B8 */ .space 0x04

dlabel g_CreditsDataPtr
/* 65F94 800757BC */ .space 0x04

dlabel g_FlightResultsUpdate
/* 65F98 800757C0 */ .space 0x04

dlabel D_800757C4
/* 65F9C 800757C4 */ .space 0x04

/* Boolean, set to 1 when the options submenu is open */
dlabel D_800757C8
/* 65FA0 800757C8 */ .space 0x04

dlabel D_800757CC
/* 65FA4 800757CC */ .space 0x04

dlabel D_800757D0
/* 65FA8 800757D0 */ .space 0x04

dlabel D_800757D4
/* 65FAC 800757D4 */ .space 0x04

dlabel g_Gamestate
/* 65FB0 800757D8 */ .space 0x04

dlabel g_CreditsTotalEntries
/* 65FB4 800757DC */ .space 0x04

dlabel D_800757E0
/* 65FB8 800757E0 */ .space 0x04

dlabel D_800757E4
/* 65FBC 800757E4 */ .space 0x04

dlabel D_800757E8
/* 65FC0 800757E8 */ .space 0x04

dlabel D_800757EC
/* 65FC4 800757EC */ .space 0x04

dlabel D_800757F0
/* 65FC8 800757F0 */ .space 0x04

dlabel D_800757F4
/* 65FCC 800757F4 */ .space 0x04

dlabel g_MobyPods
/* 65FD0 800757F8 */ .space 0x04

dlabel D_800757FC
/* 65FD4 800757FC */ .space 0x04

dlabel D_80075800
/* 65FD8 80075800 */ .space 0x04

dlabel D_80075804
/* 65FDC 80075804 */ .space 0x04

dlabel g_CollisionTriangleIndex
/* 65FE0 80075808 */ .space 0x04

dlabel D_8007580C
/* 65FE4 8007580C */ .space 0x04

dlabel g_EggTotal
/* 65FE8 80075810 */ .space 0x04

dlabel g_IsSpyroHidden
/* 65FEC 80075814 */ .space 0x04

dlabel D_80075818
/* 65FF0 80075818 */ .space 0x04

dlabel g_HudOT
/* 65FF4 8007581C */ .space 0x04

dlabel g_WorldOT
/* 65FF8 80075820 */ .space 0x04

dlabel D_80075824
/* 65FFC 80075824 */ .space 0x04

dlabel g_LevelMobys
/* 66000 80075828 */ .space 0x04

dlabel D_8007582C
/* 66004 8007582C */ .space 0x04

dlabel D_80075830
/* 66008 80075830 */ .space 0x04

dlabel D_80075834
/* 6600C 80075834 */ .space 0x04

dlabel D_80075838
/* 66010 80075838 */ .space 0x04

dlabel D_8007583C
/* 66014 8007583C */ .space 0x04

dlabel D_80075840
/* 66018 80075840 */ .space 0x04

dlabel D_80075844
/* 6601C 80075844 */ .space 0x04

dlabel D_80075848
/* 66020 80075848 */ .space 0x04

dlabel D_8007584C
/* 66024 8007584C */ .space 0x04

dlabel D_80075850
/* 66028 80075850 */ .space 0x04

dlabel D_80075854
/* 6602C 80075854 */ .space 0x04

dlabel D_80075858
/* 66030 80075858 */ .space 0x04

dlabel D_8007585C
/* 66034 8007585C */ .space 0x04

dlabel g_GemTotal
/* 66038 80075860 */ .space 0x04

dlabel g_LoadStage
/* 6603C 80075864 */ .space 0x04

dlabel g_PadMutex
/* 66040 80075868 */ .space 0x08

dlabel D_80075870
/* 66048 80075870 */ .space 0x04

dlabel D_80075874
/* 6604C 80075874 */ .space 0x04

dlabel g_CreditsDisplayedCount
/* 66050 80075878 */ .space 0x04

dlabel D_8007587C
/* 66054 8007587C */ .space 0x04

dlabel g_LevelCheatActive
/* 66058 80075880 */ .space 0x04

dlabel g_DemoFadeTimer
/* 6605C 80075884 */ .space 0x04

dlabel g_CurDB
/* 66060 80075888 */ .space 0x04

dlabel g_CDReadTime
/* 66064 8007588C */ .space 0x04

dlabel D_80075890
/* 66068 80075890 */ .space 0x04

dlabel D_80075894
/* 6606C 80075894 */ .space 0x04

dlabel g_Sparx
/* 66070 80075898 */ .space 0x04

dlabel D_8007589C
/* 66074 8007589C */ .space 0x04

dlabel D_800758A0
/* 66078 800758A0 */ .space 0x04

dlabel g_SavedFairyKissTimer
/* 6607C 800758A4 */ .space 0x04

dlabel D_800758A8
/* 66080 800758A8 */ .space 0x04

dlabel g_PortalLevelId
/* 66084 800758AC */ .space 0x04

dlabel D_800758B0
/* 66088 800758B0 */ .space 0x04

dlabel g_NextLevelId
/* 6608C 800758B4 */ .space 0x04

dlabel D_800758B8
/* 66090 800758B8 */ .space 0x04

dlabel g_PortalCount
/* 66094 800758BC */ .space 0x04

dlabel D_800758C0
/* 66098 800758C0 */ .space 0x04

dlabel D_800758C4
/* 6609C 800758C4 */ .space 0x04

dlabel D_800758C8
/* 660A0 800758C8 */ .space 0x04

dlabel g_SpawnMoby
/* 660A4 800758CC */ .space 0x04

dlabel D_800758D0
/* 660A8 800758D0 */ .space 0x01

dlabel D_800758D1
/* 660A9 800758D1 */ .space 0x01

dlabel D_800758D2
/* 660AA 800758D2 */ .space 0x01

dlabel D_800758D3
/* 660AB 800758D3 */ .space 0x01

dlabel D_800758D4
/* 660AC 800758D4 */ .space 0x01

dlabel D_800758D5
/* 660AD 800758D5 */ .space 0x03

dlabel D_800758D8
/* 660B0 800758D8 */ .space 0x04

dlabel D_800758DC
/* 660B4 800758DC */ .space 0x04

dlabel D_800758E0
/* 660B8 800758E0 */ .space 0x04

dlabel D_800758E4
/* 660BC 800758E4 */ .space 0x04

dlabel D_800758E8
/* 660C0 800758E8 */ .space 0x04

dlabel cheat_HomeworldSelected
/* 660C4 800758EC */ .space 0x04

dlabel cheat_LevelSelected
/* 660C8 800758F0 */ .space 0x04

dlabel D_800758F4
/* 660CC 800758F4 */ .space 0x04

dlabel D_800758F8
/* 660D0 800758F8 */ .space 0x04

dlabel D_800758FC
/* 660D4 800758FC */ .space 0x04

dlabel D_80075900
/* 660D8 80075900 */ .space 0x04

dlabel D_80075904
/* 660DC 80075904 */ .space 0x04

dlabel D_80075908
/* 660E0 80075908 */ .space 0x04

dlabel D_8007590C
/* 660E4 8007590C */ .space 0x04

dlabel D_80075910
/* 660E8 80075910 */ .space 0x04

dlabel D_80075914
/* 660EC 80075914 */ .space 0x04

dlabel g_Fade
/* 660F0 80075918 */ .space 0x04

dlabel g_SkipLowPolyWorld
/* 660F4 8007591C */ .space 0x08

dlabel D_80075924
/* 660FC 80075924 */ .space 0x04

dlabel cheat_InputCounter
/* 66100 80075928 */ .space 0x04

dlabel D_8007592C
/* 66104 8007592C */ .space 0x04

dlabel D_80075930
/* 66108 80075930 */ .space 0x04

dlabel D_80075934
/* 6610C 80075934 */ .space 0x04

dlabel D_80075938
/* 66110 80075938 */ .space 0x04

dlabel D_8007593C
/* 66114 8007593C */ .space 0x04

dlabel D_80075940
/* 66118 80075940 */ .space 0x04

dlabel g_PadSwapFlag
/* 6611C 80075944 */ .space 0x04

dlabel D_80075948
/* 66120 80075948 */ .space 0x08

dlabel D_80075950
/* 66128 80075950 */ .space 0x08

dlabel D_80075958
/* 66130 80075958 */ .space 0x04

dlabel g_Homeworld
/* 66134 8007595C */ .space 0x04

dlabel D_80075960
/* 66138 80075960 */ .space 0x04

dlabel g_LevelIndex
/* 6613C 80075964 */ .space 0x04

dlabel g_CreditsEntryIndex
/* 66140 80075968 */ .space 0x04

dlabel g_LevelId
/* 66144 8007596C */ .space 0x04

dlabel D_80075970
/* 66148 80075970 */ .space 0x08
