.set noat      /* allow manual use of $at */
.set noreorder /* don't insert nops after branches */

.section .rodata.jtbl
.align 3
dlabel jtbl_level_34_8007AC5C
/* 31F5224 8007AC5C B8480880 */ .word .L800848B8_
/* 31F5228 8007AC60 44490880 */ .word .L80084944_
/* 31F522C 8007AC64 CC490880 */ .word .L800849CC_
/* 31F5230 8007AC68 F05E0880 */ .word .Llevel_34_80085EF0
/* 31F5234 8007AC6C F05E0880 */ .word .Llevel_34_80085EF0
/* 31F5238 8007AC70 F05E0880 */ .word .Llevel_34_80085EF0
/* 31F523C 8007AC74 544A0880 */ .word .L80084A54_
/* 31F5240 8007AC78 244B0880 */ .word .L80084B24_
/* 31F5244 8007AC7C BC4B0880 */ .word .L80084BBC_
/* 31F5248 8007AC80 E44D0880 */ .word .L80084DE4_
/* 31F524C 8007AC84 4C4E0880 */ .word .L80084E4C_
/* 31F5250 8007AC88 584F0880 */ .word .L80084F58_
/* 31F5254 8007AC8C 9C4F0880 */ .word .L80084F9C_
/* 31F5258 8007AC90 F05E0880 */ .word .Llevel_34_80085EF0
/* 31F525C 8007AC94 F05E0880 */ .word .Llevel_34_80085EF0
/* 31F5260 8007AC98 F05E0880 */ .word .Llevel_34_80085EF0
/* 31F5264 8007AC9C 10500880 */ .word .L80085010_
/* 31F5268 8007ACA0 94500880 */ .word .L80085094_
/* 31F526C 8007ACA4 F05E0880 */ .word .Llevel_34_80085EF0
/* 31F5270 8007ACA8 F05E0880 */ .word .Llevel_34_80085EF0
/* 31F5274 8007ACAC F05E0880 */ .word .Llevel_34_80085EF0
/* 31F5278 8007ACB0 30510880 */ .word .L80085130_
/* 31F527C 8007ACB4 F05E0880 */ .word .Llevel_34_80085EF0
/* 31F5280 8007ACB8 F05E0880 */ .word .Llevel_34_80085EF0
/* 31F5284 8007ACBC 00520880 */ .word .L80085200_
/* 31F5288 8007ACC0 F05E0880 */ .word .Llevel_34_80085EF0
/* 31F528C 8007ACC4 F05E0880 */ .word .Llevel_34_80085EF0
/* 31F5290 8007ACC8 F05E0880 */ .word .Llevel_34_80085EF0
/* 31F5294 8007ACCC F05E0880 */ .word .Llevel_34_80085EF0
/* 31F5298 8007ACD0 F05E0880 */ .word .Llevel_34_80085EF0
/* 31F529C 8007ACD4 F05E0880 */ .word .Llevel_34_80085EF0
/* 31F52A0 8007ACD8 F05E0880 */ .word .Llevel_34_80085EF0
/* 31F52A4 8007ACDC F05E0880 */ .word .Llevel_34_80085EF0
/* 31F52A8 8007ACE0 38530880 */ .word .L80085338_
/* 31F52AC 8007ACE4 F05E0880 */ .word .Llevel_34_80085EF0
/* 31F52B0 8007ACE8 F05E0880 */ .word .Llevel_34_80085EF0
/* 31F52B4 8007ACEC F05E0880 */ .word .Llevel_34_80085EF0
/* 31F52B8 8007ACF0 F05E0880 */ .word .Llevel_34_80085EF0
/* 31F52BC 8007ACF4 F05E0880 */ .word .Llevel_34_80085EF0
/* 31F52C0 8007ACF8 F05E0880 */ .word .Llevel_34_80085EF0
/* 31F52C4 8007ACFC F05E0880 */ .word .Llevel_34_80085EF0
/* 31F52C8 8007AD00 F05E0880 */ .word .Llevel_34_80085EF0
/* 31F52CC 8007AD04 F05E0880 */ .word .Llevel_34_80085EF0
/* 31F52D0 8007AD08 F05E0880 */ .word .Llevel_34_80085EF0
/* 31F52D4 8007AD0C F05E0880 */ .word .Llevel_34_80085EF0
/* 31F52D8 8007AD10 F05E0880 */ .word .Llevel_34_80085EF0
/* 31F52DC 8007AD14 F05E0880 */ .word .Llevel_34_80085EF0
/* 31F52E0 8007AD18 F05E0880 */ .word .Llevel_34_80085EF0
/* 31F52E4 8007AD1C F05E0880 */ .word .Llevel_34_80085EF0
/* 31F52E8 8007AD20 F05E0880 */ .word .Llevel_34_80085EF0
/* 31F52EC 8007AD24 F05E0880 */ .word .Llevel_34_80085EF0
/* 31F52F0 8007AD28 F05E0880 */ .word .Llevel_34_80085EF0
/* 31F52F4 8007AD2C F05E0880 */ .word .Llevel_34_80085EF0
/* 31F52F8 8007AD30 F05E0880 */ .word .Llevel_34_80085EF0
/* 31F52FC 8007AD34 F05E0880 */ .word .Llevel_34_80085EF0
/* 31F5300 8007AD38 F05E0880 */ .word .Llevel_34_80085EF0
/* 31F5304 8007AD3C F05E0880 */ .word .Llevel_34_80085EF0
/* 31F5308 8007AD40 F05E0880 */ .word .Llevel_34_80085EF0
/* 31F530C 8007AD44 F05E0880 */ .word .Llevel_34_80085EF0
/* 31F5310 8007AD48 F05E0880 */ .word .Llevel_34_80085EF0
/* 31F5314 8007AD4C F05E0880 */ .word .Llevel_34_80085EF0
/* 31F5318 8007AD50 F05E0880 */ .word .Llevel_34_80085EF0
/* 31F531C 8007AD54 F05E0880 */ .word .Llevel_34_80085EF0
/* 31F5320 8007AD58 F05E0880 */ .word .Llevel_34_80085EF0
/* 31F5324 8007AD5C F05E0880 */ .word .Llevel_34_80085EF0
/* 31F5328 8007AD60 E4530880 */ .word .L800853E4_
/* 31F532C 8007AD64 E0540880 */ .word .L800854E0_
/* 31F5330 8007AD68 F05E0880 */ .word .Llevel_34_80085EF0
/* 31F5334 8007AD6C F05E0880 */ .word .Llevel_34_80085EF0
/* 31F5338 8007AD70 F05E0880 */ .word .Llevel_34_80085EF0
/* 31F533C 8007AD74 AC550880 */ .word .L800855AC_
/* 31F5340 8007AD78 98570880 */ .word .L80085798_
/* 31F5344 8007AD7C 0C590880 */ .word .L8008590C_
/* 31F5348 8007AD80 F05E0880 */ .word .Llevel_34_80085EF0
/* 31F534C 8007AD84 F05E0880 */ .word .Llevel_34_80085EF0
/* 31F5350 8007AD88 F05E0880 */ .word .Llevel_34_80085EF0
/* 31F5354 8007AD8C 485A0880 */ .word .L80085A48_
/* 31F5358 8007AD90 F85A0880 */ .word .L80085AF8_
/* 31F535C 8007AD94 DC5B0880 */ .word .L80085BDC_
/* 31F5360 8007AD98 DC5C0880 */ .word .L80085CDC_
/* 31F5364 8007AD9C 045E0880 */ .word .L80085E04_
.size jtbl_level_34_8007AC5C, . - jtbl_level_34_8007AC5C


.section .text
/* Generated by spimdisasm 1.27.0 */

glabel func_level_34_80084830
/* 31FEDF8 80084830 60FFBD27 */  addiu      $sp, $sp, -0xA0
/* 31FEDFC 80084834 8800B4AF */  sw         $s4, 0x88($sp)
/* 31FEE00 80084838 0780143C */  lui        $s4, %hi(D_80075824)
/* 31FEE04 8008483C 2458948E */  lw         $s4, %lo(D_80075824)($s4)
/* 31FEE08 80084840 9000B6AF */  sw         $s6, 0x90($sp)
/* 31FEE0C 80084844 9C00BFAF */  sw         $ra, 0x9C($sp)
/* 31FEE10 80084848 9800BEAF */  sw         $fp, 0x98($sp)
/* 31FEE14 8008484C 9400B7AF */  sw         $s7, 0x94($sp)
/* 31FEE18 80084850 8C00B5AF */  sw         $s5, 0x8C($sp)
/* 31FEE1C 80084854 8400B3AF */  sw         $s3, 0x84($sp)
/* 31FEE20 80084858 8000B2AF */  sw         $s2, 0x80($sp)
/* 31FEE24 8008485C 7C00B1AF */  sw         $s1, 0x7C($sp)
/* 31FEE28 80084860 7800B0AF */  sw         $s0, 0x78($sp)
/* 31FEE2C 80084864 01008392 */  lbu        $v1, 0x1($s4)
/* 31FEE30 80084868 FF000224 */  addiu      $v0, $zero, 0xFF
/* 31FEE34 8008486C A7056210 */  beq        $v1, $v0, .Llevel_34_80085F0C
/* 31FEE38 80084870 21B08000 */   addu      $s6, $a0, $zero
/* 31FEE3C 80084874 80B81600 */  sll        $s7, $s6, 2
/* 31FEE40 80084878 3000A727 */  addiu      $a3, $sp, 0x30
/* 31FEE44 8008487C 6800A7AF */  sw         $a3, 0x68($sp)
/* 31FEE48 80084880 01009126 */  addiu      $s1, $s4, 0x1
/* 31FEE4C 80084884 18009E26 */  addiu      $fp, $s4, 0x18
/* 31FEE50 80084888 04009526 */  addiu      $s5, $s4, 0x4
.Llevel_34_8008488C:
/* 31FEE54 8008488C 00008392 */  lbu        $v1, 0x0($s4)
/* 31FEE58 80084890 00000000 */  nop
/* 31FEE5C 80084894 5100622C */  sltiu      $v0, $v1, 0x51
/* 31FEE60 80084898 95054010 */  beqz       $v0, .Llevel_34_80085EF0
/* 31FEE64 8008489C 80100300 */   sll       $v0, $v1, 2
/* 31FEE68 800848A0 0880013C */  lui        $at, %hi(jtbl_level_34_8007AC5C)
/* 31FEE6C 800848A4 21082200 */  addu       $at, $at, $v0
/* 31FEE70 800848A8 5CAC228C */  lw         $v0, %lo(jtbl_level_34_8007AC5C)($at)
/* 31FEE74 800848AC 00000000 */  nop
/* 31FEE78 800848B0 08004000 */  jr         $v0
/* 31FEE7C 800848B4 00000000 */   nop
.L800848B8_:
/* 31FEE80 800848B8 2120A002 */  addu       $a0, $s5, $zero
/* 31FEE84 800848BC 2128A002 */  addu       $a1, $s5, $zero
/* 31FEE88 800848C0 215F000C */  jal        func_80017C84
/* 31FEE8C 800848C4 2130C003 */   addu      $a2, $fp, $zero
/* 31FEE90 800848C8 1D002286 */  lh         $v0, 0x1D($s1)
/* 31FEE94 800848CC 00000000 */  nop
/* 31FEE98 800848D0 05004010 */  beqz       $v0, .Llevel_34_800848E8
/* 31FEE9C 800848D4 00000000 */   nop
/* 31FEEA0 800848D8 1B002296 */  lhu        $v0, 0x1B($s1)
/* 31FEEA4 800848DC 00000000 */  nop
/* 31FEEA8 800848E0 01004224 */  addiu      $v0, $v0, 0x1
/* 31FEEAC 800848E4 1B0022A6 */  sh         $v0, 0x1B($s1)
.Llevel_34_800848E8:
/* 31FEEB0 800848E8 1D002396 */  lhu        $v1, 0x1D($s1)
/* 31FEEB4 800848EC 01000224 */  addiu      $v0, $zero, 0x1
/* 31FEEB8 800848F0 23104300 */  subu       $v0, $v0, $v1
/* 31FEEBC 800848F4 1D0022A6 */  sh         $v0, 0x1D($s1)
/* 31FEEC0 800848F8 09002292 */  lbu        $v0, 0x9($s1)
/* 31FEEC4 800848FC 40181600 */  sll        $v1, $s6, 1
/* 31FEEC8 80084900 21104300 */  addu       $v0, $v0, $v1
/* 31FEECC 80084904 0C002392 */  lbu        $v1, 0xC($s1)
/* 31FEED0 80084908 090022A2 */  sb         $v0, 0x9($s1)
/* 31FEED4 8008490C 0B002292 */  lbu        $v0, 0xB($s1)
/* 31FEED8 80084910 23187700 */  subu       $v1, $v1, $s7
/* 31FEEDC 80084914 0C0023A2 */  sb         $v1, 0xC($s1)
/* 31FEEE0 80084918 0D002392 */  lbu        $v1, 0xD($s1)
/* 31FEEE4 8008491C 23105700 */  subu       $v0, $v0, $s7
/* 31FEEE8 80084920 0B0022A2 */  sb         $v0, 0xB($s1)
/* 31FEEEC 80084924 01002292 */  lbu        $v0, 0x1($s1)
/* 31FEEF0 80084928 23187700 */  subu       $v1, $v1, $s7
/* 31FEEF4 8008492C 21105600 */  addu       $v0, $v0, $s6
/* 31FEEF8 80084930 010022A2 */  sb         $v0, 0x1($s1)
/* 31FEEFC 80084934 FF004230 */  andi       $v0, $v0, 0xFF
/* 31FEF00 80084938 2000422C */  sltiu      $v0, $v0, 0x20
/* 31FEF04 8008493C B4170208 */  j          .Llevel_34_80085ED0
/* 31FEF08 80084940 0D0023A2 */   sb        $v1, 0xD($s1)
.L80084944_:
/* 31FEF0C 80084944 2120A002 */  addu       $a0, $s5, $zero
/* 31FEF10 80084948 2128A002 */  addu       $a1, $s5, $zero
/* 31FEF14 8008494C 215F000C */  jal        func_80017C84
/* 31FEF18 80084950 2130C003 */   addu      $a2, $fp, $zero
/* 31FEF1C 80084954 1D002286 */  lh         $v0, 0x1D($s1)
/* 31FEF20 80084958 00000000 */  nop
/* 31FEF24 8008495C 06004010 */  beqz       $v0, .Llevel_34_80084978
/* 31FEF28 80084960 01000224 */   addiu     $v0, $zero, 0x1
/* 31FEF2C 80084964 1B002296 */  lhu        $v0, 0x1B($s1)
/* 31FEF30 80084968 00000000 */  nop
/* 31FEF34 8008496C 01004224 */  addiu      $v0, $v0, 0x1
/* 31FEF38 80084970 1B0022A6 */  sh         $v0, 0x1B($s1)
/* 31FEF3C 80084974 01000224 */  addiu      $v0, $zero, 0x1
.Llevel_34_80084978:
/* 31FEF40 80084978 09002392 */  lbu        $v1, 0x9($s1)
/* 31FEF44 8008497C 1D002496 */  lhu        $a0, 0x1D($s1)
/* 31FEF48 80084980 21187700 */  addu       $v1, $v1, $s7
/* 31FEF4C 80084984 090023A2 */  sb         $v1, 0x9($s1)
/* 31FEF50 80084988 0C002392 */  lbu        $v1, 0xC($s1)
/* 31FEF54 8008498C 23104400 */  subu       $v0, $v0, $a0
/* 31FEF58 80084990 1D0022A6 */  sh         $v0, 0x1D($s1)
/* 31FEF5C 80084994 0B002292 */  lbu        $v0, 0xB($s1)
/* 31FEF60 80084998 23187700 */  subu       $v1, $v1, $s7
/* 31FEF64 8008499C 0C0023A2 */  sb         $v1, 0xC($s1)
/* 31FEF68 800849A0 0D002392 */  lbu        $v1, 0xD($s1)
/* 31FEF6C 800849A4 23105700 */  subu       $v0, $v0, $s7
/* 31FEF70 800849A8 0B0022A2 */  sb         $v0, 0xB($s1)
/* 31FEF74 800849AC 01002292 */  lbu        $v0, 0x1($s1)
/* 31FEF78 800849B0 23187700 */  subu       $v1, $v1, $s7
/* 31FEF7C 800849B4 21105600 */  addu       $v0, $v0, $s6
/* 31FEF80 800849B8 010022A2 */  sb         $v0, 0x1($s1)
/* 31FEF84 800849BC FF004230 */  andi       $v0, $v0, 0xFF
/* 31FEF88 800849C0 1800422C */  sltiu      $v0, $v0, 0x18
/* 31FEF8C 800849C4 B4170208 */  j          .Llevel_34_80085ED0
/* 31FEF90 800849C8 0D0023A2 */   sb        $v1, 0xD($s1)
.L800849CC_:
/* 31FEF94 800849CC 2120A002 */  addu       $a0, $s5, $zero
/* 31FEF98 800849D0 2128A002 */  addu       $a1, $s5, $zero
/* 31FEF9C 800849D4 215F000C */  jal        func_80017C84
/* 31FEFA0 800849D8 2130C003 */   addu      $a2, $fp, $zero
/* 31FEFA4 800849DC 1D002286 */  lh         $v0, 0x1D($s1)
/* 31FEFA8 800849E0 00000000 */  nop
/* 31FEFAC 800849E4 06004010 */  beqz       $v0, .Llevel_34_80084A00
/* 31FEFB0 800849E8 01000224 */   addiu     $v0, $zero, 0x1
/* 31FEFB4 800849EC 1B002296 */  lhu        $v0, 0x1B($s1)
/* 31FEFB8 800849F0 00000000 */  nop
/* 31FEFBC 800849F4 01004224 */  addiu      $v0, $v0, 0x1
/* 31FEFC0 800849F8 1B0022A6 */  sh         $v0, 0x1B($s1)
/* 31FEFC4 800849FC 01000224 */  addiu      $v0, $zero, 0x1
.Llevel_34_80084A00:
/* 31FEFC8 80084A00 09002392 */  lbu        $v1, 0x9($s1)
/* 31FEFCC 80084A04 1D002496 */  lhu        $a0, 0x1D($s1)
/* 31FEFD0 80084A08 21187700 */  addu       $v1, $v1, $s7
/* 31FEFD4 80084A0C 090023A2 */  sb         $v1, 0x9($s1)
/* 31FEFD8 80084A10 0C002392 */  lbu        $v1, 0xC($s1)
/* 31FEFDC 80084A14 23104400 */  subu       $v0, $v0, $a0
/* 31FEFE0 80084A18 1D0022A6 */  sh         $v0, 0x1D($s1)
/* 31FEFE4 80084A1C 0B002292 */  lbu        $v0, 0xB($s1)
/* 31FEFE8 80084A20 23187700 */  subu       $v1, $v1, $s7
/* 31FEFEC 80084A24 0C0023A2 */  sb         $v1, 0xC($s1)
/* 31FEFF0 80084A28 0D002392 */  lbu        $v1, 0xD($s1)
/* 31FEFF4 80084A2C 23105700 */  subu       $v0, $v0, $s7
/* 31FEFF8 80084A30 0B0022A2 */  sb         $v0, 0xB($s1)
/* 31FEFFC 80084A34 01002292 */  lbu        $v0, 0x1($s1)
/* 31FF000 80084A38 23187700 */  subu       $v1, $v1, $s7
/* 31FF004 80084A3C 21105600 */  addu       $v0, $v0, $s6
/* 31FF008 80084A40 010022A2 */  sb         $v0, 0x1($s1)
/* 31FF00C 80084A44 FF004230 */  andi       $v0, $v0, 0xFF
/* 31FF010 80084A48 2000422C */  sltiu      $v0, $v0, 0x20
/* 31FF014 80084A4C B4170208 */  j          .Llevel_34_80085ED0
/* 31FF018 80084A50 0D0023A2 */   sb        $v1, 0xD($s1)
.L80084A54_:
/* 31FF01C 80084A54 1700258E */  lw         $a1, 0x17($s1)
/* 31FF020 80084A58 C05D000C */  jal        VecCopy
/* 31FF024 80084A5C 1000A427 */   addiu     $a0, $sp, 0x10
/* 31FF028 80084A60 01002292 */  lbu        $v0, 0x1($s1)
/* 31FF02C 80084A64 00000000 */  nop
/* 31FF030 80084A68 80810200 */  sll        $s0, $v0, 6
/* 31FF034 80084A6C 1D002286 */  lh         $v0, 0x1D($s1)
/* 31FF038 80084A70 1800A38F */  lw         $v1, 0x18($sp)
/* 31FF03C 80084A74 80110200 */  sll        $v0, $v0, 6
/* 31FF040 80084A78 21986200 */  addu       $s3, $v1, $v0
/* 31FF044 80084A7C 1B002386 */  lh         $v1, 0x1B($s1)
/* 31FF048 80084A80 00000000 */  nop
/* 31FF04C 80084A84 2A107000 */  slt        $v0, $v1, $s0
/* 31FF050 80084A88 02004010 */  beqz       $v0, .Llevel_34_80084A94
/* 31FF054 80084A8C 21900002 */   addu      $s2, $s0, $zero
/* 31FF058 80084A90 21806000 */  addu       $s0, $v1, $zero
.Llevel_34_80084A94:
/* 31FF05C 80084A94 2C5B000C */  jal        Cos
/* 31FF060 80084A98 21204002 */   addu      $a0, $s2, $zero
/* 31FF064 80084A9C 18000202 */  mult       $s0, $v0
/* 31FF068 80084AA0 21204002 */  addu       $a0, $s2, $zero
/* 31FF06C 80084AA4 1000A28F */  lw         $v0, 0x10($sp)
/* 31FF070 80084AA8 12380000 */  mflo       $a3
/* 31FF074 80084AAC 031B0700 */  sra        $v1, $a3, 12
/* 31FF078 80084AB0 21104300 */  addu       $v0, $v0, $v1
/* 31FF07C 80084AB4 165B000C */  jal        Sin
/* 31FF080 80084AB8 1000A2AF */   sw        $v0, 0x10($sp)
/* 31FF084 80084ABC 18000202 */  mult       $s0, $v0
/* 31FF088 80084AC0 1400A28F */  lw         $v0, 0x14($sp)
/* 31FF08C 80084AC4 12380000 */  mflo       $a3
/* 31FF090 80084AC8 031B0700 */  sra        $v1, $a3, 12
/* 31FF094 80084ACC 21104300 */  addu       $v0, $v0, $v1
/* 31FF098 80084AD0 1400A2AF */  sw         $v0, 0x14($sp)
/* 31FF09C 80084AD4 07002286 */  lh         $v0, 0x7($s1)
/* 31FF0A0 80084AD8 00000000 */  nop
/* 31FF0A4 80084ADC 80100200 */  sll        $v0, $v0, 2
/* 31FF0A8 80084AE0 40004224 */  addiu      $v0, $v0, 0x40
/* 31FF0AC 80084AE4 1800A2AF */  sw         $v0, 0x18($sp)
/* 31FF0B0 80084AE8 2A106202 */  slt        $v0, $s3, $v0
/* 31FF0B4 80084AEC FE044014 */  bnez       $v0, .Llevel_34_80085EE8
/* 31FF0B8 80084AF0 00000000 */   nop
/* 31FF0BC 80084AF4 01002292 */  lbu        $v0, 0x1($s1)
/* 31FF0C0 80084AF8 00000000 */  nop
/* 31FF0C4 80084AFC C900422C */  sltiu      $v0, $v0, 0xC9
/* 31FF0C8 80084B00 F9044010 */  beqz       $v0, .Llevel_34_80085EE8
/* 31FF0CC 80084B04 2120A002 */   addu      $a0, $s5, $zero
/* 31FF0D0 80084B08 FF5E000C */  jal        func_80017BFC
/* 31FF0D4 80084B0C 1000A527 */   addiu     $a1, $sp, 0x10
/* 31FF0D8 80084B10 01002292 */  lbu        $v0, 0x1($s1)
/* 31FF0DC 80084B14 00000000 */  nop
/* 31FF0E0 80084B18 01004224 */  addiu      $v0, $v0, 0x1
/* 31FF0E4 80084B1C BC170208 */  j          .Llevel_34_80085EF0
/* 31FF0E8 80084B20 010022A2 */   sb        $v0, 0x1($s1)
.L80084B24_:
/* 31FF0EC 80084B24 01002292 */  lbu        $v0, 0x1($s1)
/* 31FF0F0 80084B28 00000000 */  nop
/* 31FF0F4 80084B2C 1900422C */  sltiu      $v0, $v0, 0x19
/* 31FF0F8 80084B30 ED044010 */  beqz       $v0, .Llevel_34_80085EE8
/* 31FF0FC 80084B34 00000000 */   nop
/* 31FF100 80084B38 02002292 */  lbu        $v0, 0x2($s1)
/* 31FF104 80084B3C 00000000 */  nop
/* 31FF108 80084B40 E9044010 */  beqz       $v0, .Llevel_34_80085EE8
/* 31FF10C 80084B44 00000000 */   nop
/* 31FF110 80084B48 0A002292 */  lbu        $v0, 0xA($s1)
/* 31FF114 80084B4C 1D002392 */  lbu        $v1, 0x1D($s1)
/* 31FF118 80084B50 01002492 */  lbu        $a0, 0x1($s1)
/* 31FF11C 80084B54 21104300 */  addu       $v0, $v0, $v1
/* 31FF120 80084B58 0A0022A2 */  sb         $v0, 0xA($s1)
/* 31FF124 80084B5C 0D00822C */  sltiu      $v0, $a0, 0xD
/* 31FF128 80084B60 04004014 */  bnez       $v0, .Llevel_34_80084B74
/* 31FF12C 80084B64 18000224 */   addiu     $v0, $zero, 0x18
/* 31FF130 80084B68 23104400 */  subu       $v0, $v0, $a0
/* 31FF134 80084B6C DE120208 */  j          .Llevel_34_80084B78
/* 31FF138 80084B70 80100200 */   sll       $v0, $v0, 2
.Llevel_34_80084B74:
/* 31FF13C 80084B74 80100400 */  sll        $v0, $a0, 2
.Llevel_34_80084B78:
/* 31FF140 80084B78 090022A2 */  sb         $v0, 0x9($s1)
/* 31FF144 80084B7C 03002296 */  lhu        $v0, 0x3($s1)
/* 31FF148 80084B80 01002692 */  lbu        $a2, 0x1($s1)
/* 31FF14C 80084B84 17002396 */  lhu        $v1, 0x17($s1)
/* 31FF150 80084B88 19002496 */  lhu        $a0, 0x19($s1)
/* 31FF154 80084B8C 1B002596 */  lhu        $a1, 0x1B($s1)
/* 31FF158 80084B90 21104300 */  addu       $v0, $v0, $v1
/* 31FF15C 80084B94 030022A6 */  sh         $v0, 0x3($s1)
/* 31FF160 80084B98 05002296 */  lhu        $v0, 0x5($s1)
/* 31FF164 80084B9C 07002396 */  lhu        $v1, 0x7($s1)
/* 31FF168 80084BA0 0100C624 */  addiu      $a2, $a2, 0x1
/* 31FF16C 80084BA4 010026A2 */  sb         $a2, 0x1($s1)
/* 31FF170 80084BA8 21104400 */  addu       $v0, $v0, $a0
/* 31FF174 80084BAC 21186500 */  addu       $v1, $v1, $a1
/* 31FF178 80084BB0 050022A6 */  sh         $v0, 0x5($s1)
/* 31FF17C 80084BB4 BC170208 */  j          .Llevel_34_80085EF0
/* 31FF180 80084BB8 070023A6 */   sh        $v1, 0x7($s1)
.L80084BBC_:
/* 31FF184 80084BBC 2000A427 */  addiu      $a0, $sp, 0x20
/* 31FF188 80084BC0 095F000C */  jal        func_80017C24
/* 31FF18C 80084BC4 2128A002 */   addu      $a1, $s5, $zero
/* 31FF190 80084BC8 02002292 */  lbu        $v0, 0x2($s1)
/* 31FF194 80084BCC 00000000 */  nop
/* 31FF198 80084BD0 C5044010 */  beqz       $v0, .Llevel_34_80085EE8
/* 31FF19C 80084BD4 00000000 */   nop
/* 31FF1A0 80084BD8 1D002392 */  lbu        $v1, 0x1D($s1)
/* 31FF1A4 80084BDC 6800A48F */  lw         $a0, 0x68($sp)
/* 31FF1A8 80084BE0 0780053C */  lui        $a1, %hi(g_LevelMobys)
/* 31FF1AC 80084BE4 2858A58C */  lw         $a1, %lo(g_LevelMobys)($a1)
/* 31FF1B0 80084BE8 40100300 */  sll        $v0, $v1, 1
/* 31FF1B4 80084BEC 21104300 */  addu       $v0, $v0, $v1
/* 31FF1B8 80084BF0 80100200 */  sll        $v0, $v0, 2
/* 31FF1BC 80084BF4 23104300 */  subu       $v0, $v0, $v1
/* 31FF1C0 80084BF8 C0100200 */  sll        $v0, $v0, 3
/* 31FF1C4 80084BFC 2128A200 */  addu       $a1, $a1, $v0
/* 31FF1C8 80084C00 C05D000C */  jal        VecCopy
/* 31FF1CC 80084C04 0C00A524 */   addiu     $a1, $a1, 0xC
/* 31FF1D0 80084C08 01002492 */  lbu        $a0, 0x1($s1)
/* 31FF1D4 80084C0C 2C5B000C */  jal        Cos
/* 31FF1D8 80084C10 C0210400 */   sll       $a0, $a0, 7
/* 31FF1DC 80084C14 3000A38F */  lw         $v1, 0x30($sp)
/* 31FF1E0 80084C18 43100200 */  sra        $v0, $v0, 1
/* 31FF1E4 80084C1C 21186200 */  addu       $v1, $v1, $v0
/* 31FF1E8 80084C20 3000A3AF */  sw         $v1, 0x30($sp)
/* 31FF1EC 80084C24 01002492 */  lbu        $a0, 0x1($s1)
/* 31FF1F0 80084C28 165B000C */  jal        Sin
/* 31FF1F4 80084C2C C0210400 */   sll       $a0, $a0, 7
/* 31FF1F8 80084C30 3400A38F */  lw         $v1, 0x34($sp)
/* 31FF1FC 80084C34 43100200 */  sra        $v0, $v0, 1
/* 31FF200 80084C38 21186200 */  addu       $v1, $v1, $v0
/* 31FF204 80084C3C 3400A3AF */  sw         $v1, 0x34($sp)
/* 31FF208 80084C40 01002492 */  lbu        $a0, 0x1($s1)
/* 31FF20C 80084C44 00000000 */  nop
/* 31FF210 80084C48 C0210400 */  sll        $a0, $a0, 7
/* 31FF214 80084C4C 2C5B000C */  jal        Cos
/* 31FF218 80084C50 00FF8424 */   addiu     $a0, $a0, -0x100
/* 31FF21C 80084C54 2000B027 */  addiu      $s0, $sp, 0x20
/* 31FF220 80084C58 21300002 */  addu       $a2, $s0, $zero
/* 31FF224 80084C5C 83100200 */  sra        $v0, $v0, 2
/* 31FF228 80084C60 6800A48F */  lw         $a0, 0x68($sp)
/* 31FF22C 80084C64 3800A38F */  lw         $v1, 0x38($sp)
/* 31FF230 80084C68 6800A58F */  lw         $a1, 0x68($sp)
/* 31FF234 80084C6C 21186200 */  addu       $v1, $v1, $v0
/* 31FF238 80084C70 E35D000C */  jal        VecSub
/* 31FF23C 80084C74 3800A3AF */   sw        $v1, 0x38($sp)
/* 31FF240 80084C78 6800A48F */  lw         $a0, 0x68($sp)
/* 31FF244 80084C7C 7F5C000C */  jal        VecMagnitude
/* 31FF248 80084C80 01000524 */   addiu     $a1, $zero, 0x1
/* 31FF24C 80084C84 21284000 */  addu       $a1, $v0, $zero
/* 31FF250 80084C88 0104A228 */  slti       $v0, $a1, 0x401
/* 31FF254 80084C8C 96044014 */  bnez       $v0, .Llevel_34_80085EE8
/* 31FF258 80084C90 00000000 */   nop
/* 31FF25C 80084C94 01002292 */  lbu        $v0, 0x1($s1)
/* 31FF260 80084C98 00000000 */  nop
/* 31FF264 80084C9C 4100422C */  sltiu      $v0, $v0, 0x41
/* 31FF268 80084CA0 91044010 */  beqz       $v0, .Llevel_34_80085EE8
/* 31FF26C 80084CA4 00000000 */   nop
/* 31FF270 80084CA8 6800A48F */  lw         $a0, 0x68($sp)
/* 31FF274 80084CAC 6E5D000C */  jal        VecScaleToLength
/* 31FF278 80084CB0 80000624 */   addiu     $a2, $zero, 0x80
/* 31FF27C 80084CB4 21200002 */  addu       $a0, $s0, $zero
/* 31FF280 80084CB8 6800A68F */  lw         $a2, 0x68($sp)
/* 31FF284 80084CBC D65D000C */  jal        VecAdd
/* 31FF288 80084CC0 21280002 */   addu      $a1, $s0, $zero
/* 31FF28C 80084CC4 2120A002 */  addu       $a0, $s5, $zero
/* 31FF290 80084CC8 FF5E000C */  jal        func_80017BFC
/* 31FF294 80084CCC 21280002 */   addu      $a1, $s0, $zero
/* 31FF298 80084CD0 3000A427 */  addiu      $a0, $sp, 0x30
/* 31FF29C 80084CD4 2000A527 */  addiu      $a1, $sp, 0x20
/* 31FF2A0 80084CD8 01002292 */  lbu        $v0, 0x1($s1)
/* 31FF2A4 80084CDC 0780063C */  lui        $a2, %hi(g_Camera + 0x28)
/* 31FF2A8 80084CE0 F86DC624 */  addiu      $a2, $a2, %lo(g_Camera + 0x28)
/* 31FF2AC 80084CE4 01004224 */  addiu      $v0, $v0, 0x1
/* 31FF2B0 80084CE8 E35D000C */  jal        VecSub
/* 31FF2B4 80084CEC 010022A2 */   sb        $v0, 0x1($s1)
/* 31FF2B8 80084CF0 3000A48F */  lw         $a0, 0x30($sp)
/* 31FF2BC 80084CF4 3400A38F */  lw         $v1, 0x34($sp)
/* 31FF2C0 80084CF8 3800A28F */  lw         $v0, 0x38($sp)
/* 31FF2C4 80084CFC 02008104 */  bgez       $a0, .Llevel_34_80084D08
/* 31FF2C8 80084D00 00000000 */   nop
/* 31FF2CC 80084D04 23200400 */  negu       $a0, $a0
.Llevel_34_80084D08:
/* 31FF2D0 80084D08 02006104 */  bgez       $v1, .Llevel_34_80084D14
/* 31FF2D4 80084D0C 00000000 */   nop
/* 31FF2D8 80084D10 23180300 */  negu       $v1, $v1
.Llevel_34_80084D14:
/* 31FF2DC 80084D14 21208300 */  addu       $a0, $a0, $v1
/* 31FF2E0 80084D18 02004104 */  bgez       $v0, .Llevel_34_80084D24
/* 31FF2E4 80084D1C 00000000 */   nop
/* 31FF2E8 80084D20 23100200 */  negu       $v0, $v0
.Llevel_34_80084D24:
/* 31FF2EC 80084D24 21288200 */  addu       $a1, $a0, $v0
/* 31FF2F0 80084D28 00002392 */  lbu        $v1, 0x0($s1)
/* 31FF2F4 80084D2C 03000224 */  addiu      $v0, $zero, 0x3
/* 31FF2F8 80084D30 12006214 */  bne        $v1, $v0, .Llevel_34_80084D7C
/* 31FF2FC 80084D34 0028A228 */   slti      $v0, $a1, 0x2800
/* 31FF300 80084D38 0130A228 */  slti       $v0, $a1, 0x3001
/* 31FF304 80084D3C 6C044014 */  bnez       $v0, .Llevel_34_80085EF0
/* 31FF308 80084D40 04000224 */   addiu     $v0, $zero, 0x4
/* 31FF30C 80084D44 0B002392 */  lbu        $v1, 0xB($s1)
/* 31FF310 80084D48 090022A2 */  sb         $v0, 0x9($s1)
/* 31FF314 80084D4C 40000224 */  addiu      $v0, $zero, 0x40
/* 31FF318 80084D50 0E0022A2 */  sb         $v0, 0xE($s1)
/* 31FF31C 80084D54 0C002292 */  lbu        $v0, 0xC($s1)
/* 31FF320 80084D58 000020A2 */  sb         $zero, 0x0($s1)
/* 31FF324 80084D5C 40200300 */  sll        $a0, $v1, 1
/* 31FF328 80084D60 0D002392 */  lbu        $v1, 0xD($s1)
/* 31FF32C 80084D64 40100200 */  sll        $v0, $v0, 1
/* 31FF330 80084D68 0B0024A2 */  sb         $a0, 0xB($s1)
/* 31FF334 80084D6C 0C0022A2 */  sb         $v0, 0xC($s1)
/* 31FF338 80084D70 40180300 */  sll        $v1, $v1, 1
/* 31FF33C 80084D74 BC170208 */  j          .Llevel_34_80085EF0
/* 31FF340 80084D78 0D0023A2 */   sb        $v1, 0xD($s1)
.Llevel_34_80084D7C:
/* 31FF344 80084D7C 5C044010 */  beqz       $v0, .Llevel_34_80085EF0
/* 31FF348 80084D80 03000224 */   addiu     $v0, $zero, 0x3
/* 31FF34C 80084D84 0B002392 */  lbu        $v1, 0xB($s1)
/* 31FF350 80084D88 000022A2 */  sb         $v0, 0x0($s1)
/* 31FF354 80084D8C 04000224 */  addiu      $v0, $zero, 0x4
/* 31FF358 80084D90 100022A2 */  sb         $v0, 0x10($s1)
/* 31FF35C 80084D94 2C000224 */  addiu      $v0, $zero, 0x2C
/* 31FF360 80084D98 0E0022A2 */  sb         $v0, 0xE($s1)
/* 31FF364 80084D9C 0C002292 */  lbu        $v0, 0xC($s1)
/* 31FF368 80084DA0 0F0020A2 */  sb         $zero, 0xF($s1)
/* 31FF36C 80084DA4 42200300 */  srl        $a0, $v1, 1
/* 31FF370 80084DA8 0D002392 */  lbu        $v1, 0xD($s1)
/* 31FF374 80084DAC 42100200 */  srl        $v0, $v0, 1
/* 31FF378 80084DB0 0B0024A2 */  sb         $a0, 0xB($s1)
/* 31FF37C 80084DB4 0C0022A2 */  sb         $v0, 0xC($s1)
/* 31FF380 80084DB8 42180300 */  srl        $v1, $v1, 1
/* 31FF384 80084DBC CB89010C */  jal        rand
/* 31FF388 80084DC0 0D0023A2 */   sb        $v1, 0xD($s1)
/* 31FF38C 80084DC4 0F004230 */  andi       $v0, $v0, 0xF
/* 31FF390 80084DC8 18004224 */  addiu      $v0, $v0, 0x18
/* 31FF394 80084DCC CB89010C */  jal        rand
/* 31FF398 80084DD0 090022A2 */   sb        $v0, 0x9($s1)
/* 31FF39C 80084DD4 07004230 */  andi       $v0, $v0, 0x7
/* 31FF3A0 80084DD8 0F004224 */  addiu      $v0, $v0, 0xF
/* 31FF3A4 80084DDC BC170208 */  j          .Llevel_34_80085EF0
/* 31FF3A8 80084DE0 0A0022A2 */   sb        $v0, 0xA($s1)
.L80084DE4_:
/* 31FF3AC 80084DE4 2120A002 */  addu       $a0, $s5, $zero
/* 31FF3B0 80084DE8 2128A002 */  addu       $a1, $s5, $zero
/* 31FF3B4 80084DEC 215F000C */  jal        func_80017C84
/* 31FF3B8 80084DF0 2130C003 */   addu      $a2, $fp, $zero
/* 31FF3BC 80084DF4 1D002286 */  lh         $v0, 0x1D($s1)
/* 31FF3C0 80084DF8 00000000 */  nop
/* 31FF3C4 80084DFC 05004010 */  beqz       $v0, .Llevel_34_80084E14
/* 31FF3C8 80084E00 00000000 */   nop
/* 31FF3CC 80084E04 1B002296 */  lhu        $v0, 0x1B($s1)
/* 31FF3D0 80084E08 00000000 */  nop
/* 31FF3D4 80084E0C 01004224 */  addiu      $v0, $v0, 0x1
/* 31FF3D8 80084E10 1B0022A6 */  sh         $v0, 0x1B($s1)
.Llevel_34_80084E14:
/* 31FF3DC 80084E14 1D002396 */  lhu        $v1, 0x1D($s1)
/* 31FF3E0 80084E18 01000224 */  addiu      $v0, $zero, 0x1
/* 31FF3E4 80084E1C 23104300 */  subu       $v0, $v0, $v1
/* 31FF3E8 80084E20 09002392 */  lbu        $v1, 0x9($s1)
/* 31FF3EC 80084E24 40201600 */  sll        $a0, $s6, 1
/* 31FF3F0 80084E28 1D0022A6 */  sh         $v0, 0x1D($s1)
/* 31FF3F4 80084E2C 01002292 */  lbu        $v0, 0x1($s1)
/* 31FF3F8 80084E30 21186400 */  addu       $v1, $v1, $a0
/* 31FF3FC 80084E34 21105600 */  addu       $v0, $v0, $s6
/* 31FF400 80084E38 010022A2 */  sb         $v0, 0x1($s1)
/* 31FF404 80084E3C FF004230 */  andi       $v0, $v0, 0xFF
/* 31FF408 80084E40 2000422C */  sltiu      $v0, $v0, 0x20
/* 31FF40C 80084E44 B4170208 */  j          .Llevel_34_80085ED0
/* 31FF410 80084E48 090023A2 */   sb        $v1, 0x9($s1)
.L80084E4C_:
/* 31FF414 80084E4C 0880033C */  lui        $v1, %hi(g_Spyro + 0x78)
/* 31FF418 80084E50 D08A638C */  lw         $v1, %lo(g_Spyro + 0x78)($v1)
/* 31FF41C 80084E54 1D000224 */  addiu      $v0, $zero, 0x1D
/* 31FF420 80084E58 06006214 */  bne        $v1, $v0, .Llevel_34_80084E74
/* 31FF424 80084E5C 00000000 */   nop
/* 31FF428 80084E60 0880023C */  lui        $v0, %hi(g_Spyro + 0x164)
/* 31FF42C 80084E64 BC8B428C */  lw         $v0, %lo(g_Spyro + 0x164)($v0)
/* 31FF430 80084E68 00000000 */  nop
/* 31FF434 80084E6C 1E044004 */  bltz       $v0, .Llevel_34_80085EE8
/* 31FF438 80084E70 00000000 */   nop
.Llevel_34_80084E74:
/* 31FF43C 80084E74 0780023C */  lui        $v0, %hi(g_IsSpyroHidden)
/* 31FF440 80084E78 1458428C */  lw         $v0, %lo(g_IsSpyroHidden)($v0)
/* 31FF444 80084E7C 00000000 */  nop
/* 31FF448 80084E80 19044014 */  bnez       $v0, .Llevel_34_80085EE8
/* 31FF44C 80084E84 00000000 */   nop
/* 31FF450 80084E88 0880053C */  lui        $a1, %hi(g_Spyro + 0x160)
/* 31FF454 80084E8C B88BA524 */  addiu      $a1, $a1, %lo(g_Spyro + 0x160)
/* 31FF458 80084E90 0000A28C */  lw         $v0, 0x0($a1)
/* 31FF45C 80084E94 00000000 */  nop
/* 31FF460 80084E98 13044018 */  blez       $v0, .Llevel_34_80085EE8
/* 31FF464 80084E9C 4000B027 */   addiu     $s0, $sp, 0x40
/* 31FF468 80084EA0 21200002 */  addu       $a0, $s0, $zero
/* 31FF46C 80084EA4 C05D000C */  jal        VecCopy
/* 31FF470 80084EA8 A0FEA524 */   addiu     $a1, $a1, -0x160
/* 31FF474 80084EAC 17002486 */  lh         $a0, 0x17($s1)
/* 31FF478 80084EB0 2C5B000C */  jal        Cos
/* 31FF47C 80084EB4 00000000 */   nop
/* 31FF480 80084EB8 4000A38F */  lw         $v1, 0x40($sp)
/* 31FF484 80084EBC 03110200 */  sra        $v0, $v0, 4
/* 31FF488 80084EC0 21186200 */  addu       $v1, $v1, $v0
/* 31FF48C 80084EC4 4000A3AF */  sw         $v1, 0x40($sp)
/* 31FF490 80084EC8 17002486 */  lh         $a0, 0x17($s1)
/* 31FF494 80084ECC 165B000C */  jal        Sin
/* 31FF498 80084ED0 00000000 */   nop
/* 31FF49C 80084ED4 2120A002 */  addu       $a0, $s5, $zero
/* 31FF4A0 80084ED8 21280002 */  addu       $a1, $s0, $zero
/* 31FF4A4 80084EDC 03110200 */  sra        $v0, $v0, 4
/* 31FF4A8 80084EE0 4400A38F */  lw         $v1, 0x44($sp)
/* 31FF4AC 80084EE4 4800A68F */  lw         $a2, 0x48($sp)
/* 31FF4B0 80084EE8 21186200 */  addu       $v1, $v1, $v0
/* 31FF4B4 80084EEC 0001C624 */  addiu      $a2, $a2, 0x100
/* 31FF4B8 80084EF0 4400A3AF */  sw         $v1, 0x44($sp)
/* 31FF4BC 80084EF4 FF5E000C */  jal        func_80017BFC
/* 31FF4C0 80084EF8 4800A6AF */   sw        $a2, 0x48($sp)
/* 31FF4C4 80084EFC 17002496 */  lhu        $a0, 0x17($s1)
/* 31FF4C8 80084F00 00000000 */  nop
/* 31FF4CC 80084F04 40008424 */  addiu      $a0, $a0, 0x40
/* 31FF4D0 80084F08 170024A6 */  sh         $a0, 0x17($s1)
/* 31FF4D4 80084F0C 00240400 */  sll        $a0, $a0, 16
/* 31FF4D8 80084F10 0780023C */  lui        $v0, %hi(g_Camera + 0x50)
/* 31FF4DC 80084F14 206E4284 */  lh         $v0, %lo(g_Camera + 0x50)($v0)
/* 31FF4E0 80084F18 03240400 */  sra        $a0, $a0, 16
/* 31FF4E4 80084F1C 23208200 */  subu       $a0, $a0, $v0
/* 31FF4E8 80084F20 2C5B000C */  jal        Cos
/* 31FF4EC 80084F24 FF0F8430 */   andi      $a0, $a0, 0xFFF
/* 31FF4F0 80084F28 6060033C */  lui        $v1, (0x60606061 >> 16)
/* 31FF4F4 80084F2C 61606334 */  ori        $v1, $v1, (0x60606061 & 0xFFFF)
/* 31FF4F8 80084F30 02004104 */  bgez       $v0, .Llevel_34_80084F3C
/* 31FF4FC 80084F34 00000000 */   nop
/* 31FF500 80084F38 23100200 */  negu       $v0, $v0
.Llevel_34_80084F3C:
/* 31FF504 80084F3C 18004300 */  mult       $v0, $v1
/* 31FF508 80084F40 C3170200 */  sra        $v0, $v0, 31
/* 31FF50C 80084F44 10380000 */  mfhi       $a3
/* 31FF510 80084F48 83190700 */  sra        $v1, $a3, 6
/* 31FF514 80084F4C 23186200 */  subu       $v1, $v1, $v0
/* 31FF518 80084F50 BC170208 */  j          .Llevel_34_80085EF0
/* 31FF51C 80084F54 090023A2 */   sb        $v1, 0x9($s1)
.L80084F58_:
/* 31FF520 80084F58 2120A002 */  addu       $a0, $s5, $zero
/* 31FF524 80084F5C 2128A002 */  addu       $a1, $s5, $zero
/* 31FF528 80084F60 215F000C */  jal        func_80017C84
/* 31FF52C 80084F64 12008626 */   addiu     $a2, $s4, 0x12
/* 31FF530 80084F68 0B002292 */  lbu        $v0, 0xB($s1)
/* 31FF534 80084F6C 0C002392 */  lbu        $v1, 0xC($s1)
/* 31FF538 80084F70 F8FF4224 */  addiu      $v0, $v0, -0x8
/* 31FF53C 80084F74 0B0022A2 */  sb         $v0, 0xB($s1)
/* 31FF540 80084F78 0D002292 */  lbu        $v0, 0xD($s1)
/* 31FF544 80084F7C F8FF6324 */  addiu      $v1, $v1, -0x8
/* 31FF548 80084F80 0C0023A2 */  sb         $v1, 0xC($s1)
/* 31FF54C 80084F84 0B002392 */  lbu        $v1, 0xB($s1)
/* 31FF550 80084F88 F8FF4224 */  addiu      $v0, $v0, -0x8
/* 31FF554 80084F8C D6036010 */  beqz       $v1, .Llevel_34_80085EE8
/* 31FF558 80084F90 0D0022A2 */   sb        $v0, 0xD($s1)
/* 31FF55C 80084F94 B6170208 */  j          .Llevel_34_80085ED8
/* 31FF560 80084F98 00000000 */   nop
.L80084F9C_:
/* 31FF564 80084F9C 0A002292 */  lbu        $v0, 0xA($s1)
/* 31FF568 80084FA0 00000000 */  nop
/* 31FF56C 80084FA4 08004224 */  addiu      $v0, $v0, 0x8
/* 31FF570 80084FA8 0A0022A2 */  sb         $v0, 0xA($s1)
/* 31FF574 80084FAC 09002292 */  lbu        $v0, 0x9($s1)
/* 31FF578 80084FB0 0B002392 */  lbu        $v1, 0xB($s1)
/* 31FF57C 80084FB4 02004224 */  addiu      $v0, $v0, 0x2
/* 31FF580 80084FB8 03006010 */  beqz       $v1, .Llevel_34_80084FC8
/* 31FF584 80084FBC 090022A2 */   sb        $v0, 0x9($s1)
/* 31FF588 80084FC0 F8FF6224 */  addiu      $v0, $v1, -0x8
/* 31FF58C 80084FC4 0B0022A2 */  sb         $v0, 0xB($s1)
.Llevel_34_80084FC8:
/* 31FF590 80084FC8 0C002292 */  lbu        $v0, 0xC($s1)
/* 31FF594 80084FCC 00000000 */  nop
/* 31FF598 80084FD0 02004010 */  beqz       $v0, .Llevel_34_80084FDC
/* 31FF59C 80084FD4 F8FF4224 */   addiu     $v0, $v0, -0x8
/* 31FF5A0 80084FD8 0C0022A2 */  sb         $v0, 0xC($s1)
.Llevel_34_80084FDC:
/* 31FF5A4 80084FDC 0D002292 */  lbu        $v0, 0xD($s1)
/* 31FF5A8 80084FE0 00000000 */  nop
/* 31FF5AC 80084FE4 02004010 */  beqz       $v0, .Llevel_34_80084FF0
/* 31FF5B0 80084FE8 F8FF4224 */   addiu     $v0, $v0, -0x8
/* 31FF5B4 80084FEC 0D0022A2 */  sb         $v0, 0xD($s1)
.Llevel_34_80084FF0:
/* 31FF5B8 80084FF0 FF00033C */  lui        $v1, (0xFFFFFF >> 16)
/* 31FF5BC 80084FF4 0B00228E */  lw         $v0, 0xB($s1)
/* 31FF5C0 80084FF8 FFFF6334 */  ori        $v1, $v1, (0xFFFFFF & 0xFFFF)
/* 31FF5C4 80084FFC 24104300 */  and        $v0, $v0, $v1
/* 31FF5C8 80085000 B9034010 */  beqz       $v0, .Llevel_34_80085EE8
/* 31FF5CC 80085004 00000000 */   nop
/* 31FF5D0 80085008 B6170208 */  j          .Llevel_34_80085ED8
/* 31FF5D4 8008500C 00000000 */   nop
.L80085010_:
/* 31FF5D8 80085010 2120A002 */  addu       $a0, $s5, $zero
/* 31FF5DC 80085014 2128A002 */  addu       $a1, $s5, $zero
/* 31FF5E0 80085018 215F000C */  jal        func_80017C84
/* 31FF5E4 8008501C 2130C003 */   addu      $a2, $fp, $zero
/* 31FF5E8 80085020 1D002286 */  lh         $v0, 0x1D($s1)
/* 31FF5EC 80085024 00000000 */  nop
/* 31FF5F0 80085028 05004010 */  beqz       $v0, .Llevel_34_80085040
/* 31FF5F4 8008502C 00000000 */   nop
/* 31FF5F8 80085030 1B002296 */  lhu        $v0, 0x1B($s1)
/* 31FF5FC 80085034 00000000 */  nop
/* 31FF600 80085038 01004224 */  addiu      $v0, $v0, 0x1
/* 31FF604 8008503C 1B0022A6 */  sh         $v0, 0x1B($s1)
.Llevel_34_80085040:
/* 31FF608 80085040 1D002396 */  lhu        $v1, 0x1D($s1)
/* 31FF60C 80085044 01000224 */  addiu      $v0, $zero, 0x1
/* 31FF610 80085048 23104300 */  subu       $v0, $v0, $v1
/* 31FF614 8008504C 1D0022A6 */  sh         $v0, 0x1D($s1)
/* 31FF618 80085050 09002292 */  lbu        $v0, 0x9($s1)
/* 31FF61C 80085054 40181600 */  sll        $v1, $s6, 1
/* 31FF620 80085058 21104300 */  addu       $v0, $v0, $v1
/* 31FF624 8008505C 090022A2 */  sb         $v0, 0x9($s1)
/* 31FF628 80085060 0B002292 */  lbu        $v0, 0xB($s1)
/* 31FF62C 80085064 0C002392 */  lbu        $v1, 0xC($s1)
/* 31FF630 80085068 FCFF4224 */  addiu      $v0, $v0, -0x4
/* 31FF634 8008506C 0B0022A2 */  sb         $v0, 0xB($s1)
/* 31FF638 80085070 0D002292 */  lbu        $v0, 0xD($s1)
/* 31FF63C 80085074 FCFF6324 */  addiu      $v1, $v1, -0x4
/* 31FF640 80085078 0C0023A2 */  sb         $v1, 0xC($s1)
/* 31FF644 8008507C 0B002392 */  lbu        $v1, 0xB($s1)
/* 31FF648 80085080 FCFF4224 */  addiu      $v0, $v0, -0x4
/* 31FF64C 80085084 98036010 */  beqz       $v1, .Llevel_34_80085EE8
/* 31FF650 80085088 0D0022A2 */   sb        $v0, 0xD($s1)
/* 31FF654 8008508C B6170208 */  j          .Llevel_34_80085ED8
/* 31FF658 80085090 00000000 */   nop
.L80085094_:
/* 31FF65C 80085094 2120A002 */  addu       $a0, $s5, $zero
/* 31FF660 80085098 2128A002 */  addu       $a1, $s5, $zero
/* 31FF664 8008509C 215F000C */  jal        func_80017C84
/* 31FF668 800850A0 2130C003 */   addu      $a2, $fp, $zero
/* 31FF66C 800850A4 1D002286 */  lh         $v0, 0x1D($s1)
/* 31FF670 800850A8 00000000 */  nop
/* 31FF674 800850AC 06004010 */  beqz       $v0, .Llevel_34_800850C8
/* 31FF678 800850B0 01000224 */   addiu     $v0, $zero, 0x1
/* 31FF67C 800850B4 1B002296 */  lhu        $v0, 0x1B($s1)
/* 31FF680 800850B8 00000000 */  nop
/* 31FF684 800850BC 01004224 */  addiu      $v0, $v0, 0x1
/* 31FF688 800850C0 1B0022A6 */  sh         $v0, 0x1B($s1)
/* 31FF68C 800850C4 01000224 */  addiu      $v0, $zero, 0x1
.Llevel_34_800850C8:
/* 31FF690 800850C8 1D002396 */  lhu        $v1, 0x1D($s1)
/* 31FF694 800850CC 40201600 */  sll        $a0, $s6, 1
/* 31FF698 800850D0 23104300 */  subu       $v0, $v0, $v1
/* 31FF69C 800850D4 1D0022A6 */  sh         $v0, 0x1D($s1)
/* 31FF6A0 800850D8 09002292 */  lbu        $v0, 0x9($s1)
/* 31FF6A4 800850DC 01002392 */  lbu        $v1, 0x1($s1)
/* 31FF6A8 800850E0 21104400 */  addu       $v0, $v0, $a0
/* 31FF6AC 800850E4 0900632C */  sltiu      $v1, $v1, 0x9
/* 31FF6B0 800850E8 05006014 */  bnez       $v1, .Llevel_34_80085100
/* 31FF6B4 800850EC 090022A2 */   sb        $v0, 0x9($s1)
/* 31FF6B8 800850F0 0B002292 */  lbu        $v0, 0xB($s1)
/* 31FF6BC 800850F4 00000000 */  nop
/* 31FF6C0 800850F8 E0FF4224 */  addiu      $v0, $v0, -0x20
/* 31FF6C4 800850FC 0B0022A2 */  sb         $v0, 0xB($s1)
.Llevel_34_80085100:
/* 31FF6C8 80085100 01002292 */  lbu        $v0, 0x1($s1)
/* 31FF6CC 80085104 0C002392 */  lbu        $v1, 0xC($s1)
/* 31FF6D0 80085108 0D002492 */  lbu        $a0, 0xD($s1)
/* 31FF6D4 8008510C 01004224 */  addiu      $v0, $v0, 0x1
/* 31FF6D8 80085110 F8FF6324 */  addiu      $v1, $v1, -0x8
/* 31FF6DC 80085114 FCFF8424 */  addiu      $a0, $a0, -0x4
/* 31FF6E0 80085118 010022A2 */  sb         $v0, 0x1($s1)
/* 31FF6E4 8008511C FF004230 */  andi       $v0, $v0, 0xFF
/* 31FF6E8 80085120 0C00422C */  sltiu      $v0, $v0, 0xC
/* 31FF6EC 80085124 0C0023A2 */  sb         $v1, 0xC($s1)
/* 31FF6F0 80085128 B4170208 */  j          .Llevel_34_80085ED0
/* 31FF6F4 8008512C 0D0024A2 */   sb        $a0, 0xD($s1)
.L80085130_:
/* 31FF6F8 80085130 0780023C */  lui        $v0, %hi(g_DeltaTime)
/* 31FF6FC 80085134 CC56428C */  lw         $v0, %lo(g_DeltaTime)($v0)
/* 31FF700 80085138 17002392 */  lbu        $v1, 0x17($s1)
/* 31FF704 8008513C 80100200 */  sll        $v0, $v0, 2
/* 31FF708 80085140 21186200 */  addu       $v1, $v1, $v0
/* 31FF70C 80085144 170023A2 */  sb         $v1, 0x17($s1)
/* 31FF710 80085148 0780043C */  lui        $a0, %hi(g_DeltaTime)
/* 31FF714 8008514C CC56848C */  lw         $a0, %lo(g_DeltaTime)($a0)
/* 31FF718 80085150 18002292 */  lbu        $v0, 0x18($s1)
/* 31FF71C 80085154 17002392 */  lbu        $v1, 0x17($s1)
/* 31FF720 80085158 21104400 */  addu       $v0, $v0, $a0
/* 31FF724 8008515C 40180300 */  sll        $v1, $v1, 1
/* 31FF728 80085160 180022A2 */  sb         $v0, 0x18($s1)
/* 31FF72C 80085164 0780013C */  lui        $at, %hi(D_8006CC78)
/* 31FF730 80085168 21082300 */  addu       $at, $at, $v1
/* 31FF734 8008516C 78CC2384 */  lh         $v1, %lo(D_8006CC78)($at)
/* 31FF738 80085170 FF004230 */  andi       $v0, $v0, 0xFF
/* 31FF73C 80085174 18006200 */  mult       $v1, $v0
/* 31FF740 80085178 17002392 */  lbu        $v1, 0x17($s1)
/* 31FF744 8008517C 11002296 */  lhu        $v0, 0x11($s1)
/* 31FF748 80085180 40180300 */  sll        $v1, $v1, 1
/* 31FF74C 80085184 12380000 */  mflo       $a3
/* 31FF750 80085188 03230700 */  sra        $a0, $a3, 12
/* 31FF754 8008518C 21104400 */  addu       $v0, $v0, $a0
/* 31FF758 80085190 030022A6 */  sh         $v0, 0x3($s1)
/* 31FF75C 80085194 0780013C */  lui        $at, %hi(D_8006CBF8)
/* 31FF760 80085198 21082300 */  addu       $at, $at, $v1
/* 31FF764 8008519C F8CB2384 */  lh         $v1, %lo(D_8006CBF8)($at)
/* 31FF768 800851A0 18002292 */  lbu        $v0, 0x18($s1)
/* 31FF76C 800851A4 00000000 */  nop
/* 31FF770 800851A8 18006200 */  mult       $v1, $v0
/* 31FF774 800851AC 0780023C */  lui        $v0, %hi(g_DeltaTime)
/* 31FF778 800851B0 CC56428C */  lw         $v0, %lo(g_DeltaTime)($v0)
/* 31FF77C 800851B4 0A002492 */  lbu        $a0, 0xA($s1)
/* 31FF780 800851B8 40180200 */  sll        $v1, $v0, 1
/* 31FF784 800851BC 21186200 */  addu       $v1, $v1, $v0
/* 31FF788 800851C0 07002296 */  lhu        $v0, 0x7($s1)
/* 31FF78C 800851C4 40180300 */  sll        $v1, $v1, 1
/* 31FF790 800851C8 21104300 */  addu       $v0, $v0, $v1
/* 31FF794 800851CC 18002392 */  lbu        $v1, 0x18($s1)
/* 31FF798 800851D0 04008424 */  addiu      $a0, $a0, 0x4
/* 31FF79C 800851D4 0A0024A2 */  sb         $a0, 0xA($s1)
/* 31FF7A0 800851D8 070022A6 */  sh         $v0, 0x7($s1)
/* 31FF7A4 800851DC 13002296 */  lhu        $v0, 0x13($s1)
/* 31FF7A8 800851E0 C100632C */  sltiu      $v1, $v1, 0xC1
.Llevel_34_800851E4:
/* 31FF7AC 800851E4 12380000 */  mflo       $a3
/* 31FF7B0 800851E8 03230700 */  sra        $a0, $a3, 12
/* 31FF7B4 800851EC 21104400 */  addu       $v0, $v0, $a0
/* 31FF7B8 800851F0 3F036014 */  bnez       $v1, .Llevel_34_80085EF0
/* 31FF7BC 800851F4 050022A6 */   sh        $v0, 0x5($s1)
/* 31FF7C0 800851F8 BA170208 */  j          .Llevel_34_80085EE8
/* 31FF7C4 800851FC 00000000 */   nop
.L80085200_:
/* 31FF7C8 80085200 0B002392 */  lbu        $v1, 0xB($s1)
/* 31FF7CC 80085204 00000000 */  nop
/* 31FF7D0 80085208 F000622C */  sltiu      $v0, $v1, 0xF0
/* 31FF7D4 8008520C 02004010 */  beqz       $v0, .Llevel_34_80085218
/* 31FF7D8 80085210 04006224 */   addiu     $v0, $v1, 0x4
/* 31FF7DC 80085214 0B0022A2 */  sb         $v0, 0xB($s1)
.Llevel_34_80085218:
/* 31FF7E0 80085218 0C002392 */  lbu        $v1, 0xC($s1)
/* 31FF7E4 8008521C 00000000 */  nop
/* 31FF7E8 80085220 F000622C */  sltiu      $v0, $v1, 0xF0
/* 31FF7EC 80085224 02004010 */  beqz       $v0, .Llevel_34_80085230
/* 31FF7F0 80085228 04006224 */   addiu     $v0, $v1, 0x4
/* 31FF7F4 8008522C 0C0022A2 */  sb         $v0, 0xC($s1)
.Llevel_34_80085230:
/* 31FF7F8 80085230 0D002392 */  lbu        $v1, 0xD($s1)
/* 31FF7FC 80085234 00000000 */  nop
/* 31FF800 80085238 F000622C */  sltiu      $v0, $v1, 0xF0
/* 31FF804 8008523C 02004010 */  beqz       $v0, .Llevel_34_80085248
/* 31FF808 80085240 04006224 */   addiu     $v0, $v1, 0x4
/* 31FF80C 80085244 0D0022A2 */  sb         $v0, 0xD($s1)
.Llevel_34_80085248:
/* 31FF810 80085248 0780023C */  lui        $v0, %hi(g_DeltaTime)
/* 31FF814 8008524C CC56428C */  lw         $v0, %lo(g_DeltaTime)($v0)
/* 31FF818 80085250 1B002392 */  lbu        $v1, 0x1B($s1)
/* 31FF81C 80085254 C0100200 */  sll        $v0, $v0, 3
/* 31FF820 80085258 21186200 */  addu       $v1, $v1, $v0
/* 31FF824 8008525C 1B0023A2 */  sb         $v1, 0x1B($s1)
/* 31FF828 80085260 0780033C */  lui        $v1, %hi(g_DragonCutscene + 0x3C)
/* 31FF82C 80085264 6C70638C */  lw         $v1, %lo(g_DragonCutscene + 0x3C)($v1)
/* 31FF830 80085268 00000000 */  nop
/* 31FF834 8008526C 40006228 */  slti       $v0, $v1, 0x40
/* 31FF838 80085270 02004010 */  beqz       $v0, .Llevel_34_8008527C
/* 31FF83C 80085274 3F000424 */   addiu     $a0, $zero, 0x3F
/* 31FF840 80085278 21206000 */  addu       $a0, $v1, $zero
.Llevel_34_8008527C:
/* 31FF844 8008527C 48000224 */  addiu      $v0, $zero, 0x48
/* 31FF848 80085280 1C002392 */  lbu        $v1, 0x1C($s1)
/* 31FF84C 80085284 23104400 */  subu       $v0, $v0, $a0
/* 31FF850 80085288 18006200 */  mult       $v1, $v0
/* 31FF854 8008528C 1C002392 */  lbu        $v1, 0x1C($s1)
/* 31FF858 80085290 12280000 */  mflo       $a1
/* 31FF85C 80085294 20000224 */  addiu      $v0, $zero, 0x20
/* 31FF860 80085298 23104300 */  subu       $v0, $v0, $v1
/* 31FF864 8008529C 18004400 */  mult       $v0, $a0
/* 31FF868 800852A0 C3100500 */  sra        $v0, $a1, 3
/* 31FF86C 800852A4 170022A6 */  sh         $v0, 0x17($s1)
/* 31FF870 800852A8 12180000 */  mflo       $v1
/* 31FF874 800852AC 03110300 */  sra        $v0, $v1, 4
/* 31FF878 800852B0 1B002392 */  lbu        $v1, 0x1B($s1)
/* 31FF87C 800852B4 08004224 */  addiu      $v0, $v0, 0x8
/* 31FF880 800852B8 190022A6 */  sh         $v0, 0x19($s1)
/* 31FF884 800852BC 00140200 */  sll        $v0, $v0, 16
/* 31FF888 800852C0 40180300 */  sll        $v1, $v1, 1
/* 31FF88C 800852C4 0780013C */  lui        $at, %hi(D_8006CC78)
/* 31FF890 800852C8 21082300 */  addu       $at, $at, $v1
/* 31FF894 800852CC 78CC2384 */  lh         $v1, %lo(D_8006CC78)($at)
/* 31FF898 800852D0 03140200 */  sra        $v0, $v0, 16
/* 31FF89C 800852D4 18006200 */  mult       $v1, $v0
/* 31FF8A0 800852D8 11002296 */  lhu        $v0, 0x11($s1)
/* 31FF8A4 800852DC 12180000 */  mflo       $v1
/* 31FF8A8 800852E0 03230300 */  sra        $a0, $v1, 12
/* 31FF8AC 800852E4 1B002392 */  lbu        $v1, 0x1B($s1)
/* 31FF8B0 800852E8 21104400 */  addu       $v0, $v0, $a0
/* 31FF8B4 800852EC 030022A6 */  sh         $v0, 0x3($s1)
/* 31FF8B8 800852F0 19002286 */  lh         $v0, 0x19($s1)
/* 31FF8BC 800852F4 40180300 */  sll        $v1, $v1, 1
/* 31FF8C0 800852F8 0780013C */  lui        $at, %hi(D_8006CBF8)
/* 31FF8C4 800852FC 21082300 */  addu       $at, $at, $v1
/* 31FF8C8 80085300 F8CB2384 */  lh         $v1, %lo(D_8006CBF8)($at)
/* 31FF8CC 80085304 00000000 */  nop
/* 31FF8D0 80085308 18006200 */  mult       $v1, $v0
/* 31FF8D4 8008530C 17002296 */  lhu        $v0, 0x17($s1)
/* 31FF8D8 80085310 15002396 */  lhu        $v1, 0x15($s1)
/* 31FF8DC 80085314 20004224 */  addiu      $v0, $v0, 0x20
/* 31FF8E0 80085318 21186200 */  addu       $v1, $v1, $v0
/* 31FF8E4 8008531C 13002296 */  lhu        $v0, 0x13($s1)
/* 31FF8E8 80085320 070023A6 */  sh         $v1, 0x7($s1)
/* 31FF8EC 80085324 12400000 */  mflo       $t0
/* 31FF8F0 80085328 031B0800 */  sra        $v1, $t0, 12
/* 31FF8F4 8008532C 21104300 */  addu       $v0, $v0, $v1
/* 31FF8F8 80085330 BC170208 */  j          .Llevel_34_80085EF0
/* 31FF8FC 80085334 050022A6 */   sh        $v0, 0x5($s1)
.L80085338_:
/* 31FF900 80085338 2120A002 */  addu       $a0, $s5, $zero
/* 31FF904 8008533C 2128A002 */  addu       $a1, $s5, $zero
/* 31FF908 80085340 215F000C */  jal        func_80017C84
/* 31FF90C 80085344 2130C003 */   addu      $a2, $fp, $zero
/* 31FF910 80085348 1D002286 */  lh         $v0, 0x1D($s1)
/* 31FF914 8008534C 00000000 */  nop
/* 31FF918 80085350 05004010 */  beqz       $v0, .Llevel_34_80085368
/* 31FF91C 80085354 00000000 */   nop
/* 31FF920 80085358 1B002296 */  lhu        $v0, 0x1B($s1)
/* 31FF924 8008535C 00000000 */  nop
/* 31FF928 80085360 01004224 */  addiu      $v0, $v0, 0x1
/* 31FF92C 80085364 1B0022A6 */  sh         $v0, 0x1B($s1)
.Llevel_34_80085368:
/* 31FF930 80085368 0B002292 */  lbu        $v0, 0xB($s1)
/* 31FF934 8008536C 1D002396 */  lhu        $v1, 0x1D($s1)
/* 31FF938 80085370 23205600 */  subu       $a0, $v0, $s6
/* 31FF93C 80085374 01000224 */  addiu      $v0, $zero, 0x1
/* 31FF940 80085378 23104300 */  subu       $v0, $v0, $v1
/* 31FF944 8008537C 1D0022A6 */  sh         $v0, 0x1D($s1)
/* 31FF948 80085380 09002292 */  lbu        $v0, 0x9($s1)
/* 31FF94C 80085384 40181600 */  sll        $v1, $s6, 1
/* 31FF950 80085388 21104300 */  addu       $v0, $v0, $v1
/* 31FF954 8008538C 02008104 */  bgez       $a0, .Llevel_34_80085398
/* 31FF958 80085390 090022A2 */   sb        $v0, 0x9($s1)
/* 31FF95C 80085394 21200000 */  addu       $a0, $zero, $zero
.Llevel_34_80085398:
/* 31FF960 80085398 0C002292 */  lbu        $v0, 0xC($s1)
/* 31FF964 8008539C 0B0024A2 */  sb         $a0, 0xB($s1)
/* 31FF968 800853A0 23205600 */  subu       $a0, $v0, $s6
/* 31FF96C 800853A4 02008104 */  bgez       $a0, .Llevel_34_800853B0
/* 31FF970 800853A8 00000000 */   nop
/* 31FF974 800853AC 21200000 */  addu       $a0, $zero, $zero
.Llevel_34_800853B0:
/* 31FF978 800853B0 0D002292 */  lbu        $v0, 0xD($s1)
/* 31FF97C 800853B4 0C0024A2 */  sb         $a0, 0xC($s1)
/* 31FF980 800853B8 23205600 */  subu       $a0, $v0, $s6
/* 31FF984 800853BC 02008104 */  bgez       $a0, .Llevel_34_800853C8
/* 31FF988 800853C0 00000000 */   nop
/* 31FF98C 800853C4 21200000 */  addu       $a0, $zero, $zero
.Llevel_34_800853C8:
/* 31FF990 800853C8 01002292 */  lbu        $v0, 0x1($s1)
/* 31FF994 800853CC 0D0024A2 */  sb         $a0, 0xD($s1)
/* 31FF998 800853D0 21105600 */  addu       $v0, $v0, $s6
/* 31FF99C 800853D4 010022A2 */  sb         $v0, 0x1($s1)
/* 31FF9A0 800853D8 FF004230 */  andi       $v0, $v0, 0xFF
/* 31FF9A4 800853DC B4170208 */  j          .Llevel_34_80085ED0
/* 31FF9A8 800853E0 2000422C */   sltiu     $v0, $v0, 0x20
.L800853E4_:
/* 31FF9AC 800853E4 09002486 */  lh         $a0, 0x9($s1)
/* 31FF9B0 800853E8 03002286 */  lh         $v0, 0x3($s1)
/* 31FF9B4 800853EC 00000000 */  nop
/* 31FF9B8 800853F0 23208200 */  subu       $a0, $a0, $v0
/* 31FF9BC 800853F4 43200400 */  sra        $a0, $a0, 1
/* 31FF9C0 800853F8 5000A4A7 */  sh         $a0, 0x50($sp)
/* 31FF9C4 800853FC 0B002286 */  lh         $v0, 0xB($s1)
/* 31FF9C8 80085400 05002386 */  lh         $v1, 0x5($s1)
/* 31FF9CC 80085404 00000000 */  nop
/* 31FF9D0 80085408 23104300 */  subu       $v0, $v0, $v1
/* 31FF9D4 8008540C 43100200 */  sra        $v0, $v0, 1
/* 31FF9D8 80085410 5200A2A7 */  sh         $v0, 0x52($sp)
/* 31FF9DC 80085414 0D002286 */  lh         $v0, 0xD($s1)
/* 31FF9E0 80085418 07002386 */  lh         $v1, 0x7($s1)
/* 31FF9E4 8008541C 00000000 */  nop
/* 31FF9E8 80085420 23104300 */  subu       $v0, $v0, $v1
/* 31FF9EC 80085424 43100200 */  sra        $v0, $v0, 1
/* 31FF9F0 80085428 5400A2A7 */  sh         $v0, 0x54($sp)
/* 31FF9F4 8008542C 03002296 */  lhu        $v0, 0x3($s1)
/* 31FF9F8 80085430 00000000 */  nop
/* 31FF9FC 80085434 21104400 */  addu       $v0, $v0, $a0
/* 31FFA00 80085438 030022A6 */  sh         $v0, 0x3($s1)
/* 31FFA04 8008543C 05002296 */  lhu        $v0, 0x5($s1)
/* 31FFA08 80085440 5200A397 */  lhu        $v1, 0x52($sp)
/* 31FFA0C 80085444 00000000 */  nop
/* 31FFA10 80085448 21104300 */  addu       $v0, $v0, $v1
/* 31FFA14 8008544C 050022A6 */  sh         $v0, 0x5($s1)
/* 31FFA18 80085450 07002296 */  lhu        $v0, 0x7($s1)
/* 31FFA1C 80085454 5400A397 */  lhu        $v1, 0x54($sp)
/* 31FFA20 80085458 00000000 */  nop
/* 31FFA24 8008545C 21104300 */  addu       $v0, $v0, $v1
/* 31FFA28 80085460 CB89010C */  jal        rand
/* 31FFA2C 80085464 070022A6 */   sh        $v0, 0x7($s1)
/* 31FFA30 80085468 5000A397 */  lhu        $v1, 0x50($sp)
/* 31FFA34 8008546C 02004230 */  andi       $v0, $v0, 0x2
/* 31FFA38 80085470 FFFF6324 */  addiu      $v1, $v1, -0x1
/* 31FFA3C 80085474 21186200 */  addu       $v1, $v1, $v0
/* 31FFA40 80085478 CB89010C */  jal        rand
/* 31FFA44 8008547C 5000A3A7 */   sh        $v1, 0x50($sp)
/* 31FFA48 80085480 5200A397 */  lhu        $v1, 0x52($sp)
/* 31FFA4C 80085484 02004230 */  andi       $v0, $v0, 0x2
/* 31FFA50 80085488 FFFF6324 */  addiu      $v1, $v1, -0x1
/* 31FFA54 8008548C 21186200 */  addu       $v1, $v1, $v0
/* 31FFA58 80085490 5200A3A7 */  sh         $v1, 0x52($sp)
/* 31FFA5C 80085494 09002296 */  lhu        $v0, 0x9($s1)
/* 31FFA60 80085498 5000A397 */  lhu        $v1, 0x50($sp)
/* 31FFA64 8008549C 00000000 */  nop
/* 31FFA68 800854A0 21104300 */  addu       $v0, $v0, $v1
/* 31FFA6C 800854A4 090022A6 */  sh         $v0, 0x9($s1)
/* 31FFA70 800854A8 0B002296 */  lhu        $v0, 0xB($s1)
/* 31FFA74 800854AC 5200A397 */  lhu        $v1, 0x52($sp)
/* 31FFA78 800854B0 00000000 */  nop
/* 31FFA7C 800854B4 21104300 */  addu       $v0, $v0, $v1
/* 31FFA80 800854B8 0D002396 */  lhu        $v1, 0xD($s1)
/* 31FFA84 800854BC 0B0022A6 */  sh         $v0, 0xB($s1)
/* 31FFA88 800854C0 01002292 */  lbu        $v0, 0x1($s1)
/* 31FFA8C 800854C4 5400A497 */  lhu        $a0, 0x54($sp)
/* 31FFA90 800854C8 01004224 */  addiu      $v0, $v0, 0x1
/* 31FFA94 800854CC 21186400 */  addu       $v1, $v1, $a0
/* 31FFA98 800854D0 010022A2 */  sb         $v0, 0x1($s1)
/* 31FFA9C 800854D4 FF004230 */  andi       $v0, $v0, 0xFF
/* 31FFAA0 800854D8 B3170208 */  j          .Llevel_34_80085ECC
/* 31FFAA4 800854DC 0800422C */   sltiu     $v0, $v0, 0x8
.L800854E0_:
/* 31FFAA8 800854E0 2F00C01A */  blez       $s6, .Llevel_34_800855A0
/* 31FFAAC 800854E4 21800000 */   addu      $s0, $zero, $zero
.Llevel_34_800854E8:
/* 31FFAB0 800854E8 01002292 */  lbu        $v0, 0x1($s1)
/* 31FFAB4 800854EC 00000000 */  nop
/* 31FFAB8 800854F0 01004230 */  andi       $v0, $v0, 0x1
/* 31FFABC 800854F4 23004010 */  beqz       $v0, .Llevel_34_80085584
/* 31FFAC0 800854F8 00000000 */   nop
/* 31FFAC4 800854FC 03002296 */  lhu        $v0, 0x3($s1)
/* 31FFAC8 80085500 0F002496 */  lhu        $a0, 0xF($s1)
/* 31FFACC 80085504 05002396 */  lhu        $v1, 0x5($s1)
/* 31FFAD0 80085508 11002596 */  lhu        $a1, 0x11($s1)
/* 31FFAD4 8008550C 21104400 */  addu       $v0, $v0, $a0
/* 31FFAD8 80085510 030022A6 */  sh         $v0, 0x3($s1)
/* 31FFADC 80085514 07002296 */  lhu        $v0, 0x7($s1)
/* 31FFAE0 80085518 13002496 */  lhu        $a0, 0x13($s1)
/* 31FFAE4 8008551C 21186500 */  addu       $v1, $v1, $a1
/* 31FFAE8 80085520 050023A6 */  sh         $v1, 0x5($s1)
/* 31FFAEC 80085524 01002392 */  lbu        $v1, 0x1($s1)
/* 31FFAF0 80085528 21104400 */  addu       $v0, $v0, $a0
/* 31FFAF4 8008552C 02006330 */  andi       $v1, $v1, 0x2
/* 31FFAF8 80085530 14006010 */  beqz       $v1, .Llevel_34_80085584
/* 31FFAFC 80085534 070022A6 */   sh        $v0, 0x7($s1)
/* 31FFB00 80085538 CB89010C */  jal        rand
/* 31FFB04 8008553C 00000000 */   nop
/* 31FFB08 80085540 0F002396 */  lhu        $v1, 0xF($s1)
/* 31FFB0C 80085544 02004230 */  andi       $v0, $v0, 0x2
/* 31FFB10 80085548 FFFF6324 */  addiu      $v1, $v1, -0x1
/* 31FFB14 8008554C 21186200 */  addu       $v1, $v1, $v0
/* 31FFB18 80085550 CB89010C */  jal        rand
/* 31FFB1C 80085554 0F0023A6 */   sh        $v1, 0xF($s1)
/* 31FFB20 80085558 11002396 */  lhu        $v1, 0x11($s1)
/* 31FFB24 8008555C 02004230 */  andi       $v0, $v0, 0x2
/* 31FFB28 80085560 FFFF6324 */  addiu      $v1, $v1, -0x1
/* 31FFB2C 80085564 21186200 */  addu       $v1, $v1, $v0
/* 31FFB30 80085568 CB89010C */  jal        rand
/* 31FFB34 8008556C 110023A6 */   sh        $v1, 0x11($s1)
/* 31FFB38 80085570 13002396 */  lhu        $v1, 0x13($s1)
/* 31FFB3C 80085574 02004230 */  andi       $v0, $v0, 0x2
/* 31FFB40 80085578 FFFF6324 */  addiu      $v1, $v1, -0x1
/* 31FFB44 8008557C 21186200 */  addu       $v1, $v1, $v0
/* 31FFB48 80085580 130023A6 */  sh         $v1, 0x13($s1)
.Llevel_34_80085584:
/* 31FFB4C 80085584 01002292 */  lbu        $v0, 0x1($s1)
/* 31FFB50 80085588 01001026 */  addiu      $s0, $s0, 0x1
/* 31FFB54 8008558C 01004224 */  addiu      $v0, $v0, 0x1
/* 31FFB58 80085590 010022A2 */  sb         $v0, 0x1($s1)
/* 31FFB5C 80085594 2A101602 */  slt        $v0, $s0, $s6
/* 31FFB60 80085598 D3FF4014 */  bnez       $v0, .Llevel_34_800854E8
/* 31FFB64 8008559C 00000000 */   nop
.Llevel_34_800855A0:
/* 31FFB68 800855A0 01002292 */  lbu        $v0, 0x1($s1)
/* 31FFB6C 800855A4 B4170208 */  j          .Llevel_34_80085ED0
/* 31FFB70 800855A8 1800422C */   sltiu     $v0, $v0, 0x18
.L800855AC_:
/* 31FFB74 800855AC 09002486 */  lh         $a0, 0x9($s1)
/* 31FFB78 800855B0 03002286 */  lh         $v0, 0x3($s1)
/* 31FFB7C 800855B4 00000000 */  nop
/* 31FFB80 800855B8 23208200 */  subu       $a0, $a0, $v0
/* 31FFB84 800855BC 43200400 */  sra        $a0, $a0, 1
/* 31FFB88 800855C0 5000A4A7 */  sh         $a0, 0x50($sp)
/* 31FFB8C 800855C4 0B002286 */  lh         $v0, 0xB($s1)
/* 31FFB90 800855C8 05002386 */  lh         $v1, 0x5($s1)
/* 31FFB94 800855CC 00000000 */  nop
/* 31FFB98 800855D0 23104300 */  subu       $v0, $v0, $v1
/* 31FFB9C 800855D4 43100200 */  sra        $v0, $v0, 1
/* 31FFBA0 800855D8 5200A2A7 */  sh         $v0, 0x52($sp)
/* 31FFBA4 800855DC 0D002286 */  lh         $v0, 0xD($s1)
/* 31FFBA8 800855E0 07002386 */  lh         $v1, 0x7($s1)
/* 31FFBAC 800855E4 00000000 */  nop
/* 31FFBB0 800855E8 23104300 */  subu       $v0, $v0, $v1
/* 31FFBB4 800855EC 43100200 */  sra        $v0, $v0, 1
/* 31FFBB8 800855F0 5400A2A7 */  sh         $v0, 0x54($sp)
/* 31FFBBC 800855F4 03002296 */  lhu        $v0, 0x3($s1)
/* 31FFBC0 800855F8 00000000 */  nop
/* 31FFBC4 800855FC 21104400 */  addu       $v0, $v0, $a0
/* 31FFBC8 80085600 030022A6 */  sh         $v0, 0x3($s1)
/* 31FFBCC 80085604 05002296 */  lhu        $v0, 0x5($s1)
/* 31FFBD0 80085608 5200A397 */  lhu        $v1, 0x52($sp)
/* 31FFBD4 8008560C 00000000 */  nop
/* 31FFBD8 80085610 21104300 */  addu       $v0, $v0, $v1
/* 31FFBDC 80085614 050022A6 */  sh         $v0, 0x5($s1)
/* 31FFBE0 80085618 07002296 */  lhu        $v0, 0x7($s1)
/* 31FFBE4 8008561C 5400A397 */  lhu        $v1, 0x54($sp)
/* 31FFBE8 80085620 00000000 */  nop
/* 31FFBEC 80085624 21104300 */  addu       $v0, $v0, $v1
/* 31FFBF0 80085628 CB89010C */  jal        rand
/* 31FFBF4 8008562C 070022A6 */   sh        $v0, 0x7($s1)
/* 31FFBF8 80085630 5000A397 */  lhu        $v1, 0x50($sp)
/* 31FFBFC 80085634 02004230 */  andi       $v0, $v0, 0x2
/* 31FFC00 80085638 FFFF6324 */  addiu      $v1, $v1, -0x1
/* 31FFC04 8008563C 21186200 */  addu       $v1, $v1, $v0
/* 31FFC08 80085640 CB89010C */  jal        rand
/* 31FFC0C 80085644 5000A3A7 */   sh        $v1, 0x50($sp)
/* 31FFC10 80085648 5200A397 */  lhu        $v1, 0x52($sp)
/* 31FFC14 8008564C 02004230 */  andi       $v0, $v0, 0x2
/* 31FFC18 80085650 FFFF6324 */  addiu      $v1, $v1, -0x1
/* 31FFC1C 80085654 21186200 */  addu       $v1, $v1, $v0
/* 31FFC20 80085658 5200A3A7 */  sh         $v1, 0x52($sp)
/* 31FFC24 8008565C 01002292 */  lbu        $v0, 0x1($s1)
/* 31FFC28 80085660 00000000 */  nop
/* 31FFC2C 80085664 01004230 */  andi       $v0, $v0, 0x1
/* 31FFC30 80085668 05004010 */  beqz       $v0, .Llevel_34_80085680
/* 31FFC34 8008566C 00000000 */   nop
/* 31FFC38 80085670 5400A297 */  lhu        $v0, 0x54($sp)
/* 31FFC3C 80085674 00000000 */  nop
/* 31FFC40 80085678 FFFF4224 */  addiu      $v0, $v0, -0x1
/* 31FFC44 8008567C 5400A2A7 */  sh         $v0, 0x54($sp)
.Llevel_34_80085680:
/* 31FFC48 80085680 09002296 */  lhu        $v0, 0x9($s1)
/* 31FFC4C 80085684 5000A397 */  lhu        $v1, 0x50($sp)
/* 31FFC50 80085688 00000000 */  nop
/* 31FFC54 8008568C 21104300 */  addu       $v0, $v0, $v1
/* 31FFC58 80085690 090022A6 */  sh         $v0, 0x9($s1)
/* 31FFC5C 80085694 0B002296 */  lhu        $v0, 0xB($s1)
/* 31FFC60 80085698 5200A397 */  lhu        $v1, 0x52($sp)
/* 31FFC64 8008569C 00000000 */  nop
/* 31FFC68 800856A0 21104300 */  addu       $v0, $v0, $v1
/* 31FFC6C 800856A4 0D002396 */  lhu        $v1, 0xD($s1)
/* 31FFC70 800856A8 0B0022A6 */  sh         $v0, 0xB($s1)
/* 31FFC74 800856AC 01002292 */  lbu        $v0, 0x1($s1)
/* 31FFC78 800856B0 5400A497 */  lhu        $a0, 0x54($sp)
/* 31FFC7C 800856B4 01004224 */  addiu      $v0, $v0, 0x1
/* 31FFC80 800856B8 21186400 */  addu       $v1, $v1, $a0
/* 31FFC84 800856BC 010022A2 */  sb         $v0, 0x1($s1)
/* 31FFC88 800856C0 FF004230 */  andi       $v0, $v0, 0xFF
/* 31FFC8C 800856C4 2000422C */  sltiu      $v0, $v0, 0x20
/* 31FFC90 800856C8 07024010 */  beqz       $v0, .Llevel_34_80085EE8
/* 31FFC94 800856CC 0D0023A6 */   sh        $v1, 0xD($s1)
/* 31FFC98 800856D0 02002292 */  lbu        $v0, 0x2($s1)
/* 31FFC9C 800856D4 00000000 */  nop
/* 31FFCA0 800856D8 03024010 */  beqz       $v0, .Llevel_34_80085EE8
/* 31FFCA4 800856DC 00000000 */   nop
/* 31FFCA8 800856E0 0F002292 */  lbu        $v0, 0xF($s1)
/* 31FFCAC 800856E4 00000000 */  nop
/* 31FFCB0 800856E8 FDFF4224 */  addiu      $v0, $v0, -0x3
/* 31FFCB4 800856EC 0F0022A2 */  sb         $v0, 0xF($s1)
/* 31FFCB8 800856F0 FF004230 */  andi       $v0, $v0, 0xFF
/* 31FFCBC 800856F4 8000422C */  sltiu      $v0, $v0, 0x80
/* 31FFCC0 800856F8 02004010 */  beqz       $v0, .Llevel_34_80085704
/* 31FFCC4 800856FC 80000224 */   addiu     $v0, $zero, 0x80
/* 31FFCC8 80085700 0F0022A2 */  sb         $v0, 0xF($s1)
.Llevel_34_80085704:
/* 31FFCCC 80085704 10002292 */  lbu        $v0, 0x10($s1)
/* 31FFCD0 80085708 00000000 */  nop
/* 31FFCD4 8008570C FCFF4224 */  addiu      $v0, $v0, -0x4
/* 31FFCD8 80085710 100022A2 */  sb         $v0, 0x10($s1)
/* 31FFCDC 80085714 FF004230 */  andi       $v0, $v0, 0xFF
/* 31FFCE0 80085718 6000422C */  sltiu      $v0, $v0, 0x60
/* 31FFCE4 8008571C 02004010 */  beqz       $v0, .Llevel_34_80085728
/* 31FFCE8 80085720 60000224 */   addiu     $v0, $zero, 0x60
/* 31FFCEC 80085724 100022A2 */  sb         $v0, 0x10($s1)
.Llevel_34_80085728:
/* 31FFCF0 80085728 13002292 */  lbu        $v0, 0x13($s1)
/* 31FFCF4 8008572C 110020A2 */  sb         $zero, 0x11($s1)
/* 31FFCF8 80085730 FDFF4224 */  addiu      $v0, $v0, -0x3
/* 31FFCFC 80085734 130022A2 */  sb         $v0, 0x13($s1)
/* 31FFD00 80085738 FF004230 */  andi       $v0, $v0, 0xFF
/* 31FFD04 8008573C C000422C */  sltiu      $v0, $v0, 0xC0
/* 31FFD08 80085740 02004010 */  beqz       $v0, .Llevel_34_8008574C
/* 31FFD0C 80085744 C0000224 */   addiu     $v0, $zero, 0xC0
/* 31FFD10 80085748 130022A2 */  sb         $v0, 0x13($s1)
.Llevel_34_8008574C:
/* 31FFD14 8008574C 14002292 */  lbu        $v0, 0x14($s1)
/* 31FFD18 80085750 00000000 */  nop
/* 31FFD1C 80085754 FCFF4224 */  addiu      $v0, $v0, -0x4
/* 31FFD20 80085758 140022A2 */  sb         $v0, 0x14($s1)
/* 31FFD24 8008575C FF004230 */  andi       $v0, $v0, 0xFF
/* 31FFD28 80085760 8000422C */  sltiu      $v0, $v0, 0x80
/* 31FFD2C 80085764 02004010 */  beqz       $v0, .Llevel_34_80085770
/* 31FFD30 80085768 80000224 */   addiu     $v0, $zero, 0x80
/* 31FFD34 8008576C 140022A2 */  sb         $v0, 0x14($s1)
.Llevel_34_80085770:
/* 31FFD38 80085770 15002292 */  lbu        $v0, 0x15($s1)
/* 31FFD3C 80085774 00000000 */  nop
/* 31FFD40 80085778 FAFF4224 */  addiu      $v0, $v0, -0x6
/* 31FFD44 8008577C 150022A2 */  sb         $v0, 0x15($s1)
/* 31FFD48 80085780 FF004230 */  andi       $v0, $v0, 0xFF
/* 31FFD4C 80085784 2000422C */  sltiu      $v0, $v0, 0x20
/* 31FFD50 80085788 D9014010 */  beqz       $v0, .Llevel_34_80085EF0
/* 31FFD54 8008578C 20000224 */   addiu     $v0, $zero, 0x20
/* 31FFD58 80085790 BC170208 */  j          .Llevel_34_80085EF0
/* 31FFD5C 80085794 150022A2 */   sb        $v0, 0x15($s1)
.L80085798_:
/* 31FFD60 80085798 01002292 */  lbu        $v0, 0x1($s1)
/* 31FFD64 8008579C 00000000 */  nop
/* 31FFD68 800857A0 01004224 */  addiu      $v0, $v0, 0x1
/* 31FFD6C 800857A4 010022A2 */  sb         $v0, 0x1($s1)
/* 31FFD70 800857A8 FF004230 */  andi       $v0, $v0, 0xFF
/* 31FFD74 800857AC 2000422C */  sltiu      $v0, $v0, 0x20
/* 31FFD78 800857B0 CD014010 */  beqz       $v0, .Llevel_34_80085EE8
/* 31FFD7C 800857B4 00000000 */   nop
/* 31FFD80 800857B8 02002292 */  lbu        $v0, 0x2($s1)
/* 31FFD84 800857BC 00000000 */  nop
/* 31FFD88 800857C0 C9014010 */  beqz       $v0, .Llevel_34_80085EE8
/* 31FFD8C 800857C4 00000000 */   nop
/* 31FFD90 800857C8 09002286 */  lh         $v0, 0x9($s1)
/* 31FFD94 800857CC 03002386 */  lh         $v1, 0x3($s1)
/* 31FFD98 800857D0 00000000 */  nop
/* 31FFD9C 800857D4 23104300 */  subu       $v0, $v0, $v1
/* 31FFDA0 800857D8 5800A2AF */  sw         $v0, 0x58($sp)
/* 31FFDA4 800857DC 0B002286 */  lh         $v0, 0xB($s1)
/* 31FFDA8 800857E0 05002386 */  lh         $v1, 0x5($s1)
/* 31FFDAC 800857E4 00000000 */  nop
/* 31FFDB0 800857E8 23104300 */  subu       $v0, $v0, $v1
/* 31FFDB4 800857EC 5C00A2AF */  sw         $v0, 0x5C($sp)
/* 31FFDB8 800857F0 0D002286 */  lh         $v0, 0xD($s1)
/* 31FFDBC 800857F4 07002386 */  lh         $v1, 0x7($s1)
/* 31FFDC0 800857F8 00000000 */  nop
/* 31FFDC4 800857FC 23104300 */  subu       $v0, $v0, $v1
/* 31FFDC8 80085800 CB89010C */  jal        rand
/* 31FFDCC 80085804 6000A2AF */   sw        $v0, 0x60($sp)
/* 31FFDD0 80085808 5800A38F */  lw         $v1, 0x58($sp)
/* 31FFDD4 8008580C 02004230 */  andi       $v0, $v0, 0x2
/* 31FFDD8 80085810 FFFF6324 */  addiu      $v1, $v1, -0x1
/* 31FFDDC 80085814 21186200 */  addu       $v1, $v1, $v0
/* 31FFDE0 80085818 CB89010C */  jal        rand
/* 31FFDE4 8008581C 5800A3AF */   sw        $v1, 0x58($sp)
/* 31FFDE8 80085820 5C00A38F */  lw         $v1, 0x5C($sp)
/* 31FFDEC 80085824 02004230 */  andi       $v0, $v0, 0x2
/* 31FFDF0 80085828 FFFF6324 */  addiu      $v1, $v1, -0x1
/* 31FFDF4 8008582C 21186200 */  addu       $v1, $v1, $v0
/* 31FFDF8 80085830 CB89010C */  jal        rand
/* 31FFDFC 80085834 5C00A3AF */   sw        $v1, 0x5C($sp)
/* 31FFE00 80085838 6000A38F */  lw         $v1, 0x60($sp)
/* 31FFE04 8008583C 02004230 */  andi       $v0, $v0, 0x2
/* 31FFE08 80085840 FFFF6324 */  addiu      $v1, $v1, -0x1
/* 31FFE0C 80085844 21186200 */  addu       $v1, $v1, $v0
/* 31FFE10 80085848 6000A3AF */  sw         $v1, 0x60($sp)
/* 31FFE14 8008584C 5800A38F */  lw         $v1, 0x58($sp)
/* 31FFE18 80085850 09002296 */  lhu        $v0, 0x9($s1)
/* 31FFE1C 80085854 00000000 */  nop
/* 31FFE20 80085858 21104300 */  addu       $v0, $v0, $v1
/* 31FFE24 8008585C 090022A6 */  sh         $v0, 0x9($s1)
/* 31FFE28 80085860 5C00A38F */  lw         $v1, 0x5C($sp)
/* 31FFE2C 80085864 0B002296 */  lhu        $v0, 0xB($s1)
/* 31FFE30 80085868 00000000 */  nop
/* 31FFE34 8008586C 21104300 */  addu       $v0, $v0, $v1
/* 31FFE38 80085870 0B0022A6 */  sh         $v0, 0xB($s1)
/* 31FFE3C 80085874 6000A38F */  lw         $v1, 0x60($sp)
/* 31FFE40 80085878 0D002296 */  lhu        $v0, 0xD($s1)
/* 31FFE44 8008587C 00000000 */  nop
/* 31FFE48 80085880 21104300 */  addu       $v0, $v0, $v1
/* 31FFE4C 80085884 0D0022A6 */  sh         $v0, 0xD($s1)
/* 31FFE50 80085888 5800A38F */  lw         $v1, 0x58($sp)
/* 31FFE54 8008588C 09002296 */  lhu        $v0, 0x9($s1)
/* 31FFE58 80085890 00000000 */  nop
/* 31FFE5C 80085894 23104300 */  subu       $v0, $v0, $v1
/* 31FFE60 80085898 030022A6 */  sh         $v0, 0x3($s1)
/* 31FFE64 8008589C 5C00A38F */  lw         $v1, 0x5C($sp)
/* 31FFE68 800858A0 0B002296 */  lhu        $v0, 0xB($s1)
/* 31FFE6C 800858A4 00000000 */  nop
/* 31FFE70 800858A8 23104300 */  subu       $v0, $v0, $v1
/* 31FFE74 800858AC 050022A6 */  sh         $v0, 0x5($s1)
/* 31FFE78 800858B0 13002292 */  lbu        $v0, 0x13($s1)
/* 31FFE7C 800858B4 6000A48F */  lw         $a0, 0x60($sp)
/* 31FFE80 800858B8 15002392 */  lbu        $v1, 0x15($s1)
/* 31FFE84 800858BC FEFF4224 */  addiu      $v0, $v0, -0x2
/* 31FFE88 800858C0 130022A2 */  sb         $v0, 0x13($s1)
/* 31FFE8C 800858C4 14002292 */  lbu        $v0, 0x14($s1)
/* 31FFE90 800858C8 FCFF6324 */  addiu      $v1, $v1, -0x4
/* 31FFE94 800858CC 150023A2 */  sb         $v1, 0x15($s1)
/* 31FFE98 800858D0 10002392 */  lbu        $v1, 0x10($s1)
/* 31FFE9C 800858D4 FEFF4224 */  addiu      $v0, $v0, -0x2
/* 31FFEA0 800858D8 140022A2 */  sb         $v0, 0x14($s1)
/* 31FFEA4 800858DC 0F002292 */  lbu        $v0, 0xF($s1)
/* 31FFEA8 800858E0 FDFF6324 */  addiu      $v1, $v1, -0x3
/* 31FFEAC 800858E4 100023A2 */  sb         $v1, 0x10($s1)
/* 31FFEB0 800858E8 0D002396 */  lhu        $v1, 0xD($s1)
/* 31FFEB4 800858EC FDFF4224 */  addiu      $v0, $v0, -0x3
/* 31FFEB8 800858F0 0F0022A2 */  sb         $v0, 0xF($s1)
/* 31FFEBC 800858F4 11002292 */  lbu        $v0, 0x11($s1)
/* 31FFEC0 800858F8 23186400 */  subu       $v1, $v1, $a0
/* 31FFEC4 800858FC 070023A6 */  sh         $v1, 0x7($s1)
/* 31FFEC8 80085900 FDFF4224 */  addiu      $v0, $v0, -0x3
/* 31FFECC 80085904 BC170208 */  j          .Llevel_34_80085EF0
/* 31FFED0 80085908 110022A2 */   sb        $v0, 0x11($s1)
.L8008590C_:
/* 31FFED4 8008590C 01002292 */  lbu        $v0, 0x1($s1)
/* 31FFED8 80085910 00000000 */  nop
/* 31FFEDC 80085914 01004224 */  addiu      $v0, $v0, 0x1
/* 31FFEE0 80085918 010022A2 */  sb         $v0, 0x1($s1)
/* 31FFEE4 8008591C FF004230 */  andi       $v0, $v0, 0xFF
/* 31FFEE8 80085920 3000422C */  sltiu      $v0, $v0, 0x30
/* 31FFEEC 80085924 70014010 */  beqz       $v0, .Llevel_34_80085EE8
/* 31FFEF0 80085928 00000000 */   nop
/* 31FFEF4 8008592C 02002292 */  lbu        $v0, 0x2($s1)
/* 31FFEF8 80085930 00000000 */  nop
/* 31FFEFC 80085934 6C014010 */  beqz       $v0, .Llevel_34_80085EE8
/* 31FFF00 80085938 00000000 */   nop
/* 31FFF04 8008593C 03002286 */  lh         $v0, 0x3($s1)
/* 31FFF08 80085940 09002386 */  lh         $v1, 0x9($s1)
/* 31FFF0C 80085944 00000000 */  nop
/* 31FFF10 80085948 23104300 */  subu       $v0, $v0, $v1
/* 31FFF14 8008594C 43100200 */  sra        $v0, $v0, 1
/* 31FFF18 80085950 5000A2AF */  sw         $v0, 0x50($sp)
/* 31FFF1C 80085954 05002286 */  lh         $v0, 0x5($s1)
/* 31FFF20 80085958 0B002386 */  lh         $v1, 0xB($s1)
/* 31FFF24 8008595C 00000000 */  nop
/* 31FFF28 80085960 23104300 */  subu       $v0, $v0, $v1
/* 31FFF2C 80085964 43100200 */  sra        $v0, $v0, 1
/* 31FFF30 80085968 5400A2AF */  sw         $v0, 0x54($sp)
/* 31FFF34 8008596C 07002286 */  lh         $v0, 0x7($s1)
/* 31FFF38 80085970 0D002386 */  lh         $v1, 0xD($s1)
/* 31FFF3C 80085974 00000000 */  nop
/* 31FFF40 80085978 23104300 */  subu       $v0, $v0, $v1
/* 31FFF44 8008597C 43100200 */  sra        $v0, $v0, 1
/* 31FFF48 80085980 CB89010C */  jal        rand
/* 31FFF4C 80085984 5800A2AF */   sw        $v0, 0x58($sp)
/* 31FFF50 80085988 5000A38F */  lw         $v1, 0x50($sp)
/* 31FFF54 8008598C 04004230 */  andi       $v0, $v0, 0x4
/* 31FFF58 80085990 FEFF6324 */  addiu      $v1, $v1, -0x2
/* 31FFF5C 80085994 21186200 */  addu       $v1, $v1, $v0
/* 31FFF60 80085998 CB89010C */  jal        rand
/* 31FFF64 8008599C 5000A3AF */   sw        $v1, 0x50($sp)
/* 31FFF68 800859A0 5400A38F */  lw         $v1, 0x54($sp)
/* 31FFF6C 800859A4 04004230 */  andi       $v0, $v0, 0x4
/* 31FFF70 800859A8 FEFF6324 */  addiu      $v1, $v1, -0x2
/* 31FFF74 800859AC 21186200 */  addu       $v1, $v1, $v0
/* 31FFF78 800859B0 CB89010C */  jal        rand
/* 31FFF7C 800859B4 5400A3AF */   sw        $v1, 0x54($sp)
/* 31FFF80 800859B8 5800A38F */  lw         $v1, 0x58($sp)
/* 31FFF84 800859BC 02004230 */  andi       $v0, $v0, 0x2
/* 31FFF88 800859C0 FFFF6324 */  addiu      $v1, $v1, -0x1
/* 31FFF8C 800859C4 21186200 */  addu       $v1, $v1, $v0
/* 31FFF90 800859C8 5800A3AF */  sw         $v1, 0x58($sp)
/* 31FFF94 800859CC 5000A38F */  lw         $v1, 0x50($sp)
/* 31FFF98 800859D0 03002296 */  lhu        $v0, 0x3($s1)
/* 31FFF9C 800859D4 00000000 */  nop
/* 31FFFA0 800859D8 21104300 */  addu       $v0, $v0, $v1
/* 31FFFA4 800859DC 030022A6 */  sh         $v0, 0x3($s1)
/* 31FFFA8 800859E0 5400A38F */  lw         $v1, 0x54($sp)
/* 31FFFAC 800859E4 05002296 */  lhu        $v0, 0x5($s1)
/* 31FFFB0 800859E8 00000000 */  nop
/* 31FFFB4 800859EC 21104300 */  addu       $v0, $v0, $v1
/* 31FFFB8 800859F0 050022A6 */  sh         $v0, 0x5($s1)
/* 31FFFBC 800859F4 5800A38F */  lw         $v1, 0x58($sp)
/* 31FFFC0 800859F8 07002296 */  lhu        $v0, 0x7($s1)
/* 31FFFC4 800859FC 00000000 */  nop
/* 31FFFC8 80085A00 21104300 */  addu       $v0, $v0, $v1
/* 31FFFCC 80085A04 070022A6 */  sh         $v0, 0x7($s1)
/* 31FFFD0 80085A08 5000A28F */  lw         $v0, 0x50($sp)
/* 31FFFD4 80085A0C 03002396 */  lhu        $v1, 0x3($s1)
/* 31FFFD8 80085A10 40100200 */  sll        $v0, $v0, 1
/* 31FFFDC 80085A14 23186200 */  subu       $v1, $v1, $v0
/* 31FFFE0 80085A18 090023A6 */  sh         $v1, 0x9($s1)
/* 31FFFE4 80085A1C 5400A28F */  lw         $v0, 0x54($sp)
/* 31FFFE8 80085A20 05002396 */  lhu        $v1, 0x5($s1)
/* 31FFFEC 80085A24 40100200 */  sll        $v0, $v0, 1
/* 31FFFF0 80085A28 23186200 */  subu       $v1, $v1, $v0
/* 31FFFF4 80085A2C 0B0023A6 */  sh         $v1, 0xB($s1)
/* 31FFFF8 80085A30 5800A28F */  lw         $v0, 0x58($sp)
/* 31FFFFC 80085A34 07002396 */  lhu        $v1, 0x7($s1)
/* 3200000 80085A38 40100200 */  sll        $v0, $v0, 1
/* 3200004 80085A3C 23186200 */  subu       $v1, $v1, $v0
/* 3200008 80085A40 BC170208 */  j          .Llevel_34_80085EF0
/* 320000C 80085A44 0D0023A6 */   sh        $v1, 0xD($s1)
.L80085A48_:
/* 3200010 80085A48 0780023C */  lui        $v0, %hi(g_DeltaTime)
/* 3200014 80085A4C CC56428C */  lw         $v0, %lo(g_DeltaTime)($v0)
/* 3200018 80085A50 17002392 */  lbu        $v1, 0x17($s1)
/* 320001C 80085A54 80100200 */  sll        $v0, $v0, 2
/* 3200020 80085A58 21186200 */  addu       $v1, $v1, $v0
/* 3200024 80085A5C 170023A2 */  sb         $v1, 0x17($s1)
/* 3200028 80085A60 0780043C */  lui        $a0, %hi(g_DeltaTime)
/* 320002C 80085A64 CC56848C */  lw         $a0, %lo(g_DeltaTime)($a0)
/* 3200030 80085A68 18002292 */  lbu        $v0, 0x18($s1)
/* 3200034 80085A6C 17002392 */  lbu        $v1, 0x17($s1)
/* 3200038 80085A70 21104400 */  addu       $v0, $v0, $a0
/* 320003C 80085A74 40180300 */  sll        $v1, $v1, 1
/* 3200040 80085A78 180022A2 */  sb         $v0, 0x18($s1)
/* 3200044 80085A7C 0780013C */  lui        $at, %hi(D_8006CC78)
/* 3200048 80085A80 21082300 */  addu       $at, $at, $v1
/* 320004C 80085A84 78CC2384 */  lh         $v1, %lo(D_8006CC78)($at)
/* 3200050 80085A88 FF004230 */  andi       $v0, $v0, 0xFF
/* 3200054 80085A8C 18006200 */  mult       $v1, $v0
/* 3200058 80085A90 17002392 */  lbu        $v1, 0x17($s1)
/* 320005C 80085A94 0F002296 */  lhu        $v0, 0xF($s1)
/* 3200060 80085A98 40180300 */  sll        $v1, $v1, 1
/* 3200064 80085A9C 12380000 */  mflo       $a3
/* 3200068 80085AA0 03230700 */  sra        $a0, $a3, 12
/* 320006C 80085AA4 21104400 */  addu       $v0, $v0, $a0
/* 3200070 80085AA8 030022A6 */  sh         $v0, 0x3($s1)
/* 3200074 80085AAC 0780013C */  lui        $at, %hi(D_8006CBF8)
/* 3200078 80085AB0 21082300 */  addu       $at, $at, $v1
/* 320007C 80085AB4 F8CB2384 */  lh         $v1, %lo(D_8006CBF8)($at)
/* 3200080 80085AB8 18002292 */  lbu        $v0, 0x18($s1)
/* 3200084 80085ABC 00000000 */  nop
/* 3200088 80085AC0 18006200 */  mult       $v1, $v0
/* 320008C 80085AC4 0780033C */  lui        $v1, %hi(g_DeltaTime)
/* 3200090 80085AC8 CC56638C */  lw         $v1, %lo(g_DeltaTime)($v1)
/* 3200094 80085ACC 00000000 */  nop
/* 3200098 80085AD0 40100300 */  sll        $v0, $v1, 1
/* 320009C 80085AD4 21104300 */  addu       $v0, $v0, $v1
/* 32000A0 80085AD8 07002396 */  lhu        $v1, 0x7($s1)
/* 32000A4 80085ADC 40100200 */  sll        $v0, $v0, 1
/* 32000A8 80085AE0 21186200 */  addu       $v1, $v1, $v0
/* 32000AC 80085AE4 070023A6 */  sh         $v1, 0x7($s1)
/* 32000B0 80085AE8 18002392 */  lbu        $v1, 0x18($s1)
/* 32000B4 80085AEC 11002296 */  lhu        $v0, 0x11($s1)
/* 32000B8 80085AF0 79140208 */  j          .Llevel_34_800851E4
/* 32000BC 80085AF4 C100632C */   sltiu     $v1, $v1, 0xC1
.L80085AF8_:
/* 32000C0 80085AF8 09002486 */  lh         $a0, 0x9($s1)
/* 32000C4 80085AFC 03002286 */  lh         $v0, 0x3($s1)
/* 32000C8 80085B00 00000000 */  nop
/* 32000CC 80085B04 23208200 */  subu       $a0, $a0, $v0
/* 32000D0 80085B08 43200400 */  sra        $a0, $a0, 1
/* 32000D4 80085B0C 5000A4A7 */  sh         $a0, 0x50($sp)
/* 32000D8 80085B10 0B002286 */  lh         $v0, 0xB($s1)
/* 32000DC 80085B14 05002386 */  lh         $v1, 0x5($s1)
/* 32000E0 80085B18 00000000 */  nop
/* 32000E4 80085B1C 23104300 */  subu       $v0, $v0, $v1
/* 32000E8 80085B20 43100200 */  sra        $v0, $v0, 1
/* 32000EC 80085B24 5200A2A7 */  sh         $v0, 0x52($sp)
/* 32000F0 80085B28 0D002286 */  lh         $v0, 0xD($s1)
/* 32000F4 80085B2C 07002386 */  lh         $v1, 0x7($s1)
/* 32000F8 80085B30 00000000 */  nop
/* 32000FC 80085B34 23104300 */  subu       $v0, $v0, $v1
/* 3200100 80085B38 43100200 */  sra        $v0, $v0, 1
/* 3200104 80085B3C 5400A2A7 */  sh         $v0, 0x54($sp)
/* 3200108 80085B40 03002296 */  lhu        $v0, 0x3($s1)
/* 320010C 80085B44 00000000 */  nop
/* 3200110 80085B48 21104400 */  addu       $v0, $v0, $a0
/* 3200114 80085B4C 030022A6 */  sh         $v0, 0x3($s1)
/* 3200118 80085B50 05002296 */  lhu        $v0, 0x5($s1)
/* 320011C 80085B54 5200A397 */  lhu        $v1, 0x52($sp)
/* 3200120 80085B58 00000000 */  nop
/* 3200124 80085B5C 21104300 */  addu       $v0, $v0, $v1
/* 3200128 80085B60 050022A6 */  sh         $v0, 0x5($s1)
/* 320012C 80085B64 07002296 */  lhu        $v0, 0x7($s1)
/* 3200130 80085B68 5400A397 */  lhu        $v1, 0x54($sp)
/* 3200134 80085B6C 00000000 */  nop
/* 3200138 80085B70 21104300 */  addu       $v0, $v0, $v1
/* 320013C 80085B74 070022A6 */  sh         $v0, 0x7($s1)
/* 3200140 80085B78 5200A297 */  lhu        $v0, 0x52($sp)
/* 3200144 80085B7C 5000A397 */  lhu        $v1, 0x50($sp)
/* 3200148 80085B80 01004224 */  addiu      $v0, $v0, 0x1
/* 320014C 80085B84 5200A2A7 */  sh         $v0, 0x52($sp)
/* 3200150 80085B88 09002296 */  lhu        $v0, 0x9($s1)
/* 3200154 80085B8C 00000000 */  nop
/* 3200158 80085B90 21104300 */  addu       $v0, $v0, $v1
/* 320015C 80085B94 090022A6 */  sh         $v0, 0x9($s1)
/* 3200160 80085B98 0B002296 */  lhu        $v0, 0xB($s1)
/* 3200164 80085B9C 5200A397 */  lhu        $v1, 0x52($sp)
/* 3200168 80085BA0 00000000 */  nop
/* 320016C 80085BA4 21104300 */  addu       $v0, $v0, $v1
/* 3200170 80085BA8 0D002396 */  lhu        $v1, 0xD($s1)
/* 3200174 80085BAC 0B0022A6 */  sh         $v0, 0xB($s1)
/* 3200178 80085BB0 01002292 */  lbu        $v0, 0x1($s1)
/* 320017C 80085BB4 5400A497 */  lhu        $a0, 0x54($sp)
/* 3200180 80085BB8 01004224 */  addiu      $v0, $v0, 0x1
/* 3200184 80085BBC 21186400 */  addu       $v1, $v1, $a0
/* 3200188 80085BC0 010022A2 */  sb         $v0, 0x1($s1)
/* 320018C 80085BC4 FF004230 */  andi       $v0, $v0, 0xFF
/* 3200190 80085BC8 2000422C */  sltiu      $v0, $v0, 0x20
/* 3200194 80085BCC C8004014 */  bnez       $v0, .Llevel_34_80085EF0
/* 3200198 80085BD0 0D0023A6 */   sh        $v1, 0xD($s1)
/* 320019C 80085BD4 BA170208 */  j          .Llevel_34_80085EE8
/* 32001A0 80085BD8 00000000 */   nop
.L80085BDC_:
/* 32001A4 80085BDC 01002292 */  lbu        $v0, 0x1($s1)
/* 32001A8 80085BE0 00000000 */  nop
/* 32001AC 80085BE4 01004224 */  addiu      $v0, $v0, 0x1
/* 32001B0 80085BE8 010022A2 */  sb         $v0, 0x1($s1)
/* 32001B4 80085BEC FF004230 */  andi       $v0, $v0, 0xFF
/* 32001B8 80085BF0 2800422C */  sltiu      $v0, $v0, 0x28
/* 32001BC 80085BF4 BC004010 */  beqz       $v0, .Llevel_34_80085EE8
/* 32001C0 80085BF8 00000000 */   nop
/* 32001C4 80085BFC 02002292 */  lbu        $v0, 0x2($s1)
/* 32001C8 80085C00 00000000 */  nop
/* 32001CC 80085C04 B8004010 */  beqz       $v0, .Llevel_34_80085EE8
/* 32001D0 80085C08 00000000 */   nop
/* 32001D4 80085C0C 03002296 */  lhu        $v0, 0x3($s1)
/* 32001D8 80085C10 0F002396 */  lhu        $v1, 0xF($s1)
/* 32001DC 80085C14 11002496 */  lhu        $a0, 0x11($s1)
/* 32001E0 80085C18 13002596 */  lhu        $a1, 0x13($s1)
/* 32001E4 80085C1C 21104300 */  addu       $v0, $v0, $v1
/* 32001E8 80085C20 030022A6 */  sh         $v0, 0x3($s1)
/* 32001EC 80085C24 05002296 */  lhu        $v0, 0x5($s1)
/* 32001F0 80085C28 07002396 */  lhu        $v1, 0x7($s1)
/* 32001F4 80085C2C 21104400 */  addu       $v0, $v0, $a0
/* 32001F8 80085C30 21186500 */  addu       $v1, $v1, $a1
/* 32001FC 80085C34 050022A6 */  sh         $v0, 0x5($s1)
/* 3200200 80085C38 CB89010C */  jal        rand
/* 3200204 80085C3C 070023A6 */   sh        $v1, 0x7($s1)
/* 3200208 80085C40 0F002396 */  lhu        $v1, 0xF($s1)
/* 320020C 80085C44 02004230 */  andi       $v0, $v0, 0x2
/* 3200210 80085C48 FFFF6324 */  addiu      $v1, $v1, -0x1
/* 3200214 80085C4C 21186200 */  addu       $v1, $v1, $v0
/* 3200218 80085C50 CB89010C */  jal        rand
/* 320021C 80085C54 0F0023A6 */   sh        $v1, 0xF($s1)
/* 3200220 80085C58 11002396 */  lhu        $v1, 0x11($s1)
/* 3200224 80085C5C 02004230 */  andi       $v0, $v0, 0x2
/* 3200228 80085C60 FFFF6324 */  addiu      $v1, $v1, -0x1
/* 320022C 80085C64 21186200 */  addu       $v1, $v1, $v0
/* 3200230 80085C68 CB89010C */  jal        rand
/* 3200234 80085C6C 110023A6 */   sh        $v1, 0x11($s1)
/* 3200238 80085C70 13002396 */  lhu        $v1, 0x13($s1)
/* 320023C 80085C74 02004230 */  andi       $v0, $v0, 0x2
/* 3200240 80085C78 FFFF6324 */  addiu      $v1, $v1, -0x1
/* 3200244 80085C7C 21186200 */  addu       $v1, $v1, $v0
/* 3200248 80085C80 130023A6 */  sh         $v1, 0x13($s1)
/* 320024C 80085C84 001C0300 */  sll        $v1, $v1, 16
/* 3200250 80085C88 031C0300 */  sra        $v1, $v1, 16
/* 3200254 80085C8C 03006328 */  slti       $v1, $v1, 0x3
/* 3200258 80085C90 02006014 */  bnez       $v1, .Llevel_34_80085C9C
/* 320025C 80085C94 02000224 */   addiu     $v0, $zero, 0x2
/* 3200260 80085C98 130022A6 */  sh         $v0, 0x13($s1)
.Llevel_34_80085C9C:
/* 3200264 80085C9C 13002286 */  lh         $v0, 0x13($s1)
/* 3200268 80085CA0 00000000 */  nop
/* 320026C 80085CA4 FCFF4228 */  slti       $v0, $v0, -0x4
/* 3200270 80085CA8 02004010 */  beqz       $v0, .Llevel_34_80085CB4
/* 3200274 80085CAC FCFF0224 */   addiu     $v0, $zero, -0x4
/* 3200278 80085CB0 130022A6 */  sh         $v0, 0x13($s1)
.Llevel_34_80085CB4:
/* 320027C 80085CB4 0B002292 */  lbu        $v0, 0xB($s1)
/* 3200280 80085CB8 0D002392 */  lbu        $v1, 0xD($s1)
/* 3200284 80085CBC FEFF4224 */  addiu      $v0, $v0, -0x2
/* 3200288 80085CC0 0B0022A2 */  sb         $v0, 0xB($s1)
/* 320028C 80085CC4 0C002292 */  lbu        $v0, 0xC($s1)
/* 3200290 80085CC8 FFFF6324 */  addiu      $v1, $v1, -0x1
/* 3200294 80085CCC 0D0023A2 */  sb         $v1, 0xD($s1)
/* 3200298 80085CD0 FEFF4224 */  addiu      $v0, $v0, -0x2
/* 320029C 80085CD4 BC170208 */  j          .Llevel_34_80085EF0
/* 32002A0 80085CD8 0C0022A2 */   sb        $v0, 0xC($s1)
.L80085CDC_:
/* 32002A4 80085CDC 09002486 */  lh         $a0, 0x9($s1)
/* 32002A8 80085CE0 03002286 */  lh         $v0, 0x3($s1)
/* 32002AC 80085CE4 00000000 */  nop
/* 32002B0 80085CE8 23208200 */  subu       $a0, $a0, $v0
/* 32002B4 80085CEC 43200400 */  sra        $a0, $a0, 1
/* 32002B8 80085CF0 5000A4A7 */  sh         $a0, 0x50($sp)
/* 32002BC 80085CF4 0B002286 */  lh         $v0, 0xB($s1)
/* 32002C0 80085CF8 05002386 */  lh         $v1, 0x5($s1)
/* 32002C4 80085CFC 00000000 */  nop
/* 32002C8 80085D00 23104300 */  subu       $v0, $v0, $v1
/* 32002CC 80085D04 43100200 */  sra        $v0, $v0, 1
/* 32002D0 80085D08 5200A2A7 */  sh         $v0, 0x52($sp)
/* 32002D4 80085D0C 0D002286 */  lh         $v0, 0xD($s1)
/* 32002D8 80085D10 07002386 */  lh         $v1, 0x7($s1)
/* 32002DC 80085D14 00000000 */  nop
/* 32002E0 80085D18 23104300 */  subu       $v0, $v0, $v1
/* 32002E4 80085D1C 43100200 */  sra        $v0, $v0, 1
/* 32002E8 80085D20 5400A2A7 */  sh         $v0, 0x54($sp)
/* 32002EC 80085D24 03002296 */  lhu        $v0, 0x3($s1)
/* 32002F0 80085D28 00000000 */  nop
/* 32002F4 80085D2C 21104400 */  addu       $v0, $v0, $a0
/* 32002F8 80085D30 030022A6 */  sh         $v0, 0x3($s1)
/* 32002FC 80085D34 05002296 */  lhu        $v0, 0x5($s1)
/* 3200300 80085D38 5200A397 */  lhu        $v1, 0x52($sp)
/* 3200304 80085D3C 00000000 */  nop
/* 3200308 80085D40 21104300 */  addu       $v0, $v0, $v1
/* 320030C 80085D44 050022A6 */  sh         $v0, 0x5($s1)
/* 3200310 80085D48 07002296 */  lhu        $v0, 0x7($s1)
/* 3200314 80085D4C 5400A397 */  lhu        $v1, 0x54($sp)
/* 3200318 80085D50 00000000 */  nop
/* 320031C 80085D54 21104300 */  addu       $v0, $v0, $v1
/* 3200320 80085D58 070022A6 */  sh         $v0, 0x7($s1)
/* 3200324 80085D5C 09002296 */  lhu        $v0, 0x9($s1)
/* 3200328 80085D60 5000A397 */  lhu        $v1, 0x50($sp)
/* 320032C 80085D64 00000000 */  nop
/* 3200330 80085D68 21104300 */  addu       $v0, $v0, $v1
/* 3200334 80085D6C 090022A6 */  sh         $v0, 0x9($s1)
/* 3200338 80085D70 0B002296 */  lhu        $v0, 0xB($s1)
/* 320033C 80085D74 5200A397 */  lhu        $v1, 0x52($sp)
/* 3200340 80085D78 00000000 */  nop
/* 3200344 80085D7C 21104300 */  addu       $v0, $v0, $v1
/* 3200348 80085D80 0D002396 */  lhu        $v1, 0xD($s1)
/* 320034C 80085D84 0B0022A6 */  sh         $v0, 0xB($s1)
/* 3200350 80085D88 01002292 */  lbu        $v0, 0x1($s1)
/* 3200354 80085D8C 5400A497 */  lhu        $a0, 0x54($sp)
/* 3200358 80085D90 01004224 */  addiu      $v0, $v0, 0x1
/* 320035C 80085D94 21186400 */  addu       $v1, $v1, $a0
/* 3200360 80085D98 010022A2 */  sb         $v0, 0x1($s1)
/* 3200364 80085D9C FF004230 */  andi       $v0, $v0, 0xFF
/* 3200368 80085DA0 1800422C */  sltiu      $v0, $v0, 0x18
/* 320036C 80085DA4 50004010 */  beqz       $v0, .Llevel_34_80085EE8
/* 3200370 80085DA8 0D0023A6 */   sh        $v1, 0xD($s1)
/* 3200374 80085DAC 02002292 */  lbu        $v0, 0x2($s1)
/* 3200378 80085DB0 00000000 */  nop
/* 320037C 80085DB4 4C004010 */  beqz       $v0, .Llevel_34_80085EE8
/* 3200380 80085DB8 00000000 */   nop
/* 3200384 80085DBC 0F002292 */  lbu        $v0, 0xF($s1)
/* 3200388 80085DC0 13002392 */  lbu        $v1, 0x13($s1)
/* 320038C 80085DC4 FDFF4224 */  addiu      $v0, $v0, -0x3
/* 3200390 80085DC8 0F0022A2 */  sb         $v0, 0xF($s1)
/* 3200394 80085DCC 10002292 */  lbu        $v0, 0x10($s1)
/* 3200398 80085DD0 FDFF6324 */  addiu      $v1, $v1, -0x3
/* 320039C 80085DD4 130023A2 */  sb         $v1, 0x13($s1)
/* 32003A0 80085DD8 FCFF4224 */  addiu      $v0, $v0, -0x4
/* 32003A4 80085DDC 100022A2 */  sb         $v0, 0x10($s1)
/* 32003A8 80085DE0 14002292 */  lbu        $v0, 0x14($s1)
/* 32003AC 80085DE4 15002392 */  lbu        $v1, 0x15($s1)
/* 32003B0 80085DE8 FCFF4224 */  addiu      $v0, $v0, -0x4
/* 32003B4 80085DEC 140022A2 */  sb         $v0, 0x14($s1)
/* 32003B8 80085DF0 0600622C */  sltiu      $v0, $v1, 0x6
/* 32003BC 80085DF4 3E004014 */  bnez       $v0, .Llevel_34_80085EF0
/* 32003C0 80085DF8 FAFF6224 */   addiu     $v0, $v1, -0x6
/* 32003C4 80085DFC BC170208 */  j          .Llevel_34_80085EF0
/* 32003C8 80085E00 150022A2 */   sb        $v0, 0x15($s1)
.L80085E04_:
/* 32003CC 80085E04 09002496 */  lhu        $a0, 0x9($s1)
/* 32003D0 80085E08 03002296 */  lhu        $v0, 0x3($s1)
/* 32003D4 80085E0C 00000000 */  nop
/* 32003D8 80085E10 23208200 */  subu       $a0, $a0, $v0
/* 32003DC 80085E14 5000A4A7 */  sh         $a0, 0x50($sp)
/* 32003E0 80085E18 0B002296 */  lhu        $v0, 0xB($s1)
/* 32003E4 80085E1C 05002396 */  lhu        $v1, 0x5($s1)
/* 32003E8 80085E20 00000000 */  nop
/* 32003EC 80085E24 23104300 */  subu       $v0, $v0, $v1
/* 32003F0 80085E28 5200A2A7 */  sh         $v0, 0x52($sp)
/* 32003F4 80085E2C 0D002296 */  lhu        $v0, 0xD($s1)
/* 32003F8 80085E30 07002396 */  lhu        $v1, 0x7($s1)
/* 32003FC 80085E34 00000000 */  nop
/* 3200400 80085E38 23104300 */  subu       $v0, $v0, $v1
/* 3200404 80085E3C 5400A2A7 */  sh         $v0, 0x54($sp)
/* 3200408 80085E40 03002296 */  lhu        $v0, 0x3($s1)
/* 320040C 80085E44 00000000 */  nop
/* 3200410 80085E48 21104400 */  addu       $v0, $v0, $a0
/* 3200414 80085E4C 030022A6 */  sh         $v0, 0x3($s1)
/* 3200418 80085E50 05002296 */  lhu        $v0, 0x5($s1)
/* 320041C 80085E54 5200A397 */  lhu        $v1, 0x52($sp)
/* 3200420 80085E58 00000000 */  nop
/* 3200424 80085E5C 21104300 */  addu       $v0, $v0, $v1
/* 3200428 80085E60 050022A6 */  sh         $v0, 0x5($s1)
/* 320042C 80085E64 07002296 */  lhu        $v0, 0x7($s1)
/* 3200430 80085E68 5400A397 */  lhu        $v1, 0x54($sp)
/* 3200434 80085E6C 00000000 */  nop
/* 3200438 80085E70 21104300 */  addu       $v0, $v0, $v1
/* 320043C 80085E74 070022A6 */  sh         $v0, 0x7($s1)
/* 3200440 80085E78 5400A297 */  lhu        $v0, 0x54($sp)
/* 3200444 80085E7C 5000A397 */  lhu        $v1, 0x50($sp)
/* 3200448 80085E80 FFFF4224 */  addiu      $v0, $v0, -0x1
/* 320044C 80085E84 5400A2A7 */  sh         $v0, 0x54($sp)
/* 3200450 80085E88 09002296 */  lhu        $v0, 0x9($s1)
/* 3200454 80085E8C 00000000 */  nop
/* 3200458 80085E90 21104300 */  addu       $v0, $v0, $v1
/* 320045C 80085E94 090022A6 */  sh         $v0, 0x9($s1)
/* 3200460 80085E98 0B002296 */  lhu        $v0, 0xB($s1)
/* 3200464 80085E9C 5200A397 */  lhu        $v1, 0x52($sp)
/* 3200468 80085EA0 00000000 */  nop
/* 320046C 80085EA4 21104300 */  addu       $v0, $v0, $v1
/* 3200470 80085EA8 0D002396 */  lhu        $v1, 0xD($s1)
/* 3200474 80085EAC 0B0022A6 */  sh         $v0, 0xB($s1)
/* 3200478 80085EB0 01002292 */  lbu        $v0, 0x1($s1)
/* 320047C 80085EB4 5400A497 */  lhu        $a0, 0x54($sp)
/* 3200480 80085EB8 01004224 */  addiu      $v0, $v0, 0x1
/* 3200484 80085EBC 21186400 */  addu       $v1, $v1, $a0
/* 3200488 80085EC0 010022A2 */  sb         $v0, 0x1($s1)
/* 320048C 80085EC4 FF004230 */  andi       $v0, $v0, 0xFF
/* 3200490 80085EC8 2000422C */  sltiu      $v0, $v0, 0x20
.Llevel_34_80085ECC:
/* 3200494 80085ECC 0D0023A6 */  sh         $v1, 0xD($s1)
.Llevel_34_80085ED0:
/* 3200498 80085ED0 05004010 */  beqz       $v0, .Llevel_34_80085EE8
/* 320049C 80085ED4 00000000 */   nop
.Llevel_34_80085ED8:
/* 32004A0 80085ED8 02002292 */  lbu        $v0, 0x2($s1)
/* 32004A4 80085EDC 00000000 */  nop
/* 32004A8 80085EE0 03004014 */  bnez       $v0, .Llevel_34_80085EF0
/* 32004AC 80085EE4 00000000 */   nop
.Llevel_34_80085EE8:
/* 32004B0 80085EE8 824D010C */  jal        func_80053608
/* 32004B4 80085EEC 21208002 */   addu      $a0, $s4, $zero
.Llevel_34_80085EF0:
/* 32004B8 80085EF0 20003126 */  addiu      $s1, $s1, 0x20
/* 32004BC 80085EF4 2000DE27 */  addiu      $fp, $fp, 0x20
/* 32004C0 80085EF8 2000B526 */  addiu      $s5, $s5, 0x20
/* 32004C4 80085EFC 00002392 */  lbu        $v1, 0x0($s1)
/* 32004C8 80085F00 FF000224 */  addiu      $v0, $zero, 0xFF
/* 32004CC 80085F04 61FA6214 */  bne        $v1, $v0, .Llevel_34_8008488C
/* 32004D0 80085F08 20009426 */   addiu     $s4, $s4, 0x20
.Llevel_34_80085F0C:
/* 32004D4 80085F0C 9C00BF8F */  lw         $ra, 0x9C($sp)
/* 32004D8 80085F10 9800BE8F */  lw         $fp, 0x98($sp)
/* 32004DC 80085F14 9400B78F */  lw         $s7, 0x94($sp)
/* 32004E0 80085F18 9000B68F */  lw         $s6, 0x90($sp)
/* 32004E4 80085F1C 8C00B58F */  lw         $s5, 0x8C($sp)
/* 32004E8 80085F20 8800B48F */  lw         $s4, 0x88($sp)
/* 32004EC 80085F24 8400B38F */  lw         $s3, 0x84($sp)
/* 32004F0 80085F28 8000B28F */  lw         $s2, 0x80($sp)
/* 32004F4 80085F2C 7C00B18F */  lw         $s1, 0x7C($sp)
/* 32004F8 80085F30 7800B08F */  lw         $s0, 0x78($sp)
/* 32004FC 80085F34 A000BD27 */  addiu      $sp, $sp, 0xA0
/* 3200500 80085F38 0800E003 */  jr         $ra
/* 3200504 80085F3C 00000000 */   nop
.size func_level_34_80084830, . - func_level_34_80084830
