.set noat      /* allow manual use of $at */
.set noreorder /* don't insert nops after branches */

.section .rodata.jtbl
.align 3
dlabel jtbl_level_21_8007B46C
/* 1B2FA34 8007B46C 48B20880 */ .word .L8008B248_
/* 1B2FA38 8007B470 CCB20880 */ .word .L8008B2CC_
/* 1B2FA3C 8007B474 50B30880 */ .word .L8008B350_
/* 1B2FA40 8007B478 F0C40880 */ .word .Llevel_21_8008C4F0
/* 1B2FA44 8007B47C F0C40880 */ .word .Llevel_21_8008C4F0
/* 1B2FA48 8007B480 F0C40880 */ .word .Llevel_21_8008C4F0
/* 1B2FA4C 8007B484 F0C40880 */ .word .Llevel_21_8008C4F0
/* 1B2FA50 8007B488 F0C40880 */ .word .Llevel_21_8008C4F0
/* 1B2FA54 8007B48C F0C40880 */ .word .Llevel_21_8008C4F0
/* 1B2FA58 8007B490 D4B30880 */ .word .L8008B3D4_
/* 1B2FA5C 8007B494 34B40880 */ .word .L8008B434_
/* 1B2FA60 8007B498 3CB50880 */ .word .L8008B53C_
/* 1B2FA64 8007B49C 80B50880 */ .word .L8008B580_
/* 1B2FA68 8007B4A0 F4B50880 */ .word .L8008B5F4_
/* 1B2FA6C 8007B4A4 F0C40880 */ .word .Llevel_21_8008C4F0
/* 1B2FA70 8007B4A8 F0C40880 */ .word .Llevel_21_8008C4F0
/* 1B2FA74 8007B4AC 24B70880 */ .word .L8008B724_
/* 1B2FA78 8007B4B0 A0B70880 */ .word .L8008B7A0_
/* 1B2FA7C 8007B4B4 F0C40880 */ .word .Llevel_21_8008C4F0
/* 1B2FA80 8007B4B8 F0C40880 */ .word .Llevel_21_8008C4F0
/* 1B2FA84 8007B4BC F0C40880 */ .word .Llevel_21_8008C4F0
/* 1B2FA88 8007B4C0 34B80880 */ .word .L8008B834_
/* 1B2FA8C 8007B4C4 F0C40880 */ .word .Llevel_21_8008C4F0
/* 1B2FA90 8007B4C8 F0C40880 */ .word .Llevel_21_8008C4F0
/* 1B2FA94 8007B4CC 04B90880 */ .word .L8008B904_
/* 1B2FA98 8007B4D0 F0C40880 */ .word .Llevel_21_8008C4F0
/* 1B2FA9C 8007B4D4 F0C40880 */ .word .Llevel_21_8008C4F0
/* 1B2FAA0 8007B4D8 F0C40880 */ .word .Llevel_21_8008C4F0
/* 1B2FAA4 8007B4DC F0C40880 */ .word .Llevel_21_8008C4F0
/* 1B2FAA8 8007B4E0 F0C40880 */ .word .Llevel_21_8008C4F0
/* 1B2FAAC 8007B4E4 F0C40880 */ .word .Llevel_21_8008C4F0
/* 1B2FAB0 8007B4E8 F0C40880 */ .word .Llevel_21_8008C4F0
/* 1B2FAB4 8007B4EC F0C40880 */ .word .Llevel_21_8008C4F0
/* 1B2FAB8 8007B4F0 3CBA0880 */ .word .L8008BA3C_
/* 1B2FABC 8007B4F4 F0C40880 */ .word .Llevel_21_8008C4F0
/* 1B2FAC0 8007B4F8 F0C40880 */ .word .Llevel_21_8008C4F0
/* 1B2FAC4 8007B4FC F0C40880 */ .word .Llevel_21_8008C4F0
/* 1B2FAC8 8007B500 F0C40880 */ .word .Llevel_21_8008C4F0
/* 1B2FACC 8007B504 F0C40880 */ .word .Llevel_21_8008C4F0
/* 1B2FAD0 8007B508 F0C40880 */ .word .Llevel_21_8008C4F0
/* 1B2FAD4 8007B50C F0C40880 */ .word .Llevel_21_8008C4F0
/* 1B2FAD8 8007B510 F0C40880 */ .word .Llevel_21_8008C4F0
/* 1B2FADC 8007B514 F0C40880 */ .word .Llevel_21_8008C4F0
/* 1B2FAE0 8007B518 F0C40880 */ .word .Llevel_21_8008C4F0
/* 1B2FAE4 8007B51C F0C40880 */ .word .Llevel_21_8008C4F0
/* 1B2FAE8 8007B520 F0C40880 */ .word .Llevel_21_8008C4F0
/* 1B2FAEC 8007B524 F0C40880 */ .word .Llevel_21_8008C4F0
/* 1B2FAF0 8007B528 F0C40880 */ .word .Llevel_21_8008C4F0
/* 1B2FAF4 8007B52C F0C40880 */ .word .Llevel_21_8008C4F0
/* 1B2FAF8 8007B530 F0C40880 */ .word .Llevel_21_8008C4F0
/* 1B2FAFC 8007B534 F0C40880 */ .word .Llevel_21_8008C4F0
/* 1B2FB00 8007B538 F0C40880 */ .word .Llevel_21_8008C4F0
/* 1B2FB04 8007B53C F0C40880 */ .word .Llevel_21_8008C4F0
/* 1B2FB08 8007B540 F0C40880 */ .word .Llevel_21_8008C4F0
/* 1B2FB0C 8007B544 F0C40880 */ .word .Llevel_21_8008C4F0
/* 1B2FB10 8007B548 F0C40880 */ .word .Llevel_21_8008C4F0
/* 1B2FB14 8007B54C F0C40880 */ .word .Llevel_21_8008C4F0
/* 1B2FB18 8007B550 F0C40880 */ .word .Llevel_21_8008C4F0
/* 1B2FB1C 8007B554 F0C40880 */ .word .Llevel_21_8008C4F0
/* 1B2FB20 8007B558 F0C40880 */ .word .Llevel_21_8008C4F0
/* 1B2FB24 8007B55C F0C40880 */ .word .Llevel_21_8008C4F0
/* 1B2FB28 8007B560 F0C40880 */ .word .Llevel_21_8008C4F0
/* 1B2FB2C 8007B564 F0C40880 */ .word .Llevel_21_8008C4F0
/* 1B2FB30 8007B568 F0C40880 */ .word .Llevel_21_8008C4F0
/* 1B2FB34 8007B56C F0C40880 */ .word .Llevel_21_8008C4F0
/* 1B2FB38 8007B570 F0C40880 */ .word .Llevel_21_8008C4F0
/* 1B2FB3C 8007B574 E0BA0880 */ .word .L8008BAE0_
/* 1B2FB40 8007B578 F0C40880 */ .word .Llevel_21_8008C4F0
/* 1B2FB44 8007B57C F0C40880 */ .word .Llevel_21_8008C4F0
/* 1B2FB48 8007B580 F0C40880 */ .word .Llevel_21_8008C4F0
/* 1B2FB4C 8007B584 ACBB0880 */ .word .L8008BBAC_
/* 1B2FB50 8007B588 98BD0880 */ .word .L8008BD98_
/* 1B2FB54 8007B58C 0CBF0880 */ .word .L8008BF0C_
/* 1B2FB58 8007B590 F0C40880 */ .word .Llevel_21_8008C4F0
/* 1B2FB5C 8007B594 F0C40880 */ .word .Llevel_21_8008C4F0
/* 1B2FB60 8007B598 F0C40880 */ .word .Llevel_21_8008C4F0
/* 1B2FB64 8007B59C 48C00880 */ .word .L8008C048_
/* 1B2FB68 8007B5A0 F8C00880 */ .word .L8008C0F8_
/* 1B2FB6C 8007B5A4 DCC10880 */ .word .L8008C1DC_
/* 1B2FB70 8007B5A8 DCC20880 */ .word .L8008C2DC_
/* 1B2FB74 8007B5AC 04C40880 */ .word .L8008C404_
.size jtbl_level_21_8007B46C, . - jtbl_level_21_8007B46C


.section .text
/* Generated by spimdisasm 1.27.0 */

glabel func_level_21_8008B1C0
/* 1B3F788 8008B1C0 98FFBD27 */  addiu      $sp, $sp, -0x68
/* 1B3F78C 8008B1C4 4800B2AF */  sw         $s2, 0x48($sp)
/* 1B3F790 8008B1C8 0780123C */  lui        $s2, %hi(D_80075824)
/* 1B3F794 8008B1CC 2458528E */  lw         $s2, %lo(D_80075824)($s2)
/* 1B3F798 8008B1D0 5000B4AF */  sw         $s4, 0x50($sp)
/* 1B3F79C 8008B1D4 6400BFAF */  sw         $ra, 0x64($sp)
/* 1B3F7A0 8008B1D8 6000BEAF */  sw         $fp, 0x60($sp)
/* 1B3F7A4 8008B1DC 5C00B7AF */  sw         $s7, 0x5C($sp)
/* 1B3F7A8 8008B1E0 5800B6AF */  sw         $s6, 0x58($sp)
/* 1B3F7AC 8008B1E4 5400B5AF */  sw         $s5, 0x54($sp)
/* 1B3F7B0 8008B1E8 4C00B3AF */  sw         $s3, 0x4C($sp)
/* 1B3F7B4 8008B1EC 4400B1AF */  sw         $s1, 0x44($sp)
/* 1B3F7B8 8008B1F0 4000B0AF */  sw         $s0, 0x40($sp)
/* 1B3F7BC 8008B1F4 01004392 */  lbu        $v1, 0x1($s2)
/* 1B3F7C0 8008B1F8 FF000224 */  addiu      $v0, $zero, 0xFF
/* 1B3F7C4 8008B1FC C3046210 */  beq        $v1, $v0, .Llevel_21_8008C50C
/* 1B3F7C8 8008B200 21A08000 */   addu      $s4, $a0, $zero
/* 1B3F7CC 8008B204 01001E24 */  addiu      $fp, $zero, 0x1
/* 1B3F7D0 8008B208 40B81400 */  sll        $s7, $s4, 1
/* 1B3F7D4 8008B20C 80A81400 */  sll        $s5, $s4, 2
/* 1B3F7D8 8008B210 01005026 */  addiu      $s0, $s2, 0x1
/* 1B3F7DC 8008B214 18005626 */  addiu      $s6, $s2, 0x18
/* 1B3F7E0 8008B218 04005326 */  addiu      $s3, $s2, 0x4
.Llevel_21_8008B21C:
/* 1B3F7E4 8008B21C 00004392 */  lbu        $v1, 0x0($s2)
/* 1B3F7E8 8008B220 00000000 */  nop
/* 1B3F7EC 8008B224 5100622C */  sltiu      $v0, $v1, 0x51
/* 1B3F7F0 8008B228 B1044010 */  beqz       $v0, .Llevel_21_8008C4F0
/* 1B3F7F4 8008B22C 80100300 */   sll       $v0, $v1, 2
/* 1B3F7F8 8008B230 0880013C */  lui        $at, %hi(jtbl_level_21_8007B46C)
/* 1B3F7FC 8008B234 21082200 */  addu       $at, $at, $v0
/* 1B3F800 8008B238 6CB4228C */  lw         $v0, %lo(jtbl_level_21_8007B46C)($at)
/* 1B3F804 8008B23C 00000000 */  nop
/* 1B3F808 8008B240 08004000 */  jr         $v0
/* 1B3F80C 8008B244 00000000 */   nop
.L8008B248_:
/* 1B3F810 8008B248 21206002 */  addu       $a0, $s3, $zero
/* 1B3F814 8008B24C 21286002 */  addu       $a1, $s3, $zero
/* 1B3F818 8008B250 215F000C */  jal        func_80017C84
/* 1B3F81C 8008B254 2130C002 */   addu      $a2, $s6, $zero
/* 1B3F820 8008B258 1D000286 */  lh         $v0, 0x1D($s0)
/* 1B3F824 8008B25C 00000000 */  nop
/* 1B3F828 8008B260 05004010 */  beqz       $v0, .Llevel_21_8008B278
/* 1B3F82C 8008B264 00000000 */   nop
/* 1B3F830 8008B268 1B000296 */  lhu        $v0, 0x1B($s0)
/* 1B3F834 8008B26C 00000000 */  nop
/* 1B3F838 8008B270 01004224 */  addiu      $v0, $v0, 0x1
/* 1B3F83C 8008B274 1B0002A6 */  sh         $v0, 0x1B($s0)
.Llevel_21_8008B278:
/* 1B3F840 8008B278 09000392 */  lbu        $v1, 0x9($s0)
/* 1B3F844 8008B27C 1D000296 */  lhu        $v0, 0x1D($s0)
/* 1B3F848 8008B280 21187700 */  addu       $v1, $v1, $s7
/* 1B3F84C 8008B284 090003A2 */  sb         $v1, 0x9($s0)
/* 1B3F850 8008B288 0C000392 */  lbu        $v1, 0xC($s0)
/* 1B3F854 8008B28C 2310C203 */  subu       $v0, $fp, $v0
/* 1B3F858 8008B290 1D0002A6 */  sh         $v0, 0x1D($s0)
/* 1B3F85C 8008B294 0B000292 */  lbu        $v0, 0xB($s0)
/* 1B3F860 8008B298 23187500 */  subu       $v1, $v1, $s5
/* 1B3F864 8008B29C 0C0003A2 */  sb         $v1, 0xC($s0)
/* 1B3F868 8008B2A0 0D000392 */  lbu        $v1, 0xD($s0)
/* 1B3F86C 8008B2A4 23105500 */  subu       $v0, $v0, $s5
/* 1B3F870 8008B2A8 0B0002A2 */  sb         $v0, 0xB($s0)
/* 1B3F874 8008B2AC 01000292 */  lbu        $v0, 0x1($s0)
/* 1B3F878 8008B2B0 23187500 */  subu       $v1, $v1, $s5
/* 1B3F87C 8008B2B4 21105400 */  addu       $v0, $v0, $s4
/* 1B3F880 8008B2B8 010002A2 */  sb         $v0, 0x1($s0)
/* 1B3F884 8008B2BC FF004230 */  andi       $v0, $v0, 0xFF
/* 1B3F888 8008B2C0 2000422C */  sltiu      $v0, $v0, 0x20
/* 1B3F88C 8008B2C4 34310208 */  j          .Llevel_21_8008C4D0
/* 1B3F890 8008B2C8 0D0003A2 */   sb        $v1, 0xD($s0)
.L8008B2CC_:
/* 1B3F894 8008B2CC 21206002 */  addu       $a0, $s3, $zero
/* 1B3F898 8008B2D0 21286002 */  addu       $a1, $s3, $zero
/* 1B3F89C 8008B2D4 215F000C */  jal        func_80017C84
/* 1B3F8A0 8008B2D8 2130C002 */   addu      $a2, $s6, $zero
/* 1B3F8A4 8008B2DC 1D000286 */  lh         $v0, 0x1D($s0)
/* 1B3F8A8 8008B2E0 00000000 */  nop
/* 1B3F8AC 8008B2E4 05004010 */  beqz       $v0, .Llevel_21_8008B2FC
/* 1B3F8B0 8008B2E8 00000000 */   nop
/* 1B3F8B4 8008B2EC 1B000296 */  lhu        $v0, 0x1B($s0)
/* 1B3F8B8 8008B2F0 00000000 */  nop
/* 1B3F8BC 8008B2F4 01004224 */  addiu      $v0, $v0, 0x1
/* 1B3F8C0 8008B2F8 1B0002A6 */  sh         $v0, 0x1B($s0)
.Llevel_21_8008B2FC:
/* 1B3F8C4 8008B2FC 09000392 */  lbu        $v1, 0x9($s0)
/* 1B3F8C8 8008B300 1D000296 */  lhu        $v0, 0x1D($s0)
/* 1B3F8CC 8008B304 21187500 */  addu       $v1, $v1, $s5
/* 1B3F8D0 8008B308 090003A2 */  sb         $v1, 0x9($s0)
/* 1B3F8D4 8008B30C 0C000392 */  lbu        $v1, 0xC($s0)
/* 1B3F8D8 8008B310 2310C203 */  subu       $v0, $fp, $v0
/* 1B3F8DC 8008B314 1D0002A6 */  sh         $v0, 0x1D($s0)
/* 1B3F8E0 8008B318 0B000292 */  lbu        $v0, 0xB($s0)
/* 1B3F8E4 8008B31C 23187500 */  subu       $v1, $v1, $s5
/* 1B3F8E8 8008B320 0C0003A2 */  sb         $v1, 0xC($s0)
/* 1B3F8EC 8008B324 0D000392 */  lbu        $v1, 0xD($s0)
/* 1B3F8F0 8008B328 23105500 */  subu       $v0, $v0, $s5
/* 1B3F8F4 8008B32C 0B0002A2 */  sb         $v0, 0xB($s0)
/* 1B3F8F8 8008B330 01000292 */  lbu        $v0, 0x1($s0)
/* 1B3F8FC 8008B334 23187500 */  subu       $v1, $v1, $s5
/* 1B3F900 8008B338 21105400 */  addu       $v0, $v0, $s4
/* 1B3F904 8008B33C 010002A2 */  sb         $v0, 0x1($s0)
/* 1B3F908 8008B340 FF004230 */  andi       $v0, $v0, 0xFF
/* 1B3F90C 8008B344 1800422C */  sltiu      $v0, $v0, 0x18
/* 1B3F910 8008B348 34310208 */  j          .Llevel_21_8008C4D0
/* 1B3F914 8008B34C 0D0003A2 */   sb        $v1, 0xD($s0)
.L8008B350_:
/* 1B3F918 8008B350 21206002 */  addu       $a0, $s3, $zero
/* 1B3F91C 8008B354 21286002 */  addu       $a1, $s3, $zero
/* 1B3F920 8008B358 215F000C */  jal        func_80017C84
/* 1B3F924 8008B35C 2130C002 */   addu      $a2, $s6, $zero
/* 1B3F928 8008B360 1D000286 */  lh         $v0, 0x1D($s0)
/* 1B3F92C 8008B364 00000000 */  nop
/* 1B3F930 8008B368 05004010 */  beqz       $v0, .Llevel_21_8008B380
/* 1B3F934 8008B36C 00000000 */   nop
/* 1B3F938 8008B370 1B000296 */  lhu        $v0, 0x1B($s0)
/* 1B3F93C 8008B374 00000000 */  nop
/* 1B3F940 8008B378 01004224 */  addiu      $v0, $v0, 0x1
/* 1B3F944 8008B37C 1B0002A6 */  sh         $v0, 0x1B($s0)
.Llevel_21_8008B380:
/* 1B3F948 8008B380 09000392 */  lbu        $v1, 0x9($s0)
/* 1B3F94C 8008B384 1D000296 */  lhu        $v0, 0x1D($s0)
/* 1B3F950 8008B388 21187500 */  addu       $v1, $v1, $s5
/* 1B3F954 8008B38C 090003A2 */  sb         $v1, 0x9($s0)
/* 1B3F958 8008B390 0C000392 */  lbu        $v1, 0xC($s0)
/* 1B3F95C 8008B394 2310C203 */  subu       $v0, $fp, $v0
/* 1B3F960 8008B398 1D0002A6 */  sh         $v0, 0x1D($s0)
/* 1B3F964 8008B39C 0B000292 */  lbu        $v0, 0xB($s0)
/* 1B3F968 8008B3A0 23187500 */  subu       $v1, $v1, $s5
/* 1B3F96C 8008B3A4 0C0003A2 */  sb         $v1, 0xC($s0)
/* 1B3F970 8008B3A8 0D000392 */  lbu        $v1, 0xD($s0)
/* 1B3F974 8008B3AC 23105500 */  subu       $v0, $v0, $s5
/* 1B3F978 8008B3B0 0B0002A2 */  sb         $v0, 0xB($s0)
/* 1B3F97C 8008B3B4 01000292 */  lbu        $v0, 0x1($s0)
/* 1B3F980 8008B3B8 23187500 */  subu       $v1, $v1, $s5
/* 1B3F984 8008B3BC 21105400 */  addu       $v0, $v0, $s4
/* 1B3F988 8008B3C0 010002A2 */  sb         $v0, 0x1($s0)
/* 1B3F98C 8008B3C4 FF004230 */  andi       $v0, $v0, 0xFF
/* 1B3F990 8008B3C8 2000422C */  sltiu      $v0, $v0, 0x20
/* 1B3F994 8008B3CC 34310208 */  j          .Llevel_21_8008C4D0
/* 1B3F998 8008B3D0 0D0003A2 */   sb        $v1, 0xD($s0)
.L8008B3D4_:
/* 1B3F99C 8008B3D4 21206002 */  addu       $a0, $s3, $zero
/* 1B3F9A0 8008B3D8 21286002 */  addu       $a1, $s3, $zero
/* 1B3F9A4 8008B3DC 215F000C */  jal        func_80017C84
/* 1B3F9A8 8008B3E0 2130C002 */   addu      $a2, $s6, $zero
/* 1B3F9AC 8008B3E4 1D000286 */  lh         $v0, 0x1D($s0)
/* 1B3F9B0 8008B3E8 00000000 */  nop
/* 1B3F9B4 8008B3EC 05004010 */  beqz       $v0, .Llevel_21_8008B404
/* 1B3F9B8 8008B3F0 00000000 */   nop
/* 1B3F9BC 8008B3F4 1B000296 */  lhu        $v0, 0x1B($s0)
/* 1B3F9C0 8008B3F8 00000000 */  nop
/* 1B3F9C4 8008B3FC 01004224 */  addiu      $v0, $v0, 0x1
/* 1B3F9C8 8008B400 1B0002A6 */  sh         $v0, 0x1B($s0)
.Llevel_21_8008B404:
/* 1B3F9CC 8008B404 1D000296 */  lhu        $v0, 0x1D($s0)
/* 1B3F9D0 8008B408 09000392 */  lbu        $v1, 0x9($s0)
/* 1B3F9D4 8008B40C 2310C203 */  subu       $v0, $fp, $v0
/* 1B3F9D8 8008B410 1D0002A6 */  sh         $v0, 0x1D($s0)
/* 1B3F9DC 8008B414 01000292 */  lbu        $v0, 0x1($s0)
/* 1B3F9E0 8008B418 21187700 */  addu       $v1, $v1, $s7
/* 1B3F9E4 8008B41C 090003A2 */  sb         $v1, 0x9($s0)
/* 1B3F9E8 8008B420 21105400 */  addu       $v0, $v0, $s4
/* 1B3F9EC 8008B424 010002A2 */  sb         $v0, 0x1($s0)
/* 1B3F9F0 8008B428 FF004230 */  andi       $v0, $v0, 0xFF
/* 1B3F9F4 8008B42C 34310208 */  j          .Llevel_21_8008C4D0
/* 1B3F9F8 8008B430 2000422C */   sltiu     $v0, $v0, 0x20
.L8008B434_:
/* 1B3F9FC 8008B434 0880033C */  lui        $v1, %hi(g_Spyro + 0x78)
/* 1B3FA00 8008B438 D08A638C */  lw         $v1, %lo(g_Spyro + 0x78)($v1)
/* 1B3FA04 8008B43C 1D000224 */  addiu      $v0, $zero, 0x1D
/* 1B3FA08 8008B440 06006214 */  bne        $v1, $v0, .Llevel_21_8008B45C
/* 1B3FA0C 8008B444 00000000 */   nop
/* 1B3FA10 8008B448 0880023C */  lui        $v0, %hi(g_Spyro + 0x164)
/* 1B3FA14 8008B44C BC8B428C */  lw         $v0, %lo(g_Spyro + 0x164)($v0)
/* 1B3FA18 8008B450 00000000 */  nop
/* 1B3FA1C 8008B454 24044004 */  bltz       $v0, .Llevel_21_8008C4E8
/* 1B3FA20 8008B458 00000000 */   nop
.Llevel_21_8008B45C:
/* 1B3FA24 8008B45C 0780023C */  lui        $v0, %hi(g_IsSpyroHidden)
/* 1B3FA28 8008B460 1458428C */  lw         $v0, %lo(g_IsSpyroHidden)($v0)
/* 1B3FA2C 8008B464 00000000 */  nop
/* 1B3FA30 8008B468 1F044014 */  bnez       $v0, .Llevel_21_8008C4E8
/* 1B3FA34 8008B46C 00000000 */   nop
/* 1B3FA38 8008B470 0880053C */  lui        $a1, %hi(g_Spyro + 0x160)
/* 1B3FA3C 8008B474 B88BA524 */  addiu      $a1, $a1, %lo(g_Spyro + 0x160)
/* 1B3FA40 8008B478 0000A28C */  lw         $v0, 0x0($a1)
/* 1B3FA44 8008B47C 00000000 */  nop
/* 1B3FA48 8008B480 19044018 */  blez       $v0, .Llevel_21_8008C4E8
/* 1B3FA4C 8008B484 1000A427 */   addiu     $a0, $sp, 0x10
/* 1B3FA50 8008B488 C05D000C */  jal        VecCopy
/* 1B3FA54 8008B48C A0FEA524 */   addiu     $a1, $a1, -0x160
/* 1B3FA58 8008B490 17000486 */  lh         $a0, 0x17($s0)
/* 1B3FA5C 8008B494 2C5B000C */  jal        Cos
/* 1B3FA60 8008B498 00000000 */   nop
/* 1B3FA64 8008B49C 1000A38F */  lw         $v1, 0x10($sp)
/* 1B3FA68 8008B4A0 03110200 */  sra        $v0, $v0, 4
/* 1B3FA6C 8008B4A4 21186200 */  addu       $v1, $v1, $v0
/* 1B3FA70 8008B4A8 1000A3AF */  sw         $v1, 0x10($sp)
/* 1B3FA74 8008B4AC 17000486 */  lh         $a0, 0x17($s0)
/* 1B3FA78 8008B4B0 165B000C */  jal        Sin
/* 1B3FA7C 8008B4B4 00000000 */   nop
/* 1B3FA80 8008B4B8 21206002 */  addu       $a0, $s3, $zero
/* 1B3FA84 8008B4BC 1000A527 */  addiu      $a1, $sp, 0x10
/* 1B3FA88 8008B4C0 03110200 */  sra        $v0, $v0, 4
/* 1B3FA8C 8008B4C4 1400A38F */  lw         $v1, 0x14($sp)
/* 1B3FA90 8008B4C8 1800A68F */  lw         $a2, 0x18($sp)
/* 1B3FA94 8008B4CC 21186200 */  addu       $v1, $v1, $v0
/* 1B3FA98 8008B4D0 0001C624 */  addiu      $a2, $a2, 0x100
/* 1B3FA9C 8008B4D4 1400A3AF */  sw         $v1, 0x14($sp)
/* 1B3FAA0 8008B4D8 FF5E000C */  jal        func_80017BFC
/* 1B3FAA4 8008B4DC 1800A6AF */   sw        $a2, 0x18($sp)
/* 1B3FAA8 8008B4E0 17000496 */  lhu        $a0, 0x17($s0)
/* 1B3FAAC 8008B4E4 00000000 */  nop
/* 1B3FAB0 8008B4E8 40008424 */  addiu      $a0, $a0, 0x40
/* 1B3FAB4 8008B4EC 170004A6 */  sh         $a0, 0x17($s0)
/* 1B3FAB8 8008B4F0 00240400 */  sll        $a0, $a0, 16
/* 1B3FABC 8008B4F4 0780023C */  lui        $v0, %hi(g_Camera + 0x50)
/* 1B3FAC0 8008B4F8 206E4284 */  lh         $v0, %lo(g_Camera + 0x50)($v0)
/* 1B3FAC4 8008B4FC 03240400 */  sra        $a0, $a0, 16
/* 1B3FAC8 8008B500 23208200 */  subu       $a0, $a0, $v0
/* 1B3FACC 8008B504 2C5B000C */  jal        Cos
/* 1B3FAD0 8008B508 FF0F8430 */   andi      $a0, $a0, 0xFFF
/* 1B3FAD4 8008B50C 6060033C */  lui        $v1, (0x60606061 >> 16)
/* 1B3FAD8 8008B510 61606334 */  ori        $v1, $v1, (0x60606061 & 0xFFFF)
/* 1B3FADC 8008B514 02004104 */  bgez       $v0, .Llevel_21_8008B520
/* 1B3FAE0 8008B518 00000000 */   nop
/* 1B3FAE4 8008B51C 23100200 */  negu       $v0, $v0
.Llevel_21_8008B520:
/* 1B3FAE8 8008B520 18004300 */  mult       $v0, $v1
/* 1B3FAEC 8008B524 C3170200 */  sra        $v0, $v0, 31
/* 1B3FAF0 8008B528 10380000 */  mfhi       $a3
/* 1B3FAF4 8008B52C 83190700 */  sra        $v1, $a3, 6
/* 1B3FAF8 8008B530 23186200 */  subu       $v1, $v1, $v0
/* 1B3FAFC 8008B534 3C310208 */  j          .Llevel_21_8008C4F0
/* 1B3FB00 8008B538 090003A2 */   sb        $v1, 0x9($s0)
.L8008B53C_:
/* 1B3FB04 8008B53C 21206002 */  addu       $a0, $s3, $zero
/* 1B3FB08 8008B540 21286002 */  addu       $a1, $s3, $zero
/* 1B3FB0C 8008B544 215F000C */  jal        func_80017C84
/* 1B3FB10 8008B548 12004626 */   addiu     $a2, $s2, 0x12
/* 1B3FB14 8008B54C 0B000292 */  lbu        $v0, 0xB($s0)
/* 1B3FB18 8008B550 0C000392 */  lbu        $v1, 0xC($s0)
/* 1B3FB1C 8008B554 F8FF4224 */  addiu      $v0, $v0, -0x8
/* 1B3FB20 8008B558 0B0002A2 */  sb         $v0, 0xB($s0)
/* 1B3FB24 8008B55C 0D000292 */  lbu        $v0, 0xD($s0)
/* 1B3FB28 8008B560 F8FF6324 */  addiu      $v1, $v1, -0x8
/* 1B3FB2C 8008B564 0C0003A2 */  sb         $v1, 0xC($s0)
/* 1B3FB30 8008B568 0B000392 */  lbu        $v1, 0xB($s0)
/* 1B3FB34 8008B56C F8FF4224 */  addiu      $v0, $v0, -0x8
/* 1B3FB38 8008B570 DD036010 */  beqz       $v1, .Llevel_21_8008C4E8
/* 1B3FB3C 8008B574 0D0002A2 */   sb        $v0, 0xD($s0)
/* 1B3FB40 8008B578 36310208 */  j          .Llevel_21_8008C4D8
/* 1B3FB44 8008B57C 00000000 */   nop
.L8008B580_:
/* 1B3FB48 8008B580 0A000292 */  lbu        $v0, 0xA($s0)
/* 1B3FB4C 8008B584 00000000 */  nop
/* 1B3FB50 8008B588 08004224 */  addiu      $v0, $v0, 0x8
/* 1B3FB54 8008B58C 0A0002A2 */  sb         $v0, 0xA($s0)
/* 1B3FB58 8008B590 09000292 */  lbu        $v0, 0x9($s0)
/* 1B3FB5C 8008B594 0B000392 */  lbu        $v1, 0xB($s0)
/* 1B3FB60 8008B598 02004224 */  addiu      $v0, $v0, 0x2
/* 1B3FB64 8008B59C 03006010 */  beqz       $v1, .Llevel_21_8008B5AC
/* 1B3FB68 8008B5A0 090002A2 */   sb        $v0, 0x9($s0)
/* 1B3FB6C 8008B5A4 F8FF6224 */  addiu      $v0, $v1, -0x8
/* 1B3FB70 8008B5A8 0B0002A2 */  sb         $v0, 0xB($s0)
.Llevel_21_8008B5AC:
/* 1B3FB74 8008B5AC 0C000292 */  lbu        $v0, 0xC($s0)
/* 1B3FB78 8008B5B0 00000000 */  nop
/* 1B3FB7C 8008B5B4 02004010 */  beqz       $v0, .Llevel_21_8008B5C0
/* 1B3FB80 8008B5B8 F8FF4224 */   addiu     $v0, $v0, -0x8
/* 1B3FB84 8008B5BC 0C0002A2 */  sb         $v0, 0xC($s0)
.Llevel_21_8008B5C0:
/* 1B3FB88 8008B5C0 0D000292 */  lbu        $v0, 0xD($s0)
/* 1B3FB8C 8008B5C4 00000000 */  nop
/* 1B3FB90 8008B5C8 02004010 */  beqz       $v0, .Llevel_21_8008B5D4
/* 1B3FB94 8008B5CC F8FF4224 */   addiu     $v0, $v0, -0x8
/* 1B3FB98 8008B5D0 0D0002A2 */  sb         $v0, 0xD($s0)
.Llevel_21_8008B5D4:
/* 1B3FB9C 8008B5D4 FF00033C */  lui        $v1, (0xFFFFFF >> 16)
/* 1B3FBA0 8008B5D8 0B00028E */  lw         $v0, 0xB($s0)
/* 1B3FBA4 8008B5DC FFFF6334 */  ori        $v1, $v1, (0xFFFFFF & 0xFFFF)
/* 1B3FBA8 8008B5E0 24104300 */  and        $v0, $v0, $v1
/* 1B3FBAC 8008B5E4 C0034010 */  beqz       $v0, .Llevel_21_8008C4E8
/* 1B3FBB0 8008B5E8 00000000 */   nop
/* 1B3FBB4 8008B5EC 36310208 */  j          .Llevel_21_8008C4D8
/* 1B3FBB8 8008B5F0 00000000 */   nop
.L8008B5F4_:
/* 1B3FBBC 8008B5F4 01000292 */  lbu        $v0, 0x1($s0)
/* 1B3FBC0 8008B5F8 00000000 */  nop
/* 1B3FBC4 8008B5FC 1C00422C */  sltiu      $v0, $v0, 0x1C
/* 1B3FBC8 8008B600 B9034010 */  beqz       $v0, .Llevel_21_8008C4E8
/* 1B3FBCC 8008B604 00000000 */   nop
/* 1B3FBD0 8008B608 02000292 */  lbu        $v0, 0x2($s0)
/* 1B3FBD4 8008B60C 00000000 */  nop
/* 1B3FBD8 8008B610 B5034010 */  beqz       $v0, .Llevel_21_8008C4E8
/* 1B3FBDC 8008B614 21206002 */   addu      $a0, $s3, $zero
/* 1B3FBE0 8008B618 21286002 */  addu       $a1, $s3, $zero
/* 1B3FBE4 8008B61C 215F000C */  jal        func_80017C84
/* 1B3FBE8 8008B620 2130C002 */   addu      $a2, $s6, $zero
/* 1B3FBEC 8008B624 1D000286 */  lh         $v0, 0x1D($s0)
/* 1B3FBF0 8008B628 00000000 */  nop
/* 1B3FBF4 8008B62C 05004010 */  beqz       $v0, .Llevel_21_8008B644
/* 1B3FBF8 8008B630 00000000 */   nop
/* 1B3FBFC 8008B634 1B000296 */  lhu        $v0, 0x1B($s0)
/* 1B3FC00 8008B638 00000000 */  nop
/* 1B3FC04 8008B63C 01004224 */  addiu      $v0, $v0, 0x1
/* 1B3FC08 8008B640 1B0002A6 */  sh         $v0, 0x1B($s0)
.Llevel_21_8008B644:
/* 1B3FC0C 8008B644 1D000296 */  lhu        $v0, 0x1D($s0)
/* 1B3FC10 8008B648 00000000 */  nop
/* 1B3FC14 8008B64C 2310C203 */  subu       $v0, $fp, $v0
/* 1B3FC18 8008B650 1D0002A6 */  sh         $v0, 0x1D($s0)
/* 1B3FC1C 8008B654 09000292 */  lbu        $v0, 0x9($s0)
/* 1B3FC20 8008B658 01000392 */  lbu        $v1, 0x1($s0)
/* 1B3FC24 8008B65C 21105700 */  addu       $v0, $v0, $s7
/* 1B3FC28 8008B660 090002A2 */  sb         $v0, 0x9($s0)
/* 1B3FC2C 8008B664 0D00622C */  sltiu      $v0, $v1, 0xD
/* 1B3FC30 8008B668 14004014 */  bnez       $v0, .Llevel_21_8008B6BC
/* 1B3FC34 8008B66C 0500622C */   sltiu     $v0, $v1, 0x5
/* 1B3FC38 8008B670 F4FF6224 */  addiu      $v0, $v1, -0xC
/* 1B3FC3C 8008B674 C0100200 */  sll        $v0, $v0, 3
/* 1B3FC40 8008B678 80000324 */  addiu      $v1, $zero, 0x80
/* 1B3FC44 8008B67C 23106200 */  subu       $v0, $v1, $v0
/* 1B3FC48 8008B680 02004104 */  bgez       $v0, .Llevel_21_8008B68C
/* 1B3FC4C 8008B684 00000000 */   nop
/* 1B3FC50 8008B688 21100000 */  addu       $v0, $zero, $zero
.Llevel_21_8008B68C:
/* 1B3FC54 8008B68C 01000392 */  lbu        $v1, 0x1($s0)
/* 1B3FC58 8008B690 0B0002A2 */  sb         $v0, 0xB($s0)
/* 1B3FC5C 8008B694 40000224 */  addiu      $v0, $zero, 0x40
/* 1B3FC60 8008B698 F4FF6324 */  addiu      $v1, $v1, -0xC
/* 1B3FC64 8008B69C 80180300 */  sll        $v1, $v1, 2
/* 1B3FC68 8008B6A0 23104300 */  subu       $v0, $v0, $v1
/* 1B3FC6C 8008B6A4 02004104 */  bgez       $v0, .Llevel_21_8008B6B0
/* 1B3FC70 8008B6A8 00000000 */   nop
/* 1B3FC74 8008B6AC 21100000 */  addu       $v0, $zero, $zero
.Llevel_21_8008B6B0:
/* 1B3FC78 8008B6B0 0C0002A2 */  sb         $v0, 0xC($s0)
/* 1B3FC7C 8008B6B4 C42D0208 */  j          .Llevel_21_8008B710
/* 1B3FC80 8008B6B8 0D0000A2 */   sb        $zero, 0xD($s0)
.Llevel_21_8008B6BC:
/* 1B3FC84 8008B6BC 0A004014 */  bnez       $v0, .Llevel_21_8008B6E8
/* 1B3FC88 8008B6C0 80000224 */   addiu     $v0, $zero, 0x80
/* 1B3FC8C 8008B6C4 01000392 */  lbu        $v1, 0x1($s0)
/* 1B3FC90 8008B6C8 0B0002A2 */  sb         $v0, 0xB($s0)
/* 1B3FC94 8008B6CC 80FF0224 */  addiu      $v0, $zero, -0x80
/* 1B3FC98 8008B6D0 0D0000A2 */  sb         $zero, 0xD($s0)
/* 1B3FC9C 8008B6D4 FCFF6324 */  addiu      $v1, $v1, -0x4
/* 1B3FCA0 8008B6D8 C0180300 */  sll        $v1, $v1, 3
/* 1B3FCA4 8008B6DC 23104300 */  subu       $v0, $v0, $v1
/* 1B3FCA8 8008B6E0 C42D0208 */  j          .Llevel_21_8008B710
/* 1B3FCAC 8008B6E4 0C0002A2 */   sb        $v0, 0xC($s0)
.Llevel_21_8008B6E8:
/* 1B3FCB0 8008B6E8 01000392 */  lbu        $v1, 0x1($s0)
/* 1B3FCB4 8008B6EC 0B0002A2 */  sb         $v0, 0xB($s0)
/* 1B3FCB8 8008B6F0 0C0002A2 */  sb         $v0, 0xC($s0)
/* 1B3FCBC 8008B6F4 80000224 */  addiu      $v0, $zero, 0x80
/* 1B3FCC0 8008B6F8 40190300 */  sll        $v1, $v1, 5
/* 1B3FCC4 8008B6FC 23104300 */  subu       $v0, $v0, $v1
/* 1B3FCC8 8008B700 02004104 */  bgez       $v0, .Llevel_21_8008B70C
/* 1B3FCCC 8008B704 00000000 */   nop
/* 1B3FCD0 8008B708 21100000 */  addu       $v0, $zero, $zero
.Llevel_21_8008B70C:
/* 1B3FCD4 8008B70C 0D0002A2 */  sb         $v0, 0xD($s0)
.Llevel_21_8008B710:
/* 1B3FCD8 8008B710 01000292 */  lbu        $v0, 0x1($s0)
/* 1B3FCDC 8008B714 00000000 */  nop
/* 1B3FCE0 8008B718 21105400 */  addu       $v0, $v0, $s4
/* 1B3FCE4 8008B71C 3C310208 */  j          .Llevel_21_8008C4F0
/* 1B3FCE8 8008B720 010002A2 */   sb        $v0, 0x1($s0)
.L8008B724_:
/* 1B3FCEC 8008B724 21206002 */  addu       $a0, $s3, $zero
/* 1B3FCF0 8008B728 21286002 */  addu       $a1, $s3, $zero
/* 1B3FCF4 8008B72C 215F000C */  jal        func_80017C84
/* 1B3FCF8 8008B730 2130C002 */   addu      $a2, $s6, $zero
/* 1B3FCFC 8008B734 1D000286 */  lh         $v0, 0x1D($s0)
/* 1B3FD00 8008B738 00000000 */  nop
/* 1B3FD04 8008B73C 05004010 */  beqz       $v0, .Llevel_21_8008B754
/* 1B3FD08 8008B740 00000000 */   nop
/* 1B3FD0C 8008B744 1B000296 */  lhu        $v0, 0x1B($s0)
/* 1B3FD10 8008B748 00000000 */  nop
/* 1B3FD14 8008B74C 01004224 */  addiu      $v0, $v0, 0x1
/* 1B3FD18 8008B750 1B0002A6 */  sh         $v0, 0x1B($s0)
.Llevel_21_8008B754:
/* 1B3FD1C 8008B754 1D000296 */  lhu        $v0, 0x1D($s0)
/* 1B3FD20 8008B758 09000392 */  lbu        $v1, 0x9($s0)
/* 1B3FD24 8008B75C 2310C203 */  subu       $v0, $fp, $v0
/* 1B3FD28 8008B760 1D0002A6 */  sh         $v0, 0x1D($s0)
/* 1B3FD2C 8008B764 0B000292 */  lbu        $v0, 0xB($s0)
/* 1B3FD30 8008B768 21187700 */  addu       $v1, $v1, $s7
/* 1B3FD34 8008B76C 090003A2 */  sb         $v1, 0x9($s0)
/* 1B3FD38 8008B770 0C000392 */  lbu        $v1, 0xC($s0)
/* 1B3FD3C 8008B774 FCFF4224 */  addiu      $v0, $v0, -0x4
/* 1B3FD40 8008B778 0B0002A2 */  sb         $v0, 0xB($s0)
/* 1B3FD44 8008B77C 0D000292 */  lbu        $v0, 0xD($s0)
/* 1B3FD48 8008B780 FCFF6324 */  addiu      $v1, $v1, -0x4
/* 1B3FD4C 8008B784 0C0003A2 */  sb         $v1, 0xC($s0)
/* 1B3FD50 8008B788 0B000392 */  lbu        $v1, 0xB($s0)
/* 1B3FD54 8008B78C FCFF4224 */  addiu      $v0, $v0, -0x4
/* 1B3FD58 8008B790 55036010 */  beqz       $v1, .Llevel_21_8008C4E8
/* 1B3FD5C 8008B794 0D0002A2 */   sb        $v0, 0xD($s0)
/* 1B3FD60 8008B798 36310208 */  j          .Llevel_21_8008C4D8
/* 1B3FD64 8008B79C 00000000 */   nop
.L8008B7A0_:
/* 1B3FD68 8008B7A0 21206002 */  addu       $a0, $s3, $zero
/* 1B3FD6C 8008B7A4 21286002 */  addu       $a1, $s3, $zero
/* 1B3FD70 8008B7A8 215F000C */  jal        func_80017C84
/* 1B3FD74 8008B7AC 2130C002 */   addu      $a2, $s6, $zero
/* 1B3FD78 8008B7B0 1D000286 */  lh         $v0, 0x1D($s0)
/* 1B3FD7C 8008B7B4 00000000 */  nop
/* 1B3FD80 8008B7B8 05004010 */  beqz       $v0, .Llevel_21_8008B7D0
/* 1B3FD84 8008B7BC 00000000 */   nop
/* 1B3FD88 8008B7C0 1B000296 */  lhu        $v0, 0x1B($s0)
/* 1B3FD8C 8008B7C4 00000000 */  nop
/* 1B3FD90 8008B7C8 01004224 */  addiu      $v0, $v0, 0x1
/* 1B3FD94 8008B7CC 1B0002A6 */  sh         $v0, 0x1B($s0)
.Llevel_21_8008B7D0:
/* 1B3FD98 8008B7D0 1D000296 */  lhu        $v0, 0x1D($s0)
/* 1B3FD9C 8008B7D4 01000392 */  lbu        $v1, 0x1($s0)
/* 1B3FDA0 8008B7D8 2310C203 */  subu       $v0, $fp, $v0
/* 1B3FDA4 8008B7DC 1D0002A6 */  sh         $v0, 0x1D($s0)
/* 1B3FDA8 8008B7E0 09000292 */  lbu        $v0, 0x9($s0)
/* 1B3FDAC 8008B7E4 0900632C */  sltiu      $v1, $v1, 0x9
/* 1B3FDB0 8008B7E8 21105700 */  addu       $v0, $v0, $s7
/* 1B3FDB4 8008B7EC 05006014 */  bnez       $v1, .Llevel_21_8008B804
/* 1B3FDB8 8008B7F0 090002A2 */   sb        $v0, 0x9($s0)
/* 1B3FDBC 8008B7F4 0B000292 */  lbu        $v0, 0xB($s0)
/* 1B3FDC0 8008B7F8 00000000 */  nop
/* 1B3FDC4 8008B7FC E0FF4224 */  addiu      $v0, $v0, -0x20
/* 1B3FDC8 8008B800 0B0002A2 */  sb         $v0, 0xB($s0)
.Llevel_21_8008B804:
/* 1B3FDCC 8008B804 01000292 */  lbu        $v0, 0x1($s0)
/* 1B3FDD0 8008B808 0C000392 */  lbu        $v1, 0xC($s0)
/* 1B3FDD4 8008B80C 0D000492 */  lbu        $a0, 0xD($s0)
/* 1B3FDD8 8008B810 01004224 */  addiu      $v0, $v0, 0x1
/* 1B3FDDC 8008B814 F8FF6324 */  addiu      $v1, $v1, -0x8
/* 1B3FDE0 8008B818 FCFF8424 */  addiu      $a0, $a0, -0x4
/* 1B3FDE4 8008B81C 010002A2 */  sb         $v0, 0x1($s0)
/* 1B3FDE8 8008B820 FF004230 */  andi       $v0, $v0, 0xFF
/* 1B3FDEC 8008B824 0C00422C */  sltiu      $v0, $v0, 0xC
/* 1B3FDF0 8008B828 0C0003A2 */  sb         $v1, 0xC($s0)
/* 1B3FDF4 8008B82C 34310208 */  j          .Llevel_21_8008C4D0
/* 1B3FDF8 8008B830 0D0004A2 */   sb        $a0, 0xD($s0)
.L8008B834_:
/* 1B3FDFC 8008B834 0780023C */  lui        $v0, %hi(g_DeltaTime)
/* 1B3FE00 8008B838 CC56428C */  lw         $v0, %lo(g_DeltaTime)($v0)
/* 1B3FE04 8008B83C 17000392 */  lbu        $v1, 0x17($s0)
/* 1B3FE08 8008B840 80100200 */  sll        $v0, $v0, 2
/* 1B3FE0C 8008B844 21186200 */  addu       $v1, $v1, $v0
/* 1B3FE10 8008B848 170003A2 */  sb         $v1, 0x17($s0)
/* 1B3FE14 8008B84C 0780043C */  lui        $a0, %hi(g_DeltaTime)
/* 1B3FE18 8008B850 CC56848C */  lw         $a0, %lo(g_DeltaTime)($a0)
/* 1B3FE1C 8008B854 18000292 */  lbu        $v0, 0x18($s0)
/* 1B3FE20 8008B858 17000392 */  lbu        $v1, 0x17($s0)
/* 1B3FE24 8008B85C 21104400 */  addu       $v0, $v0, $a0
/* 1B3FE28 8008B860 40180300 */  sll        $v1, $v1, 1
/* 1B3FE2C 8008B864 180002A2 */  sb         $v0, 0x18($s0)
/* 1B3FE30 8008B868 0780013C */  lui        $at, %hi(D_8006CC78)
/* 1B3FE34 8008B86C 21082300 */  addu       $at, $at, $v1
/* 1B3FE38 8008B870 78CC2384 */  lh         $v1, %lo(D_8006CC78)($at)
/* 1B3FE3C 8008B874 FF004230 */  andi       $v0, $v0, 0xFF
/* 1B3FE40 8008B878 18006200 */  mult       $v1, $v0
/* 1B3FE44 8008B87C 17000392 */  lbu        $v1, 0x17($s0)
/* 1B3FE48 8008B880 11000296 */  lhu        $v0, 0x11($s0)
/* 1B3FE4C 8008B884 40180300 */  sll        $v1, $v1, 1
/* 1B3FE50 8008B888 12380000 */  mflo       $a3
/* 1B3FE54 8008B88C 03230700 */  sra        $a0, $a3, 12
/* 1B3FE58 8008B890 21104400 */  addu       $v0, $v0, $a0
/* 1B3FE5C 8008B894 030002A6 */  sh         $v0, 0x3($s0)
/* 1B3FE60 8008B898 0780013C */  lui        $at, %hi(D_8006CBF8)
/* 1B3FE64 8008B89C 21082300 */  addu       $at, $at, $v1
/* 1B3FE68 8008B8A0 F8CB2384 */  lh         $v1, %lo(D_8006CBF8)($at)
/* 1B3FE6C 8008B8A4 18000292 */  lbu        $v0, 0x18($s0)
/* 1B3FE70 8008B8A8 00000000 */  nop
/* 1B3FE74 8008B8AC 18006200 */  mult       $v1, $v0
/* 1B3FE78 8008B8B0 0780023C */  lui        $v0, %hi(g_DeltaTime)
/* 1B3FE7C 8008B8B4 CC56428C */  lw         $v0, %lo(g_DeltaTime)($v0)
/* 1B3FE80 8008B8B8 0A000492 */  lbu        $a0, 0xA($s0)
/* 1B3FE84 8008B8BC 40180200 */  sll        $v1, $v0, 1
/* 1B3FE88 8008B8C0 21186200 */  addu       $v1, $v1, $v0
/* 1B3FE8C 8008B8C4 07000296 */  lhu        $v0, 0x7($s0)
/* 1B3FE90 8008B8C8 40180300 */  sll        $v1, $v1, 1
/* 1B3FE94 8008B8CC 21104300 */  addu       $v0, $v0, $v1
/* 1B3FE98 8008B8D0 18000392 */  lbu        $v1, 0x18($s0)
/* 1B3FE9C 8008B8D4 04008424 */  addiu      $a0, $a0, 0x4
/* 1B3FEA0 8008B8D8 0A0004A2 */  sb         $a0, 0xA($s0)
/* 1B3FEA4 8008B8DC 070002A6 */  sh         $v0, 0x7($s0)
/* 1B3FEA8 8008B8E0 13000296 */  lhu        $v0, 0x13($s0)
/* 1B3FEAC 8008B8E4 C100632C */  sltiu      $v1, $v1, 0xC1
.Llevel_21_8008B8E8:
/* 1B3FEB0 8008B8E8 12380000 */  mflo       $a3
/* 1B3FEB4 8008B8EC 03230700 */  sra        $a0, $a3, 12
/* 1B3FEB8 8008B8F0 21104400 */  addu       $v0, $v0, $a0
/* 1B3FEBC 8008B8F4 FE026014 */  bnez       $v1, .Llevel_21_8008C4F0
/* 1B3FEC0 8008B8F8 050002A6 */   sh        $v0, 0x5($s0)
/* 1B3FEC4 8008B8FC 3A310208 */  j          .Llevel_21_8008C4E8
/* 1B3FEC8 8008B900 00000000 */   nop
.L8008B904_:
/* 1B3FECC 8008B904 0B000392 */  lbu        $v1, 0xB($s0)
/* 1B3FED0 8008B908 00000000 */  nop
/* 1B3FED4 8008B90C F000622C */  sltiu      $v0, $v1, 0xF0
/* 1B3FED8 8008B910 02004010 */  beqz       $v0, .Llevel_21_8008B91C
/* 1B3FEDC 8008B914 04006224 */   addiu     $v0, $v1, 0x4
/* 1B3FEE0 8008B918 0B0002A2 */  sb         $v0, 0xB($s0)
.Llevel_21_8008B91C:
/* 1B3FEE4 8008B91C 0C000392 */  lbu        $v1, 0xC($s0)
/* 1B3FEE8 8008B920 00000000 */  nop
/* 1B3FEEC 8008B924 F000622C */  sltiu      $v0, $v1, 0xF0
/* 1B3FEF0 8008B928 02004010 */  beqz       $v0, .Llevel_21_8008B934
/* 1B3FEF4 8008B92C 04006224 */   addiu     $v0, $v1, 0x4
/* 1B3FEF8 8008B930 0C0002A2 */  sb         $v0, 0xC($s0)
.Llevel_21_8008B934:
/* 1B3FEFC 8008B934 0D000392 */  lbu        $v1, 0xD($s0)
/* 1B3FF00 8008B938 00000000 */  nop
/* 1B3FF04 8008B93C F000622C */  sltiu      $v0, $v1, 0xF0
/* 1B3FF08 8008B940 02004010 */  beqz       $v0, .Llevel_21_8008B94C
/* 1B3FF0C 8008B944 04006224 */   addiu     $v0, $v1, 0x4
/* 1B3FF10 8008B948 0D0002A2 */  sb         $v0, 0xD($s0)
.Llevel_21_8008B94C:
/* 1B3FF14 8008B94C 0780023C */  lui        $v0, %hi(g_DeltaTime)
/* 1B3FF18 8008B950 CC56428C */  lw         $v0, %lo(g_DeltaTime)($v0)
/* 1B3FF1C 8008B954 1B000392 */  lbu        $v1, 0x1B($s0)
/* 1B3FF20 8008B958 C0100200 */  sll        $v0, $v0, 3
/* 1B3FF24 8008B95C 21186200 */  addu       $v1, $v1, $v0
/* 1B3FF28 8008B960 1B0003A2 */  sb         $v1, 0x1B($s0)
/* 1B3FF2C 8008B964 0780033C */  lui        $v1, %hi(g_DragonCutscene + 0x3C)
/* 1B3FF30 8008B968 6C70638C */  lw         $v1, %lo(g_DragonCutscene + 0x3C)($v1)
/* 1B3FF34 8008B96C 00000000 */  nop
/* 1B3FF38 8008B970 40006228 */  slti       $v0, $v1, 0x40
/* 1B3FF3C 8008B974 02004010 */  beqz       $v0, .Llevel_21_8008B980
/* 1B3FF40 8008B978 3F000424 */   addiu     $a0, $zero, 0x3F
/* 1B3FF44 8008B97C 21206000 */  addu       $a0, $v1, $zero
.Llevel_21_8008B980:
/* 1B3FF48 8008B980 48000224 */  addiu      $v0, $zero, 0x48
/* 1B3FF4C 8008B984 1C000392 */  lbu        $v1, 0x1C($s0)
/* 1B3FF50 8008B988 23104400 */  subu       $v0, $v0, $a0
/* 1B3FF54 8008B98C 18006200 */  mult       $v1, $v0
/* 1B3FF58 8008B990 1C000392 */  lbu        $v1, 0x1C($s0)
/* 1B3FF5C 8008B994 12280000 */  mflo       $a1
/* 1B3FF60 8008B998 20000224 */  addiu      $v0, $zero, 0x20
/* 1B3FF64 8008B99C 23104300 */  subu       $v0, $v0, $v1
/* 1B3FF68 8008B9A0 18004400 */  mult       $v0, $a0
/* 1B3FF6C 8008B9A4 C3100500 */  sra        $v0, $a1, 3
/* 1B3FF70 8008B9A8 170002A6 */  sh         $v0, 0x17($s0)
/* 1B3FF74 8008B9AC 12180000 */  mflo       $v1
/* 1B3FF78 8008B9B0 03110300 */  sra        $v0, $v1, 4
/* 1B3FF7C 8008B9B4 1B000392 */  lbu        $v1, 0x1B($s0)
/* 1B3FF80 8008B9B8 08004224 */  addiu      $v0, $v0, 0x8
/* 1B3FF84 8008B9BC 190002A6 */  sh         $v0, 0x19($s0)
/* 1B3FF88 8008B9C0 00140200 */  sll        $v0, $v0, 16
/* 1B3FF8C 8008B9C4 40180300 */  sll        $v1, $v1, 1
/* 1B3FF90 8008B9C8 0780013C */  lui        $at, %hi(D_8006CC78)
/* 1B3FF94 8008B9CC 21082300 */  addu       $at, $at, $v1
/* 1B3FF98 8008B9D0 78CC2384 */  lh         $v1, %lo(D_8006CC78)($at)
/* 1B3FF9C 8008B9D4 03140200 */  sra        $v0, $v0, 16
/* 1B3FFA0 8008B9D8 18006200 */  mult       $v1, $v0
/* 1B3FFA4 8008B9DC 11000296 */  lhu        $v0, 0x11($s0)
/* 1B3FFA8 8008B9E0 12180000 */  mflo       $v1
/* 1B3FFAC 8008B9E4 03230300 */  sra        $a0, $v1, 12
/* 1B3FFB0 8008B9E8 1B000392 */  lbu        $v1, 0x1B($s0)
/* 1B3FFB4 8008B9EC 21104400 */  addu       $v0, $v0, $a0
/* 1B3FFB8 8008B9F0 030002A6 */  sh         $v0, 0x3($s0)
/* 1B3FFBC 8008B9F4 19000286 */  lh         $v0, 0x19($s0)
/* 1B3FFC0 8008B9F8 40180300 */  sll        $v1, $v1, 1
/* 1B3FFC4 8008B9FC 0780013C */  lui        $at, %hi(D_8006CBF8)
/* 1B3FFC8 8008BA00 21082300 */  addu       $at, $at, $v1
/* 1B3FFCC 8008BA04 F8CB2384 */  lh         $v1, %lo(D_8006CBF8)($at)
/* 1B3FFD0 8008BA08 00000000 */  nop
/* 1B3FFD4 8008BA0C 18006200 */  mult       $v1, $v0
/* 1B3FFD8 8008BA10 17000296 */  lhu        $v0, 0x17($s0)
/* 1B3FFDC 8008BA14 15000396 */  lhu        $v1, 0x15($s0)
/* 1B3FFE0 8008BA18 20004224 */  addiu      $v0, $v0, 0x20
/* 1B3FFE4 8008BA1C 21186200 */  addu       $v1, $v1, $v0
/* 1B3FFE8 8008BA20 13000296 */  lhu        $v0, 0x13($s0)
/* 1B3FFEC 8008BA24 070003A6 */  sh         $v1, 0x7($s0)
/* 1B3FFF0 8008BA28 12400000 */  mflo       $t0
/* 1B3FFF4 8008BA2C 031B0800 */  sra        $v1, $t0, 12
/* 1B3FFF8 8008BA30 21104300 */  addu       $v0, $v0, $v1
/* 1B3FFFC 8008BA34 3C310208 */  j          .Llevel_21_8008C4F0
/* 1B40000 8008BA38 050002A6 */   sh        $v0, 0x5($s0)
.L8008BA3C_:
/* 1B40004 8008BA3C 21206002 */  addu       $a0, $s3, $zero
/* 1B40008 8008BA40 21286002 */  addu       $a1, $s3, $zero
/* 1B4000C 8008BA44 215F000C */  jal        func_80017C84
/* 1B40010 8008BA48 2130C002 */   addu      $a2, $s6, $zero
/* 1B40014 8008BA4C 1D000286 */  lh         $v0, 0x1D($s0)
/* 1B40018 8008BA50 00000000 */  nop
/* 1B4001C 8008BA54 05004010 */  beqz       $v0, .Llevel_21_8008BA6C
/* 1B40020 8008BA58 00000000 */   nop
/* 1B40024 8008BA5C 1B000296 */  lhu        $v0, 0x1B($s0)
/* 1B40028 8008BA60 00000000 */  nop
/* 1B4002C 8008BA64 01004224 */  addiu      $v0, $v0, 0x1
/* 1B40030 8008BA68 1B0002A6 */  sh         $v0, 0x1B($s0)
.Llevel_21_8008BA6C:
/* 1B40034 8008BA6C 0B000292 */  lbu        $v0, 0xB($s0)
/* 1B40038 8008BA70 09000392 */  lbu        $v1, 0x9($s0)
/* 1B4003C 8008BA74 23205400 */  subu       $a0, $v0, $s4
/* 1B40040 8008BA78 1D000296 */  lhu        $v0, 0x1D($s0)
/* 1B40044 8008BA7C 21187700 */  addu       $v1, $v1, $s7
/* 1B40048 8008BA80 090003A2 */  sb         $v1, 0x9($s0)
/* 1B4004C 8008BA84 2310C203 */  subu       $v0, $fp, $v0
/* 1B40050 8008BA88 02008104 */  bgez       $a0, .Llevel_21_8008BA94
/* 1B40054 8008BA8C 1D0002A6 */   sh        $v0, 0x1D($s0)
/* 1B40058 8008BA90 21200000 */  addu       $a0, $zero, $zero
.Llevel_21_8008BA94:
/* 1B4005C 8008BA94 0C000292 */  lbu        $v0, 0xC($s0)
/* 1B40060 8008BA98 0B0004A2 */  sb         $a0, 0xB($s0)
/* 1B40064 8008BA9C 23205400 */  subu       $a0, $v0, $s4
/* 1B40068 8008BAA0 02008104 */  bgez       $a0, .Llevel_21_8008BAAC
/* 1B4006C 8008BAA4 00000000 */   nop
/* 1B40070 8008BAA8 21200000 */  addu       $a0, $zero, $zero
.Llevel_21_8008BAAC:
/* 1B40074 8008BAAC 0D000292 */  lbu        $v0, 0xD($s0)
/* 1B40078 8008BAB0 0C0004A2 */  sb         $a0, 0xC($s0)
/* 1B4007C 8008BAB4 23205400 */  subu       $a0, $v0, $s4
/* 1B40080 8008BAB8 02008104 */  bgez       $a0, .Llevel_21_8008BAC4
/* 1B40084 8008BABC 00000000 */   nop
/* 1B40088 8008BAC0 21200000 */  addu       $a0, $zero, $zero
.Llevel_21_8008BAC4:
/* 1B4008C 8008BAC4 01000292 */  lbu        $v0, 0x1($s0)
/* 1B40090 8008BAC8 0D0004A2 */  sb         $a0, 0xD($s0)
/* 1B40094 8008BACC 21105400 */  addu       $v0, $v0, $s4
/* 1B40098 8008BAD0 010002A2 */  sb         $v0, 0x1($s0)
/* 1B4009C 8008BAD4 FF004230 */  andi       $v0, $v0, 0xFF
/* 1B400A0 8008BAD8 34310208 */  j          .Llevel_21_8008C4D0
/* 1B400A4 8008BADC 2000422C */   sltiu     $v0, $v0, 0x20
.L8008BAE0_:
/* 1B400A8 8008BAE0 2F00801A */  blez       $s4, .Llevel_21_8008BBA0
/* 1B400AC 8008BAE4 21880000 */   addu      $s1, $zero, $zero
.Llevel_21_8008BAE8:
/* 1B400B0 8008BAE8 01000292 */  lbu        $v0, 0x1($s0)
/* 1B400B4 8008BAEC 00000000 */  nop
/* 1B400B8 8008BAF0 01004230 */  andi       $v0, $v0, 0x1
/* 1B400BC 8008BAF4 23004010 */  beqz       $v0, .Llevel_21_8008BB84
/* 1B400C0 8008BAF8 00000000 */   nop
/* 1B400C4 8008BAFC 03000296 */  lhu        $v0, 0x3($s0)
/* 1B400C8 8008BB00 0F000496 */  lhu        $a0, 0xF($s0)
/* 1B400CC 8008BB04 05000396 */  lhu        $v1, 0x5($s0)
/* 1B400D0 8008BB08 11000596 */  lhu        $a1, 0x11($s0)
/* 1B400D4 8008BB0C 21104400 */  addu       $v0, $v0, $a0
/* 1B400D8 8008BB10 030002A6 */  sh         $v0, 0x3($s0)
/* 1B400DC 8008BB14 07000296 */  lhu        $v0, 0x7($s0)
/* 1B400E0 8008BB18 13000496 */  lhu        $a0, 0x13($s0)
/* 1B400E4 8008BB1C 21186500 */  addu       $v1, $v1, $a1
/* 1B400E8 8008BB20 050003A6 */  sh         $v1, 0x5($s0)
/* 1B400EC 8008BB24 01000392 */  lbu        $v1, 0x1($s0)
/* 1B400F0 8008BB28 21104400 */  addu       $v0, $v0, $a0
/* 1B400F4 8008BB2C 02006330 */  andi       $v1, $v1, 0x2
/* 1B400F8 8008BB30 14006010 */  beqz       $v1, .Llevel_21_8008BB84
/* 1B400FC 8008BB34 070002A6 */   sh        $v0, 0x7($s0)
/* 1B40100 8008BB38 CB89010C */  jal        rand
/* 1B40104 8008BB3C 00000000 */   nop
/* 1B40108 8008BB40 0F000396 */  lhu        $v1, 0xF($s0)
/* 1B4010C 8008BB44 02004230 */  andi       $v0, $v0, 0x2
/* 1B40110 8008BB48 FFFF6324 */  addiu      $v1, $v1, -0x1
/* 1B40114 8008BB4C 21186200 */  addu       $v1, $v1, $v0
/* 1B40118 8008BB50 CB89010C */  jal        rand
/* 1B4011C 8008BB54 0F0003A6 */   sh        $v1, 0xF($s0)
/* 1B40120 8008BB58 11000396 */  lhu        $v1, 0x11($s0)
/* 1B40124 8008BB5C 02004230 */  andi       $v0, $v0, 0x2
/* 1B40128 8008BB60 FFFF6324 */  addiu      $v1, $v1, -0x1
/* 1B4012C 8008BB64 21186200 */  addu       $v1, $v1, $v0
/* 1B40130 8008BB68 CB89010C */  jal        rand
/* 1B40134 8008BB6C 110003A6 */   sh        $v1, 0x11($s0)
/* 1B40138 8008BB70 13000396 */  lhu        $v1, 0x13($s0)
/* 1B4013C 8008BB74 02004230 */  andi       $v0, $v0, 0x2
/* 1B40140 8008BB78 FFFF6324 */  addiu      $v1, $v1, -0x1
/* 1B40144 8008BB7C 21186200 */  addu       $v1, $v1, $v0
/* 1B40148 8008BB80 130003A6 */  sh         $v1, 0x13($s0)
.Llevel_21_8008BB84:
/* 1B4014C 8008BB84 01000292 */  lbu        $v0, 0x1($s0)
/* 1B40150 8008BB88 01003126 */  addiu      $s1, $s1, 0x1
/* 1B40154 8008BB8C 01004224 */  addiu      $v0, $v0, 0x1
/* 1B40158 8008BB90 010002A2 */  sb         $v0, 0x1($s0)
/* 1B4015C 8008BB94 2A103402 */  slt        $v0, $s1, $s4
/* 1B40160 8008BB98 D3FF4014 */  bnez       $v0, .Llevel_21_8008BAE8
/* 1B40164 8008BB9C 00000000 */   nop
.Llevel_21_8008BBA0:
/* 1B40168 8008BBA0 01000292 */  lbu        $v0, 0x1($s0)
/* 1B4016C 8008BBA4 34310208 */  j          .Llevel_21_8008C4D0
/* 1B40170 8008BBA8 1800422C */   sltiu     $v0, $v0, 0x18
.L8008BBAC_:
/* 1B40174 8008BBAC 09000486 */  lh         $a0, 0x9($s0)
/* 1B40178 8008BBB0 03000286 */  lh         $v0, 0x3($s0)
/* 1B4017C 8008BBB4 00000000 */  nop
/* 1B40180 8008BBB8 23208200 */  subu       $a0, $a0, $v0
/* 1B40184 8008BBBC 43200400 */  sra        $a0, $a0, 1
/* 1B40188 8008BBC0 2000A4A7 */  sh         $a0, 0x20($sp)
/* 1B4018C 8008BBC4 0B000286 */  lh         $v0, 0xB($s0)
/* 1B40190 8008BBC8 05000386 */  lh         $v1, 0x5($s0)
/* 1B40194 8008BBCC 00000000 */  nop
/* 1B40198 8008BBD0 23104300 */  subu       $v0, $v0, $v1
/* 1B4019C 8008BBD4 43100200 */  sra        $v0, $v0, 1
/* 1B401A0 8008BBD8 2200A2A7 */  sh         $v0, 0x22($sp)
/* 1B401A4 8008BBDC 0D000286 */  lh         $v0, 0xD($s0)
/* 1B401A8 8008BBE0 07000386 */  lh         $v1, 0x7($s0)
/* 1B401AC 8008BBE4 00000000 */  nop
/* 1B401B0 8008BBE8 23104300 */  subu       $v0, $v0, $v1
/* 1B401B4 8008BBEC 43100200 */  sra        $v0, $v0, 1
/* 1B401B8 8008BBF0 2400A2A7 */  sh         $v0, 0x24($sp)
/* 1B401BC 8008BBF4 03000296 */  lhu        $v0, 0x3($s0)
/* 1B401C0 8008BBF8 00000000 */  nop
/* 1B401C4 8008BBFC 21104400 */  addu       $v0, $v0, $a0
/* 1B401C8 8008BC00 030002A6 */  sh         $v0, 0x3($s0)
/* 1B401CC 8008BC04 05000296 */  lhu        $v0, 0x5($s0)
/* 1B401D0 8008BC08 2200A397 */  lhu        $v1, 0x22($sp)
/* 1B401D4 8008BC0C 00000000 */  nop
/* 1B401D8 8008BC10 21104300 */  addu       $v0, $v0, $v1
/* 1B401DC 8008BC14 050002A6 */  sh         $v0, 0x5($s0)
/* 1B401E0 8008BC18 07000296 */  lhu        $v0, 0x7($s0)
/* 1B401E4 8008BC1C 2400A397 */  lhu        $v1, 0x24($sp)
/* 1B401E8 8008BC20 00000000 */  nop
/* 1B401EC 8008BC24 21104300 */  addu       $v0, $v0, $v1
/* 1B401F0 8008BC28 CB89010C */  jal        rand
/* 1B401F4 8008BC2C 070002A6 */   sh        $v0, 0x7($s0)
/* 1B401F8 8008BC30 2000A397 */  lhu        $v1, 0x20($sp)
/* 1B401FC 8008BC34 02004230 */  andi       $v0, $v0, 0x2
/* 1B40200 8008BC38 FFFF6324 */  addiu      $v1, $v1, -0x1
/* 1B40204 8008BC3C 21186200 */  addu       $v1, $v1, $v0
/* 1B40208 8008BC40 CB89010C */  jal        rand
/* 1B4020C 8008BC44 2000A3A7 */   sh        $v1, 0x20($sp)
/* 1B40210 8008BC48 2200A397 */  lhu        $v1, 0x22($sp)
/* 1B40214 8008BC4C 02004230 */  andi       $v0, $v0, 0x2
/* 1B40218 8008BC50 FFFF6324 */  addiu      $v1, $v1, -0x1
/* 1B4021C 8008BC54 21186200 */  addu       $v1, $v1, $v0
/* 1B40220 8008BC58 2200A3A7 */  sh         $v1, 0x22($sp)
/* 1B40224 8008BC5C 01000292 */  lbu        $v0, 0x1($s0)
/* 1B40228 8008BC60 00000000 */  nop
/* 1B4022C 8008BC64 01004230 */  andi       $v0, $v0, 0x1
/* 1B40230 8008BC68 05004010 */  beqz       $v0, .Llevel_21_8008BC80
/* 1B40234 8008BC6C 00000000 */   nop
/* 1B40238 8008BC70 2400A297 */  lhu        $v0, 0x24($sp)
/* 1B4023C 8008BC74 00000000 */  nop
/* 1B40240 8008BC78 FFFF4224 */  addiu      $v0, $v0, -0x1
/* 1B40244 8008BC7C 2400A2A7 */  sh         $v0, 0x24($sp)
.Llevel_21_8008BC80:
/* 1B40248 8008BC80 09000296 */  lhu        $v0, 0x9($s0)
/* 1B4024C 8008BC84 2000A397 */  lhu        $v1, 0x20($sp)
/* 1B40250 8008BC88 00000000 */  nop
/* 1B40254 8008BC8C 21104300 */  addu       $v0, $v0, $v1
/* 1B40258 8008BC90 090002A6 */  sh         $v0, 0x9($s0)
/* 1B4025C 8008BC94 0B000296 */  lhu        $v0, 0xB($s0)
/* 1B40260 8008BC98 2200A397 */  lhu        $v1, 0x22($sp)
/* 1B40264 8008BC9C 00000000 */  nop
/* 1B40268 8008BCA0 21104300 */  addu       $v0, $v0, $v1
/* 1B4026C 8008BCA4 0D000396 */  lhu        $v1, 0xD($s0)
/* 1B40270 8008BCA8 0B0002A6 */  sh         $v0, 0xB($s0)
/* 1B40274 8008BCAC 01000292 */  lbu        $v0, 0x1($s0)
/* 1B40278 8008BCB0 2400A497 */  lhu        $a0, 0x24($sp)
/* 1B4027C 8008BCB4 01004224 */  addiu      $v0, $v0, 0x1
/* 1B40280 8008BCB8 21186400 */  addu       $v1, $v1, $a0
/* 1B40284 8008BCBC 010002A2 */  sb         $v0, 0x1($s0)
/* 1B40288 8008BCC0 FF004230 */  andi       $v0, $v0, 0xFF
/* 1B4028C 8008BCC4 2000422C */  sltiu      $v0, $v0, 0x20
/* 1B40290 8008BCC8 07024010 */  beqz       $v0, .Llevel_21_8008C4E8
/* 1B40294 8008BCCC 0D0003A6 */   sh        $v1, 0xD($s0)
/* 1B40298 8008BCD0 02000292 */  lbu        $v0, 0x2($s0)
/* 1B4029C 8008BCD4 00000000 */  nop
/* 1B402A0 8008BCD8 03024010 */  beqz       $v0, .Llevel_21_8008C4E8
/* 1B402A4 8008BCDC 00000000 */   nop
/* 1B402A8 8008BCE0 0F000292 */  lbu        $v0, 0xF($s0)
/* 1B402AC 8008BCE4 00000000 */  nop
/* 1B402B0 8008BCE8 FDFF4224 */  addiu      $v0, $v0, -0x3
/* 1B402B4 8008BCEC 0F0002A2 */  sb         $v0, 0xF($s0)
/* 1B402B8 8008BCF0 FF004230 */  andi       $v0, $v0, 0xFF
/* 1B402BC 8008BCF4 8000422C */  sltiu      $v0, $v0, 0x80
/* 1B402C0 8008BCF8 02004010 */  beqz       $v0, .Llevel_21_8008BD04
/* 1B402C4 8008BCFC 80000224 */   addiu     $v0, $zero, 0x80
/* 1B402C8 8008BD00 0F0002A2 */  sb         $v0, 0xF($s0)
.Llevel_21_8008BD04:
/* 1B402CC 8008BD04 10000292 */  lbu        $v0, 0x10($s0)
/* 1B402D0 8008BD08 00000000 */  nop
/* 1B402D4 8008BD0C FCFF4224 */  addiu      $v0, $v0, -0x4
/* 1B402D8 8008BD10 100002A2 */  sb         $v0, 0x10($s0)
/* 1B402DC 8008BD14 FF004230 */  andi       $v0, $v0, 0xFF
/* 1B402E0 8008BD18 6000422C */  sltiu      $v0, $v0, 0x60
/* 1B402E4 8008BD1C 02004010 */  beqz       $v0, .Llevel_21_8008BD28
/* 1B402E8 8008BD20 60000224 */   addiu     $v0, $zero, 0x60
/* 1B402EC 8008BD24 100002A2 */  sb         $v0, 0x10($s0)
.Llevel_21_8008BD28:
/* 1B402F0 8008BD28 13000292 */  lbu        $v0, 0x13($s0)
/* 1B402F4 8008BD2C 110000A2 */  sb         $zero, 0x11($s0)
/* 1B402F8 8008BD30 FDFF4224 */  addiu      $v0, $v0, -0x3
/* 1B402FC 8008BD34 130002A2 */  sb         $v0, 0x13($s0)
/* 1B40300 8008BD38 FF004230 */  andi       $v0, $v0, 0xFF
/* 1B40304 8008BD3C C000422C */  sltiu      $v0, $v0, 0xC0
/* 1B40308 8008BD40 02004010 */  beqz       $v0, .Llevel_21_8008BD4C
/* 1B4030C 8008BD44 C0000224 */   addiu     $v0, $zero, 0xC0
/* 1B40310 8008BD48 130002A2 */  sb         $v0, 0x13($s0)
.Llevel_21_8008BD4C:
/* 1B40314 8008BD4C 14000292 */  lbu        $v0, 0x14($s0)
/* 1B40318 8008BD50 00000000 */  nop
/* 1B4031C 8008BD54 FCFF4224 */  addiu      $v0, $v0, -0x4
/* 1B40320 8008BD58 140002A2 */  sb         $v0, 0x14($s0)
/* 1B40324 8008BD5C FF004230 */  andi       $v0, $v0, 0xFF
/* 1B40328 8008BD60 8000422C */  sltiu      $v0, $v0, 0x80
/* 1B4032C 8008BD64 02004010 */  beqz       $v0, .Llevel_21_8008BD70
/* 1B40330 8008BD68 80000224 */   addiu     $v0, $zero, 0x80
/* 1B40334 8008BD6C 140002A2 */  sb         $v0, 0x14($s0)
.Llevel_21_8008BD70:
/* 1B40338 8008BD70 15000292 */  lbu        $v0, 0x15($s0)
/* 1B4033C 8008BD74 00000000 */  nop
/* 1B40340 8008BD78 FAFF4224 */  addiu      $v0, $v0, -0x6
/* 1B40344 8008BD7C 150002A2 */  sb         $v0, 0x15($s0)
/* 1B40348 8008BD80 FF004230 */  andi       $v0, $v0, 0xFF
/* 1B4034C 8008BD84 2000422C */  sltiu      $v0, $v0, 0x20
/* 1B40350 8008BD88 D9014010 */  beqz       $v0, .Llevel_21_8008C4F0
/* 1B40354 8008BD8C 20000224 */   addiu     $v0, $zero, 0x20
/* 1B40358 8008BD90 3C310208 */  j          .Llevel_21_8008C4F0
/* 1B4035C 8008BD94 150002A2 */   sb        $v0, 0x15($s0)
.L8008BD98_:
/* 1B40360 8008BD98 01000292 */  lbu        $v0, 0x1($s0)
/* 1B40364 8008BD9C 00000000 */  nop
/* 1B40368 8008BDA0 01004224 */  addiu      $v0, $v0, 0x1
/* 1B4036C 8008BDA4 010002A2 */  sb         $v0, 0x1($s0)
/* 1B40370 8008BDA8 FF004230 */  andi       $v0, $v0, 0xFF
/* 1B40374 8008BDAC 2000422C */  sltiu      $v0, $v0, 0x20
/* 1B40378 8008BDB0 CD014010 */  beqz       $v0, .Llevel_21_8008C4E8
/* 1B4037C 8008BDB4 00000000 */   nop
/* 1B40380 8008BDB8 02000292 */  lbu        $v0, 0x2($s0)
/* 1B40384 8008BDBC 00000000 */  nop
/* 1B40388 8008BDC0 C9014010 */  beqz       $v0, .Llevel_21_8008C4E8
/* 1B4038C 8008BDC4 00000000 */   nop
/* 1B40390 8008BDC8 09000286 */  lh         $v0, 0x9($s0)
/* 1B40394 8008BDCC 03000386 */  lh         $v1, 0x3($s0)
/* 1B40398 8008BDD0 00000000 */  nop
/* 1B4039C 8008BDD4 23104300 */  subu       $v0, $v0, $v1
/* 1B403A0 8008BDD8 2800A2AF */  sw         $v0, 0x28($sp)
/* 1B403A4 8008BDDC 0B000286 */  lh         $v0, 0xB($s0)
/* 1B403A8 8008BDE0 05000386 */  lh         $v1, 0x5($s0)
/* 1B403AC 8008BDE4 00000000 */  nop
/* 1B403B0 8008BDE8 23104300 */  subu       $v0, $v0, $v1
/* 1B403B4 8008BDEC 2C00A2AF */  sw         $v0, 0x2C($sp)
/* 1B403B8 8008BDF0 0D000286 */  lh         $v0, 0xD($s0)
/* 1B403BC 8008BDF4 07000386 */  lh         $v1, 0x7($s0)
/* 1B403C0 8008BDF8 00000000 */  nop
/* 1B403C4 8008BDFC 23104300 */  subu       $v0, $v0, $v1
/* 1B403C8 8008BE00 CB89010C */  jal        rand
/* 1B403CC 8008BE04 3000A2AF */   sw        $v0, 0x30($sp)
/* 1B403D0 8008BE08 2800A38F */  lw         $v1, 0x28($sp)
/* 1B403D4 8008BE0C 02004230 */  andi       $v0, $v0, 0x2
/* 1B403D8 8008BE10 FFFF6324 */  addiu      $v1, $v1, -0x1
/* 1B403DC 8008BE14 21186200 */  addu       $v1, $v1, $v0
/* 1B403E0 8008BE18 CB89010C */  jal        rand
/* 1B403E4 8008BE1C 2800A3AF */   sw        $v1, 0x28($sp)
/* 1B403E8 8008BE20 2C00A38F */  lw         $v1, 0x2C($sp)
/* 1B403EC 8008BE24 02004230 */  andi       $v0, $v0, 0x2
/* 1B403F0 8008BE28 FFFF6324 */  addiu      $v1, $v1, -0x1
/* 1B403F4 8008BE2C 21186200 */  addu       $v1, $v1, $v0
/* 1B403F8 8008BE30 CB89010C */  jal        rand
/* 1B403FC 8008BE34 2C00A3AF */   sw        $v1, 0x2C($sp)
/* 1B40400 8008BE38 3000A38F */  lw         $v1, 0x30($sp)
/* 1B40404 8008BE3C 02004230 */  andi       $v0, $v0, 0x2
/* 1B40408 8008BE40 FFFF6324 */  addiu      $v1, $v1, -0x1
/* 1B4040C 8008BE44 21186200 */  addu       $v1, $v1, $v0
/* 1B40410 8008BE48 3000A3AF */  sw         $v1, 0x30($sp)
/* 1B40414 8008BE4C 2800A38F */  lw         $v1, 0x28($sp)
/* 1B40418 8008BE50 09000296 */  lhu        $v0, 0x9($s0)
/* 1B4041C 8008BE54 00000000 */  nop
/* 1B40420 8008BE58 21104300 */  addu       $v0, $v0, $v1
/* 1B40424 8008BE5C 090002A6 */  sh         $v0, 0x9($s0)
/* 1B40428 8008BE60 2C00A38F */  lw         $v1, 0x2C($sp)
/* 1B4042C 8008BE64 0B000296 */  lhu        $v0, 0xB($s0)
/* 1B40430 8008BE68 00000000 */  nop
/* 1B40434 8008BE6C 21104300 */  addu       $v0, $v0, $v1
/* 1B40438 8008BE70 0B0002A6 */  sh         $v0, 0xB($s0)
/* 1B4043C 8008BE74 3000A38F */  lw         $v1, 0x30($sp)
/* 1B40440 8008BE78 0D000296 */  lhu        $v0, 0xD($s0)
/* 1B40444 8008BE7C 00000000 */  nop
/* 1B40448 8008BE80 21104300 */  addu       $v0, $v0, $v1
/* 1B4044C 8008BE84 0D0002A6 */  sh         $v0, 0xD($s0)
/* 1B40450 8008BE88 2800A38F */  lw         $v1, 0x28($sp)
/* 1B40454 8008BE8C 09000296 */  lhu        $v0, 0x9($s0)
/* 1B40458 8008BE90 00000000 */  nop
/* 1B4045C 8008BE94 23104300 */  subu       $v0, $v0, $v1
/* 1B40460 8008BE98 030002A6 */  sh         $v0, 0x3($s0)
/* 1B40464 8008BE9C 2C00A38F */  lw         $v1, 0x2C($sp)
/* 1B40468 8008BEA0 0B000296 */  lhu        $v0, 0xB($s0)
/* 1B4046C 8008BEA4 00000000 */  nop
/* 1B40470 8008BEA8 23104300 */  subu       $v0, $v0, $v1
/* 1B40474 8008BEAC 050002A6 */  sh         $v0, 0x5($s0)
/* 1B40478 8008BEB0 13000292 */  lbu        $v0, 0x13($s0)
/* 1B4047C 8008BEB4 3000A48F */  lw         $a0, 0x30($sp)
/* 1B40480 8008BEB8 15000392 */  lbu        $v1, 0x15($s0)
/* 1B40484 8008BEBC FEFF4224 */  addiu      $v0, $v0, -0x2
/* 1B40488 8008BEC0 130002A2 */  sb         $v0, 0x13($s0)
/* 1B4048C 8008BEC4 14000292 */  lbu        $v0, 0x14($s0)
/* 1B40490 8008BEC8 FCFF6324 */  addiu      $v1, $v1, -0x4
/* 1B40494 8008BECC 150003A2 */  sb         $v1, 0x15($s0)
/* 1B40498 8008BED0 10000392 */  lbu        $v1, 0x10($s0)
/* 1B4049C 8008BED4 FEFF4224 */  addiu      $v0, $v0, -0x2
/* 1B404A0 8008BED8 140002A2 */  sb         $v0, 0x14($s0)
/* 1B404A4 8008BEDC 0F000292 */  lbu        $v0, 0xF($s0)
/* 1B404A8 8008BEE0 FDFF6324 */  addiu      $v1, $v1, -0x3
/* 1B404AC 8008BEE4 100003A2 */  sb         $v1, 0x10($s0)
/* 1B404B0 8008BEE8 0D000396 */  lhu        $v1, 0xD($s0)
/* 1B404B4 8008BEEC FDFF4224 */  addiu      $v0, $v0, -0x3
/* 1B404B8 8008BEF0 0F0002A2 */  sb         $v0, 0xF($s0)
/* 1B404BC 8008BEF4 11000292 */  lbu        $v0, 0x11($s0)
/* 1B404C0 8008BEF8 23186400 */  subu       $v1, $v1, $a0
/* 1B404C4 8008BEFC 070003A6 */  sh         $v1, 0x7($s0)
/* 1B404C8 8008BF00 FDFF4224 */  addiu      $v0, $v0, -0x3
/* 1B404CC 8008BF04 3C310208 */  j          .Llevel_21_8008C4F0
/* 1B404D0 8008BF08 110002A2 */   sb        $v0, 0x11($s0)
.L8008BF0C_:
/* 1B404D4 8008BF0C 01000292 */  lbu        $v0, 0x1($s0)
/* 1B404D8 8008BF10 00000000 */  nop
/* 1B404DC 8008BF14 01004224 */  addiu      $v0, $v0, 0x1
/* 1B404E0 8008BF18 010002A2 */  sb         $v0, 0x1($s0)
/* 1B404E4 8008BF1C FF004230 */  andi       $v0, $v0, 0xFF
/* 1B404E8 8008BF20 3000422C */  sltiu      $v0, $v0, 0x30
/* 1B404EC 8008BF24 70014010 */  beqz       $v0, .Llevel_21_8008C4E8
/* 1B404F0 8008BF28 00000000 */   nop
/* 1B404F4 8008BF2C 02000292 */  lbu        $v0, 0x2($s0)
/* 1B404F8 8008BF30 00000000 */  nop
/* 1B404FC 8008BF34 6C014010 */  beqz       $v0, .Llevel_21_8008C4E8
/* 1B40500 8008BF38 00000000 */   nop
/* 1B40504 8008BF3C 03000286 */  lh         $v0, 0x3($s0)
/* 1B40508 8008BF40 09000386 */  lh         $v1, 0x9($s0)
/* 1B4050C 8008BF44 00000000 */  nop
/* 1B40510 8008BF48 23104300 */  subu       $v0, $v0, $v1
/* 1B40514 8008BF4C 43100200 */  sra        $v0, $v0, 1
/* 1B40518 8008BF50 2000A2AF */  sw         $v0, 0x20($sp)
/* 1B4051C 8008BF54 05000286 */  lh         $v0, 0x5($s0)
/* 1B40520 8008BF58 0B000386 */  lh         $v1, 0xB($s0)
/* 1B40524 8008BF5C 00000000 */  nop
/* 1B40528 8008BF60 23104300 */  subu       $v0, $v0, $v1
/* 1B4052C 8008BF64 43100200 */  sra        $v0, $v0, 1
/* 1B40530 8008BF68 2400A2AF */  sw         $v0, 0x24($sp)
/* 1B40534 8008BF6C 07000286 */  lh         $v0, 0x7($s0)
/* 1B40538 8008BF70 0D000386 */  lh         $v1, 0xD($s0)
/* 1B4053C 8008BF74 00000000 */  nop
/* 1B40540 8008BF78 23104300 */  subu       $v0, $v0, $v1
/* 1B40544 8008BF7C 43100200 */  sra        $v0, $v0, 1
/* 1B40548 8008BF80 CB89010C */  jal        rand
/* 1B4054C 8008BF84 2800A2AF */   sw        $v0, 0x28($sp)
/* 1B40550 8008BF88 2000A38F */  lw         $v1, 0x20($sp)
/* 1B40554 8008BF8C 04004230 */  andi       $v0, $v0, 0x4
/* 1B40558 8008BF90 FEFF6324 */  addiu      $v1, $v1, -0x2
/* 1B4055C 8008BF94 21186200 */  addu       $v1, $v1, $v0
/* 1B40560 8008BF98 CB89010C */  jal        rand
/* 1B40564 8008BF9C 2000A3AF */   sw        $v1, 0x20($sp)
/* 1B40568 8008BFA0 2400A38F */  lw         $v1, 0x24($sp)
/* 1B4056C 8008BFA4 04004230 */  andi       $v0, $v0, 0x4
/* 1B40570 8008BFA8 FEFF6324 */  addiu      $v1, $v1, -0x2
/* 1B40574 8008BFAC 21186200 */  addu       $v1, $v1, $v0
/* 1B40578 8008BFB0 CB89010C */  jal        rand
/* 1B4057C 8008BFB4 2400A3AF */   sw        $v1, 0x24($sp)
/* 1B40580 8008BFB8 2800A38F */  lw         $v1, 0x28($sp)
/* 1B40584 8008BFBC 02004230 */  andi       $v0, $v0, 0x2
/* 1B40588 8008BFC0 FFFF6324 */  addiu      $v1, $v1, -0x1
/* 1B4058C 8008BFC4 21186200 */  addu       $v1, $v1, $v0
/* 1B40590 8008BFC8 2800A3AF */  sw         $v1, 0x28($sp)
/* 1B40594 8008BFCC 2000A38F */  lw         $v1, 0x20($sp)
/* 1B40598 8008BFD0 03000296 */  lhu        $v0, 0x3($s0)
/* 1B4059C 8008BFD4 00000000 */  nop
/* 1B405A0 8008BFD8 21104300 */  addu       $v0, $v0, $v1
/* 1B405A4 8008BFDC 030002A6 */  sh         $v0, 0x3($s0)
/* 1B405A8 8008BFE0 2400A38F */  lw         $v1, 0x24($sp)
/* 1B405AC 8008BFE4 05000296 */  lhu        $v0, 0x5($s0)
/* 1B405B0 8008BFE8 00000000 */  nop
/* 1B405B4 8008BFEC 21104300 */  addu       $v0, $v0, $v1
/* 1B405B8 8008BFF0 050002A6 */  sh         $v0, 0x5($s0)
/* 1B405BC 8008BFF4 2800A38F */  lw         $v1, 0x28($sp)
/* 1B405C0 8008BFF8 07000296 */  lhu        $v0, 0x7($s0)
/* 1B405C4 8008BFFC 00000000 */  nop
/* 1B405C8 8008C000 21104300 */  addu       $v0, $v0, $v1
/* 1B405CC 8008C004 070002A6 */  sh         $v0, 0x7($s0)
/* 1B405D0 8008C008 2000A28F */  lw         $v0, 0x20($sp)
/* 1B405D4 8008C00C 03000396 */  lhu        $v1, 0x3($s0)
/* 1B405D8 8008C010 40100200 */  sll        $v0, $v0, 1
/* 1B405DC 8008C014 23186200 */  subu       $v1, $v1, $v0
/* 1B405E0 8008C018 090003A6 */  sh         $v1, 0x9($s0)
/* 1B405E4 8008C01C 2400A28F */  lw         $v0, 0x24($sp)
/* 1B405E8 8008C020 05000396 */  lhu        $v1, 0x5($s0)
/* 1B405EC 8008C024 40100200 */  sll        $v0, $v0, 1
/* 1B405F0 8008C028 23186200 */  subu       $v1, $v1, $v0
/* 1B405F4 8008C02C 0B0003A6 */  sh         $v1, 0xB($s0)
/* 1B405F8 8008C030 2800A28F */  lw         $v0, 0x28($sp)
/* 1B405FC 8008C034 07000396 */  lhu        $v1, 0x7($s0)
/* 1B40600 8008C038 40100200 */  sll        $v0, $v0, 1
/* 1B40604 8008C03C 23186200 */  subu       $v1, $v1, $v0
/* 1B40608 8008C040 3C310208 */  j          .Llevel_21_8008C4F0
/* 1B4060C 8008C044 0D0003A6 */   sh        $v1, 0xD($s0)
.L8008C048_:
/* 1B40610 8008C048 0780023C */  lui        $v0, %hi(g_DeltaTime)
/* 1B40614 8008C04C CC56428C */  lw         $v0, %lo(g_DeltaTime)($v0)
/* 1B40618 8008C050 17000392 */  lbu        $v1, 0x17($s0)
/* 1B4061C 8008C054 80100200 */  sll        $v0, $v0, 2
/* 1B40620 8008C058 21186200 */  addu       $v1, $v1, $v0
/* 1B40624 8008C05C 170003A2 */  sb         $v1, 0x17($s0)
/* 1B40628 8008C060 0780043C */  lui        $a0, %hi(g_DeltaTime)
/* 1B4062C 8008C064 CC56848C */  lw         $a0, %lo(g_DeltaTime)($a0)
/* 1B40630 8008C068 18000292 */  lbu        $v0, 0x18($s0)
/* 1B40634 8008C06C 17000392 */  lbu        $v1, 0x17($s0)
/* 1B40638 8008C070 21104400 */  addu       $v0, $v0, $a0
/* 1B4063C 8008C074 40180300 */  sll        $v1, $v1, 1
/* 1B40640 8008C078 180002A2 */  sb         $v0, 0x18($s0)
/* 1B40644 8008C07C 0780013C */  lui        $at, %hi(D_8006CC78)
/* 1B40648 8008C080 21082300 */  addu       $at, $at, $v1
/* 1B4064C 8008C084 78CC2384 */  lh         $v1, %lo(D_8006CC78)($at)
/* 1B40650 8008C088 FF004230 */  andi       $v0, $v0, 0xFF
/* 1B40654 8008C08C 18006200 */  mult       $v1, $v0
/* 1B40658 8008C090 17000392 */  lbu        $v1, 0x17($s0)
/* 1B4065C 8008C094 0F000296 */  lhu        $v0, 0xF($s0)
/* 1B40660 8008C098 40180300 */  sll        $v1, $v1, 1
/* 1B40664 8008C09C 12380000 */  mflo       $a3
/* 1B40668 8008C0A0 03230700 */  sra        $a0, $a3, 12
/* 1B4066C 8008C0A4 21104400 */  addu       $v0, $v0, $a0
/* 1B40670 8008C0A8 030002A6 */  sh         $v0, 0x3($s0)
/* 1B40674 8008C0AC 0780013C */  lui        $at, %hi(D_8006CBF8)
/* 1B40678 8008C0B0 21082300 */  addu       $at, $at, $v1
/* 1B4067C 8008C0B4 F8CB2384 */  lh         $v1, %lo(D_8006CBF8)($at)
/* 1B40680 8008C0B8 18000292 */  lbu        $v0, 0x18($s0)
/* 1B40684 8008C0BC 00000000 */  nop
/* 1B40688 8008C0C0 18006200 */  mult       $v1, $v0
/* 1B4068C 8008C0C4 0780033C */  lui        $v1, %hi(g_DeltaTime)
/* 1B40690 8008C0C8 CC56638C */  lw         $v1, %lo(g_DeltaTime)($v1)
/* 1B40694 8008C0CC 00000000 */  nop
/* 1B40698 8008C0D0 40100300 */  sll        $v0, $v1, 1
/* 1B4069C 8008C0D4 21104300 */  addu       $v0, $v0, $v1
/* 1B406A0 8008C0D8 07000396 */  lhu        $v1, 0x7($s0)
/* 1B406A4 8008C0DC 40100200 */  sll        $v0, $v0, 1
/* 1B406A8 8008C0E0 21186200 */  addu       $v1, $v1, $v0
/* 1B406AC 8008C0E4 070003A6 */  sh         $v1, 0x7($s0)
/* 1B406B0 8008C0E8 18000392 */  lbu        $v1, 0x18($s0)
/* 1B406B4 8008C0EC 11000296 */  lhu        $v0, 0x11($s0)
/* 1B406B8 8008C0F0 3A2E0208 */  j          .Llevel_21_8008B8E8
/* 1B406BC 8008C0F4 C100632C */   sltiu     $v1, $v1, 0xC1
.L8008C0F8_:
/* 1B406C0 8008C0F8 09000486 */  lh         $a0, 0x9($s0)
/* 1B406C4 8008C0FC 03000286 */  lh         $v0, 0x3($s0)
/* 1B406C8 8008C100 00000000 */  nop
/* 1B406CC 8008C104 23208200 */  subu       $a0, $a0, $v0
/* 1B406D0 8008C108 43200400 */  sra        $a0, $a0, 1
/* 1B406D4 8008C10C 2000A4A7 */  sh         $a0, 0x20($sp)
/* 1B406D8 8008C110 0B000286 */  lh         $v0, 0xB($s0)
/* 1B406DC 8008C114 05000386 */  lh         $v1, 0x5($s0)
/* 1B406E0 8008C118 00000000 */  nop
/* 1B406E4 8008C11C 23104300 */  subu       $v0, $v0, $v1
/* 1B406E8 8008C120 43100200 */  sra        $v0, $v0, 1
/* 1B406EC 8008C124 2200A2A7 */  sh         $v0, 0x22($sp)
/* 1B406F0 8008C128 0D000286 */  lh         $v0, 0xD($s0)
/* 1B406F4 8008C12C 07000386 */  lh         $v1, 0x7($s0)
/* 1B406F8 8008C130 00000000 */  nop
/* 1B406FC 8008C134 23104300 */  subu       $v0, $v0, $v1
/* 1B40700 8008C138 43100200 */  sra        $v0, $v0, 1
/* 1B40704 8008C13C 2400A2A7 */  sh         $v0, 0x24($sp)
/* 1B40708 8008C140 03000296 */  lhu        $v0, 0x3($s0)
/* 1B4070C 8008C144 00000000 */  nop
/* 1B40710 8008C148 21104400 */  addu       $v0, $v0, $a0
/* 1B40714 8008C14C 030002A6 */  sh         $v0, 0x3($s0)
/* 1B40718 8008C150 05000296 */  lhu        $v0, 0x5($s0)
/* 1B4071C 8008C154 2200A397 */  lhu        $v1, 0x22($sp)
/* 1B40720 8008C158 00000000 */  nop
/* 1B40724 8008C15C 21104300 */  addu       $v0, $v0, $v1
/* 1B40728 8008C160 050002A6 */  sh         $v0, 0x5($s0)
/* 1B4072C 8008C164 07000296 */  lhu        $v0, 0x7($s0)
/* 1B40730 8008C168 2400A397 */  lhu        $v1, 0x24($sp)
/* 1B40734 8008C16C 00000000 */  nop
/* 1B40738 8008C170 21104300 */  addu       $v0, $v0, $v1
/* 1B4073C 8008C174 070002A6 */  sh         $v0, 0x7($s0)
/* 1B40740 8008C178 2200A297 */  lhu        $v0, 0x22($sp)
/* 1B40744 8008C17C 2000A397 */  lhu        $v1, 0x20($sp)
/* 1B40748 8008C180 01004224 */  addiu      $v0, $v0, 0x1
/* 1B4074C 8008C184 2200A2A7 */  sh         $v0, 0x22($sp)
/* 1B40750 8008C188 09000296 */  lhu        $v0, 0x9($s0)
/* 1B40754 8008C18C 00000000 */  nop
/* 1B40758 8008C190 21104300 */  addu       $v0, $v0, $v1
/* 1B4075C 8008C194 090002A6 */  sh         $v0, 0x9($s0)
/* 1B40760 8008C198 0B000296 */  lhu        $v0, 0xB($s0)
/* 1B40764 8008C19C 2200A397 */  lhu        $v1, 0x22($sp)
/* 1B40768 8008C1A0 00000000 */  nop
/* 1B4076C 8008C1A4 21104300 */  addu       $v0, $v0, $v1
/* 1B40770 8008C1A8 0D000396 */  lhu        $v1, 0xD($s0)
/* 1B40774 8008C1AC 0B0002A6 */  sh         $v0, 0xB($s0)
/* 1B40778 8008C1B0 01000292 */  lbu        $v0, 0x1($s0)
/* 1B4077C 8008C1B4 2400A497 */  lhu        $a0, 0x24($sp)
/* 1B40780 8008C1B8 01004224 */  addiu      $v0, $v0, 0x1
/* 1B40784 8008C1BC 21186400 */  addu       $v1, $v1, $a0
/* 1B40788 8008C1C0 010002A2 */  sb         $v0, 0x1($s0)
/* 1B4078C 8008C1C4 FF004230 */  andi       $v0, $v0, 0xFF
/* 1B40790 8008C1C8 2000422C */  sltiu      $v0, $v0, 0x20
/* 1B40794 8008C1CC C8004014 */  bnez       $v0, .Llevel_21_8008C4F0
/* 1B40798 8008C1D0 0D0003A6 */   sh        $v1, 0xD($s0)
/* 1B4079C 8008C1D4 3A310208 */  j          .Llevel_21_8008C4E8
/* 1B407A0 8008C1D8 00000000 */   nop
.L8008C1DC_:
/* 1B407A4 8008C1DC 01000292 */  lbu        $v0, 0x1($s0)
/* 1B407A8 8008C1E0 00000000 */  nop
/* 1B407AC 8008C1E4 01004224 */  addiu      $v0, $v0, 0x1
/* 1B407B0 8008C1E8 010002A2 */  sb         $v0, 0x1($s0)
/* 1B407B4 8008C1EC FF004230 */  andi       $v0, $v0, 0xFF
/* 1B407B8 8008C1F0 2800422C */  sltiu      $v0, $v0, 0x28
/* 1B407BC 8008C1F4 BC004010 */  beqz       $v0, .Llevel_21_8008C4E8
/* 1B407C0 8008C1F8 00000000 */   nop
/* 1B407C4 8008C1FC 02000292 */  lbu        $v0, 0x2($s0)
/* 1B407C8 8008C200 00000000 */  nop
/* 1B407CC 8008C204 B8004010 */  beqz       $v0, .Llevel_21_8008C4E8
/* 1B407D0 8008C208 00000000 */   nop
/* 1B407D4 8008C20C 03000296 */  lhu        $v0, 0x3($s0)
/* 1B407D8 8008C210 0F000396 */  lhu        $v1, 0xF($s0)
/* 1B407DC 8008C214 11000496 */  lhu        $a0, 0x11($s0)
/* 1B407E0 8008C218 13000596 */  lhu        $a1, 0x13($s0)
/* 1B407E4 8008C21C 21104300 */  addu       $v0, $v0, $v1
/* 1B407E8 8008C220 030002A6 */  sh         $v0, 0x3($s0)
/* 1B407EC 8008C224 05000296 */  lhu        $v0, 0x5($s0)
/* 1B407F0 8008C228 07000396 */  lhu        $v1, 0x7($s0)
/* 1B407F4 8008C22C 21104400 */  addu       $v0, $v0, $a0
/* 1B407F8 8008C230 21186500 */  addu       $v1, $v1, $a1
/* 1B407FC 8008C234 050002A6 */  sh         $v0, 0x5($s0)
/* 1B40800 8008C238 CB89010C */  jal        rand
/* 1B40804 8008C23C 070003A6 */   sh        $v1, 0x7($s0)
/* 1B40808 8008C240 0F000396 */  lhu        $v1, 0xF($s0)
/* 1B4080C 8008C244 02004230 */  andi       $v0, $v0, 0x2
/* 1B40810 8008C248 FFFF6324 */  addiu      $v1, $v1, -0x1
/* 1B40814 8008C24C 21186200 */  addu       $v1, $v1, $v0
/* 1B40818 8008C250 CB89010C */  jal        rand
/* 1B4081C 8008C254 0F0003A6 */   sh        $v1, 0xF($s0)
/* 1B40820 8008C258 11000396 */  lhu        $v1, 0x11($s0)
/* 1B40824 8008C25C 02004230 */  andi       $v0, $v0, 0x2
/* 1B40828 8008C260 FFFF6324 */  addiu      $v1, $v1, -0x1
/* 1B4082C 8008C264 21186200 */  addu       $v1, $v1, $v0
/* 1B40830 8008C268 CB89010C */  jal        rand
/* 1B40834 8008C26C 110003A6 */   sh        $v1, 0x11($s0)
/* 1B40838 8008C270 13000396 */  lhu        $v1, 0x13($s0)
/* 1B4083C 8008C274 02004230 */  andi       $v0, $v0, 0x2
/* 1B40840 8008C278 FFFF6324 */  addiu      $v1, $v1, -0x1
/* 1B40844 8008C27C 21186200 */  addu       $v1, $v1, $v0
/* 1B40848 8008C280 130003A6 */  sh         $v1, 0x13($s0)
/* 1B4084C 8008C284 001C0300 */  sll        $v1, $v1, 16
/* 1B40850 8008C288 031C0300 */  sra        $v1, $v1, 16
/* 1B40854 8008C28C 03006328 */  slti       $v1, $v1, 0x3
/* 1B40858 8008C290 02006014 */  bnez       $v1, .Llevel_21_8008C29C
/* 1B4085C 8008C294 02000224 */   addiu     $v0, $zero, 0x2
/* 1B40860 8008C298 130002A6 */  sh         $v0, 0x13($s0)
.Llevel_21_8008C29C:
/* 1B40864 8008C29C 13000286 */  lh         $v0, 0x13($s0)
/* 1B40868 8008C2A0 00000000 */  nop
/* 1B4086C 8008C2A4 FCFF4228 */  slti       $v0, $v0, -0x4
/* 1B40870 8008C2A8 02004010 */  beqz       $v0, .Llevel_21_8008C2B4
/* 1B40874 8008C2AC FCFF0224 */   addiu     $v0, $zero, -0x4
/* 1B40878 8008C2B0 130002A6 */  sh         $v0, 0x13($s0)
.Llevel_21_8008C2B4:
/* 1B4087C 8008C2B4 0B000292 */  lbu        $v0, 0xB($s0)
/* 1B40880 8008C2B8 0D000392 */  lbu        $v1, 0xD($s0)
/* 1B40884 8008C2BC FEFF4224 */  addiu      $v0, $v0, -0x2
/* 1B40888 8008C2C0 0B0002A2 */  sb         $v0, 0xB($s0)
/* 1B4088C 8008C2C4 0C000292 */  lbu        $v0, 0xC($s0)
/* 1B40890 8008C2C8 FFFF6324 */  addiu      $v1, $v1, -0x1
/* 1B40894 8008C2CC 0D0003A2 */  sb         $v1, 0xD($s0)
/* 1B40898 8008C2D0 FEFF4224 */  addiu      $v0, $v0, -0x2
/* 1B4089C 8008C2D4 3C310208 */  j          .Llevel_21_8008C4F0
/* 1B408A0 8008C2D8 0C0002A2 */   sb        $v0, 0xC($s0)
.L8008C2DC_:
/* 1B408A4 8008C2DC 09000486 */  lh         $a0, 0x9($s0)
/* 1B408A8 8008C2E0 03000286 */  lh         $v0, 0x3($s0)
/* 1B408AC 8008C2E4 00000000 */  nop
/* 1B408B0 8008C2E8 23208200 */  subu       $a0, $a0, $v0
/* 1B408B4 8008C2EC 43200400 */  sra        $a0, $a0, 1
/* 1B408B8 8008C2F0 2000A4A7 */  sh         $a0, 0x20($sp)
/* 1B408BC 8008C2F4 0B000286 */  lh         $v0, 0xB($s0)
/* 1B408C0 8008C2F8 05000386 */  lh         $v1, 0x5($s0)
/* 1B408C4 8008C2FC 00000000 */  nop
/* 1B408C8 8008C300 23104300 */  subu       $v0, $v0, $v1
/* 1B408CC 8008C304 43100200 */  sra        $v0, $v0, 1
/* 1B408D0 8008C308 2200A2A7 */  sh         $v0, 0x22($sp)
/* 1B408D4 8008C30C 0D000286 */  lh         $v0, 0xD($s0)
/* 1B408D8 8008C310 07000386 */  lh         $v1, 0x7($s0)
/* 1B408DC 8008C314 00000000 */  nop
/* 1B408E0 8008C318 23104300 */  subu       $v0, $v0, $v1
/* 1B408E4 8008C31C 43100200 */  sra        $v0, $v0, 1
/* 1B408E8 8008C320 2400A2A7 */  sh         $v0, 0x24($sp)
/* 1B408EC 8008C324 03000296 */  lhu        $v0, 0x3($s0)
/* 1B408F0 8008C328 00000000 */  nop
/* 1B408F4 8008C32C 21104400 */  addu       $v0, $v0, $a0
/* 1B408F8 8008C330 030002A6 */  sh         $v0, 0x3($s0)
/* 1B408FC 8008C334 05000296 */  lhu        $v0, 0x5($s0)
/* 1B40900 8008C338 2200A397 */  lhu        $v1, 0x22($sp)
/* 1B40904 8008C33C 00000000 */  nop
/* 1B40908 8008C340 21104300 */  addu       $v0, $v0, $v1
/* 1B4090C 8008C344 050002A6 */  sh         $v0, 0x5($s0)
/* 1B40910 8008C348 07000296 */  lhu        $v0, 0x7($s0)
/* 1B40914 8008C34C 2400A397 */  lhu        $v1, 0x24($sp)
/* 1B40918 8008C350 00000000 */  nop
/* 1B4091C 8008C354 21104300 */  addu       $v0, $v0, $v1
/* 1B40920 8008C358 070002A6 */  sh         $v0, 0x7($s0)
/* 1B40924 8008C35C 09000296 */  lhu        $v0, 0x9($s0)
/* 1B40928 8008C360 2000A397 */  lhu        $v1, 0x20($sp)
/* 1B4092C 8008C364 00000000 */  nop
/* 1B40930 8008C368 21104300 */  addu       $v0, $v0, $v1
/* 1B40934 8008C36C 090002A6 */  sh         $v0, 0x9($s0)
/* 1B40938 8008C370 0B000296 */  lhu        $v0, 0xB($s0)
/* 1B4093C 8008C374 2200A397 */  lhu        $v1, 0x22($sp)
/* 1B40940 8008C378 00000000 */  nop
/* 1B40944 8008C37C 21104300 */  addu       $v0, $v0, $v1
/* 1B40948 8008C380 0D000396 */  lhu        $v1, 0xD($s0)
/* 1B4094C 8008C384 0B0002A6 */  sh         $v0, 0xB($s0)
/* 1B40950 8008C388 01000292 */  lbu        $v0, 0x1($s0)
/* 1B40954 8008C38C 2400A497 */  lhu        $a0, 0x24($sp)
/* 1B40958 8008C390 01004224 */  addiu      $v0, $v0, 0x1
/* 1B4095C 8008C394 21186400 */  addu       $v1, $v1, $a0
/* 1B40960 8008C398 010002A2 */  sb         $v0, 0x1($s0)
/* 1B40964 8008C39C FF004230 */  andi       $v0, $v0, 0xFF
/* 1B40968 8008C3A0 1800422C */  sltiu      $v0, $v0, 0x18
/* 1B4096C 8008C3A4 50004010 */  beqz       $v0, .Llevel_21_8008C4E8
/* 1B40970 8008C3A8 0D0003A6 */   sh        $v1, 0xD($s0)
/* 1B40974 8008C3AC 02000292 */  lbu        $v0, 0x2($s0)
/* 1B40978 8008C3B0 00000000 */  nop
/* 1B4097C 8008C3B4 4C004010 */  beqz       $v0, .Llevel_21_8008C4E8
/* 1B40980 8008C3B8 00000000 */   nop
/* 1B40984 8008C3BC 0F000292 */  lbu        $v0, 0xF($s0)
/* 1B40988 8008C3C0 13000392 */  lbu        $v1, 0x13($s0)
/* 1B4098C 8008C3C4 FDFF4224 */  addiu      $v0, $v0, -0x3
/* 1B40990 8008C3C8 0F0002A2 */  sb         $v0, 0xF($s0)
/* 1B40994 8008C3CC 10000292 */  lbu        $v0, 0x10($s0)
/* 1B40998 8008C3D0 FDFF6324 */  addiu      $v1, $v1, -0x3
/* 1B4099C 8008C3D4 130003A2 */  sb         $v1, 0x13($s0)
/* 1B409A0 8008C3D8 FCFF4224 */  addiu      $v0, $v0, -0x4
/* 1B409A4 8008C3DC 100002A2 */  sb         $v0, 0x10($s0)
/* 1B409A8 8008C3E0 14000292 */  lbu        $v0, 0x14($s0)
/* 1B409AC 8008C3E4 15000392 */  lbu        $v1, 0x15($s0)
/* 1B409B0 8008C3E8 FCFF4224 */  addiu      $v0, $v0, -0x4
/* 1B409B4 8008C3EC 140002A2 */  sb         $v0, 0x14($s0)
/* 1B409B8 8008C3F0 0600622C */  sltiu      $v0, $v1, 0x6
/* 1B409BC 8008C3F4 3E004014 */  bnez       $v0, .Llevel_21_8008C4F0
/* 1B409C0 8008C3F8 FAFF6224 */   addiu     $v0, $v1, -0x6
/* 1B409C4 8008C3FC 3C310208 */  j          .Llevel_21_8008C4F0
/* 1B409C8 8008C400 150002A2 */   sb        $v0, 0x15($s0)
.L8008C404_:
/* 1B409CC 8008C404 09000496 */  lhu        $a0, 0x9($s0)
/* 1B409D0 8008C408 03000296 */  lhu        $v0, 0x3($s0)
/* 1B409D4 8008C40C 00000000 */  nop
/* 1B409D8 8008C410 23208200 */  subu       $a0, $a0, $v0
/* 1B409DC 8008C414 2000A4A7 */  sh         $a0, 0x20($sp)
/* 1B409E0 8008C418 0B000296 */  lhu        $v0, 0xB($s0)
/* 1B409E4 8008C41C 05000396 */  lhu        $v1, 0x5($s0)
/* 1B409E8 8008C420 00000000 */  nop
/* 1B409EC 8008C424 23104300 */  subu       $v0, $v0, $v1
/* 1B409F0 8008C428 2200A2A7 */  sh         $v0, 0x22($sp)
/* 1B409F4 8008C42C 0D000296 */  lhu        $v0, 0xD($s0)
/* 1B409F8 8008C430 07000396 */  lhu        $v1, 0x7($s0)
/* 1B409FC 8008C434 00000000 */  nop
/* 1B40A00 8008C438 23104300 */  subu       $v0, $v0, $v1
/* 1B40A04 8008C43C 2400A2A7 */  sh         $v0, 0x24($sp)
/* 1B40A08 8008C440 03000296 */  lhu        $v0, 0x3($s0)
/* 1B40A0C 8008C444 00000000 */  nop
/* 1B40A10 8008C448 21104400 */  addu       $v0, $v0, $a0
/* 1B40A14 8008C44C 030002A6 */  sh         $v0, 0x3($s0)
/* 1B40A18 8008C450 05000296 */  lhu        $v0, 0x5($s0)
/* 1B40A1C 8008C454 2200A397 */  lhu        $v1, 0x22($sp)
/* 1B40A20 8008C458 00000000 */  nop
/* 1B40A24 8008C45C 21104300 */  addu       $v0, $v0, $v1
/* 1B40A28 8008C460 050002A6 */  sh         $v0, 0x5($s0)
/* 1B40A2C 8008C464 07000296 */  lhu        $v0, 0x7($s0)
/* 1B40A30 8008C468 2400A397 */  lhu        $v1, 0x24($sp)
/* 1B40A34 8008C46C 00000000 */  nop
/* 1B40A38 8008C470 21104300 */  addu       $v0, $v0, $v1
/* 1B40A3C 8008C474 070002A6 */  sh         $v0, 0x7($s0)
/* 1B40A40 8008C478 2400A297 */  lhu        $v0, 0x24($sp)
/* 1B40A44 8008C47C 2000A397 */  lhu        $v1, 0x20($sp)
/* 1B40A48 8008C480 FFFF4224 */  addiu      $v0, $v0, -0x1
/* 1B40A4C 8008C484 2400A2A7 */  sh         $v0, 0x24($sp)
/* 1B40A50 8008C488 09000296 */  lhu        $v0, 0x9($s0)
/* 1B40A54 8008C48C 00000000 */  nop
/* 1B40A58 8008C490 21104300 */  addu       $v0, $v0, $v1
/* 1B40A5C 8008C494 090002A6 */  sh         $v0, 0x9($s0)
/* 1B40A60 8008C498 0B000296 */  lhu        $v0, 0xB($s0)
/* 1B40A64 8008C49C 2200A397 */  lhu        $v1, 0x22($sp)
/* 1B40A68 8008C4A0 00000000 */  nop
/* 1B40A6C 8008C4A4 21104300 */  addu       $v0, $v0, $v1
/* 1B40A70 8008C4A8 0D000396 */  lhu        $v1, 0xD($s0)
/* 1B40A74 8008C4AC 0B0002A6 */  sh         $v0, 0xB($s0)
/* 1B40A78 8008C4B0 01000292 */  lbu        $v0, 0x1($s0)
/* 1B40A7C 8008C4B4 2400A497 */  lhu        $a0, 0x24($sp)
/* 1B40A80 8008C4B8 01004224 */  addiu      $v0, $v0, 0x1
/* 1B40A84 8008C4BC 21186400 */  addu       $v1, $v1, $a0
/* 1B40A88 8008C4C0 010002A2 */  sb         $v0, 0x1($s0)
/* 1B40A8C 8008C4C4 FF004230 */  andi       $v0, $v0, 0xFF
/* 1B40A90 8008C4C8 2000422C */  sltiu      $v0, $v0, 0x20
/* 1B40A94 8008C4CC 0D0003A6 */  sh         $v1, 0xD($s0)
.Llevel_21_8008C4D0:
/* 1B40A98 8008C4D0 05004010 */  beqz       $v0, .Llevel_21_8008C4E8
/* 1B40A9C 8008C4D4 00000000 */   nop
.Llevel_21_8008C4D8:
/* 1B40AA0 8008C4D8 02000292 */  lbu        $v0, 0x2($s0)
/* 1B40AA4 8008C4DC 00000000 */  nop
/* 1B40AA8 8008C4E0 03004014 */  bnez       $v0, .Llevel_21_8008C4F0
/* 1B40AAC 8008C4E4 00000000 */   nop
.Llevel_21_8008C4E8:
/* 1B40AB0 8008C4E8 824D010C */  jal        func_80053608
/* 1B40AB4 8008C4EC 21204002 */   addu      $a0, $s2, $zero
.Llevel_21_8008C4F0:
/* 1B40AB8 8008C4F0 20001026 */  addiu      $s0, $s0, 0x20
/* 1B40ABC 8008C4F4 2000D626 */  addiu      $s6, $s6, 0x20
/* 1B40AC0 8008C4F8 20007326 */  addiu      $s3, $s3, 0x20
/* 1B40AC4 8008C4FC 00000392 */  lbu        $v1, 0x0($s0)
/* 1B40AC8 8008C500 FF000224 */  addiu      $v0, $zero, 0xFF
/* 1B40ACC 8008C504 45FB6214 */  bne        $v1, $v0, .Llevel_21_8008B21C
/* 1B40AD0 8008C508 20005226 */   addiu     $s2, $s2, 0x20
.Llevel_21_8008C50C:
/* 1B40AD4 8008C50C 6400BF8F */  lw         $ra, 0x64($sp)
/* 1B40AD8 8008C510 6000BE8F */  lw         $fp, 0x60($sp)
/* 1B40ADC 8008C514 5C00B78F */  lw         $s7, 0x5C($sp)
/* 1B40AE0 8008C518 5800B68F */  lw         $s6, 0x58($sp)
/* 1B40AE4 8008C51C 5400B58F */  lw         $s5, 0x54($sp)
/* 1B40AE8 8008C520 5000B48F */  lw         $s4, 0x50($sp)
/* 1B40AEC 8008C524 4C00B38F */  lw         $s3, 0x4C($sp)
/* 1B40AF0 8008C528 4800B28F */  lw         $s2, 0x48($sp)
/* 1B40AF4 8008C52C 4400B18F */  lw         $s1, 0x44($sp)
/* 1B40AF8 8008C530 4000B08F */  lw         $s0, 0x40($sp)
/* 1B40AFC 8008C534 6800BD27 */  addiu      $sp, $sp, 0x68
/* 1B40B00 8008C538 0800E003 */  jr         $ra
/* 1B40B04 8008C53C 00000000 */   nop
.size func_level_21_8008B1C0, . - func_level_21_8008B1C0
