.set noat      /* allow manual use of $at */
.set noreorder /* don't insert nops after branches */

.section .rodata.jtbl
.align 3
dlabel jtbl_level_50_8007B5CC
/* 43DBB94 8007B5CC 84980880 */ .word .L80089884_
/* 43DBB98 8007B5D0 0C990880 */ .word .L8008990C_
/* 43DBB9C 8007B5D4 90990880 */ .word .L80089990_
/* 43DBBA0 8007B5D8 D4A90880 */ .word .Llevel_50_8008A9D4
/* 43DBBA4 8007B5DC D4A90880 */ .word .Llevel_50_8008A9D4
/* 43DBBA8 8007B5E0 D4A90880 */ .word .Llevel_50_8008A9D4
/* 43DBBAC 8007B5E4 149A0880 */ .word .L80089A14_
/* 43DBBB0 8007B5E8 D4A90880 */ .word .Llevel_50_8008A9D4
/* 43DBBB4 8007B5EC D4A90880 */ .word .Llevel_50_8008A9D4
/* 43DBBB8 8007B5F0 E49A0880 */ .word .L80089AE4_
/* 43DBBBC 8007B5F4 489B0880 */ .word .L80089B48_
/* 43DBBC0 8007B5F8 549C0880 */ .word .L80089C54_
/* 43DBBC4 8007B5FC 989C0880 */ .word .L80089C98_
/* 43DBBC8 8007B600 D4A90880 */ .word .Llevel_50_8008A9D4
/* 43DBBCC 8007B604 D4A90880 */ .word .Llevel_50_8008A9D4
/* 43DBBD0 8007B608 D4A90880 */ .word .Llevel_50_8008A9D4
/* 43DBBD4 8007B60C 0C9D0880 */ .word .L80089D0C_
/* 43DBBD8 8007B610 8C9D0880 */ .word .L80089D8C_
/* 43DBBDC 8007B614 D4A90880 */ .word .Llevel_50_8008A9D4
/* 43DBBE0 8007B618 D4A90880 */ .word .Llevel_50_8008A9D4
/* 43DBBE4 8007B61C D4A90880 */ .word .Llevel_50_8008A9D4
/* 43DBBE8 8007B620 D4A90880 */ .word .Llevel_50_8008A9D4
/* 43DBBEC 8007B624 D4A90880 */ .word .Llevel_50_8008A9D4
/* 43DBBF0 8007B628 D4A90880 */ .word .Llevel_50_8008A9D4
/* 43DBBF4 8007B62C 249E0880 */ .word .L80089E24_
/* 43DBBF8 8007B630 D4A90880 */ .word .Llevel_50_8008A9D4
/* 43DBBFC 8007B634 D4A90880 */ .word .Llevel_50_8008A9D4
/* 43DBC00 8007B638 D4A90880 */ .word .Llevel_50_8008A9D4
/* 43DBC04 8007B63C D4A90880 */ .word .Llevel_50_8008A9D4
/* 43DBC08 8007B640 D4A90880 */ .word .Llevel_50_8008A9D4
/* 43DBC0C 8007B644 D4A90880 */ .word .Llevel_50_8008A9D4
/* 43DBC10 8007B648 D4A90880 */ .word .Llevel_50_8008A9D4
/* 43DBC14 8007B64C D4A90880 */ .word .Llevel_50_8008A9D4
/* 43DBC18 8007B650 5C9F0880 */ .word .L80089F5C_
/* 43DBC1C 8007B654 D4A90880 */ .word .Llevel_50_8008A9D4
/* 43DBC20 8007B658 D4A90880 */ .word .Llevel_50_8008A9D4
/* 43DBC24 8007B65C D4A90880 */ .word .Llevel_50_8008A9D4
/* 43DBC28 8007B660 D4A90880 */ .word .Llevel_50_8008A9D4
/* 43DBC2C 8007B664 D4A90880 */ .word .Llevel_50_8008A9D4
/* 43DBC30 8007B668 D4A90880 */ .word .Llevel_50_8008A9D4
/* 43DBC34 8007B66C D4A90880 */ .word .Llevel_50_8008A9D4
/* 43DBC38 8007B670 D4A90880 */ .word .Llevel_50_8008A9D4
/* 43DBC3C 8007B674 D4A90880 */ .word .Llevel_50_8008A9D4
/* 43DBC40 8007B678 D4A90880 */ .word .Llevel_50_8008A9D4
/* 43DBC44 8007B67C D4A90880 */ .word .Llevel_50_8008A9D4
/* 43DBC48 8007B680 D4A90880 */ .word .Llevel_50_8008A9D4
/* 43DBC4C 8007B684 D4A90880 */ .word .Llevel_50_8008A9D4
/* 43DBC50 8007B688 D4A90880 */ .word .Llevel_50_8008A9D4
/* 43DBC54 8007B68C D4A90880 */ .word .Llevel_50_8008A9D4
/* 43DBC58 8007B690 D4A90880 */ .word .Llevel_50_8008A9D4
/* 43DBC5C 8007B694 D4A90880 */ .word .Llevel_50_8008A9D4
/* 43DBC60 8007B698 D4A90880 */ .word .Llevel_50_8008A9D4
/* 43DBC64 8007B69C D4A90880 */ .word .Llevel_50_8008A9D4
/* 43DBC68 8007B6A0 D4A90880 */ .word .Llevel_50_8008A9D4
/* 43DBC6C 8007B6A4 D4A90880 */ .word .Llevel_50_8008A9D4
/* 43DBC70 8007B6A8 D4A90880 */ .word .Llevel_50_8008A9D4
/* 43DBC74 8007B6AC D4A90880 */ .word .Llevel_50_8008A9D4
/* 43DBC78 8007B6B0 D4A90880 */ .word .Llevel_50_8008A9D4
/* 43DBC7C 8007B6B4 D4A90880 */ .word .Llevel_50_8008A9D4
/* 43DBC80 8007B6B8 D4A90880 */ .word .Llevel_50_8008A9D4
/* 43DBC84 8007B6BC D4A90880 */ .word .Llevel_50_8008A9D4
/* 43DBC88 8007B6C0 D4A90880 */ .word .Llevel_50_8008A9D4
/* 43DBC8C 8007B6C4 D4A90880 */ .word .Llevel_50_8008A9D4
/* 43DBC90 8007B6C8 D4A90880 */ .word .Llevel_50_8008A9D4
/* 43DBC94 8007B6CC D4A90880 */ .word .Llevel_50_8008A9D4
/* 43DBC98 8007B6D0 D4A90880 */ .word .Llevel_50_8008A9D4
/* 43DBC9C 8007B6D4 0CA00880 */ .word .L8008A00C_
/* 43DBCA0 8007B6D8 D4A90880 */ .word .Llevel_50_8008A9D4
/* 43DBCA4 8007B6DC D4A90880 */ .word .Llevel_50_8008A9D4
/* 43DBCA8 8007B6E0 D4A90880 */ .word .Llevel_50_8008A9D4
/* 43DBCAC 8007B6E4 D8A00880 */ .word .L8008A0D8_
/* 43DBCB0 8007B6E8 C4A20880 */ .word .L8008A2C4_
/* 43DBCB4 8007B6EC 38A40880 */ .word .L8008A438_
/* 43DBCB8 8007B6F0 D4A90880 */ .word .Llevel_50_8008A9D4
/* 43DBCBC 8007B6F4 74A50880 */ .word .L8008A574_
/* 43DBCC0 8007B6F8 D4A90880 */ .word .Llevel_50_8008A9D4
/* 43DBCC4 8007B6FC D4A90880 */ .word .Llevel_50_8008A9D4
/* 43DBCC8 8007B700 DCA50880 */ .word .L8008A5DC_
/* 43DBCCC 8007B704 C0A60880 */ .word .L8008A6C0_
/* 43DBCD0 8007B708 C0A70880 */ .word .L8008A7C0_
/* 43DBCD4 8007B70C E8A80880 */ .word .L8008A8E8_
.size jtbl_level_50_8007B5CC, . - jtbl_level_50_8007B5CC


.section .text
/* Generated by spimdisasm 1.27.0 */

glabel func_level_50_800897FC
/* 43E9DC4 800897FC 80FFBD27 */  addiu      $sp, $sp, -0x80
/* 43E9DC8 80089800 6800B4AF */  sw         $s4, 0x68($sp)
/* 43E9DCC 80089804 0780143C */  lui        $s4, %hi(D_80075824)
/* 43E9DD0 80089808 2458948E */  lw         $s4, %lo(D_80075824)($s4)
/* 43E9DD4 8008980C 7000B6AF */  sw         $s6, 0x70($sp)
/* 43E9DD8 80089810 7C00BFAF */  sw         $ra, 0x7C($sp)
/* 43E9DDC 80089814 7800BEAF */  sw         $fp, 0x78($sp)
/* 43E9DE0 80089818 7400B7AF */  sw         $s7, 0x74($sp)
/* 43E9DE4 8008981C 6C00B5AF */  sw         $s5, 0x6C($sp)
/* 43E9DE8 80089820 6400B3AF */  sw         $s3, 0x64($sp)
/* 43E9DEC 80089824 6000B2AF */  sw         $s2, 0x60($sp)
/* 43E9DF0 80089828 5C00B1AF */  sw         $s1, 0x5C($sp)
/* 43E9DF4 8008982C 5800B0AF */  sw         $s0, 0x58($sp)
/* 43E9DF8 80089830 01008392 */  lbu        $v1, 0x1($s4)
/* 43E9DFC 80089834 FF000224 */  addiu      $v0, $zero, 0xFF
/* 43E9E00 80089838 6D046210 */  beq        $v1, $v0, .Llevel_50_8008A9F0
/* 43E9E04 8008983C 21B08000 */   addu      $s6, $a0, $zero
/* 43E9E08 80089840 40381600 */  sll        $a3, $s6, 1
/* 43E9E0C 80089844 4800A7AF */  sw         $a3, 0x48($sp)
/* 43E9E10 80089848 80B81600 */  sll        $s7, $s6, 2
/* 43E9E14 8008984C 01009126 */  addiu      $s1, $s4, 0x1
/* 43E9E18 80089850 18009E26 */  addiu      $fp, $s4, 0x18
/* 43E9E1C 80089854 04009526 */  addiu      $s5, $s4, 0x4
.Llevel_50_80089858:
/* 43E9E20 80089858 00008392 */  lbu        $v1, 0x0($s4)
/* 43E9E24 8008985C 00000000 */  nop
/* 43E9E28 80089860 5100622C */  sltiu      $v0, $v1, 0x51
/* 43E9E2C 80089864 5B044010 */  beqz       $v0, .Llevel_50_8008A9D4
/* 43E9E30 80089868 80100300 */   sll       $v0, $v1, 2
/* 43E9E34 8008986C 0880013C */  lui        $at, %hi(jtbl_level_50_8007B5CC)
/* 43E9E38 80089870 21082200 */  addu       $at, $at, $v0
/* 43E9E3C 80089874 CCB5228C */  lw         $v0, %lo(jtbl_level_50_8007B5CC)($at)
/* 43E9E40 80089878 00000000 */  nop
/* 43E9E44 8008987C 08004000 */  jr         $v0
/* 43E9E48 80089880 00000000 */   nop
.L80089884_:
/* 43E9E4C 80089884 2120A002 */  addu       $a0, $s5, $zero
/* 43E9E50 80089888 2128A002 */  addu       $a1, $s5, $zero
/* 43E9E54 8008988C 215F000C */  jal        func_80017C84
/* 43E9E58 80089890 2130C003 */   addu      $a2, $fp, $zero
/* 43E9E5C 80089894 1D002286 */  lh         $v0, 0x1D($s1)
/* 43E9E60 80089898 00000000 */  nop
/* 43E9E64 8008989C 05004010 */  beqz       $v0, .Llevel_50_800898B4
/* 43E9E68 800898A0 01000724 */   addiu     $a3, $zero, 0x1
/* 43E9E6C 800898A4 1B002296 */  lhu        $v0, 0x1B($s1)
/* 43E9E70 800898A8 00000000 */  nop
/* 43E9E74 800898AC 01004224 */  addiu      $v0, $v0, 0x1
/* 43E9E78 800898B0 1B0022A6 */  sh         $v0, 0x1B($s1)
.Llevel_50_800898B4:
/* 43E9E7C 800898B4 1D002296 */  lhu        $v0, 0x1D($s1)
/* 43E9E80 800898B8 09002392 */  lbu        $v1, 0x9($s1)
/* 43E9E84 800898BC 2310E200 */  subu       $v0, $a3, $v0
/* 43E9E88 800898C0 1D0022A6 */  sh         $v0, 0x1D($s1)
/* 43E9E8C 800898C4 4800A78F */  lw         $a3, 0x48($sp)
/* 43E9E90 800898C8 0B002292 */  lbu        $v0, 0xB($s1)
/* 43E9E94 800898CC 21186700 */  addu       $v1, $v1, $a3
/* 43E9E98 800898D0 090023A2 */  sb         $v1, 0x9($s1)
/* 43E9E9C 800898D4 0C002392 */  lbu        $v1, 0xC($s1)
/* 43E9EA0 800898D8 23105700 */  subu       $v0, $v0, $s7
/* 43E9EA4 800898DC 0B0022A2 */  sb         $v0, 0xB($s1)
/* 43E9EA8 800898E0 01002292 */  lbu        $v0, 0x1($s1)
/* 43E9EAC 800898E4 23187700 */  subu       $v1, $v1, $s7
/* 43E9EB0 800898E8 21105600 */  addu       $v0, $v0, $s6
/* 43E9EB4 800898EC 010022A2 */  sb         $v0, 0x1($s1)
/* 43E9EB8 800898F0 FF004230 */  andi       $v0, $v0, 0xFF
/* 43E9EBC 800898F4 0C0023A2 */  sb         $v1, 0xC($s1)
/* 43E9EC0 800898F8 0D002392 */  lbu        $v1, 0xD($s1)
/* 43E9EC4 800898FC 2000422C */  sltiu      $v0, $v0, 0x20
/* 43E9EC8 80089900 23187700 */  subu       $v1, $v1, $s7
/* 43E9ECC 80089904 6D2A0208 */  j          .Llevel_50_8008A9B4
/* 43E9ED0 80089908 0D0023A2 */   sb        $v1, 0xD($s1)
.L8008990C_:
/* 43E9ED4 8008990C 2120A002 */  addu       $a0, $s5, $zero
/* 43E9ED8 80089910 2128A002 */  addu       $a1, $s5, $zero
/* 43E9EDC 80089914 215F000C */  jal        func_80017C84
/* 43E9EE0 80089918 2130C003 */   addu      $a2, $fp, $zero
/* 43E9EE4 8008991C 1D002286 */  lh         $v0, 0x1D($s1)
/* 43E9EE8 80089920 00000000 */  nop
/* 43E9EEC 80089924 05004010 */  beqz       $v0, .Llevel_50_8008993C
/* 43E9EF0 80089928 01000724 */   addiu     $a3, $zero, 0x1
/* 43E9EF4 8008992C 1B002296 */  lhu        $v0, 0x1B($s1)
/* 43E9EF8 80089930 00000000 */  nop
/* 43E9EFC 80089934 01004224 */  addiu      $v0, $v0, 0x1
/* 43E9F00 80089938 1B0022A6 */  sh         $v0, 0x1B($s1)
.Llevel_50_8008993C:
/* 43E9F04 8008993C 09002392 */  lbu        $v1, 0x9($s1)
/* 43E9F08 80089940 1D002296 */  lhu        $v0, 0x1D($s1)
/* 43E9F0C 80089944 21187700 */  addu       $v1, $v1, $s7
/* 43E9F10 80089948 090023A2 */  sb         $v1, 0x9($s1)
/* 43E9F14 8008994C 0C002392 */  lbu        $v1, 0xC($s1)
/* 43E9F18 80089950 2310E200 */  subu       $v0, $a3, $v0
/* 43E9F1C 80089954 1D0022A6 */  sh         $v0, 0x1D($s1)
/* 43E9F20 80089958 0B002292 */  lbu        $v0, 0xB($s1)
/* 43E9F24 8008995C 23187700 */  subu       $v1, $v1, $s7
/* 43E9F28 80089960 0C0023A2 */  sb         $v1, 0xC($s1)
/* 43E9F2C 80089964 0D002392 */  lbu        $v1, 0xD($s1)
/* 43E9F30 80089968 23105700 */  subu       $v0, $v0, $s7
/* 43E9F34 8008996C 0B0022A2 */  sb         $v0, 0xB($s1)
/* 43E9F38 80089970 01002292 */  lbu        $v0, 0x1($s1)
/* 43E9F3C 80089974 23187700 */  subu       $v1, $v1, $s7
/* 43E9F40 80089978 21105600 */  addu       $v0, $v0, $s6
/* 43E9F44 8008997C 010022A2 */  sb         $v0, 0x1($s1)
/* 43E9F48 80089980 FF004230 */  andi       $v0, $v0, 0xFF
/* 43E9F4C 80089984 1800422C */  sltiu      $v0, $v0, 0x18
/* 43E9F50 80089988 6D2A0208 */  j          .Llevel_50_8008A9B4
/* 43E9F54 8008998C 0D0023A2 */   sb        $v1, 0xD($s1)
.L80089990_:
/* 43E9F58 80089990 2120A002 */  addu       $a0, $s5, $zero
/* 43E9F5C 80089994 2128A002 */  addu       $a1, $s5, $zero
/* 43E9F60 80089998 215F000C */  jal        func_80017C84
/* 43E9F64 8008999C 2130C003 */   addu      $a2, $fp, $zero
/* 43E9F68 800899A0 1D002286 */  lh         $v0, 0x1D($s1)
/* 43E9F6C 800899A4 00000000 */  nop
/* 43E9F70 800899A8 05004010 */  beqz       $v0, .Llevel_50_800899C0
/* 43E9F74 800899AC 01000724 */   addiu     $a3, $zero, 0x1
/* 43E9F78 800899B0 1B002296 */  lhu        $v0, 0x1B($s1)
/* 43E9F7C 800899B4 00000000 */  nop
/* 43E9F80 800899B8 01004224 */  addiu      $v0, $v0, 0x1
/* 43E9F84 800899BC 1B0022A6 */  sh         $v0, 0x1B($s1)
.Llevel_50_800899C0:
/* 43E9F88 800899C0 09002392 */  lbu        $v1, 0x9($s1)
/* 43E9F8C 800899C4 1D002296 */  lhu        $v0, 0x1D($s1)
/* 43E9F90 800899C8 21187700 */  addu       $v1, $v1, $s7
/* 43E9F94 800899CC 090023A2 */  sb         $v1, 0x9($s1)
/* 43E9F98 800899D0 0C002392 */  lbu        $v1, 0xC($s1)
/* 43E9F9C 800899D4 2310E200 */  subu       $v0, $a3, $v0
/* 43E9FA0 800899D8 1D0022A6 */  sh         $v0, 0x1D($s1)
/* 43E9FA4 800899DC 0B002292 */  lbu        $v0, 0xB($s1)
/* 43E9FA8 800899E0 23187700 */  subu       $v1, $v1, $s7
/* 43E9FAC 800899E4 0C0023A2 */  sb         $v1, 0xC($s1)
/* 43E9FB0 800899E8 0D002392 */  lbu        $v1, 0xD($s1)
/* 43E9FB4 800899EC 23105700 */  subu       $v0, $v0, $s7
/* 43E9FB8 800899F0 0B0022A2 */  sb         $v0, 0xB($s1)
/* 43E9FBC 800899F4 01002292 */  lbu        $v0, 0x1($s1)
/* 43E9FC0 800899F8 23187700 */  subu       $v1, $v1, $s7
/* 43E9FC4 800899FC 21105600 */  addu       $v0, $v0, $s6
/* 43E9FC8 80089A00 010022A2 */  sb         $v0, 0x1($s1)
/* 43E9FCC 80089A04 FF004230 */  andi       $v0, $v0, 0xFF
/* 43E9FD0 80089A08 2000422C */  sltiu      $v0, $v0, 0x20
/* 43E9FD4 80089A0C 6D2A0208 */  j          .Llevel_50_8008A9B4
/* 43E9FD8 80089A10 0D0023A2 */   sb        $v1, 0xD($s1)
.L80089A14_:
/* 43E9FDC 80089A14 1700258E */  lw         $a1, 0x17($s1)
/* 43E9FE0 80089A18 C05D000C */  jal        VecCopy
/* 43E9FE4 80089A1C 1000A427 */   addiu     $a0, $sp, 0x10
/* 43E9FE8 80089A20 01002292 */  lbu        $v0, 0x1($s1)
/* 43E9FEC 80089A24 00000000 */  nop
/* 43E9FF0 80089A28 80810200 */  sll        $s0, $v0, 6
/* 43E9FF4 80089A2C 1D002286 */  lh         $v0, 0x1D($s1)
/* 43E9FF8 80089A30 1800A38F */  lw         $v1, 0x18($sp)
/* 43E9FFC 80089A34 80110200 */  sll        $v0, $v0, 6
/* 43EA000 80089A38 21986200 */  addu       $s3, $v1, $v0
/* 43EA004 80089A3C 1B002386 */  lh         $v1, 0x1B($s1)
/* 43EA008 80089A40 00000000 */  nop
/* 43EA00C 80089A44 2A107000 */  slt        $v0, $v1, $s0
/* 43EA010 80089A48 02004010 */  beqz       $v0, .Llevel_50_80089A54
/* 43EA014 80089A4C 21900002 */   addu      $s2, $s0, $zero
/* 43EA018 80089A50 21806000 */  addu       $s0, $v1, $zero
.Llevel_50_80089A54:
/* 43EA01C 80089A54 2C5B000C */  jal        Cos
/* 43EA020 80089A58 21204002 */   addu      $a0, $s2, $zero
/* 43EA024 80089A5C 18000202 */  mult       $s0, $v0
/* 43EA028 80089A60 21204002 */  addu       $a0, $s2, $zero
/* 43EA02C 80089A64 1000A28F */  lw         $v0, 0x10($sp)
/* 43EA030 80089A68 12380000 */  mflo       $a3
/* 43EA034 80089A6C 031B0700 */  sra        $v1, $a3, 12
/* 43EA038 80089A70 21104300 */  addu       $v0, $v0, $v1
/* 43EA03C 80089A74 165B000C */  jal        Sin
/* 43EA040 80089A78 1000A2AF */   sw        $v0, 0x10($sp)
/* 43EA044 80089A7C 18000202 */  mult       $s0, $v0
/* 43EA048 80089A80 1400A28F */  lw         $v0, 0x14($sp)
/* 43EA04C 80089A84 12380000 */  mflo       $a3
/* 43EA050 80089A88 031B0700 */  sra        $v1, $a3, 12
/* 43EA054 80089A8C 21104300 */  addu       $v0, $v0, $v1
/* 43EA058 80089A90 1400A2AF */  sw         $v0, 0x14($sp)
/* 43EA05C 80089A94 07002286 */  lh         $v0, 0x7($s1)
/* 43EA060 80089A98 00000000 */  nop
/* 43EA064 80089A9C 80100200 */  sll        $v0, $v0, 2
/* 43EA068 80089AA0 40004224 */  addiu      $v0, $v0, 0x40
/* 43EA06C 80089AA4 1800A2AF */  sw         $v0, 0x18($sp)
/* 43EA070 80089AA8 2A106202 */  slt        $v0, $s3, $v0
/* 43EA074 80089AAC C7034014 */  bnez       $v0, .Llevel_50_8008A9CC
/* 43EA078 80089AB0 00000000 */   nop
/* 43EA07C 80089AB4 01002292 */  lbu        $v0, 0x1($s1)
/* 43EA080 80089AB8 00000000 */  nop
/* 43EA084 80089ABC C900422C */  sltiu      $v0, $v0, 0xC9
/* 43EA088 80089AC0 C2034010 */  beqz       $v0, .Llevel_50_8008A9CC
/* 43EA08C 80089AC4 2120A002 */   addu      $a0, $s5, $zero
/* 43EA090 80089AC8 FF5E000C */  jal        func_80017BFC
/* 43EA094 80089ACC 1000A527 */   addiu     $a1, $sp, 0x10
/* 43EA098 80089AD0 01002292 */  lbu        $v0, 0x1($s1)
/* 43EA09C 80089AD4 00000000 */  nop
/* 43EA0A0 80089AD8 01004224 */  addiu      $v0, $v0, 0x1
/* 43EA0A4 80089ADC 752A0208 */  j          .Llevel_50_8008A9D4
/* 43EA0A8 80089AE0 010022A2 */   sb        $v0, 0x1($s1)
.L80089AE4_:
/* 43EA0AC 80089AE4 2120A002 */  addu       $a0, $s5, $zero
/* 43EA0B0 80089AE8 2128A002 */  addu       $a1, $s5, $zero
/* 43EA0B4 80089AEC 215F000C */  jal        func_80017C84
/* 43EA0B8 80089AF0 2130C003 */   addu      $a2, $fp, $zero
/* 43EA0BC 80089AF4 1D002286 */  lh         $v0, 0x1D($s1)
/* 43EA0C0 80089AF8 00000000 */  nop
/* 43EA0C4 80089AFC 05004010 */  beqz       $v0, .Llevel_50_80089B14
/* 43EA0C8 80089B00 01000724 */   addiu     $a3, $zero, 0x1
/* 43EA0CC 80089B04 1B002296 */  lhu        $v0, 0x1B($s1)
/* 43EA0D0 80089B08 00000000 */  nop
/* 43EA0D4 80089B0C 01004224 */  addiu      $v0, $v0, 0x1
/* 43EA0D8 80089B10 1B0022A6 */  sh         $v0, 0x1B($s1)
.Llevel_50_80089B14:
/* 43EA0DC 80089B14 1D002296 */  lhu        $v0, 0x1D($s1)
/* 43EA0E0 80089B18 09002392 */  lbu        $v1, 0x9($s1)
/* 43EA0E4 80089B1C 2310E200 */  subu       $v0, $a3, $v0
/* 43EA0E8 80089B20 1D0022A6 */  sh         $v0, 0x1D($s1)
/* 43EA0EC 80089B24 4800A78F */  lw         $a3, 0x48($sp)
/* 43EA0F0 80089B28 01002292 */  lbu        $v0, 0x1($s1)
/* 43EA0F4 80089B2C 21186700 */  addu       $v1, $v1, $a3
/* 43EA0F8 80089B30 21105600 */  addu       $v0, $v0, $s6
/* 43EA0FC 80089B34 010022A2 */  sb         $v0, 0x1($s1)
/* 43EA100 80089B38 FF004230 */  andi       $v0, $v0, 0xFF
/* 43EA104 80089B3C 2000422C */  sltiu      $v0, $v0, 0x20
/* 43EA108 80089B40 6D2A0208 */  j          .Llevel_50_8008A9B4
/* 43EA10C 80089B44 090023A2 */   sb        $v1, 0x9($s1)
.L80089B48_:
/* 43EA110 80089B48 0880033C */  lui        $v1, %hi(g_Spyro + 0x78)
/* 43EA114 80089B4C D08A638C */  lw         $v1, %lo(g_Spyro + 0x78)($v1)
/* 43EA118 80089B50 1D000224 */  addiu      $v0, $zero, 0x1D
/* 43EA11C 80089B54 06006214 */  bne        $v1, $v0, .Llevel_50_80089B70
/* 43EA120 80089B58 00000000 */   nop
/* 43EA124 80089B5C 0880023C */  lui        $v0, %hi(g_Spyro + 0x164)
/* 43EA128 80089B60 BC8B428C */  lw         $v0, %lo(g_Spyro + 0x164)($v0)
/* 43EA12C 80089B64 00000000 */  nop
/* 43EA130 80089B68 98034004 */  bltz       $v0, .Llevel_50_8008A9CC
/* 43EA134 80089B6C 00000000 */   nop
.Llevel_50_80089B70:
/* 43EA138 80089B70 0780023C */  lui        $v0, %hi(g_IsSpyroHidden)
/* 43EA13C 80089B74 1458428C */  lw         $v0, %lo(g_IsSpyroHidden)($v0)
/* 43EA140 80089B78 00000000 */  nop
/* 43EA144 80089B7C 93034014 */  bnez       $v0, .Llevel_50_8008A9CC
/* 43EA148 80089B80 00000000 */   nop
/* 43EA14C 80089B84 0880053C */  lui        $a1, %hi(g_Spyro + 0x160)
/* 43EA150 80089B88 B88BA524 */  addiu      $a1, $a1, %lo(g_Spyro + 0x160)
/* 43EA154 80089B8C 0000A28C */  lw         $v0, 0x0($a1)
/* 43EA158 80089B90 00000000 */  nop
/* 43EA15C 80089B94 8D034018 */  blez       $v0, .Llevel_50_8008A9CC
/* 43EA160 80089B98 2000B027 */   addiu     $s0, $sp, 0x20
/* 43EA164 80089B9C 21200002 */  addu       $a0, $s0, $zero
/* 43EA168 80089BA0 C05D000C */  jal        VecCopy
/* 43EA16C 80089BA4 A0FEA524 */   addiu     $a1, $a1, -0x160
/* 43EA170 80089BA8 17002486 */  lh         $a0, 0x17($s1)
/* 43EA174 80089BAC 2C5B000C */  jal        Cos
/* 43EA178 80089BB0 00000000 */   nop
/* 43EA17C 80089BB4 2000A38F */  lw         $v1, 0x20($sp)
/* 43EA180 80089BB8 03110200 */  sra        $v0, $v0, 4
/* 43EA184 80089BBC 21186200 */  addu       $v1, $v1, $v0
/* 43EA188 80089BC0 2000A3AF */  sw         $v1, 0x20($sp)
/* 43EA18C 80089BC4 17002486 */  lh         $a0, 0x17($s1)
/* 43EA190 80089BC8 165B000C */  jal        Sin
/* 43EA194 80089BCC 00000000 */   nop
/* 43EA198 80089BD0 2120A002 */  addu       $a0, $s5, $zero
/* 43EA19C 80089BD4 21280002 */  addu       $a1, $s0, $zero
/* 43EA1A0 80089BD8 03110200 */  sra        $v0, $v0, 4
/* 43EA1A4 80089BDC 2400A38F */  lw         $v1, 0x24($sp)
/* 43EA1A8 80089BE0 2800A68F */  lw         $a2, 0x28($sp)
/* 43EA1AC 80089BE4 21186200 */  addu       $v1, $v1, $v0
/* 43EA1B0 80089BE8 0001C624 */  addiu      $a2, $a2, 0x100
/* 43EA1B4 80089BEC 2400A3AF */  sw         $v1, 0x24($sp)
/* 43EA1B8 80089BF0 FF5E000C */  jal        func_80017BFC
/* 43EA1BC 80089BF4 2800A6AF */   sw        $a2, 0x28($sp)
/* 43EA1C0 80089BF8 17002496 */  lhu        $a0, 0x17($s1)
/* 43EA1C4 80089BFC 00000000 */  nop
/* 43EA1C8 80089C00 40008424 */  addiu      $a0, $a0, 0x40
/* 43EA1CC 80089C04 170024A6 */  sh         $a0, 0x17($s1)
/* 43EA1D0 80089C08 00240400 */  sll        $a0, $a0, 16
/* 43EA1D4 80089C0C 0780023C */  lui        $v0, %hi(g_Camera + 0x50)
/* 43EA1D8 80089C10 206E4284 */  lh         $v0, %lo(g_Camera + 0x50)($v0)
/* 43EA1DC 80089C14 03240400 */  sra        $a0, $a0, 16
/* 43EA1E0 80089C18 23208200 */  subu       $a0, $a0, $v0
/* 43EA1E4 80089C1C 2C5B000C */  jal        Cos
/* 43EA1E8 80089C20 FF0F8430 */   andi      $a0, $a0, 0xFFF
/* 43EA1EC 80089C24 6060033C */  lui        $v1, (0x60606061 >> 16)
/* 43EA1F0 80089C28 61606334 */  ori        $v1, $v1, (0x60606061 & 0xFFFF)
/* 43EA1F4 80089C2C 02004104 */  bgez       $v0, .Llevel_50_80089C38
/* 43EA1F8 80089C30 00000000 */   nop
/* 43EA1FC 80089C34 23100200 */  negu       $v0, $v0
.Llevel_50_80089C38:
/* 43EA200 80089C38 18004300 */  mult       $v0, $v1
/* 43EA204 80089C3C C3170200 */  sra        $v0, $v0, 31
/* 43EA208 80089C40 10380000 */  mfhi       $a3
/* 43EA20C 80089C44 83190700 */  sra        $v1, $a3, 6
/* 43EA210 80089C48 23186200 */  subu       $v1, $v1, $v0
/* 43EA214 80089C4C 752A0208 */  j          .Llevel_50_8008A9D4
/* 43EA218 80089C50 090023A2 */   sb        $v1, 0x9($s1)
.L80089C54_:
/* 43EA21C 80089C54 2120A002 */  addu       $a0, $s5, $zero
/* 43EA220 80089C58 2128A002 */  addu       $a1, $s5, $zero
/* 43EA224 80089C5C 215F000C */  jal        func_80017C84
/* 43EA228 80089C60 12008626 */   addiu     $a2, $s4, 0x12
/* 43EA22C 80089C64 0B002292 */  lbu        $v0, 0xB($s1)
/* 43EA230 80089C68 0C002392 */  lbu        $v1, 0xC($s1)
/* 43EA234 80089C6C F8FF4224 */  addiu      $v0, $v0, -0x8
/* 43EA238 80089C70 0B0022A2 */  sb         $v0, 0xB($s1)
/* 43EA23C 80089C74 0D002292 */  lbu        $v0, 0xD($s1)
/* 43EA240 80089C78 F8FF6324 */  addiu      $v1, $v1, -0x8
/* 43EA244 80089C7C 0C0023A2 */  sb         $v1, 0xC($s1)
/* 43EA248 80089C80 0B002392 */  lbu        $v1, 0xB($s1)
/* 43EA24C 80089C84 F8FF4224 */  addiu      $v0, $v0, -0x8
/* 43EA250 80089C88 50036010 */  beqz       $v1, .Llevel_50_8008A9CC
/* 43EA254 80089C8C 0D0022A2 */   sb        $v0, 0xD($s1)
/* 43EA258 80089C90 6F2A0208 */  j          .Llevel_50_8008A9BC
/* 43EA25C 80089C94 00000000 */   nop
.L80089C98_:
/* 43EA260 80089C98 0A002292 */  lbu        $v0, 0xA($s1)
/* 43EA264 80089C9C 00000000 */  nop
/* 43EA268 80089CA0 08004224 */  addiu      $v0, $v0, 0x8
/* 43EA26C 80089CA4 0A0022A2 */  sb         $v0, 0xA($s1)
/* 43EA270 80089CA8 09002292 */  lbu        $v0, 0x9($s1)
/* 43EA274 80089CAC 0B002392 */  lbu        $v1, 0xB($s1)
/* 43EA278 80089CB0 02004224 */  addiu      $v0, $v0, 0x2
/* 43EA27C 80089CB4 03006010 */  beqz       $v1, .Llevel_50_80089CC4
/* 43EA280 80089CB8 090022A2 */   sb        $v0, 0x9($s1)
/* 43EA284 80089CBC F8FF6224 */  addiu      $v0, $v1, -0x8
/* 43EA288 80089CC0 0B0022A2 */  sb         $v0, 0xB($s1)
.Llevel_50_80089CC4:
/* 43EA28C 80089CC4 0C002292 */  lbu        $v0, 0xC($s1)
/* 43EA290 80089CC8 00000000 */  nop
/* 43EA294 80089CCC 02004010 */  beqz       $v0, .Llevel_50_80089CD8
/* 43EA298 80089CD0 F8FF4224 */   addiu     $v0, $v0, -0x8
/* 43EA29C 80089CD4 0C0022A2 */  sb         $v0, 0xC($s1)
.Llevel_50_80089CD8:
/* 43EA2A0 80089CD8 0D002292 */  lbu        $v0, 0xD($s1)
/* 43EA2A4 80089CDC 00000000 */  nop
/* 43EA2A8 80089CE0 02004010 */  beqz       $v0, .Llevel_50_80089CEC
/* 43EA2AC 80089CE4 F8FF4224 */   addiu     $v0, $v0, -0x8
/* 43EA2B0 80089CE8 0D0022A2 */  sb         $v0, 0xD($s1)
.Llevel_50_80089CEC:
/* 43EA2B4 80089CEC FF00033C */  lui        $v1, (0xFFFFFF >> 16)
/* 43EA2B8 80089CF0 0B00228E */  lw         $v0, 0xB($s1)
/* 43EA2BC 80089CF4 FFFF6334 */  ori        $v1, $v1, (0xFFFFFF & 0xFFFF)
/* 43EA2C0 80089CF8 24104300 */  and        $v0, $v0, $v1
/* 43EA2C4 80089CFC 33034010 */  beqz       $v0, .Llevel_50_8008A9CC
/* 43EA2C8 80089D00 00000000 */   nop
/* 43EA2CC 80089D04 6F2A0208 */  j          .Llevel_50_8008A9BC
/* 43EA2D0 80089D08 00000000 */   nop
.L80089D0C_:
/* 43EA2D4 80089D0C 2120A002 */  addu       $a0, $s5, $zero
/* 43EA2D8 80089D10 2128A002 */  addu       $a1, $s5, $zero
/* 43EA2DC 80089D14 215F000C */  jal        func_80017C84
/* 43EA2E0 80089D18 2130C003 */   addu      $a2, $fp, $zero
/* 43EA2E4 80089D1C 1D002286 */  lh         $v0, 0x1D($s1)
/* 43EA2E8 80089D20 00000000 */  nop
/* 43EA2EC 80089D24 05004010 */  beqz       $v0, .Llevel_50_80089D3C
/* 43EA2F0 80089D28 01000724 */   addiu     $a3, $zero, 0x1
/* 43EA2F4 80089D2C 1B002296 */  lhu        $v0, 0x1B($s1)
/* 43EA2F8 80089D30 00000000 */  nop
/* 43EA2FC 80089D34 01004224 */  addiu      $v0, $v0, 0x1
/* 43EA300 80089D38 1B0022A6 */  sh         $v0, 0x1B($s1)
.Llevel_50_80089D3C:
/* 43EA304 80089D3C 1D002296 */  lhu        $v0, 0x1D($s1)
/* 43EA308 80089D40 09002392 */  lbu        $v1, 0x9($s1)
/* 43EA30C 80089D44 2310E200 */  subu       $v0, $a3, $v0
/* 43EA310 80089D48 1D0022A6 */  sh         $v0, 0x1D($s1)
/* 43EA314 80089D4C 4800A78F */  lw         $a3, 0x48($sp)
/* 43EA318 80089D50 0B002292 */  lbu        $v0, 0xB($s1)
/* 43EA31C 80089D54 21186700 */  addu       $v1, $v1, $a3
/* 43EA320 80089D58 090023A2 */  sb         $v1, 0x9($s1)
/* 43EA324 80089D5C 0C002392 */  lbu        $v1, 0xC($s1)
/* 43EA328 80089D60 FCFF4224 */  addiu      $v0, $v0, -0x4
/* 43EA32C 80089D64 0B0022A2 */  sb         $v0, 0xB($s1)
/* 43EA330 80089D68 0D002292 */  lbu        $v0, 0xD($s1)
/* 43EA334 80089D6C FCFF6324 */  addiu      $v1, $v1, -0x4
/* 43EA338 80089D70 0C0023A2 */  sb         $v1, 0xC($s1)
/* 43EA33C 80089D74 0B002392 */  lbu        $v1, 0xB($s1)
/* 43EA340 80089D78 FCFF4224 */  addiu      $v0, $v0, -0x4
/* 43EA344 80089D7C 13036010 */  beqz       $v1, .Llevel_50_8008A9CC
/* 43EA348 80089D80 0D0022A2 */   sb        $v0, 0xD($s1)
/* 43EA34C 80089D84 6F2A0208 */  j          .Llevel_50_8008A9BC
/* 43EA350 80089D88 00000000 */   nop
.L80089D8C_:
/* 43EA354 80089D8C 2120A002 */  addu       $a0, $s5, $zero
/* 43EA358 80089D90 2128A002 */  addu       $a1, $s5, $zero
/* 43EA35C 80089D94 215F000C */  jal        func_80017C84
/* 43EA360 80089D98 2130C003 */   addu      $a2, $fp, $zero
/* 43EA364 80089D9C 1D002286 */  lh         $v0, 0x1D($s1)
/* 43EA368 80089DA0 00000000 */  nop
/* 43EA36C 80089DA4 05004010 */  beqz       $v0, .Llevel_50_80089DBC
/* 43EA370 80089DA8 01000724 */   addiu     $a3, $zero, 0x1
/* 43EA374 80089DAC 1B002296 */  lhu        $v0, 0x1B($s1)
/* 43EA378 80089DB0 00000000 */  nop
/* 43EA37C 80089DB4 01004224 */  addiu      $v0, $v0, 0x1
/* 43EA380 80089DB8 1B0022A6 */  sh         $v0, 0x1B($s1)
.Llevel_50_80089DBC:
/* 43EA384 80089DBC 1D002296 */  lhu        $v0, 0x1D($s1)
/* 43EA388 80089DC0 01002392 */  lbu        $v1, 0x1($s1)
/* 43EA38C 80089DC4 2310E200 */  subu       $v0, $a3, $v0
/* 43EA390 80089DC8 1D0022A6 */  sh         $v0, 0x1D($s1)
/* 43EA394 80089DCC 09002292 */  lbu        $v0, 0x9($s1)
/* 43EA398 80089DD0 4800A78F */  lw         $a3, 0x48($sp)
/* 43EA39C 80089DD4 0900632C */  sltiu      $v1, $v1, 0x9
/* 43EA3A0 80089DD8 21104700 */  addu       $v0, $v0, $a3
/* 43EA3A4 80089DDC 05006014 */  bnez       $v1, .Llevel_50_80089DF4
/* 43EA3A8 80089DE0 090022A2 */   sb        $v0, 0x9($s1)
/* 43EA3AC 80089DE4 0B002292 */  lbu        $v0, 0xB($s1)
/* 43EA3B0 80089DE8 00000000 */  nop
/* 43EA3B4 80089DEC E0FF4224 */  addiu      $v0, $v0, -0x20
/* 43EA3B8 80089DF0 0B0022A2 */  sb         $v0, 0xB($s1)
.Llevel_50_80089DF4:
/* 43EA3BC 80089DF4 01002292 */  lbu        $v0, 0x1($s1)
/* 43EA3C0 80089DF8 0C002392 */  lbu        $v1, 0xC($s1)
/* 43EA3C4 80089DFC 0D002492 */  lbu        $a0, 0xD($s1)
/* 43EA3C8 80089E00 01004224 */  addiu      $v0, $v0, 0x1
/* 43EA3CC 80089E04 F8FF6324 */  addiu      $v1, $v1, -0x8
/* 43EA3D0 80089E08 FCFF8424 */  addiu      $a0, $a0, -0x4
/* 43EA3D4 80089E0C 010022A2 */  sb         $v0, 0x1($s1)
/* 43EA3D8 80089E10 FF004230 */  andi       $v0, $v0, 0xFF
/* 43EA3DC 80089E14 0C00422C */  sltiu      $v0, $v0, 0xC
/* 43EA3E0 80089E18 0C0023A2 */  sb         $v1, 0xC($s1)
/* 43EA3E4 80089E1C 6D2A0208 */  j          .Llevel_50_8008A9B4
/* 43EA3E8 80089E20 0D0024A2 */   sb        $a0, 0xD($s1)
.L80089E24_:
/* 43EA3EC 80089E24 0B002392 */  lbu        $v1, 0xB($s1)
/* 43EA3F0 80089E28 00000000 */  nop
/* 43EA3F4 80089E2C F000622C */  sltiu      $v0, $v1, 0xF0
/* 43EA3F8 80089E30 02004010 */  beqz       $v0, .Llevel_50_80089E3C
/* 43EA3FC 80089E34 04006224 */   addiu     $v0, $v1, 0x4
/* 43EA400 80089E38 0B0022A2 */  sb         $v0, 0xB($s1)
.Llevel_50_80089E3C:
/* 43EA404 80089E3C 0C002392 */  lbu        $v1, 0xC($s1)
/* 43EA408 80089E40 00000000 */  nop
/* 43EA40C 80089E44 F000622C */  sltiu      $v0, $v1, 0xF0
/* 43EA410 80089E48 02004010 */  beqz       $v0, .Llevel_50_80089E54
/* 43EA414 80089E4C 04006224 */   addiu     $v0, $v1, 0x4
/* 43EA418 80089E50 0C0022A2 */  sb         $v0, 0xC($s1)
.Llevel_50_80089E54:
/* 43EA41C 80089E54 0D002392 */  lbu        $v1, 0xD($s1)
/* 43EA420 80089E58 00000000 */  nop
/* 43EA424 80089E5C F000622C */  sltiu      $v0, $v1, 0xF0
/* 43EA428 80089E60 02004010 */  beqz       $v0, .Llevel_50_80089E6C
/* 43EA42C 80089E64 04006224 */   addiu     $v0, $v1, 0x4
/* 43EA430 80089E68 0D0022A2 */  sb         $v0, 0xD($s1)
.Llevel_50_80089E6C:
/* 43EA434 80089E6C 0780023C */  lui        $v0, %hi(g_DeltaTime)
/* 43EA438 80089E70 CC56428C */  lw         $v0, %lo(g_DeltaTime)($v0)
/* 43EA43C 80089E74 1B002392 */  lbu        $v1, 0x1B($s1)
/* 43EA440 80089E78 C0100200 */  sll        $v0, $v0, 3
/* 43EA444 80089E7C 21186200 */  addu       $v1, $v1, $v0
/* 43EA448 80089E80 1B0023A2 */  sb         $v1, 0x1B($s1)
/* 43EA44C 80089E84 0780033C */  lui        $v1, %hi(g_DragonCutscene + 0x3C)
/* 43EA450 80089E88 6C70638C */  lw         $v1, %lo(g_DragonCutscene + 0x3C)($v1)
/* 43EA454 80089E8C 00000000 */  nop
/* 43EA458 80089E90 40006228 */  slti       $v0, $v1, 0x40
/* 43EA45C 80089E94 02004010 */  beqz       $v0, .Llevel_50_80089EA0
/* 43EA460 80089E98 3F000424 */   addiu     $a0, $zero, 0x3F
/* 43EA464 80089E9C 21206000 */  addu       $a0, $v1, $zero
.Llevel_50_80089EA0:
/* 43EA468 80089EA0 48000224 */  addiu      $v0, $zero, 0x48
/* 43EA46C 80089EA4 1C002392 */  lbu        $v1, 0x1C($s1)
/* 43EA470 80089EA8 23104400 */  subu       $v0, $v0, $a0
/* 43EA474 80089EAC 18006200 */  mult       $v1, $v0
/* 43EA478 80089EB0 1C002392 */  lbu        $v1, 0x1C($s1)
/* 43EA47C 80089EB4 12280000 */  mflo       $a1
/* 43EA480 80089EB8 20000224 */  addiu      $v0, $zero, 0x20
/* 43EA484 80089EBC 23104300 */  subu       $v0, $v0, $v1
/* 43EA488 80089EC0 18004400 */  mult       $v0, $a0
/* 43EA48C 80089EC4 C3100500 */  sra        $v0, $a1, 3
/* 43EA490 80089EC8 170022A6 */  sh         $v0, 0x17($s1)
/* 43EA494 80089ECC 12180000 */  mflo       $v1
/* 43EA498 80089ED0 03110300 */  sra        $v0, $v1, 4
/* 43EA49C 80089ED4 1B002392 */  lbu        $v1, 0x1B($s1)
/* 43EA4A0 80089ED8 08004224 */  addiu      $v0, $v0, 0x8
/* 43EA4A4 80089EDC 190022A6 */  sh         $v0, 0x19($s1)
/* 43EA4A8 80089EE0 00140200 */  sll        $v0, $v0, 16
/* 43EA4AC 80089EE4 40180300 */  sll        $v1, $v1, 1
/* 43EA4B0 80089EE8 0780013C */  lui        $at, %hi(D_8006CC78)
/* 43EA4B4 80089EEC 21082300 */  addu       $at, $at, $v1
/* 43EA4B8 80089EF0 78CC2384 */  lh         $v1, %lo(D_8006CC78)($at)
/* 43EA4BC 80089EF4 03140200 */  sra        $v0, $v0, 16
/* 43EA4C0 80089EF8 18006200 */  mult       $v1, $v0
/* 43EA4C4 80089EFC 11002296 */  lhu        $v0, 0x11($s1)
/* 43EA4C8 80089F00 12180000 */  mflo       $v1
/* 43EA4CC 80089F04 03230300 */  sra        $a0, $v1, 12
/* 43EA4D0 80089F08 1B002392 */  lbu        $v1, 0x1B($s1)
/* 43EA4D4 80089F0C 21104400 */  addu       $v0, $v0, $a0
/* 43EA4D8 80089F10 030022A6 */  sh         $v0, 0x3($s1)
/* 43EA4DC 80089F14 19002286 */  lh         $v0, 0x19($s1)
/* 43EA4E0 80089F18 40180300 */  sll        $v1, $v1, 1
/* 43EA4E4 80089F1C 0780013C */  lui        $at, %hi(D_8006CBF8)
/* 43EA4E8 80089F20 21082300 */  addu       $at, $at, $v1
/* 43EA4EC 80089F24 F8CB2384 */  lh         $v1, %lo(D_8006CBF8)($at)
/* 43EA4F0 80089F28 00000000 */  nop
/* 43EA4F4 80089F2C 18006200 */  mult       $v1, $v0
/* 43EA4F8 80089F30 17002296 */  lhu        $v0, 0x17($s1)
/* 43EA4FC 80089F34 15002396 */  lhu        $v1, 0x15($s1)
/* 43EA500 80089F38 20004224 */  addiu      $v0, $v0, 0x20
/* 43EA504 80089F3C 21186200 */  addu       $v1, $v1, $v0
/* 43EA508 80089F40 13002296 */  lhu        $v0, 0x13($s1)
/* 43EA50C 80089F44 070023A6 */  sh         $v1, 0x7($s1)
/* 43EA510 80089F48 12400000 */  mflo       $t0
/* 43EA514 80089F4C 031B0800 */  sra        $v1, $t0, 12
/* 43EA518 80089F50 21104300 */  addu       $v0, $v0, $v1
/* 43EA51C 80089F54 752A0208 */  j          .Llevel_50_8008A9D4
/* 43EA520 80089F58 050022A6 */   sh        $v0, 0x5($s1)
.L80089F5C_:
/* 43EA524 80089F5C 2120A002 */  addu       $a0, $s5, $zero
/* 43EA528 80089F60 2128A002 */  addu       $a1, $s5, $zero
/* 43EA52C 80089F64 215F000C */  jal        func_80017C84
/* 43EA530 80089F68 2130C003 */   addu      $a2, $fp, $zero
/* 43EA534 80089F6C 1D002286 */  lh         $v0, 0x1D($s1)
/* 43EA538 80089F70 00000000 */  nop
/* 43EA53C 80089F74 05004010 */  beqz       $v0, .Llevel_50_80089F8C
/* 43EA540 80089F78 00000000 */   nop
/* 43EA544 80089F7C 1B002296 */  lhu        $v0, 0x1B($s1)
/* 43EA548 80089F80 00000000 */  nop
/* 43EA54C 80089F84 01004224 */  addiu      $v0, $v0, 0x1
/* 43EA550 80089F88 1B0022A6 */  sh         $v0, 0x1B($s1)
.Llevel_50_80089F8C:
/* 43EA554 80089F8C 0B002292 */  lbu        $v0, 0xB($s1)
/* 43EA558 80089F90 01000724 */  addiu      $a3, $zero, 0x1
/* 43EA55C 80089F94 23205600 */  subu       $a0, $v0, $s6
/* 43EA560 80089F98 1D002296 */  lhu        $v0, 0x1D($s1)
/* 43EA564 80089F9C 09002392 */  lbu        $v1, 0x9($s1)
/* 43EA568 80089FA0 2310E200 */  subu       $v0, $a3, $v0
/* 43EA56C 80089FA4 1D0022A6 */  sh         $v0, 0x1D($s1)
/* 43EA570 80089FA8 4800A78F */  lw         $a3, 0x48($sp)
/* 43EA574 80089FAC 00000000 */  nop
/* 43EA578 80089FB0 21186700 */  addu       $v1, $v1, $a3
/* 43EA57C 80089FB4 02008104 */  bgez       $a0, .Llevel_50_80089FC0
/* 43EA580 80089FB8 090023A2 */   sb        $v1, 0x9($s1)
/* 43EA584 80089FBC 21200000 */  addu       $a0, $zero, $zero
.Llevel_50_80089FC0:
/* 43EA588 80089FC0 0C002292 */  lbu        $v0, 0xC($s1)
/* 43EA58C 80089FC4 0B0024A2 */  sb         $a0, 0xB($s1)
/* 43EA590 80089FC8 23205600 */  subu       $a0, $v0, $s6
/* 43EA594 80089FCC 02008104 */  bgez       $a0, .Llevel_50_80089FD8
/* 43EA598 80089FD0 00000000 */   nop
/* 43EA59C 80089FD4 21200000 */  addu       $a0, $zero, $zero
.Llevel_50_80089FD8:
/* 43EA5A0 80089FD8 0D002292 */  lbu        $v0, 0xD($s1)
/* 43EA5A4 80089FDC 0C0024A2 */  sb         $a0, 0xC($s1)
/* 43EA5A8 80089FE0 23205600 */  subu       $a0, $v0, $s6
/* 43EA5AC 80089FE4 02008104 */  bgez       $a0, .Llevel_50_80089FF0
/* 43EA5B0 80089FE8 00000000 */   nop
/* 43EA5B4 80089FEC 21200000 */  addu       $a0, $zero, $zero
.Llevel_50_80089FF0:
/* 43EA5B8 80089FF0 01002292 */  lbu        $v0, 0x1($s1)
/* 43EA5BC 80089FF4 0D0024A2 */  sb         $a0, 0xD($s1)
/* 43EA5C0 80089FF8 21105600 */  addu       $v0, $v0, $s6
/* 43EA5C4 80089FFC 010022A2 */  sb         $v0, 0x1($s1)
/* 43EA5C8 8008A000 FF004230 */  andi       $v0, $v0, 0xFF
/* 43EA5CC 8008A004 6D2A0208 */  j          .Llevel_50_8008A9B4
/* 43EA5D0 8008A008 2000422C */   sltiu     $v0, $v0, 0x20
.L8008A00C_:
/* 43EA5D4 8008A00C 2F00C01A */  blez       $s6, .Llevel_50_8008A0CC
/* 43EA5D8 8008A010 21800000 */   addu      $s0, $zero, $zero
.Llevel_50_8008A014:
/* 43EA5DC 8008A014 01002292 */  lbu        $v0, 0x1($s1)
/* 43EA5E0 8008A018 00000000 */  nop
/* 43EA5E4 8008A01C 01004230 */  andi       $v0, $v0, 0x1
/* 43EA5E8 8008A020 23004010 */  beqz       $v0, .Llevel_50_8008A0B0
/* 43EA5EC 8008A024 00000000 */   nop
/* 43EA5F0 8008A028 03002296 */  lhu        $v0, 0x3($s1)
/* 43EA5F4 8008A02C 0F002496 */  lhu        $a0, 0xF($s1)
/* 43EA5F8 8008A030 05002396 */  lhu        $v1, 0x5($s1)
/* 43EA5FC 8008A034 11002596 */  lhu        $a1, 0x11($s1)
/* 43EA600 8008A038 21104400 */  addu       $v0, $v0, $a0
/* 43EA604 8008A03C 030022A6 */  sh         $v0, 0x3($s1)
/* 43EA608 8008A040 07002296 */  lhu        $v0, 0x7($s1)
/* 43EA60C 8008A044 13002496 */  lhu        $a0, 0x13($s1)
/* 43EA610 8008A048 21186500 */  addu       $v1, $v1, $a1
/* 43EA614 8008A04C 050023A6 */  sh         $v1, 0x5($s1)
/* 43EA618 8008A050 01002392 */  lbu        $v1, 0x1($s1)
/* 43EA61C 8008A054 21104400 */  addu       $v0, $v0, $a0
/* 43EA620 8008A058 02006330 */  andi       $v1, $v1, 0x2
/* 43EA624 8008A05C 14006010 */  beqz       $v1, .Llevel_50_8008A0B0
/* 43EA628 8008A060 070022A6 */   sh        $v0, 0x7($s1)
/* 43EA62C 8008A064 CB89010C */  jal        rand
/* 43EA630 8008A068 00000000 */   nop
/* 43EA634 8008A06C 0F002396 */  lhu        $v1, 0xF($s1)
/* 43EA638 8008A070 02004230 */  andi       $v0, $v0, 0x2
/* 43EA63C 8008A074 FFFF6324 */  addiu      $v1, $v1, -0x1
/* 43EA640 8008A078 21186200 */  addu       $v1, $v1, $v0
/* 43EA644 8008A07C CB89010C */  jal        rand
/* 43EA648 8008A080 0F0023A6 */   sh        $v1, 0xF($s1)
/* 43EA64C 8008A084 11002396 */  lhu        $v1, 0x11($s1)
/* 43EA650 8008A088 02004230 */  andi       $v0, $v0, 0x2
/* 43EA654 8008A08C FFFF6324 */  addiu      $v1, $v1, -0x1
/* 43EA658 8008A090 21186200 */  addu       $v1, $v1, $v0
/* 43EA65C 8008A094 CB89010C */  jal        rand
/* 43EA660 8008A098 110023A6 */   sh        $v1, 0x11($s1)
/* 43EA664 8008A09C 13002396 */  lhu        $v1, 0x13($s1)
/* 43EA668 8008A0A0 02004230 */  andi       $v0, $v0, 0x2
/* 43EA66C 8008A0A4 FFFF6324 */  addiu      $v1, $v1, -0x1
/* 43EA670 8008A0A8 21186200 */  addu       $v1, $v1, $v0
/* 43EA674 8008A0AC 130023A6 */  sh         $v1, 0x13($s1)
.Llevel_50_8008A0B0:
/* 43EA678 8008A0B0 01002292 */  lbu        $v0, 0x1($s1)
/* 43EA67C 8008A0B4 01001026 */  addiu      $s0, $s0, 0x1
/* 43EA680 8008A0B8 01004224 */  addiu      $v0, $v0, 0x1
/* 43EA684 8008A0BC 010022A2 */  sb         $v0, 0x1($s1)
/* 43EA688 8008A0C0 2A101602 */  slt        $v0, $s0, $s6
/* 43EA68C 8008A0C4 D3FF4014 */  bnez       $v0, .Llevel_50_8008A014
/* 43EA690 8008A0C8 00000000 */   nop
.Llevel_50_8008A0CC:
/* 43EA694 8008A0CC 01002292 */  lbu        $v0, 0x1($s1)
/* 43EA698 8008A0D0 6D2A0208 */  j          .Llevel_50_8008A9B4
/* 43EA69C 8008A0D4 1800422C */   sltiu     $v0, $v0, 0x18
.L8008A0D8_:
/* 43EA6A0 8008A0D8 09002486 */  lh         $a0, 0x9($s1)
/* 43EA6A4 8008A0DC 03002286 */  lh         $v0, 0x3($s1)
/* 43EA6A8 8008A0E0 00000000 */  nop
/* 43EA6AC 8008A0E4 23208200 */  subu       $a0, $a0, $v0
/* 43EA6B0 8008A0E8 43200400 */  sra        $a0, $a0, 1
/* 43EA6B4 8008A0EC 3000A4A7 */  sh         $a0, 0x30($sp)
/* 43EA6B8 8008A0F0 0B002286 */  lh         $v0, 0xB($s1)
/* 43EA6BC 8008A0F4 05002386 */  lh         $v1, 0x5($s1)
/* 43EA6C0 8008A0F8 00000000 */  nop
/* 43EA6C4 8008A0FC 23104300 */  subu       $v0, $v0, $v1
/* 43EA6C8 8008A100 43100200 */  sra        $v0, $v0, 1
/* 43EA6CC 8008A104 3200A2A7 */  sh         $v0, 0x32($sp)
/* 43EA6D0 8008A108 0D002286 */  lh         $v0, 0xD($s1)
/* 43EA6D4 8008A10C 07002386 */  lh         $v1, 0x7($s1)
/* 43EA6D8 8008A110 00000000 */  nop
/* 43EA6DC 8008A114 23104300 */  subu       $v0, $v0, $v1
/* 43EA6E0 8008A118 43100200 */  sra        $v0, $v0, 1
/* 43EA6E4 8008A11C 3400A2A7 */  sh         $v0, 0x34($sp)
/* 43EA6E8 8008A120 03002296 */  lhu        $v0, 0x3($s1)
/* 43EA6EC 8008A124 00000000 */  nop
/* 43EA6F0 8008A128 21104400 */  addu       $v0, $v0, $a0
/* 43EA6F4 8008A12C 030022A6 */  sh         $v0, 0x3($s1)
/* 43EA6F8 8008A130 05002296 */  lhu        $v0, 0x5($s1)
/* 43EA6FC 8008A134 3200A397 */  lhu        $v1, 0x32($sp)
/* 43EA700 8008A138 00000000 */  nop
/* 43EA704 8008A13C 21104300 */  addu       $v0, $v0, $v1
/* 43EA708 8008A140 050022A6 */  sh         $v0, 0x5($s1)
/* 43EA70C 8008A144 07002296 */  lhu        $v0, 0x7($s1)
/* 43EA710 8008A148 3400A397 */  lhu        $v1, 0x34($sp)
/* 43EA714 8008A14C 00000000 */  nop
/* 43EA718 8008A150 21104300 */  addu       $v0, $v0, $v1
/* 43EA71C 8008A154 CB89010C */  jal        rand
/* 43EA720 8008A158 070022A6 */   sh        $v0, 0x7($s1)
/* 43EA724 8008A15C 3000A397 */  lhu        $v1, 0x30($sp)
/* 43EA728 8008A160 02004230 */  andi       $v0, $v0, 0x2
/* 43EA72C 8008A164 FFFF6324 */  addiu      $v1, $v1, -0x1
/* 43EA730 8008A168 21186200 */  addu       $v1, $v1, $v0
/* 43EA734 8008A16C CB89010C */  jal        rand
/* 43EA738 8008A170 3000A3A7 */   sh        $v1, 0x30($sp)
/* 43EA73C 8008A174 3200A397 */  lhu        $v1, 0x32($sp)
/* 43EA740 8008A178 02004230 */  andi       $v0, $v0, 0x2
/* 43EA744 8008A17C FFFF6324 */  addiu      $v1, $v1, -0x1
/* 43EA748 8008A180 21186200 */  addu       $v1, $v1, $v0
/* 43EA74C 8008A184 3200A3A7 */  sh         $v1, 0x32($sp)
/* 43EA750 8008A188 01002292 */  lbu        $v0, 0x1($s1)
/* 43EA754 8008A18C 00000000 */  nop
/* 43EA758 8008A190 01004230 */  andi       $v0, $v0, 0x1
/* 43EA75C 8008A194 05004010 */  beqz       $v0, .Llevel_50_8008A1AC
/* 43EA760 8008A198 00000000 */   nop
/* 43EA764 8008A19C 3400A297 */  lhu        $v0, 0x34($sp)
/* 43EA768 8008A1A0 00000000 */  nop
/* 43EA76C 8008A1A4 FFFF4224 */  addiu      $v0, $v0, -0x1
/* 43EA770 8008A1A8 3400A2A7 */  sh         $v0, 0x34($sp)
.Llevel_50_8008A1AC:
/* 43EA774 8008A1AC 09002296 */  lhu        $v0, 0x9($s1)
/* 43EA778 8008A1B0 3000A397 */  lhu        $v1, 0x30($sp)
/* 43EA77C 8008A1B4 00000000 */  nop
/* 43EA780 8008A1B8 21104300 */  addu       $v0, $v0, $v1
/* 43EA784 8008A1BC 090022A6 */  sh         $v0, 0x9($s1)
/* 43EA788 8008A1C0 0B002296 */  lhu        $v0, 0xB($s1)
/* 43EA78C 8008A1C4 3200A397 */  lhu        $v1, 0x32($sp)
/* 43EA790 8008A1C8 00000000 */  nop
/* 43EA794 8008A1CC 21104300 */  addu       $v0, $v0, $v1
/* 43EA798 8008A1D0 0D002396 */  lhu        $v1, 0xD($s1)
/* 43EA79C 8008A1D4 0B0022A6 */  sh         $v0, 0xB($s1)
/* 43EA7A0 8008A1D8 01002292 */  lbu        $v0, 0x1($s1)
/* 43EA7A4 8008A1DC 3400A497 */  lhu        $a0, 0x34($sp)
/* 43EA7A8 8008A1E0 01004224 */  addiu      $v0, $v0, 0x1
/* 43EA7AC 8008A1E4 21186400 */  addu       $v1, $v1, $a0
/* 43EA7B0 8008A1E8 010022A2 */  sb         $v0, 0x1($s1)
/* 43EA7B4 8008A1EC FF004230 */  andi       $v0, $v0, 0xFF
/* 43EA7B8 8008A1F0 2000422C */  sltiu      $v0, $v0, 0x20
/* 43EA7BC 8008A1F4 F5014010 */  beqz       $v0, .Llevel_50_8008A9CC
/* 43EA7C0 8008A1F8 0D0023A6 */   sh        $v1, 0xD($s1)
/* 43EA7C4 8008A1FC 02002292 */  lbu        $v0, 0x2($s1)
/* 43EA7C8 8008A200 00000000 */  nop
/* 43EA7CC 8008A204 F1014010 */  beqz       $v0, .Llevel_50_8008A9CC
/* 43EA7D0 8008A208 00000000 */   nop
/* 43EA7D4 8008A20C 0F002292 */  lbu        $v0, 0xF($s1)
/* 43EA7D8 8008A210 00000000 */  nop
/* 43EA7DC 8008A214 FDFF4224 */  addiu      $v0, $v0, -0x3
/* 43EA7E0 8008A218 0F0022A2 */  sb         $v0, 0xF($s1)
/* 43EA7E4 8008A21C FF004230 */  andi       $v0, $v0, 0xFF
/* 43EA7E8 8008A220 8000422C */  sltiu      $v0, $v0, 0x80
/* 43EA7EC 8008A224 02004010 */  beqz       $v0, .Llevel_50_8008A230
/* 43EA7F0 8008A228 80000224 */   addiu     $v0, $zero, 0x80
/* 43EA7F4 8008A22C 0F0022A2 */  sb         $v0, 0xF($s1)
.Llevel_50_8008A230:
/* 43EA7F8 8008A230 10002292 */  lbu        $v0, 0x10($s1)
/* 43EA7FC 8008A234 00000000 */  nop
/* 43EA800 8008A238 FCFF4224 */  addiu      $v0, $v0, -0x4
/* 43EA804 8008A23C 100022A2 */  sb         $v0, 0x10($s1)
/* 43EA808 8008A240 FF004230 */  andi       $v0, $v0, 0xFF
/* 43EA80C 8008A244 6000422C */  sltiu      $v0, $v0, 0x60
/* 43EA810 8008A248 02004010 */  beqz       $v0, .Llevel_50_8008A254
/* 43EA814 8008A24C 60000224 */   addiu     $v0, $zero, 0x60
/* 43EA818 8008A250 100022A2 */  sb         $v0, 0x10($s1)
.Llevel_50_8008A254:
/* 43EA81C 8008A254 13002292 */  lbu        $v0, 0x13($s1)
/* 43EA820 8008A258 110020A2 */  sb         $zero, 0x11($s1)
/* 43EA824 8008A25C FDFF4224 */  addiu      $v0, $v0, -0x3
/* 43EA828 8008A260 130022A2 */  sb         $v0, 0x13($s1)
/* 43EA82C 8008A264 FF004230 */  andi       $v0, $v0, 0xFF
/* 43EA830 8008A268 C000422C */  sltiu      $v0, $v0, 0xC0
/* 43EA834 8008A26C 02004010 */  beqz       $v0, .Llevel_50_8008A278
/* 43EA838 8008A270 C0000224 */   addiu     $v0, $zero, 0xC0
/* 43EA83C 8008A274 130022A2 */  sb         $v0, 0x13($s1)
.Llevel_50_8008A278:
/* 43EA840 8008A278 14002292 */  lbu        $v0, 0x14($s1)
/* 43EA844 8008A27C 00000000 */  nop
/* 43EA848 8008A280 FCFF4224 */  addiu      $v0, $v0, -0x4
/* 43EA84C 8008A284 140022A2 */  sb         $v0, 0x14($s1)
/* 43EA850 8008A288 FF004230 */  andi       $v0, $v0, 0xFF
/* 43EA854 8008A28C 8000422C */  sltiu      $v0, $v0, 0x80
/* 43EA858 8008A290 02004010 */  beqz       $v0, .Llevel_50_8008A29C
/* 43EA85C 8008A294 80000224 */   addiu     $v0, $zero, 0x80
/* 43EA860 8008A298 140022A2 */  sb         $v0, 0x14($s1)
.Llevel_50_8008A29C:
/* 43EA864 8008A29C 15002292 */  lbu        $v0, 0x15($s1)
/* 43EA868 8008A2A0 00000000 */  nop
/* 43EA86C 8008A2A4 FAFF4224 */  addiu      $v0, $v0, -0x6
/* 43EA870 8008A2A8 150022A2 */  sb         $v0, 0x15($s1)
/* 43EA874 8008A2AC FF004230 */  andi       $v0, $v0, 0xFF
/* 43EA878 8008A2B0 2000422C */  sltiu      $v0, $v0, 0x20
/* 43EA87C 8008A2B4 C7014010 */  beqz       $v0, .Llevel_50_8008A9D4
/* 43EA880 8008A2B8 20000224 */   addiu     $v0, $zero, 0x20
/* 43EA884 8008A2BC 752A0208 */  j          .Llevel_50_8008A9D4
/* 43EA888 8008A2C0 150022A2 */   sb        $v0, 0x15($s1)
.L8008A2C4_:
/* 43EA88C 8008A2C4 01002292 */  lbu        $v0, 0x1($s1)
/* 43EA890 8008A2C8 00000000 */  nop
/* 43EA894 8008A2CC 01004224 */  addiu      $v0, $v0, 0x1
/* 43EA898 8008A2D0 010022A2 */  sb         $v0, 0x1($s1)
/* 43EA89C 8008A2D4 FF004230 */  andi       $v0, $v0, 0xFF
/* 43EA8A0 8008A2D8 2000422C */  sltiu      $v0, $v0, 0x20
/* 43EA8A4 8008A2DC BB014010 */  beqz       $v0, .Llevel_50_8008A9CC
/* 43EA8A8 8008A2E0 00000000 */   nop
/* 43EA8AC 8008A2E4 02002292 */  lbu        $v0, 0x2($s1)
/* 43EA8B0 8008A2E8 00000000 */  nop
/* 43EA8B4 8008A2EC B7014010 */  beqz       $v0, .Llevel_50_8008A9CC
/* 43EA8B8 8008A2F0 00000000 */   nop
/* 43EA8BC 8008A2F4 09002286 */  lh         $v0, 0x9($s1)
/* 43EA8C0 8008A2F8 03002386 */  lh         $v1, 0x3($s1)
/* 43EA8C4 8008A2FC 00000000 */  nop
/* 43EA8C8 8008A300 23104300 */  subu       $v0, $v0, $v1
/* 43EA8CC 8008A304 3800A2AF */  sw         $v0, 0x38($sp)
/* 43EA8D0 8008A308 0B002286 */  lh         $v0, 0xB($s1)
/* 43EA8D4 8008A30C 05002386 */  lh         $v1, 0x5($s1)
/* 43EA8D8 8008A310 00000000 */  nop
/* 43EA8DC 8008A314 23104300 */  subu       $v0, $v0, $v1
/* 43EA8E0 8008A318 3C00A2AF */  sw         $v0, 0x3C($sp)
/* 43EA8E4 8008A31C 0D002286 */  lh         $v0, 0xD($s1)
/* 43EA8E8 8008A320 07002386 */  lh         $v1, 0x7($s1)
/* 43EA8EC 8008A324 00000000 */  nop
/* 43EA8F0 8008A328 23104300 */  subu       $v0, $v0, $v1
/* 43EA8F4 8008A32C CB89010C */  jal        rand
/* 43EA8F8 8008A330 4000A2AF */   sw        $v0, 0x40($sp)
/* 43EA8FC 8008A334 3800A38F */  lw         $v1, 0x38($sp)
/* 43EA900 8008A338 02004230 */  andi       $v0, $v0, 0x2
/* 43EA904 8008A33C FFFF6324 */  addiu      $v1, $v1, -0x1
/* 43EA908 8008A340 21186200 */  addu       $v1, $v1, $v0
/* 43EA90C 8008A344 CB89010C */  jal        rand
/* 43EA910 8008A348 3800A3AF */   sw        $v1, 0x38($sp)
/* 43EA914 8008A34C 3C00A38F */  lw         $v1, 0x3C($sp)
/* 43EA918 8008A350 02004230 */  andi       $v0, $v0, 0x2
/* 43EA91C 8008A354 FFFF6324 */  addiu      $v1, $v1, -0x1
/* 43EA920 8008A358 21186200 */  addu       $v1, $v1, $v0
/* 43EA924 8008A35C CB89010C */  jal        rand
/* 43EA928 8008A360 3C00A3AF */   sw        $v1, 0x3C($sp)
/* 43EA92C 8008A364 4000A38F */  lw         $v1, 0x40($sp)
/* 43EA930 8008A368 02004230 */  andi       $v0, $v0, 0x2
/* 43EA934 8008A36C FFFF6324 */  addiu      $v1, $v1, -0x1
/* 43EA938 8008A370 21186200 */  addu       $v1, $v1, $v0
/* 43EA93C 8008A374 4000A3AF */  sw         $v1, 0x40($sp)
/* 43EA940 8008A378 3800A38F */  lw         $v1, 0x38($sp)
/* 43EA944 8008A37C 09002296 */  lhu        $v0, 0x9($s1)
/* 43EA948 8008A380 00000000 */  nop
/* 43EA94C 8008A384 21104300 */  addu       $v0, $v0, $v1
/* 43EA950 8008A388 090022A6 */  sh         $v0, 0x9($s1)
/* 43EA954 8008A38C 3C00A38F */  lw         $v1, 0x3C($sp)
/* 43EA958 8008A390 0B002296 */  lhu        $v0, 0xB($s1)
/* 43EA95C 8008A394 00000000 */  nop
/* 43EA960 8008A398 21104300 */  addu       $v0, $v0, $v1
/* 43EA964 8008A39C 0B0022A6 */  sh         $v0, 0xB($s1)
/* 43EA968 8008A3A0 4000A38F */  lw         $v1, 0x40($sp)
/* 43EA96C 8008A3A4 0D002296 */  lhu        $v0, 0xD($s1)
/* 43EA970 8008A3A8 00000000 */  nop
/* 43EA974 8008A3AC 21104300 */  addu       $v0, $v0, $v1
/* 43EA978 8008A3B0 0D0022A6 */  sh         $v0, 0xD($s1)
/* 43EA97C 8008A3B4 3800A38F */  lw         $v1, 0x38($sp)
/* 43EA980 8008A3B8 09002296 */  lhu        $v0, 0x9($s1)
/* 43EA984 8008A3BC 00000000 */  nop
/* 43EA988 8008A3C0 23104300 */  subu       $v0, $v0, $v1
/* 43EA98C 8008A3C4 030022A6 */  sh         $v0, 0x3($s1)
/* 43EA990 8008A3C8 3C00A38F */  lw         $v1, 0x3C($sp)
/* 43EA994 8008A3CC 0B002296 */  lhu        $v0, 0xB($s1)
/* 43EA998 8008A3D0 00000000 */  nop
/* 43EA99C 8008A3D4 23104300 */  subu       $v0, $v0, $v1
/* 43EA9A0 8008A3D8 050022A6 */  sh         $v0, 0x5($s1)
/* 43EA9A4 8008A3DC 13002292 */  lbu        $v0, 0x13($s1)
/* 43EA9A8 8008A3E0 4000A48F */  lw         $a0, 0x40($sp)
/* 43EA9AC 8008A3E4 15002392 */  lbu        $v1, 0x15($s1)
/* 43EA9B0 8008A3E8 FEFF4224 */  addiu      $v0, $v0, -0x2
/* 43EA9B4 8008A3EC 130022A2 */  sb         $v0, 0x13($s1)
/* 43EA9B8 8008A3F0 14002292 */  lbu        $v0, 0x14($s1)
/* 43EA9BC 8008A3F4 FCFF6324 */  addiu      $v1, $v1, -0x4
/* 43EA9C0 8008A3F8 150023A2 */  sb         $v1, 0x15($s1)
/* 43EA9C4 8008A3FC 10002392 */  lbu        $v1, 0x10($s1)
/* 43EA9C8 8008A400 FEFF4224 */  addiu      $v0, $v0, -0x2
/* 43EA9CC 8008A404 140022A2 */  sb         $v0, 0x14($s1)
/* 43EA9D0 8008A408 0F002292 */  lbu        $v0, 0xF($s1)
/* 43EA9D4 8008A40C FDFF6324 */  addiu      $v1, $v1, -0x3
/* 43EA9D8 8008A410 100023A2 */  sb         $v1, 0x10($s1)
/* 43EA9DC 8008A414 0D002396 */  lhu        $v1, 0xD($s1)
/* 43EA9E0 8008A418 FDFF4224 */  addiu      $v0, $v0, -0x3
/* 43EA9E4 8008A41C 0F0022A2 */  sb         $v0, 0xF($s1)
/* 43EA9E8 8008A420 11002292 */  lbu        $v0, 0x11($s1)
/* 43EA9EC 8008A424 23186400 */  subu       $v1, $v1, $a0
/* 43EA9F0 8008A428 070023A6 */  sh         $v1, 0x7($s1)
/* 43EA9F4 8008A42C FDFF4224 */  addiu      $v0, $v0, -0x3
/* 43EA9F8 8008A430 752A0208 */  j          .Llevel_50_8008A9D4
/* 43EA9FC 8008A434 110022A2 */   sb        $v0, 0x11($s1)
.L8008A438_:
/* 43EAA00 8008A438 01002292 */  lbu        $v0, 0x1($s1)
/* 43EAA04 8008A43C 00000000 */  nop
/* 43EAA08 8008A440 01004224 */  addiu      $v0, $v0, 0x1
/* 43EAA0C 8008A444 010022A2 */  sb         $v0, 0x1($s1)
/* 43EAA10 8008A448 FF004230 */  andi       $v0, $v0, 0xFF
/* 43EAA14 8008A44C 3000422C */  sltiu      $v0, $v0, 0x30
/* 43EAA18 8008A450 5E014010 */  beqz       $v0, .Llevel_50_8008A9CC
/* 43EAA1C 8008A454 00000000 */   nop
/* 43EAA20 8008A458 02002292 */  lbu        $v0, 0x2($s1)
/* 43EAA24 8008A45C 00000000 */  nop
/* 43EAA28 8008A460 5A014010 */  beqz       $v0, .Llevel_50_8008A9CC
/* 43EAA2C 8008A464 00000000 */   nop
/* 43EAA30 8008A468 03002286 */  lh         $v0, 0x3($s1)
/* 43EAA34 8008A46C 09002386 */  lh         $v1, 0x9($s1)
/* 43EAA38 8008A470 00000000 */  nop
/* 43EAA3C 8008A474 23104300 */  subu       $v0, $v0, $v1
/* 43EAA40 8008A478 43100200 */  sra        $v0, $v0, 1
/* 43EAA44 8008A47C 3000A2AF */  sw         $v0, 0x30($sp)
/* 43EAA48 8008A480 05002286 */  lh         $v0, 0x5($s1)
/* 43EAA4C 8008A484 0B002386 */  lh         $v1, 0xB($s1)
/* 43EAA50 8008A488 00000000 */  nop
/* 43EAA54 8008A48C 23104300 */  subu       $v0, $v0, $v1
/* 43EAA58 8008A490 43100200 */  sra        $v0, $v0, 1
/* 43EAA5C 8008A494 3400A2AF */  sw         $v0, 0x34($sp)
/* 43EAA60 8008A498 07002286 */  lh         $v0, 0x7($s1)
/* 43EAA64 8008A49C 0D002386 */  lh         $v1, 0xD($s1)
/* 43EAA68 8008A4A0 00000000 */  nop
/* 43EAA6C 8008A4A4 23104300 */  subu       $v0, $v0, $v1
/* 43EAA70 8008A4A8 43100200 */  sra        $v0, $v0, 1
/* 43EAA74 8008A4AC CB89010C */  jal        rand
/* 43EAA78 8008A4B0 3800A2AF */   sw        $v0, 0x38($sp)
/* 43EAA7C 8008A4B4 3000A38F */  lw         $v1, 0x30($sp)
/* 43EAA80 8008A4B8 04004230 */  andi       $v0, $v0, 0x4
/* 43EAA84 8008A4BC FEFF6324 */  addiu      $v1, $v1, -0x2
/* 43EAA88 8008A4C0 21186200 */  addu       $v1, $v1, $v0
/* 43EAA8C 8008A4C4 CB89010C */  jal        rand
/* 43EAA90 8008A4C8 3000A3AF */   sw        $v1, 0x30($sp)
/* 43EAA94 8008A4CC 3400A38F */  lw         $v1, 0x34($sp)
/* 43EAA98 8008A4D0 04004230 */  andi       $v0, $v0, 0x4
/* 43EAA9C 8008A4D4 FEFF6324 */  addiu      $v1, $v1, -0x2
/* 43EAAA0 8008A4D8 21186200 */  addu       $v1, $v1, $v0
/* 43EAAA4 8008A4DC CB89010C */  jal        rand
/* 43EAAA8 8008A4E0 3400A3AF */   sw        $v1, 0x34($sp)
/* 43EAAAC 8008A4E4 3800A38F */  lw         $v1, 0x38($sp)
/* 43EAAB0 8008A4E8 02004230 */  andi       $v0, $v0, 0x2
/* 43EAAB4 8008A4EC FFFF6324 */  addiu      $v1, $v1, -0x1
/* 43EAAB8 8008A4F0 21186200 */  addu       $v1, $v1, $v0
/* 43EAABC 8008A4F4 3800A3AF */  sw         $v1, 0x38($sp)
/* 43EAAC0 8008A4F8 3000A38F */  lw         $v1, 0x30($sp)
/* 43EAAC4 8008A4FC 03002296 */  lhu        $v0, 0x3($s1)
/* 43EAAC8 8008A500 00000000 */  nop
/* 43EAACC 8008A504 21104300 */  addu       $v0, $v0, $v1
/* 43EAAD0 8008A508 030022A6 */  sh         $v0, 0x3($s1)
/* 43EAAD4 8008A50C 3400A38F */  lw         $v1, 0x34($sp)
/* 43EAAD8 8008A510 05002296 */  lhu        $v0, 0x5($s1)
/* 43EAADC 8008A514 00000000 */  nop
/* 43EAAE0 8008A518 21104300 */  addu       $v0, $v0, $v1
/* 43EAAE4 8008A51C 050022A6 */  sh         $v0, 0x5($s1)
/* 43EAAE8 8008A520 3800A38F */  lw         $v1, 0x38($sp)
/* 43EAAEC 8008A524 07002296 */  lhu        $v0, 0x7($s1)
/* 43EAAF0 8008A528 00000000 */  nop
/* 43EAAF4 8008A52C 21104300 */  addu       $v0, $v0, $v1
/* 43EAAF8 8008A530 070022A6 */  sh         $v0, 0x7($s1)
/* 43EAAFC 8008A534 3000A28F */  lw         $v0, 0x30($sp)
/* 43EAB00 8008A538 03002396 */  lhu        $v1, 0x3($s1)
/* 43EAB04 8008A53C 40100200 */  sll        $v0, $v0, 1
/* 43EAB08 8008A540 23186200 */  subu       $v1, $v1, $v0
/* 43EAB0C 8008A544 090023A6 */  sh         $v1, 0x9($s1)
/* 43EAB10 8008A548 3400A28F */  lw         $v0, 0x34($sp)
/* 43EAB14 8008A54C 05002396 */  lhu        $v1, 0x5($s1)
/* 43EAB18 8008A550 40100200 */  sll        $v0, $v0, 1
/* 43EAB1C 8008A554 23186200 */  subu       $v1, $v1, $v0
/* 43EAB20 8008A558 0B0023A6 */  sh         $v1, 0xB($s1)
/* 43EAB24 8008A55C 3800A28F */  lw         $v0, 0x38($sp)
/* 43EAB28 8008A560 07002396 */  lhu        $v1, 0x7($s1)
/* 43EAB2C 8008A564 40100200 */  sll        $v0, $v0, 1
/* 43EAB30 8008A568 23186200 */  subu       $v1, $v1, $v0
/* 43EAB34 8008A56C 752A0208 */  j          .Llevel_50_8008A9D4
/* 43EAB38 8008A570 0D0023A6 */   sh        $v1, 0xD($s1)
.L8008A574_:
/* 43EAB3C 8008A574 03002296 */  lhu        $v0, 0x3($s1)
/* 43EAB40 8008A578 01002392 */  lbu        $v1, 0x1($s1)
/* 43EAB44 8008A57C 0F002496 */  lhu        $a0, 0xF($s1)
/* 43EAB48 8008A580 13002596 */  lhu        $a1, 0x13($s1)
/* 43EAB4C 8008A584 01006624 */  addiu      $a2, $v1, 0x1
/* 43EAB50 8008A588 21104400 */  addu       $v0, $v0, $a0
/* 43EAB54 8008A58C 030022A6 */  sh         $v0, 0x3($s1)
/* 43EAB58 8008A590 05002296 */  lhu        $v0, 0x5($s1)
/* 43EAB5C 8008A594 11002496 */  lhu        $a0, 0x11($s1)
/* 43EAB60 8008A598 07002396 */  lhu        $v1, 0x7($s1)
/* 43EAB64 8008A59C 010026A2 */  sb         $a2, 0x1($s1)
/* 43EAB68 8008A5A0 21104400 */  addu       $v0, $v0, $a0
/* 43EAB6C 8008A5A4 050022A6 */  sh         $v0, 0x5($s1)
/* 43EAB70 8008A5A8 0C002292 */  lbu        $v0, 0xC($s1)
/* 43EAB74 8008A5AC 21186500 */  addu       $v1, $v1, $a1
/* 43EAB78 8008A5B0 070023A6 */  sh         $v1, 0x7($s1)
/* 43EAB7C 8008A5B4 02002392 */  lbu        $v1, 0x2($s1)
/* 43EAB80 8008A5B8 F1FF4224 */  addiu      $v0, $v0, -0xF
/* 43EAB84 8008A5BC 03016010 */  beqz       $v1, .Llevel_50_8008A9CC
/* 43EAB88 8008A5C0 0C0022A2 */   sb        $v0, 0xC($s1)
/* 43EAB8C 8008A5C4 FF00C230 */  andi       $v0, $a2, 0xFF
/* 43EAB90 8008A5C8 1100422C */  sltiu      $v0, $v0, 0x11
/* 43EAB94 8008A5CC FF004010 */  beqz       $v0, .Llevel_50_8008A9CC
/* 43EAB98 8008A5D0 00000000 */   nop
/* 43EAB9C 8008A5D4 762A0208 */  j          .Llevel_50_8008A9D8
/* 43EABA0 8008A5D8 20003126 */   addiu     $s1, $s1, 0x20
.L8008A5DC_:
/* 43EABA4 8008A5DC 09002486 */  lh         $a0, 0x9($s1)
/* 43EABA8 8008A5E0 03002286 */  lh         $v0, 0x3($s1)
/* 43EABAC 8008A5E4 00000000 */  nop
/* 43EABB0 8008A5E8 23208200 */  subu       $a0, $a0, $v0
/* 43EABB4 8008A5EC 43200400 */  sra        $a0, $a0, 1
/* 43EABB8 8008A5F0 3000A4A7 */  sh         $a0, 0x30($sp)
/* 43EABBC 8008A5F4 0B002286 */  lh         $v0, 0xB($s1)
/* 43EABC0 8008A5F8 05002386 */  lh         $v1, 0x5($s1)
/* 43EABC4 8008A5FC 00000000 */  nop
/* 43EABC8 8008A600 23104300 */  subu       $v0, $v0, $v1
/* 43EABCC 8008A604 43100200 */  sra        $v0, $v0, 1
/* 43EABD0 8008A608 3200A2A7 */  sh         $v0, 0x32($sp)
/* 43EABD4 8008A60C 0D002286 */  lh         $v0, 0xD($s1)
/* 43EABD8 8008A610 07002386 */  lh         $v1, 0x7($s1)
/* 43EABDC 8008A614 00000000 */  nop
/* 43EABE0 8008A618 23104300 */  subu       $v0, $v0, $v1
/* 43EABE4 8008A61C 43100200 */  sra        $v0, $v0, 1
/* 43EABE8 8008A620 3400A2A7 */  sh         $v0, 0x34($sp)
/* 43EABEC 8008A624 03002296 */  lhu        $v0, 0x3($s1)
/* 43EABF0 8008A628 00000000 */  nop
/* 43EABF4 8008A62C 21104400 */  addu       $v0, $v0, $a0
/* 43EABF8 8008A630 030022A6 */  sh         $v0, 0x3($s1)
/* 43EABFC 8008A634 05002296 */  lhu        $v0, 0x5($s1)
/* 43EAC00 8008A638 3200A397 */  lhu        $v1, 0x32($sp)
/* 43EAC04 8008A63C 00000000 */  nop
/* 43EAC08 8008A640 21104300 */  addu       $v0, $v0, $v1
/* 43EAC0C 8008A644 050022A6 */  sh         $v0, 0x5($s1)
/* 43EAC10 8008A648 07002296 */  lhu        $v0, 0x7($s1)
/* 43EAC14 8008A64C 3400A397 */  lhu        $v1, 0x34($sp)
/* 43EAC18 8008A650 00000000 */  nop
/* 43EAC1C 8008A654 21104300 */  addu       $v0, $v0, $v1
/* 43EAC20 8008A658 070022A6 */  sh         $v0, 0x7($s1)
/* 43EAC24 8008A65C 3200A297 */  lhu        $v0, 0x32($sp)
/* 43EAC28 8008A660 3000A397 */  lhu        $v1, 0x30($sp)
/* 43EAC2C 8008A664 01004224 */  addiu      $v0, $v0, 0x1
/* 43EAC30 8008A668 3200A2A7 */  sh         $v0, 0x32($sp)
/* 43EAC34 8008A66C 09002296 */  lhu        $v0, 0x9($s1)
/* 43EAC38 8008A670 00000000 */  nop
/* 43EAC3C 8008A674 21104300 */  addu       $v0, $v0, $v1
/* 43EAC40 8008A678 090022A6 */  sh         $v0, 0x9($s1)
/* 43EAC44 8008A67C 0B002296 */  lhu        $v0, 0xB($s1)
/* 43EAC48 8008A680 3200A397 */  lhu        $v1, 0x32($sp)
/* 43EAC4C 8008A684 00000000 */  nop
/* 43EAC50 8008A688 21104300 */  addu       $v0, $v0, $v1
/* 43EAC54 8008A68C 0D002396 */  lhu        $v1, 0xD($s1)
/* 43EAC58 8008A690 0B0022A6 */  sh         $v0, 0xB($s1)
/* 43EAC5C 8008A694 01002292 */  lbu        $v0, 0x1($s1)
/* 43EAC60 8008A698 3400A497 */  lhu        $a0, 0x34($sp)
/* 43EAC64 8008A69C 01004224 */  addiu      $v0, $v0, 0x1
/* 43EAC68 8008A6A0 21186400 */  addu       $v1, $v1, $a0
/* 43EAC6C 8008A6A4 010022A2 */  sb         $v0, 0x1($s1)
/* 43EAC70 8008A6A8 FF004230 */  andi       $v0, $v0, 0xFF
/* 43EAC74 8008A6AC 2000422C */  sltiu      $v0, $v0, 0x20
/* 43EAC78 8008A6B0 C8004014 */  bnez       $v0, .Llevel_50_8008A9D4
/* 43EAC7C 8008A6B4 0D0023A6 */   sh        $v1, 0xD($s1)
/* 43EAC80 8008A6B8 732A0208 */  j          .Llevel_50_8008A9CC
/* 43EAC84 8008A6BC 00000000 */   nop
.L8008A6C0_:
/* 43EAC88 8008A6C0 01002292 */  lbu        $v0, 0x1($s1)
/* 43EAC8C 8008A6C4 00000000 */  nop
/* 43EAC90 8008A6C8 01004224 */  addiu      $v0, $v0, 0x1
/* 43EAC94 8008A6CC 010022A2 */  sb         $v0, 0x1($s1)
/* 43EAC98 8008A6D0 FF004230 */  andi       $v0, $v0, 0xFF
/* 43EAC9C 8008A6D4 2800422C */  sltiu      $v0, $v0, 0x28
/* 43EACA0 8008A6D8 BC004010 */  beqz       $v0, .Llevel_50_8008A9CC
/* 43EACA4 8008A6DC 00000000 */   nop
/* 43EACA8 8008A6E0 02002292 */  lbu        $v0, 0x2($s1)
/* 43EACAC 8008A6E4 00000000 */  nop
/* 43EACB0 8008A6E8 B8004010 */  beqz       $v0, .Llevel_50_8008A9CC
/* 43EACB4 8008A6EC 00000000 */   nop
/* 43EACB8 8008A6F0 03002296 */  lhu        $v0, 0x3($s1)
/* 43EACBC 8008A6F4 0F002396 */  lhu        $v1, 0xF($s1)
/* 43EACC0 8008A6F8 11002496 */  lhu        $a0, 0x11($s1)
/* 43EACC4 8008A6FC 13002596 */  lhu        $a1, 0x13($s1)
/* 43EACC8 8008A700 21104300 */  addu       $v0, $v0, $v1
/* 43EACCC 8008A704 030022A6 */  sh         $v0, 0x3($s1)
/* 43EACD0 8008A708 05002296 */  lhu        $v0, 0x5($s1)
/* 43EACD4 8008A70C 07002396 */  lhu        $v1, 0x7($s1)
/* 43EACD8 8008A710 21104400 */  addu       $v0, $v0, $a0
/* 43EACDC 8008A714 21186500 */  addu       $v1, $v1, $a1
/* 43EACE0 8008A718 050022A6 */  sh         $v0, 0x5($s1)
/* 43EACE4 8008A71C CB89010C */  jal        rand
/* 43EACE8 8008A720 070023A6 */   sh        $v1, 0x7($s1)
/* 43EACEC 8008A724 0F002396 */  lhu        $v1, 0xF($s1)
/* 43EACF0 8008A728 02004230 */  andi       $v0, $v0, 0x2
/* 43EACF4 8008A72C FFFF6324 */  addiu      $v1, $v1, -0x1
/* 43EACF8 8008A730 21186200 */  addu       $v1, $v1, $v0
/* 43EACFC 8008A734 CB89010C */  jal        rand
/* 43EAD00 8008A738 0F0023A6 */   sh        $v1, 0xF($s1)
/* 43EAD04 8008A73C 11002396 */  lhu        $v1, 0x11($s1)
/* 43EAD08 8008A740 02004230 */  andi       $v0, $v0, 0x2
/* 43EAD0C 8008A744 FFFF6324 */  addiu      $v1, $v1, -0x1
/* 43EAD10 8008A748 21186200 */  addu       $v1, $v1, $v0
/* 43EAD14 8008A74C CB89010C */  jal        rand
/* 43EAD18 8008A750 110023A6 */   sh        $v1, 0x11($s1)
/* 43EAD1C 8008A754 13002396 */  lhu        $v1, 0x13($s1)
/* 43EAD20 8008A758 02004230 */  andi       $v0, $v0, 0x2
/* 43EAD24 8008A75C FFFF6324 */  addiu      $v1, $v1, -0x1
/* 43EAD28 8008A760 21186200 */  addu       $v1, $v1, $v0
/* 43EAD2C 8008A764 130023A6 */  sh         $v1, 0x13($s1)
/* 43EAD30 8008A768 001C0300 */  sll        $v1, $v1, 16
/* 43EAD34 8008A76C 031C0300 */  sra        $v1, $v1, 16
/* 43EAD38 8008A770 03006328 */  slti       $v1, $v1, 0x3
/* 43EAD3C 8008A774 02006014 */  bnez       $v1, .Llevel_50_8008A780
/* 43EAD40 8008A778 02000224 */   addiu     $v0, $zero, 0x2
/* 43EAD44 8008A77C 130022A6 */  sh         $v0, 0x13($s1)
.Llevel_50_8008A780:
/* 43EAD48 8008A780 13002286 */  lh         $v0, 0x13($s1)
/* 43EAD4C 8008A784 00000000 */  nop
/* 43EAD50 8008A788 FCFF4228 */  slti       $v0, $v0, -0x4
/* 43EAD54 8008A78C 02004010 */  beqz       $v0, .Llevel_50_8008A798
/* 43EAD58 8008A790 FCFF0224 */   addiu     $v0, $zero, -0x4
/* 43EAD5C 8008A794 130022A6 */  sh         $v0, 0x13($s1)
.Llevel_50_8008A798:
/* 43EAD60 8008A798 0B002292 */  lbu        $v0, 0xB($s1)
/* 43EAD64 8008A79C 0D002392 */  lbu        $v1, 0xD($s1)
/* 43EAD68 8008A7A0 FEFF4224 */  addiu      $v0, $v0, -0x2
/* 43EAD6C 8008A7A4 0B0022A2 */  sb         $v0, 0xB($s1)
/* 43EAD70 8008A7A8 0C002292 */  lbu        $v0, 0xC($s1)
/* 43EAD74 8008A7AC FFFF6324 */  addiu      $v1, $v1, -0x1
/* 43EAD78 8008A7B0 0D0023A2 */  sb         $v1, 0xD($s1)
/* 43EAD7C 8008A7B4 FEFF4224 */  addiu      $v0, $v0, -0x2
/* 43EAD80 8008A7B8 752A0208 */  j          .Llevel_50_8008A9D4
/* 43EAD84 8008A7BC 0C0022A2 */   sb        $v0, 0xC($s1)
.L8008A7C0_:
/* 43EAD88 8008A7C0 09002486 */  lh         $a0, 0x9($s1)
/* 43EAD8C 8008A7C4 03002286 */  lh         $v0, 0x3($s1)
/* 43EAD90 8008A7C8 00000000 */  nop
/* 43EAD94 8008A7CC 23208200 */  subu       $a0, $a0, $v0
/* 43EAD98 8008A7D0 43200400 */  sra        $a0, $a0, 1
/* 43EAD9C 8008A7D4 3000A4A7 */  sh         $a0, 0x30($sp)
/* 43EADA0 8008A7D8 0B002286 */  lh         $v0, 0xB($s1)
/* 43EADA4 8008A7DC 05002386 */  lh         $v1, 0x5($s1)
/* 43EADA8 8008A7E0 00000000 */  nop
/* 43EADAC 8008A7E4 23104300 */  subu       $v0, $v0, $v1
/* 43EADB0 8008A7E8 43100200 */  sra        $v0, $v0, 1
/* 43EADB4 8008A7EC 3200A2A7 */  sh         $v0, 0x32($sp)
/* 43EADB8 8008A7F0 0D002286 */  lh         $v0, 0xD($s1)
/* 43EADBC 8008A7F4 07002386 */  lh         $v1, 0x7($s1)
/* 43EADC0 8008A7F8 00000000 */  nop
/* 43EADC4 8008A7FC 23104300 */  subu       $v0, $v0, $v1
/* 43EADC8 8008A800 43100200 */  sra        $v0, $v0, 1
/* 43EADCC 8008A804 3400A2A7 */  sh         $v0, 0x34($sp)
/* 43EADD0 8008A808 03002296 */  lhu        $v0, 0x3($s1)
/* 43EADD4 8008A80C 00000000 */  nop
/* 43EADD8 8008A810 21104400 */  addu       $v0, $v0, $a0
/* 43EADDC 8008A814 030022A6 */  sh         $v0, 0x3($s1)
/* 43EADE0 8008A818 05002296 */  lhu        $v0, 0x5($s1)
/* 43EADE4 8008A81C 3200A397 */  lhu        $v1, 0x32($sp)
/* 43EADE8 8008A820 00000000 */  nop
/* 43EADEC 8008A824 21104300 */  addu       $v0, $v0, $v1
/* 43EADF0 8008A828 050022A6 */  sh         $v0, 0x5($s1)
/* 43EADF4 8008A82C 07002296 */  lhu        $v0, 0x7($s1)
/* 43EADF8 8008A830 3400A397 */  lhu        $v1, 0x34($sp)
/* 43EADFC 8008A834 00000000 */  nop
/* 43EAE00 8008A838 21104300 */  addu       $v0, $v0, $v1
/* 43EAE04 8008A83C 070022A6 */  sh         $v0, 0x7($s1)
/* 43EAE08 8008A840 09002296 */  lhu        $v0, 0x9($s1)
/* 43EAE0C 8008A844 3000A397 */  lhu        $v1, 0x30($sp)
/* 43EAE10 8008A848 00000000 */  nop
/* 43EAE14 8008A84C 21104300 */  addu       $v0, $v0, $v1
/* 43EAE18 8008A850 090022A6 */  sh         $v0, 0x9($s1)
/* 43EAE1C 8008A854 0B002296 */  lhu        $v0, 0xB($s1)
/* 43EAE20 8008A858 3200A397 */  lhu        $v1, 0x32($sp)
/* 43EAE24 8008A85C 00000000 */  nop
/* 43EAE28 8008A860 21104300 */  addu       $v0, $v0, $v1
/* 43EAE2C 8008A864 0D002396 */  lhu        $v1, 0xD($s1)
/* 43EAE30 8008A868 0B0022A6 */  sh         $v0, 0xB($s1)
/* 43EAE34 8008A86C 01002292 */  lbu        $v0, 0x1($s1)
/* 43EAE38 8008A870 3400A497 */  lhu        $a0, 0x34($sp)
/* 43EAE3C 8008A874 01004224 */  addiu      $v0, $v0, 0x1
/* 43EAE40 8008A878 21186400 */  addu       $v1, $v1, $a0
/* 43EAE44 8008A87C 010022A2 */  sb         $v0, 0x1($s1)
/* 43EAE48 8008A880 FF004230 */  andi       $v0, $v0, 0xFF
/* 43EAE4C 8008A884 1800422C */  sltiu      $v0, $v0, 0x18
/* 43EAE50 8008A888 50004010 */  beqz       $v0, .Llevel_50_8008A9CC
/* 43EAE54 8008A88C 0D0023A6 */   sh        $v1, 0xD($s1)
/* 43EAE58 8008A890 02002292 */  lbu        $v0, 0x2($s1)
/* 43EAE5C 8008A894 00000000 */  nop
/* 43EAE60 8008A898 4C004010 */  beqz       $v0, .Llevel_50_8008A9CC
/* 43EAE64 8008A89C 00000000 */   nop
/* 43EAE68 8008A8A0 0F002292 */  lbu        $v0, 0xF($s1)
/* 43EAE6C 8008A8A4 13002392 */  lbu        $v1, 0x13($s1)
/* 43EAE70 8008A8A8 FDFF4224 */  addiu      $v0, $v0, -0x3
/* 43EAE74 8008A8AC 0F0022A2 */  sb         $v0, 0xF($s1)
/* 43EAE78 8008A8B0 10002292 */  lbu        $v0, 0x10($s1)
/* 43EAE7C 8008A8B4 FDFF6324 */  addiu      $v1, $v1, -0x3
/* 43EAE80 8008A8B8 130023A2 */  sb         $v1, 0x13($s1)
/* 43EAE84 8008A8BC FCFF4224 */  addiu      $v0, $v0, -0x4
/* 43EAE88 8008A8C0 100022A2 */  sb         $v0, 0x10($s1)
/* 43EAE8C 8008A8C4 14002292 */  lbu        $v0, 0x14($s1)
/* 43EAE90 8008A8C8 15002392 */  lbu        $v1, 0x15($s1)
/* 43EAE94 8008A8CC FCFF4224 */  addiu      $v0, $v0, -0x4
/* 43EAE98 8008A8D0 140022A2 */  sb         $v0, 0x14($s1)
/* 43EAE9C 8008A8D4 0600622C */  sltiu      $v0, $v1, 0x6
/* 43EAEA0 8008A8D8 3E004014 */  bnez       $v0, .Llevel_50_8008A9D4
/* 43EAEA4 8008A8DC FAFF6224 */   addiu     $v0, $v1, -0x6
/* 43EAEA8 8008A8E0 752A0208 */  j          .Llevel_50_8008A9D4
/* 43EAEAC 8008A8E4 150022A2 */   sb        $v0, 0x15($s1)
.L8008A8E8_:
/* 43EAEB0 8008A8E8 09002496 */  lhu        $a0, 0x9($s1)
/* 43EAEB4 8008A8EC 03002296 */  lhu        $v0, 0x3($s1)
/* 43EAEB8 8008A8F0 00000000 */  nop
/* 43EAEBC 8008A8F4 23208200 */  subu       $a0, $a0, $v0
/* 43EAEC0 8008A8F8 3000A4A7 */  sh         $a0, 0x30($sp)
/* 43EAEC4 8008A8FC 0B002296 */  lhu        $v0, 0xB($s1)
/* 43EAEC8 8008A900 05002396 */  lhu        $v1, 0x5($s1)
/* 43EAECC 8008A904 00000000 */  nop
/* 43EAED0 8008A908 23104300 */  subu       $v0, $v0, $v1
/* 43EAED4 8008A90C 3200A2A7 */  sh         $v0, 0x32($sp)
/* 43EAED8 8008A910 0D002296 */  lhu        $v0, 0xD($s1)
/* 43EAEDC 8008A914 07002396 */  lhu        $v1, 0x7($s1)
/* 43EAEE0 8008A918 00000000 */  nop
/* 43EAEE4 8008A91C 23104300 */  subu       $v0, $v0, $v1
/* 43EAEE8 8008A920 3400A2A7 */  sh         $v0, 0x34($sp)
/* 43EAEEC 8008A924 03002296 */  lhu        $v0, 0x3($s1)
/* 43EAEF0 8008A928 00000000 */  nop
/* 43EAEF4 8008A92C 21104400 */  addu       $v0, $v0, $a0
/* 43EAEF8 8008A930 030022A6 */  sh         $v0, 0x3($s1)
/* 43EAEFC 8008A934 05002296 */  lhu        $v0, 0x5($s1)
/* 43EAF00 8008A938 3200A397 */  lhu        $v1, 0x32($sp)
/* 43EAF04 8008A93C 00000000 */  nop
/* 43EAF08 8008A940 21104300 */  addu       $v0, $v0, $v1
/* 43EAF0C 8008A944 050022A6 */  sh         $v0, 0x5($s1)
/* 43EAF10 8008A948 07002296 */  lhu        $v0, 0x7($s1)
/* 43EAF14 8008A94C 3400A397 */  lhu        $v1, 0x34($sp)
/* 43EAF18 8008A950 00000000 */  nop
/* 43EAF1C 8008A954 21104300 */  addu       $v0, $v0, $v1
/* 43EAF20 8008A958 070022A6 */  sh         $v0, 0x7($s1)
/* 43EAF24 8008A95C 3400A297 */  lhu        $v0, 0x34($sp)
/* 43EAF28 8008A960 3000A397 */  lhu        $v1, 0x30($sp)
/* 43EAF2C 8008A964 FFFF4224 */  addiu      $v0, $v0, -0x1
/* 43EAF30 8008A968 3400A2A7 */  sh         $v0, 0x34($sp)
/* 43EAF34 8008A96C 09002296 */  lhu        $v0, 0x9($s1)
/* 43EAF38 8008A970 00000000 */  nop
/* 43EAF3C 8008A974 21104300 */  addu       $v0, $v0, $v1
/* 43EAF40 8008A978 090022A6 */  sh         $v0, 0x9($s1)
/* 43EAF44 8008A97C 0B002296 */  lhu        $v0, 0xB($s1)
/* 43EAF48 8008A980 3200A397 */  lhu        $v1, 0x32($sp)
/* 43EAF4C 8008A984 00000000 */  nop
/* 43EAF50 8008A988 21104300 */  addu       $v0, $v0, $v1
/* 43EAF54 8008A98C 0D002396 */  lhu        $v1, 0xD($s1)
/* 43EAF58 8008A990 0B0022A6 */  sh         $v0, 0xB($s1)
/* 43EAF5C 8008A994 01002292 */  lbu        $v0, 0x1($s1)
/* 43EAF60 8008A998 3400A497 */  lhu        $a0, 0x34($sp)
/* 43EAF64 8008A99C 01004224 */  addiu      $v0, $v0, 0x1
/* 43EAF68 8008A9A0 21186400 */  addu       $v1, $v1, $a0
/* 43EAF6C 8008A9A4 010022A2 */  sb         $v0, 0x1($s1)
/* 43EAF70 8008A9A8 FF004230 */  andi       $v0, $v0, 0xFF
/* 43EAF74 8008A9AC 2000422C */  sltiu      $v0, $v0, 0x20
/* 43EAF78 8008A9B0 0D0023A6 */  sh         $v1, 0xD($s1)
.Llevel_50_8008A9B4:
/* 43EAF7C 8008A9B4 05004010 */  beqz       $v0, .Llevel_50_8008A9CC
/* 43EAF80 8008A9B8 00000000 */   nop
.Llevel_50_8008A9BC:
/* 43EAF84 8008A9BC 02002292 */  lbu        $v0, 0x2($s1)
/* 43EAF88 8008A9C0 00000000 */  nop
/* 43EAF8C 8008A9C4 03004014 */  bnez       $v0, .Llevel_50_8008A9D4
/* 43EAF90 8008A9C8 00000000 */   nop
.Llevel_50_8008A9CC:
/* 43EAF94 8008A9CC 824D010C */  jal        func_80053608
/* 43EAF98 8008A9D0 21208002 */   addu      $a0, $s4, $zero
.Llevel_50_8008A9D4:
/* 43EAF9C 8008A9D4 20003126 */  addiu      $s1, $s1, 0x20
.Llevel_50_8008A9D8:
/* 43EAFA0 8008A9D8 2000DE27 */  addiu      $fp, $fp, 0x20
/* 43EAFA4 8008A9DC 2000B526 */  addiu      $s5, $s5, 0x20
/* 43EAFA8 8008A9E0 00002392 */  lbu        $v1, 0x0($s1)
/* 43EAFAC 8008A9E4 FF000224 */  addiu      $v0, $zero, 0xFF
/* 43EAFB0 8008A9E8 9BFB6214 */  bne        $v1, $v0, .Llevel_50_80089858
/* 43EAFB4 8008A9EC 20009426 */   addiu     $s4, $s4, 0x20
.Llevel_50_8008A9F0:
/* 43EAFB8 8008A9F0 7C00BF8F */  lw         $ra, 0x7C($sp)
/* 43EAFBC 8008A9F4 7800BE8F */  lw         $fp, 0x78($sp)
/* 43EAFC0 8008A9F8 7400B78F */  lw         $s7, 0x74($sp)
/* 43EAFC4 8008A9FC 7000B68F */  lw         $s6, 0x70($sp)
/* 43EAFC8 8008AA00 6C00B58F */  lw         $s5, 0x6C($sp)
/* 43EAFCC 8008AA04 6800B48F */  lw         $s4, 0x68($sp)
/* 43EAFD0 8008AA08 6400B38F */  lw         $s3, 0x64($sp)
/* 43EAFD4 8008AA0C 6000B28F */  lw         $s2, 0x60($sp)
/* 43EAFD8 8008AA10 5C00B18F */  lw         $s1, 0x5C($sp)
/* 43EAFDC 8008AA14 5800B08F */  lw         $s0, 0x58($sp)
/* 43EAFE0 8008AA18 8000BD27 */  addiu      $sp, $sp, 0x80
/* 43EAFE4 8008AA1C 0800E003 */  jr         $ra
/* 43EAFE8 8008AA20 00000000 */   nop
.size func_level_50_800897FC, . - func_level_50_800897FC
