.set noat      /* allow manual use of $at */
.set noreorder /* don't insert nops after branches */

.section .rodata.jtbl
.align 3
dlabel jtbl_level_12_8007AB74
/* EF613C 8007AB74 F4320880 */ .word .L800832F4_
/* EF6140 8007AB78 80330880 */ .word .L80083380_
/* EF6144 8007AB7C 08340880 */ .word .L80083408_
/* EF6148 8007AB80 50440880 */ .word .Llevel_12_80084450
/* EF614C 8007AB84 50440880 */ .word .Llevel_12_80084450
/* EF6150 8007AB88 50440880 */ .word .Llevel_12_80084450
/* EF6154 8007AB8C 90340880 */ .word .L80083490_
/* EF6158 8007AB90 50440880 */ .word .Llevel_12_80084450
/* EF615C 8007AB94 50440880 */ .word .Llevel_12_80084450
/* EF6160 8007AB98 60350880 */ .word .L80083560_
/* EF6164 8007AB9C C8350880 */ .word .L800835C8_
/* EF6168 8007ABA0 D4360880 */ .word .L800836D4_
/* EF616C 8007ABA4 18370880 */ .word .L80083718_
/* EF6170 8007ABA8 50440880 */ .word .Llevel_12_80084450
/* EF6174 8007ABAC 50440880 */ .word .Llevel_12_80084450
/* EF6178 8007ABB0 50440880 */ .word .Llevel_12_80084450
/* EF617C 8007ABB4 50440880 */ .word .Llevel_12_80084450
/* EF6180 8007ABB8 50440880 */ .word .Llevel_12_80084450
/* EF6184 8007ABBC 50440880 */ .word .Llevel_12_80084450
/* EF6188 8007ABC0 50440880 */ .word .Llevel_12_80084450
/* EF618C 8007ABC4 50440880 */ .word .Llevel_12_80084450
/* EF6190 8007ABC8 8C370880 */ .word .L8008378C_
/* EF6194 8007ABCC 50440880 */ .word .Llevel_12_80084450
/* EF6198 8007ABD0 50440880 */ .word .Llevel_12_80084450
/* EF619C 8007ABD4 5C380880 */ .word .L8008385C_
/* EF61A0 8007ABD8 50440880 */ .word .Llevel_12_80084450
/* EF61A4 8007ABDC 50440880 */ .word .Llevel_12_80084450
/* EF61A8 8007ABE0 50440880 */ .word .Llevel_12_80084450
/* EF61AC 8007ABE4 50440880 */ .word .Llevel_12_80084450
/* EF61B0 8007ABE8 50440880 */ .word .Llevel_12_80084450
/* EF61B4 8007ABEC 50440880 */ .word .Llevel_12_80084450
/* EF61B8 8007ABF0 50440880 */ .word .Llevel_12_80084450
/* EF61BC 8007ABF4 50440880 */ .word .Llevel_12_80084450
/* EF61C0 8007ABF8 94390880 */ .word .L80083994_
/* EF61C4 8007ABFC 50440880 */ .word .Llevel_12_80084450
/* EF61C8 8007AC00 50440880 */ .word .Llevel_12_80084450
/* EF61CC 8007AC04 50440880 */ .word .Llevel_12_80084450
/* EF61D0 8007AC08 50440880 */ .word .Llevel_12_80084450
/* EF61D4 8007AC0C 50440880 */ .word .Llevel_12_80084450
/* EF61D8 8007AC10 50440880 */ .word .Llevel_12_80084450
/* EF61DC 8007AC14 50440880 */ .word .Llevel_12_80084450
/* EF61E0 8007AC18 50440880 */ .word .Llevel_12_80084450
/* EF61E4 8007AC1C 50440880 */ .word .Llevel_12_80084450
/* EF61E8 8007AC20 50440880 */ .word .Llevel_12_80084450
/* EF61EC 8007AC24 50440880 */ .word .Llevel_12_80084450
/* EF61F0 8007AC28 50440880 */ .word .Llevel_12_80084450
/* EF61F4 8007AC2C 50440880 */ .word .Llevel_12_80084450
/* EF61F8 8007AC30 50440880 */ .word .Llevel_12_80084450
/* EF61FC 8007AC34 50440880 */ .word .Llevel_12_80084450
/* EF6200 8007AC38 50440880 */ .word .Llevel_12_80084450
/* EF6204 8007AC3C 50440880 */ .word .Llevel_12_80084450
/* EF6208 8007AC40 50440880 */ .word .Llevel_12_80084450
/* EF620C 8007AC44 50440880 */ .word .Llevel_12_80084450
/* EF6210 8007AC48 50440880 */ .word .Llevel_12_80084450
/* EF6214 8007AC4C 50440880 */ .word .Llevel_12_80084450
/* EF6218 8007AC50 50440880 */ .word .Llevel_12_80084450
/* EF621C 8007AC54 50440880 */ .word .Llevel_12_80084450
/* EF6220 8007AC58 50440880 */ .word .Llevel_12_80084450
/* EF6224 8007AC5C 50440880 */ .word .Llevel_12_80084450
/* EF6228 8007AC60 50440880 */ .word .Llevel_12_80084450
/* EF622C 8007AC64 50440880 */ .word .Llevel_12_80084450
/* EF6230 8007AC68 50440880 */ .word .Llevel_12_80084450
/* EF6234 8007AC6C 50440880 */ .word .Llevel_12_80084450
/* EF6238 8007AC70 50440880 */ .word .Llevel_12_80084450
/* EF623C 8007AC74 50440880 */ .word .Llevel_12_80084450
/* EF6240 8007AC78 50440880 */ .word .Llevel_12_80084450
/* EF6244 8007AC7C 403A0880 */ .word .L80083A40_
/* EF6248 8007AC80 50440880 */ .word .Llevel_12_80084450
/* EF624C 8007AC84 50440880 */ .word .Llevel_12_80084450
/* EF6250 8007AC88 50440880 */ .word .Llevel_12_80084450
/* EF6254 8007AC8C 0C3B0880 */ .word .L80083B0C_
/* EF6258 8007AC90 F83C0880 */ .word .L80083CF8_
/* EF625C 8007AC94 6C3E0880 */ .word .L80083E6C_
/* EF6260 8007AC98 50440880 */ .word .Llevel_12_80084450
/* EF6264 8007AC9C 50440880 */ .word .Llevel_12_80084450
/* EF6268 8007ACA0 50440880 */ .word .Llevel_12_80084450
/* EF626C 8007ACA4 A83F0880 */ .word .L80083FA8_
/* EF6270 8007ACA8 58400880 */ .word .L80084058_
/* EF6274 8007ACAC 3C410880 */ .word .L8008413C_
/* EF6278 8007ACB0 3C420880 */ .word .L8008423C_
/* EF627C 8007ACB4 64430880 */ .word .L80084364_
.size jtbl_level_12_8007AB74, . - jtbl_level_12_8007AB74


.section .text
/* Generated by spimdisasm 1.27.0 */

glabel func_level_12_80083274
/* EFE83C 80083274 88FFBD27 */  addiu      $sp, $sp, -0x78
/* EFE840 80083278 6000B4AF */  sw         $s4, 0x60($sp)
/* EFE844 8008327C 0780143C */  lui        $s4, %hi(D_80075824)
/* EFE848 80083280 2458948E */  lw         $s4, %lo(D_80075824)($s4)
/* EFE84C 80083284 6800B6AF */  sw         $s6, 0x68($sp)
/* EFE850 80083288 7400BFAF */  sw         $ra, 0x74($sp)
/* EFE854 8008328C 7000BEAF */  sw         $fp, 0x70($sp)
/* EFE858 80083290 6C00B7AF */  sw         $s7, 0x6C($sp)
/* EFE85C 80083294 6400B5AF */  sw         $s5, 0x64($sp)
/* EFE860 80083298 5C00B3AF */  sw         $s3, 0x5C($sp)
/* EFE864 8008329C 5800B2AF */  sw         $s2, 0x58($sp)
/* EFE868 800832A0 5400B1AF */  sw         $s1, 0x54($sp)
/* EFE86C 800832A4 5000B0AF */  sw         $s0, 0x50($sp)
/* EFE870 800832A8 01008392 */  lbu        $v1, 0x1($s4)
/* EFE874 800832AC FF000224 */  addiu      $v0, $zero, 0xFF
/* EFE878 800832B0 6E046210 */  beq        $v1, $v0, .Llevel_12_8008446C
/* EFE87C 800832B4 21B08000 */   addu      $s6, $a0, $zero
/* EFE880 800832B8 80B81600 */  sll        $s7, $s6, 2
/* EFE884 800832BC 01009126 */  addiu      $s1, $s4, 0x1
/* EFE888 800832C0 18009E26 */  addiu      $fp, $s4, 0x18
/* EFE88C 800832C4 04009526 */  addiu      $s5, $s4, 0x4
.Llevel_12_800832C8:
/* EFE890 800832C8 00008392 */  lbu        $v1, 0x0($s4)
/* EFE894 800832CC 00000000 */  nop
/* EFE898 800832D0 5100622C */  sltiu      $v0, $v1, 0x51
/* EFE89C 800832D4 5E044010 */  beqz       $v0, .Llevel_12_80084450
/* EFE8A0 800832D8 80100300 */   sll       $v0, $v1, 2
/* EFE8A4 800832DC 0880013C */  lui        $at, %hi(jtbl_level_12_8007AB74)
/* EFE8A8 800832E0 21082200 */  addu       $at, $at, $v0
/* EFE8AC 800832E4 74AB228C */  lw         $v0, %lo(jtbl_level_12_8007AB74)($at)
/* EFE8B0 800832E8 00000000 */  nop
/* EFE8B4 800832EC 08004000 */  jr         $v0
/* EFE8B8 800832F0 00000000 */   nop
.L800832F4_:
/* EFE8BC 800832F4 2120A002 */  addu       $a0, $s5, $zero
/* EFE8C0 800832F8 2128A002 */  addu       $a1, $s5, $zero
/* EFE8C4 800832FC 215F000C */  jal        func_80017C84
/* EFE8C8 80083300 2130C003 */   addu      $a2, $fp, $zero
/* EFE8CC 80083304 1D002286 */  lh         $v0, 0x1D($s1)
/* EFE8D0 80083308 00000000 */  nop
/* EFE8D4 8008330C 05004010 */  beqz       $v0, .Llevel_12_80083324
/* EFE8D8 80083310 00000000 */   nop
/* EFE8DC 80083314 1B002296 */  lhu        $v0, 0x1B($s1)
/* EFE8E0 80083318 00000000 */  nop
/* EFE8E4 8008331C 01004224 */  addiu      $v0, $v0, 0x1
/* EFE8E8 80083320 1B0022A6 */  sh         $v0, 0x1B($s1)
.Llevel_12_80083324:
/* EFE8EC 80083324 1D002396 */  lhu        $v1, 0x1D($s1)
/* EFE8F0 80083328 01000224 */  addiu      $v0, $zero, 0x1
/* EFE8F4 8008332C 23104300 */  subu       $v0, $v0, $v1
/* EFE8F8 80083330 1D0022A6 */  sh         $v0, 0x1D($s1)
/* EFE8FC 80083334 09002292 */  lbu        $v0, 0x9($s1)
/* EFE900 80083338 40181600 */  sll        $v1, $s6, 1
/* EFE904 8008333C 21104300 */  addu       $v0, $v0, $v1
/* EFE908 80083340 0C002392 */  lbu        $v1, 0xC($s1)
/* EFE90C 80083344 090022A2 */  sb         $v0, 0x9($s1)
/* EFE910 80083348 0B002292 */  lbu        $v0, 0xB($s1)
/* EFE914 8008334C 23187700 */  subu       $v1, $v1, $s7
/* EFE918 80083350 0C0023A2 */  sb         $v1, 0xC($s1)
/* EFE91C 80083354 0D002392 */  lbu        $v1, 0xD($s1)
/* EFE920 80083358 23105700 */  subu       $v0, $v0, $s7
/* EFE924 8008335C 0B0022A2 */  sb         $v0, 0xB($s1)
/* EFE928 80083360 01002292 */  lbu        $v0, 0x1($s1)
/* EFE92C 80083364 23187700 */  subu       $v1, $v1, $s7
/* EFE930 80083368 21105600 */  addu       $v0, $v0, $s6
/* EFE934 8008336C 010022A2 */  sb         $v0, 0x1($s1)
/* EFE938 80083370 FF004230 */  andi       $v0, $v0, 0xFF
/* EFE93C 80083374 2000422C */  sltiu      $v0, $v0, 0x20
/* EFE940 80083378 0C110208 */  j          .Llevel_12_80084430
/* EFE944 8008337C 0D0023A2 */   sb        $v1, 0xD($s1)
.L80083380_:
/* EFE948 80083380 2120A002 */  addu       $a0, $s5, $zero
/* EFE94C 80083384 2128A002 */  addu       $a1, $s5, $zero
/* EFE950 80083388 215F000C */  jal        func_80017C84
/* EFE954 8008338C 2130C003 */   addu      $a2, $fp, $zero
/* EFE958 80083390 1D002286 */  lh         $v0, 0x1D($s1)
/* EFE95C 80083394 00000000 */  nop
/* EFE960 80083398 06004010 */  beqz       $v0, .Llevel_12_800833B4
/* EFE964 8008339C 01000224 */   addiu     $v0, $zero, 0x1
/* EFE968 800833A0 1B002296 */  lhu        $v0, 0x1B($s1)
/* EFE96C 800833A4 00000000 */  nop
/* EFE970 800833A8 01004224 */  addiu      $v0, $v0, 0x1
/* EFE974 800833AC 1B0022A6 */  sh         $v0, 0x1B($s1)
/* EFE978 800833B0 01000224 */  addiu      $v0, $zero, 0x1
.Llevel_12_800833B4:
/* EFE97C 800833B4 09002392 */  lbu        $v1, 0x9($s1)
/* EFE980 800833B8 1D002496 */  lhu        $a0, 0x1D($s1)
/* EFE984 800833BC 21187700 */  addu       $v1, $v1, $s7
/* EFE988 800833C0 090023A2 */  sb         $v1, 0x9($s1)
/* EFE98C 800833C4 0C002392 */  lbu        $v1, 0xC($s1)
/* EFE990 800833C8 23104400 */  subu       $v0, $v0, $a0
/* EFE994 800833CC 1D0022A6 */  sh         $v0, 0x1D($s1)
/* EFE998 800833D0 0B002292 */  lbu        $v0, 0xB($s1)
/* EFE99C 800833D4 23187700 */  subu       $v1, $v1, $s7
/* EFE9A0 800833D8 0C0023A2 */  sb         $v1, 0xC($s1)
/* EFE9A4 800833DC 0D002392 */  lbu        $v1, 0xD($s1)
/* EFE9A8 800833E0 23105700 */  subu       $v0, $v0, $s7
/* EFE9AC 800833E4 0B0022A2 */  sb         $v0, 0xB($s1)
/* EFE9B0 800833E8 01002292 */  lbu        $v0, 0x1($s1)
/* EFE9B4 800833EC 23187700 */  subu       $v1, $v1, $s7
/* EFE9B8 800833F0 21105600 */  addu       $v0, $v0, $s6
/* EFE9BC 800833F4 010022A2 */  sb         $v0, 0x1($s1)
/* EFE9C0 800833F8 FF004230 */  andi       $v0, $v0, 0xFF
/* EFE9C4 800833FC 1800422C */  sltiu      $v0, $v0, 0x18
/* EFE9C8 80083400 0C110208 */  j          .Llevel_12_80084430
/* EFE9CC 80083404 0D0023A2 */   sb        $v1, 0xD($s1)
.L80083408_:
/* EFE9D0 80083408 2120A002 */  addu       $a0, $s5, $zero
/* EFE9D4 8008340C 2128A002 */  addu       $a1, $s5, $zero
/* EFE9D8 80083410 215F000C */  jal        func_80017C84
/* EFE9DC 80083414 2130C003 */   addu      $a2, $fp, $zero
/* EFE9E0 80083418 1D002286 */  lh         $v0, 0x1D($s1)
/* EFE9E4 8008341C 00000000 */  nop
/* EFE9E8 80083420 06004010 */  beqz       $v0, .Llevel_12_8008343C
/* EFE9EC 80083424 01000224 */   addiu     $v0, $zero, 0x1
/* EFE9F0 80083428 1B002296 */  lhu        $v0, 0x1B($s1)
/* EFE9F4 8008342C 00000000 */  nop
/* EFE9F8 80083430 01004224 */  addiu      $v0, $v0, 0x1
/* EFE9FC 80083434 1B0022A6 */  sh         $v0, 0x1B($s1)
/* EFEA00 80083438 01000224 */  addiu      $v0, $zero, 0x1
.Llevel_12_8008343C:
/* EFEA04 8008343C 09002392 */  lbu        $v1, 0x9($s1)
/* EFEA08 80083440 1D002496 */  lhu        $a0, 0x1D($s1)
/* EFEA0C 80083444 21187700 */  addu       $v1, $v1, $s7
/* EFEA10 80083448 090023A2 */  sb         $v1, 0x9($s1)
/* EFEA14 8008344C 0C002392 */  lbu        $v1, 0xC($s1)
/* EFEA18 80083450 23104400 */  subu       $v0, $v0, $a0
/* EFEA1C 80083454 1D0022A6 */  sh         $v0, 0x1D($s1)
/* EFEA20 80083458 0B002292 */  lbu        $v0, 0xB($s1)
/* EFEA24 8008345C 23187700 */  subu       $v1, $v1, $s7
/* EFEA28 80083460 0C0023A2 */  sb         $v1, 0xC($s1)
/* EFEA2C 80083464 0D002392 */  lbu        $v1, 0xD($s1)
/* EFEA30 80083468 23105700 */  subu       $v0, $v0, $s7
/* EFEA34 8008346C 0B0022A2 */  sb         $v0, 0xB($s1)
/* EFEA38 80083470 01002292 */  lbu        $v0, 0x1($s1)
/* EFEA3C 80083474 23187700 */  subu       $v1, $v1, $s7
/* EFEA40 80083478 21105600 */  addu       $v0, $v0, $s6
/* EFEA44 8008347C 010022A2 */  sb         $v0, 0x1($s1)
/* EFEA48 80083480 FF004230 */  andi       $v0, $v0, 0xFF
/* EFEA4C 80083484 2000422C */  sltiu      $v0, $v0, 0x20
/* EFEA50 80083488 0C110208 */  j          .Llevel_12_80084430
/* EFEA54 8008348C 0D0023A2 */   sb        $v1, 0xD($s1)
.L80083490_:
/* EFEA58 80083490 1700258E */  lw         $a1, 0x17($s1)
/* EFEA5C 80083494 C05D000C */  jal        VecCopy
/* EFEA60 80083498 1000A427 */   addiu     $a0, $sp, 0x10
/* EFEA64 8008349C 01002292 */  lbu        $v0, 0x1($s1)
/* EFEA68 800834A0 00000000 */  nop
/* EFEA6C 800834A4 80810200 */  sll        $s0, $v0, 6
/* EFEA70 800834A8 1D002286 */  lh         $v0, 0x1D($s1)
/* EFEA74 800834AC 1800A38F */  lw         $v1, 0x18($sp)
/* EFEA78 800834B0 80110200 */  sll        $v0, $v0, 6
/* EFEA7C 800834B4 21986200 */  addu       $s3, $v1, $v0
/* EFEA80 800834B8 1B002386 */  lh         $v1, 0x1B($s1)
/* EFEA84 800834BC 00000000 */  nop
/* EFEA88 800834C0 2A107000 */  slt        $v0, $v1, $s0
/* EFEA8C 800834C4 02004010 */  beqz       $v0, .Llevel_12_800834D0
/* EFEA90 800834C8 21900002 */   addu      $s2, $s0, $zero
/* EFEA94 800834CC 21806000 */  addu       $s0, $v1, $zero
.Llevel_12_800834D0:
/* EFEA98 800834D0 2C5B000C */  jal        Cos
/* EFEA9C 800834D4 21204002 */   addu      $a0, $s2, $zero
/* EFEAA0 800834D8 18000202 */  mult       $s0, $v0
/* EFEAA4 800834DC 21204002 */  addu       $a0, $s2, $zero
/* EFEAA8 800834E0 1000A28F */  lw         $v0, 0x10($sp)
/* EFEAAC 800834E4 12380000 */  mflo       $a3
/* EFEAB0 800834E8 031B0700 */  sra        $v1, $a3, 12
/* EFEAB4 800834EC 21104300 */  addu       $v0, $v0, $v1
/* EFEAB8 800834F0 165B000C */  jal        Sin
/* EFEABC 800834F4 1000A2AF */   sw        $v0, 0x10($sp)
/* EFEAC0 800834F8 18000202 */  mult       $s0, $v0
/* EFEAC4 800834FC 1400A28F */  lw         $v0, 0x14($sp)
/* EFEAC8 80083500 12380000 */  mflo       $a3
/* EFEACC 80083504 031B0700 */  sra        $v1, $a3, 12
/* EFEAD0 80083508 21104300 */  addu       $v0, $v0, $v1
/* EFEAD4 8008350C 1400A2AF */  sw         $v0, 0x14($sp)
/* EFEAD8 80083510 07002286 */  lh         $v0, 0x7($s1)
/* EFEADC 80083514 00000000 */  nop
/* EFEAE0 80083518 80100200 */  sll        $v0, $v0, 2
/* EFEAE4 8008351C 40004224 */  addiu      $v0, $v0, 0x40
/* EFEAE8 80083520 1800A2AF */  sw         $v0, 0x18($sp)
/* EFEAEC 80083524 2A106202 */  slt        $v0, $s3, $v0
/* EFEAF0 80083528 C7034014 */  bnez       $v0, .Llevel_12_80084448
/* EFEAF4 8008352C 00000000 */   nop
/* EFEAF8 80083530 01002292 */  lbu        $v0, 0x1($s1)
/* EFEAFC 80083534 00000000 */  nop
/* EFEB00 80083538 C900422C */  sltiu      $v0, $v0, 0xC9
/* EFEB04 8008353C C2034010 */  beqz       $v0, .Llevel_12_80084448
/* EFEB08 80083540 2120A002 */   addu      $a0, $s5, $zero
/* EFEB0C 80083544 FF5E000C */  jal        func_80017BFC
/* EFEB10 80083548 1000A527 */   addiu     $a1, $sp, 0x10
/* EFEB14 8008354C 01002292 */  lbu        $v0, 0x1($s1)
/* EFEB18 80083550 00000000 */  nop
/* EFEB1C 80083554 01004224 */  addiu      $v0, $v0, 0x1
/* EFEB20 80083558 14110208 */  j          .Llevel_12_80084450
/* EFEB24 8008355C 010022A2 */   sb        $v0, 0x1($s1)
.L80083560_:
/* EFEB28 80083560 2120A002 */  addu       $a0, $s5, $zero
/* EFEB2C 80083564 2128A002 */  addu       $a1, $s5, $zero
/* EFEB30 80083568 215F000C */  jal        func_80017C84
/* EFEB34 8008356C 2130C003 */   addu      $a2, $fp, $zero
/* EFEB38 80083570 1D002286 */  lh         $v0, 0x1D($s1)
/* EFEB3C 80083574 00000000 */  nop
/* EFEB40 80083578 05004010 */  beqz       $v0, .Llevel_12_80083590
/* EFEB44 8008357C 00000000 */   nop
/* EFEB48 80083580 1B002296 */  lhu        $v0, 0x1B($s1)
/* EFEB4C 80083584 00000000 */  nop
/* EFEB50 80083588 01004224 */  addiu      $v0, $v0, 0x1
/* EFEB54 8008358C 1B0022A6 */  sh         $v0, 0x1B($s1)
.Llevel_12_80083590:
/* EFEB58 80083590 1D002396 */  lhu        $v1, 0x1D($s1)
/* EFEB5C 80083594 01000224 */  addiu      $v0, $zero, 0x1
/* EFEB60 80083598 23104300 */  subu       $v0, $v0, $v1
/* EFEB64 8008359C 09002392 */  lbu        $v1, 0x9($s1)
/* EFEB68 800835A0 40201600 */  sll        $a0, $s6, 1
/* EFEB6C 800835A4 1D0022A6 */  sh         $v0, 0x1D($s1)
/* EFEB70 800835A8 01002292 */  lbu        $v0, 0x1($s1)
/* EFEB74 800835AC 21186400 */  addu       $v1, $v1, $a0
/* EFEB78 800835B0 21105600 */  addu       $v0, $v0, $s6
/* EFEB7C 800835B4 010022A2 */  sb         $v0, 0x1($s1)
/* EFEB80 800835B8 FF004230 */  andi       $v0, $v0, 0xFF
/* EFEB84 800835BC 2000422C */  sltiu      $v0, $v0, 0x20
/* EFEB88 800835C0 0C110208 */  j          .Llevel_12_80084430
/* EFEB8C 800835C4 090023A2 */   sb        $v1, 0x9($s1)
.L800835C8_:
/* EFEB90 800835C8 0880033C */  lui        $v1, %hi(g_Spyro + 0x78)
/* EFEB94 800835CC D08A638C */  lw         $v1, %lo(g_Spyro + 0x78)($v1)
/* EFEB98 800835D0 1D000224 */  addiu      $v0, $zero, 0x1D
/* EFEB9C 800835D4 06006214 */  bne        $v1, $v0, .Llevel_12_800835F0
/* EFEBA0 800835D8 00000000 */   nop
/* EFEBA4 800835DC 0880023C */  lui        $v0, %hi(g_Spyro + 0x164)
/* EFEBA8 800835E0 BC8B428C */  lw         $v0, %lo(g_Spyro + 0x164)($v0)
/* EFEBAC 800835E4 00000000 */  nop
/* EFEBB0 800835E8 97034004 */  bltz       $v0, .Llevel_12_80084448
/* EFEBB4 800835EC 00000000 */   nop
.Llevel_12_800835F0:
/* EFEBB8 800835F0 0780023C */  lui        $v0, %hi(g_IsSpyroHidden)
/* EFEBBC 800835F4 1458428C */  lw         $v0, %lo(g_IsSpyroHidden)($v0)
/* EFEBC0 800835F8 00000000 */  nop
/* EFEBC4 800835FC 92034014 */  bnez       $v0, .Llevel_12_80084448
/* EFEBC8 80083600 00000000 */   nop
/* EFEBCC 80083604 0880053C */  lui        $a1, %hi(g_Spyro + 0x160)
/* EFEBD0 80083608 B88BA524 */  addiu      $a1, $a1, %lo(g_Spyro + 0x160)
/* EFEBD4 8008360C 0000A28C */  lw         $v0, 0x0($a1)
/* EFEBD8 80083610 00000000 */  nop
/* EFEBDC 80083614 8C034018 */  blez       $v0, .Llevel_12_80084448
/* EFEBE0 80083618 2000B027 */   addiu     $s0, $sp, 0x20
/* EFEBE4 8008361C 21200002 */  addu       $a0, $s0, $zero
/* EFEBE8 80083620 C05D000C */  jal        VecCopy
/* EFEBEC 80083624 A0FEA524 */   addiu     $a1, $a1, -0x160
/* EFEBF0 80083628 17002486 */  lh         $a0, 0x17($s1)
/* EFEBF4 8008362C 2C5B000C */  jal        Cos
/* EFEBF8 80083630 00000000 */   nop
/* EFEBFC 80083634 2000A38F */  lw         $v1, 0x20($sp)
/* EFEC00 80083638 03110200 */  sra        $v0, $v0, 4
/* EFEC04 8008363C 21186200 */  addu       $v1, $v1, $v0
/* EFEC08 80083640 2000A3AF */  sw         $v1, 0x20($sp)
/* EFEC0C 80083644 17002486 */  lh         $a0, 0x17($s1)
/* EFEC10 80083648 165B000C */  jal        Sin
/* EFEC14 8008364C 00000000 */   nop
/* EFEC18 80083650 2120A002 */  addu       $a0, $s5, $zero
/* EFEC1C 80083654 21280002 */  addu       $a1, $s0, $zero
/* EFEC20 80083658 03110200 */  sra        $v0, $v0, 4
/* EFEC24 8008365C 2400A38F */  lw         $v1, 0x24($sp)
/* EFEC28 80083660 2800A68F */  lw         $a2, 0x28($sp)
/* EFEC2C 80083664 21186200 */  addu       $v1, $v1, $v0
/* EFEC30 80083668 0001C624 */  addiu      $a2, $a2, 0x100
/* EFEC34 8008366C 2400A3AF */  sw         $v1, 0x24($sp)
/* EFEC38 80083670 FF5E000C */  jal        func_80017BFC
/* EFEC3C 80083674 2800A6AF */   sw        $a2, 0x28($sp)
/* EFEC40 80083678 17002496 */  lhu        $a0, 0x17($s1)
/* EFEC44 8008367C 00000000 */  nop
/* EFEC48 80083680 40008424 */  addiu      $a0, $a0, 0x40
/* EFEC4C 80083684 170024A6 */  sh         $a0, 0x17($s1)
/* EFEC50 80083688 00240400 */  sll        $a0, $a0, 16
/* EFEC54 8008368C 0780023C */  lui        $v0, %hi(g_Camera + 0x50)
/* EFEC58 80083690 206E4284 */  lh         $v0, %lo(g_Camera + 0x50)($v0)
/* EFEC5C 80083694 03240400 */  sra        $a0, $a0, 16
/* EFEC60 80083698 23208200 */  subu       $a0, $a0, $v0
/* EFEC64 8008369C 2C5B000C */  jal        Cos
/* EFEC68 800836A0 FF0F8430 */   andi      $a0, $a0, 0xFFF
/* EFEC6C 800836A4 6060033C */  lui        $v1, (0x60606061 >> 16)
/* EFEC70 800836A8 61606334 */  ori        $v1, $v1, (0x60606061 & 0xFFFF)
/* EFEC74 800836AC 02004104 */  bgez       $v0, .Llevel_12_800836B8
/* EFEC78 800836B0 00000000 */   nop
/* EFEC7C 800836B4 23100200 */  negu       $v0, $v0
.Llevel_12_800836B8:
/* EFEC80 800836B8 18004300 */  mult       $v0, $v1
/* EFEC84 800836BC C3170200 */  sra        $v0, $v0, 31
/* EFEC88 800836C0 10380000 */  mfhi       $a3
/* EFEC8C 800836C4 83190700 */  sra        $v1, $a3, 6
/* EFEC90 800836C8 23186200 */  subu       $v1, $v1, $v0
/* EFEC94 800836CC 14110208 */  j          .Llevel_12_80084450
/* EFEC98 800836D0 090023A2 */   sb        $v1, 0x9($s1)
.L800836D4_:
/* EFEC9C 800836D4 2120A002 */  addu       $a0, $s5, $zero
/* EFECA0 800836D8 2128A002 */  addu       $a1, $s5, $zero
/* EFECA4 800836DC 215F000C */  jal        func_80017C84
/* EFECA8 800836E0 12008626 */   addiu     $a2, $s4, 0x12
/* EFECAC 800836E4 0B002292 */  lbu        $v0, 0xB($s1)
/* EFECB0 800836E8 0C002392 */  lbu        $v1, 0xC($s1)
/* EFECB4 800836EC F8FF4224 */  addiu      $v0, $v0, -0x8
/* EFECB8 800836F0 0B0022A2 */  sb         $v0, 0xB($s1)
/* EFECBC 800836F4 0D002292 */  lbu        $v0, 0xD($s1)
/* EFECC0 800836F8 F8FF6324 */  addiu      $v1, $v1, -0x8
/* EFECC4 800836FC 0C0023A2 */  sb         $v1, 0xC($s1)
/* EFECC8 80083700 0B002392 */  lbu        $v1, 0xB($s1)
/* EFECCC 80083704 F8FF4224 */  addiu      $v0, $v0, -0x8
/* EFECD0 80083708 4F036010 */  beqz       $v1, .Llevel_12_80084448
/* EFECD4 8008370C 0D0022A2 */   sb        $v0, 0xD($s1)
/* EFECD8 80083710 0E110208 */  j          .Llevel_12_80084438
/* EFECDC 80083714 00000000 */   nop
.L80083718_:
/* EFECE0 80083718 0A002292 */  lbu        $v0, 0xA($s1)
/* EFECE4 8008371C 00000000 */  nop
/* EFECE8 80083720 08004224 */  addiu      $v0, $v0, 0x8
/* EFECEC 80083724 0A0022A2 */  sb         $v0, 0xA($s1)
/* EFECF0 80083728 09002292 */  lbu        $v0, 0x9($s1)
/* EFECF4 8008372C 0B002392 */  lbu        $v1, 0xB($s1)
/* EFECF8 80083730 02004224 */  addiu      $v0, $v0, 0x2
/* EFECFC 80083734 03006010 */  beqz       $v1, .Llevel_12_80083744
/* EFED00 80083738 090022A2 */   sb        $v0, 0x9($s1)
/* EFED04 8008373C F8FF6224 */  addiu      $v0, $v1, -0x8
/* EFED08 80083740 0B0022A2 */  sb         $v0, 0xB($s1)
.Llevel_12_80083744:
/* EFED0C 80083744 0C002292 */  lbu        $v0, 0xC($s1)
/* EFED10 80083748 00000000 */  nop
/* EFED14 8008374C 02004010 */  beqz       $v0, .Llevel_12_80083758
/* EFED18 80083750 F8FF4224 */   addiu     $v0, $v0, -0x8
/* EFED1C 80083754 0C0022A2 */  sb         $v0, 0xC($s1)
.Llevel_12_80083758:
/* EFED20 80083758 0D002292 */  lbu        $v0, 0xD($s1)
/* EFED24 8008375C 00000000 */  nop
/* EFED28 80083760 02004010 */  beqz       $v0, .Llevel_12_8008376C
/* EFED2C 80083764 F8FF4224 */   addiu     $v0, $v0, -0x8
/* EFED30 80083768 0D0022A2 */  sb         $v0, 0xD($s1)
.Llevel_12_8008376C:
/* EFED34 8008376C FF00033C */  lui        $v1, (0xFFFFFF >> 16)
/* EFED38 80083770 0B00228E */  lw         $v0, 0xB($s1)
/* EFED3C 80083774 FFFF6334 */  ori        $v1, $v1, (0xFFFFFF & 0xFFFF)
/* EFED40 80083778 24104300 */  and        $v0, $v0, $v1
/* EFED44 8008377C 32034010 */  beqz       $v0, .Llevel_12_80084448
/* EFED48 80083780 00000000 */   nop
/* EFED4C 80083784 0E110208 */  j          .Llevel_12_80084438
/* EFED50 80083788 00000000 */   nop
.L8008378C_:
/* EFED54 8008378C 0780023C */  lui        $v0, %hi(g_DeltaTime)
/* EFED58 80083790 CC56428C */  lw         $v0, %lo(g_DeltaTime)($v0)
/* EFED5C 80083794 17002392 */  lbu        $v1, 0x17($s1)
/* EFED60 80083798 80100200 */  sll        $v0, $v0, 2
/* EFED64 8008379C 21186200 */  addu       $v1, $v1, $v0
/* EFED68 800837A0 170023A2 */  sb         $v1, 0x17($s1)
/* EFED6C 800837A4 0780043C */  lui        $a0, %hi(g_DeltaTime)
/* EFED70 800837A8 CC56848C */  lw         $a0, %lo(g_DeltaTime)($a0)
/* EFED74 800837AC 18002292 */  lbu        $v0, 0x18($s1)
/* EFED78 800837B0 17002392 */  lbu        $v1, 0x17($s1)
/* EFED7C 800837B4 21104400 */  addu       $v0, $v0, $a0
/* EFED80 800837B8 40180300 */  sll        $v1, $v1, 1
/* EFED84 800837BC 180022A2 */  sb         $v0, 0x18($s1)
/* EFED88 800837C0 0780013C */  lui        $at, %hi(D_8006CC78)
/* EFED8C 800837C4 21082300 */  addu       $at, $at, $v1
/* EFED90 800837C8 78CC2384 */  lh         $v1, %lo(D_8006CC78)($at)
/* EFED94 800837CC FF004230 */  andi       $v0, $v0, 0xFF
/* EFED98 800837D0 18006200 */  mult       $v1, $v0
/* EFED9C 800837D4 17002392 */  lbu        $v1, 0x17($s1)
/* EFEDA0 800837D8 11002296 */  lhu        $v0, 0x11($s1)
/* EFEDA4 800837DC 40180300 */  sll        $v1, $v1, 1
/* EFEDA8 800837E0 12380000 */  mflo       $a3
/* EFEDAC 800837E4 03230700 */  sra        $a0, $a3, 12
/* EFEDB0 800837E8 21104400 */  addu       $v0, $v0, $a0
/* EFEDB4 800837EC 030022A6 */  sh         $v0, 0x3($s1)
/* EFEDB8 800837F0 0780013C */  lui        $at, %hi(D_8006CBF8)
/* EFEDBC 800837F4 21082300 */  addu       $at, $at, $v1
/* EFEDC0 800837F8 F8CB2384 */  lh         $v1, %lo(D_8006CBF8)($at)
/* EFEDC4 800837FC 18002292 */  lbu        $v0, 0x18($s1)
/* EFEDC8 80083800 00000000 */  nop
/* EFEDCC 80083804 18006200 */  mult       $v1, $v0
/* EFEDD0 80083808 0780023C */  lui        $v0, %hi(g_DeltaTime)
/* EFEDD4 8008380C CC56428C */  lw         $v0, %lo(g_DeltaTime)($v0)
/* EFEDD8 80083810 0A002492 */  lbu        $a0, 0xA($s1)
/* EFEDDC 80083814 40180200 */  sll        $v1, $v0, 1
/* EFEDE0 80083818 21186200 */  addu       $v1, $v1, $v0
/* EFEDE4 8008381C 07002296 */  lhu        $v0, 0x7($s1)
/* EFEDE8 80083820 40180300 */  sll        $v1, $v1, 1
/* EFEDEC 80083824 21104300 */  addu       $v0, $v0, $v1
/* EFEDF0 80083828 18002392 */  lbu        $v1, 0x18($s1)
/* EFEDF4 8008382C 04008424 */  addiu      $a0, $a0, 0x4
/* EFEDF8 80083830 0A0024A2 */  sb         $a0, 0xA($s1)
/* EFEDFC 80083834 070022A6 */  sh         $v0, 0x7($s1)
/* EFEE00 80083838 13002296 */  lhu        $v0, 0x13($s1)
/* EFEE04 8008383C C100632C */  sltiu      $v1, $v1, 0xC1
.Llevel_12_80083840:
/* EFEE08 80083840 12380000 */  mflo       $a3
/* EFEE0C 80083844 03230700 */  sra        $a0, $a3, 12
/* EFEE10 80083848 21104400 */  addu       $v0, $v0, $a0
/* EFEE14 8008384C 00036014 */  bnez       $v1, .Llevel_12_80084450
/* EFEE18 80083850 050022A6 */   sh        $v0, 0x5($s1)
/* EFEE1C 80083854 12110208 */  j          .Llevel_12_80084448
/* EFEE20 80083858 00000000 */   nop
.L8008385C_:
/* EFEE24 8008385C 0B002392 */  lbu        $v1, 0xB($s1)
/* EFEE28 80083860 00000000 */  nop
/* EFEE2C 80083864 F000622C */  sltiu      $v0, $v1, 0xF0
/* EFEE30 80083868 02004010 */  beqz       $v0, .Llevel_12_80083874
/* EFEE34 8008386C 04006224 */   addiu     $v0, $v1, 0x4
/* EFEE38 80083870 0B0022A2 */  sb         $v0, 0xB($s1)
.Llevel_12_80083874:
/* EFEE3C 80083874 0C002392 */  lbu        $v1, 0xC($s1)
/* EFEE40 80083878 00000000 */  nop
/* EFEE44 8008387C F000622C */  sltiu      $v0, $v1, 0xF0
/* EFEE48 80083880 02004010 */  beqz       $v0, .Llevel_12_8008388C
/* EFEE4C 80083884 04006224 */   addiu     $v0, $v1, 0x4
/* EFEE50 80083888 0C0022A2 */  sb         $v0, 0xC($s1)
.Llevel_12_8008388C:
/* EFEE54 8008388C 0D002392 */  lbu        $v1, 0xD($s1)
/* EFEE58 80083890 00000000 */  nop
/* EFEE5C 80083894 F000622C */  sltiu      $v0, $v1, 0xF0
/* EFEE60 80083898 02004010 */  beqz       $v0, .Llevel_12_800838A4
/* EFEE64 8008389C 04006224 */   addiu     $v0, $v1, 0x4
/* EFEE68 800838A0 0D0022A2 */  sb         $v0, 0xD($s1)
.Llevel_12_800838A4:
/* EFEE6C 800838A4 0780023C */  lui        $v0, %hi(g_DeltaTime)
/* EFEE70 800838A8 CC56428C */  lw         $v0, %lo(g_DeltaTime)($v0)
/* EFEE74 800838AC 1B002392 */  lbu        $v1, 0x1B($s1)
/* EFEE78 800838B0 C0100200 */  sll        $v0, $v0, 3
/* EFEE7C 800838B4 21186200 */  addu       $v1, $v1, $v0
/* EFEE80 800838B8 1B0023A2 */  sb         $v1, 0x1B($s1)
/* EFEE84 800838BC 0780033C */  lui        $v1, %hi(g_DragonCutscene + 0x3C)
/* EFEE88 800838C0 6C70638C */  lw         $v1, %lo(g_DragonCutscene + 0x3C)($v1)
/* EFEE8C 800838C4 00000000 */  nop
/* EFEE90 800838C8 40006228 */  slti       $v0, $v1, 0x40
/* EFEE94 800838CC 02004010 */  beqz       $v0, .Llevel_12_800838D8
/* EFEE98 800838D0 3F000424 */   addiu     $a0, $zero, 0x3F
/* EFEE9C 800838D4 21206000 */  addu       $a0, $v1, $zero
.Llevel_12_800838D8:
/* EFEEA0 800838D8 48000224 */  addiu      $v0, $zero, 0x48
/* EFEEA4 800838DC 1C002392 */  lbu        $v1, 0x1C($s1)
/* EFEEA8 800838E0 23104400 */  subu       $v0, $v0, $a0
/* EFEEAC 800838E4 18006200 */  mult       $v1, $v0
/* EFEEB0 800838E8 1C002392 */  lbu        $v1, 0x1C($s1)
/* EFEEB4 800838EC 12280000 */  mflo       $a1
/* EFEEB8 800838F0 20000224 */  addiu      $v0, $zero, 0x20
/* EFEEBC 800838F4 23104300 */  subu       $v0, $v0, $v1
/* EFEEC0 800838F8 18004400 */  mult       $v0, $a0
/* EFEEC4 800838FC C3100500 */  sra        $v0, $a1, 3
/* EFEEC8 80083900 170022A6 */  sh         $v0, 0x17($s1)
/* EFEECC 80083904 12180000 */  mflo       $v1
/* EFEED0 80083908 03110300 */  sra        $v0, $v1, 4
/* EFEED4 8008390C 1B002392 */  lbu        $v1, 0x1B($s1)
/* EFEED8 80083910 08004224 */  addiu      $v0, $v0, 0x8
/* EFEEDC 80083914 190022A6 */  sh         $v0, 0x19($s1)
/* EFEEE0 80083918 00140200 */  sll        $v0, $v0, 16
/* EFEEE4 8008391C 40180300 */  sll        $v1, $v1, 1
/* EFEEE8 80083920 0780013C */  lui        $at, %hi(D_8006CC78)
/* EFEEEC 80083924 21082300 */  addu       $at, $at, $v1
/* EFEEF0 80083928 78CC2384 */  lh         $v1, %lo(D_8006CC78)($at)
/* EFEEF4 8008392C 03140200 */  sra        $v0, $v0, 16
/* EFEEF8 80083930 18006200 */  mult       $v1, $v0
/* EFEEFC 80083934 11002296 */  lhu        $v0, 0x11($s1)
/* EFEF00 80083938 12180000 */  mflo       $v1
/* EFEF04 8008393C 03230300 */  sra        $a0, $v1, 12
/* EFEF08 80083940 1B002392 */  lbu        $v1, 0x1B($s1)
/* EFEF0C 80083944 21104400 */  addu       $v0, $v0, $a0
/* EFEF10 80083948 030022A6 */  sh         $v0, 0x3($s1)
/* EFEF14 8008394C 19002286 */  lh         $v0, 0x19($s1)
/* EFEF18 80083950 40180300 */  sll        $v1, $v1, 1
/* EFEF1C 80083954 0780013C */  lui        $at, %hi(D_8006CBF8)
/* EFEF20 80083958 21082300 */  addu       $at, $at, $v1
/* EFEF24 8008395C F8CB2384 */  lh         $v1, %lo(D_8006CBF8)($at)
/* EFEF28 80083960 00000000 */  nop
/* EFEF2C 80083964 18006200 */  mult       $v1, $v0
/* EFEF30 80083968 17002296 */  lhu        $v0, 0x17($s1)
/* EFEF34 8008396C 15002396 */  lhu        $v1, 0x15($s1)
/* EFEF38 80083970 20004224 */  addiu      $v0, $v0, 0x20
/* EFEF3C 80083974 21186200 */  addu       $v1, $v1, $v0
/* EFEF40 80083978 13002296 */  lhu        $v0, 0x13($s1)
/* EFEF44 8008397C 070023A6 */  sh         $v1, 0x7($s1)
/* EFEF48 80083980 12400000 */  mflo       $t0
/* EFEF4C 80083984 031B0800 */  sra        $v1, $t0, 12
/* EFEF50 80083988 21104300 */  addu       $v0, $v0, $v1
/* EFEF54 8008398C 14110208 */  j          .Llevel_12_80084450
/* EFEF58 80083990 050022A6 */   sh        $v0, 0x5($s1)
.L80083994_:
/* EFEF5C 80083994 2120A002 */  addu       $a0, $s5, $zero
/* EFEF60 80083998 2128A002 */  addu       $a1, $s5, $zero
/* EFEF64 8008399C 215F000C */  jal        func_80017C84
/* EFEF68 800839A0 2130C003 */   addu      $a2, $fp, $zero
/* EFEF6C 800839A4 1D002286 */  lh         $v0, 0x1D($s1)
/* EFEF70 800839A8 00000000 */  nop
/* EFEF74 800839AC 05004010 */  beqz       $v0, .Llevel_12_800839C4
/* EFEF78 800839B0 00000000 */   nop
/* EFEF7C 800839B4 1B002296 */  lhu        $v0, 0x1B($s1)
/* EFEF80 800839B8 00000000 */  nop
/* EFEF84 800839BC 01004224 */  addiu      $v0, $v0, 0x1
/* EFEF88 800839C0 1B0022A6 */  sh         $v0, 0x1B($s1)
.Llevel_12_800839C4:
/* EFEF8C 800839C4 0B002292 */  lbu        $v0, 0xB($s1)
/* EFEF90 800839C8 1D002396 */  lhu        $v1, 0x1D($s1)
/* EFEF94 800839CC 23205600 */  subu       $a0, $v0, $s6
/* EFEF98 800839D0 01000224 */  addiu      $v0, $zero, 0x1
/* EFEF9C 800839D4 23104300 */  subu       $v0, $v0, $v1
/* EFEFA0 800839D8 1D0022A6 */  sh         $v0, 0x1D($s1)
/* EFEFA4 800839DC 09002292 */  lbu        $v0, 0x9($s1)
/* EFEFA8 800839E0 40181600 */  sll        $v1, $s6, 1
/* EFEFAC 800839E4 21104300 */  addu       $v0, $v0, $v1
/* EFEFB0 800839E8 02008104 */  bgez       $a0, .Llevel_12_800839F4
/* EFEFB4 800839EC 090022A2 */   sb        $v0, 0x9($s1)
/* EFEFB8 800839F0 21200000 */  addu       $a0, $zero, $zero
.Llevel_12_800839F4:
/* EFEFBC 800839F4 0C002292 */  lbu        $v0, 0xC($s1)
/* EFEFC0 800839F8 0B0024A2 */  sb         $a0, 0xB($s1)
/* EFEFC4 800839FC 23205600 */  subu       $a0, $v0, $s6
/* EFEFC8 80083A00 02008104 */  bgez       $a0, .Llevel_12_80083A0C
/* EFEFCC 80083A04 00000000 */   nop
/* EFEFD0 80083A08 21200000 */  addu       $a0, $zero, $zero
.Llevel_12_80083A0C:
/* EFEFD4 80083A0C 0D002292 */  lbu        $v0, 0xD($s1)
/* EFEFD8 80083A10 0C0024A2 */  sb         $a0, 0xC($s1)
/* EFEFDC 80083A14 23205600 */  subu       $a0, $v0, $s6
/* EFEFE0 80083A18 02008104 */  bgez       $a0, .Llevel_12_80083A24
/* EFEFE4 80083A1C 00000000 */   nop
/* EFEFE8 80083A20 21200000 */  addu       $a0, $zero, $zero
.Llevel_12_80083A24:
/* EFEFEC 80083A24 01002292 */  lbu        $v0, 0x1($s1)
/* EFEFF0 80083A28 0D0024A2 */  sb         $a0, 0xD($s1)
/* EFEFF4 80083A2C 21105600 */  addu       $v0, $v0, $s6
/* EFEFF8 80083A30 010022A2 */  sb         $v0, 0x1($s1)
/* EFEFFC 80083A34 FF004230 */  andi       $v0, $v0, 0xFF
/* EFF000 80083A38 0C110208 */  j          .Llevel_12_80084430
/* EFF004 80083A3C 2000422C */   sltiu     $v0, $v0, 0x20
.L80083A40_:
/* EFF008 80083A40 2F00C01A */  blez       $s6, .Llevel_12_80083B00
/* EFF00C 80083A44 21800000 */   addu      $s0, $zero, $zero
.Llevel_12_80083A48:
/* EFF010 80083A48 01002292 */  lbu        $v0, 0x1($s1)
/* EFF014 80083A4C 00000000 */  nop
/* EFF018 80083A50 01004230 */  andi       $v0, $v0, 0x1
/* EFF01C 80083A54 23004010 */  beqz       $v0, .Llevel_12_80083AE4
/* EFF020 80083A58 00000000 */   nop
/* EFF024 80083A5C 03002296 */  lhu        $v0, 0x3($s1)
/* EFF028 80083A60 0F002496 */  lhu        $a0, 0xF($s1)
/* EFF02C 80083A64 05002396 */  lhu        $v1, 0x5($s1)
/* EFF030 80083A68 11002596 */  lhu        $a1, 0x11($s1)
/* EFF034 80083A6C 21104400 */  addu       $v0, $v0, $a0
/* EFF038 80083A70 030022A6 */  sh         $v0, 0x3($s1)
/* EFF03C 80083A74 07002296 */  lhu        $v0, 0x7($s1)
/* EFF040 80083A78 13002496 */  lhu        $a0, 0x13($s1)
/* EFF044 80083A7C 21186500 */  addu       $v1, $v1, $a1
/* EFF048 80083A80 050023A6 */  sh         $v1, 0x5($s1)
/* EFF04C 80083A84 01002392 */  lbu        $v1, 0x1($s1)
/* EFF050 80083A88 21104400 */  addu       $v0, $v0, $a0
/* EFF054 80083A8C 02006330 */  andi       $v1, $v1, 0x2
/* EFF058 80083A90 14006010 */  beqz       $v1, .Llevel_12_80083AE4
/* EFF05C 80083A94 070022A6 */   sh        $v0, 0x7($s1)
/* EFF060 80083A98 CB89010C */  jal        rand
/* EFF064 80083A9C 00000000 */   nop
/* EFF068 80083AA0 0F002396 */  lhu        $v1, 0xF($s1)
/* EFF06C 80083AA4 02004230 */  andi       $v0, $v0, 0x2
/* EFF070 80083AA8 FFFF6324 */  addiu      $v1, $v1, -0x1
/* EFF074 80083AAC 21186200 */  addu       $v1, $v1, $v0
/* EFF078 80083AB0 CB89010C */  jal        rand
/* EFF07C 80083AB4 0F0023A6 */   sh        $v1, 0xF($s1)
/* EFF080 80083AB8 11002396 */  lhu        $v1, 0x11($s1)
/* EFF084 80083ABC 02004230 */  andi       $v0, $v0, 0x2
/* EFF088 80083AC0 FFFF6324 */  addiu      $v1, $v1, -0x1
/* EFF08C 80083AC4 21186200 */  addu       $v1, $v1, $v0
/* EFF090 80083AC8 CB89010C */  jal        rand
/* EFF094 80083ACC 110023A6 */   sh        $v1, 0x11($s1)
/* EFF098 80083AD0 13002396 */  lhu        $v1, 0x13($s1)
/* EFF09C 80083AD4 02004230 */  andi       $v0, $v0, 0x2
/* EFF0A0 80083AD8 FFFF6324 */  addiu      $v1, $v1, -0x1
/* EFF0A4 80083ADC 21186200 */  addu       $v1, $v1, $v0
/* EFF0A8 80083AE0 130023A6 */  sh         $v1, 0x13($s1)
.Llevel_12_80083AE4:
/* EFF0AC 80083AE4 01002292 */  lbu        $v0, 0x1($s1)
/* EFF0B0 80083AE8 01001026 */  addiu      $s0, $s0, 0x1
/* EFF0B4 80083AEC 01004224 */  addiu      $v0, $v0, 0x1
/* EFF0B8 80083AF0 010022A2 */  sb         $v0, 0x1($s1)
/* EFF0BC 80083AF4 2A101602 */  slt        $v0, $s0, $s6
/* EFF0C0 80083AF8 D3FF4014 */  bnez       $v0, .Llevel_12_80083A48
/* EFF0C4 80083AFC 00000000 */   nop
.Llevel_12_80083B00:
/* EFF0C8 80083B00 01002292 */  lbu        $v0, 0x1($s1)
/* EFF0CC 80083B04 0C110208 */  j          .Llevel_12_80084430
/* EFF0D0 80083B08 1800422C */   sltiu     $v0, $v0, 0x18
.L80083B0C_:
/* EFF0D4 80083B0C 09002486 */  lh         $a0, 0x9($s1)
/* EFF0D8 80083B10 03002286 */  lh         $v0, 0x3($s1)
/* EFF0DC 80083B14 00000000 */  nop
/* EFF0E0 80083B18 23208200 */  subu       $a0, $a0, $v0
/* EFF0E4 80083B1C 43200400 */  sra        $a0, $a0, 1
/* EFF0E8 80083B20 3000A4A7 */  sh         $a0, 0x30($sp)
/* EFF0EC 80083B24 0B002286 */  lh         $v0, 0xB($s1)
/* EFF0F0 80083B28 05002386 */  lh         $v1, 0x5($s1)
/* EFF0F4 80083B2C 00000000 */  nop
/* EFF0F8 80083B30 23104300 */  subu       $v0, $v0, $v1
/* EFF0FC 80083B34 43100200 */  sra        $v0, $v0, 1
/* EFF100 80083B38 3200A2A7 */  sh         $v0, 0x32($sp)
/* EFF104 80083B3C 0D002286 */  lh         $v0, 0xD($s1)
/* EFF108 80083B40 07002386 */  lh         $v1, 0x7($s1)
/* EFF10C 80083B44 00000000 */  nop
/* EFF110 80083B48 23104300 */  subu       $v0, $v0, $v1
/* EFF114 80083B4C 43100200 */  sra        $v0, $v0, 1
/* EFF118 80083B50 3400A2A7 */  sh         $v0, 0x34($sp)
/* EFF11C 80083B54 03002296 */  lhu        $v0, 0x3($s1)
/* EFF120 80083B58 00000000 */  nop
/* EFF124 80083B5C 21104400 */  addu       $v0, $v0, $a0
/* EFF128 80083B60 030022A6 */  sh         $v0, 0x3($s1)
/* EFF12C 80083B64 05002296 */  lhu        $v0, 0x5($s1)
/* EFF130 80083B68 3200A397 */  lhu        $v1, 0x32($sp)
/* EFF134 80083B6C 00000000 */  nop
/* EFF138 80083B70 21104300 */  addu       $v0, $v0, $v1
/* EFF13C 80083B74 050022A6 */  sh         $v0, 0x5($s1)
/* EFF140 80083B78 07002296 */  lhu        $v0, 0x7($s1)
/* EFF144 80083B7C 3400A397 */  lhu        $v1, 0x34($sp)
/* EFF148 80083B80 00000000 */  nop
/* EFF14C 80083B84 21104300 */  addu       $v0, $v0, $v1
/* EFF150 80083B88 CB89010C */  jal        rand
/* EFF154 80083B8C 070022A6 */   sh        $v0, 0x7($s1)
/* EFF158 80083B90 3000A397 */  lhu        $v1, 0x30($sp)
/* EFF15C 80083B94 02004230 */  andi       $v0, $v0, 0x2
/* EFF160 80083B98 FFFF6324 */  addiu      $v1, $v1, -0x1
/* EFF164 80083B9C 21186200 */  addu       $v1, $v1, $v0
/* EFF168 80083BA0 CB89010C */  jal        rand
/* EFF16C 80083BA4 3000A3A7 */   sh        $v1, 0x30($sp)
/* EFF170 80083BA8 3200A397 */  lhu        $v1, 0x32($sp)
/* EFF174 80083BAC 02004230 */  andi       $v0, $v0, 0x2
/* EFF178 80083BB0 FFFF6324 */  addiu      $v1, $v1, -0x1
/* EFF17C 80083BB4 21186200 */  addu       $v1, $v1, $v0
/* EFF180 80083BB8 3200A3A7 */  sh         $v1, 0x32($sp)
/* EFF184 80083BBC 01002292 */  lbu        $v0, 0x1($s1)
/* EFF188 80083BC0 00000000 */  nop
/* EFF18C 80083BC4 01004230 */  andi       $v0, $v0, 0x1
/* EFF190 80083BC8 05004010 */  beqz       $v0, .Llevel_12_80083BE0
/* EFF194 80083BCC 00000000 */   nop
/* EFF198 80083BD0 3400A297 */  lhu        $v0, 0x34($sp)
/* EFF19C 80083BD4 00000000 */  nop
/* EFF1A0 80083BD8 FFFF4224 */  addiu      $v0, $v0, -0x1
/* EFF1A4 80083BDC 3400A2A7 */  sh         $v0, 0x34($sp)
.Llevel_12_80083BE0:
/* EFF1A8 80083BE0 09002296 */  lhu        $v0, 0x9($s1)
/* EFF1AC 80083BE4 3000A397 */  lhu        $v1, 0x30($sp)
/* EFF1B0 80083BE8 00000000 */  nop
/* EFF1B4 80083BEC 21104300 */  addu       $v0, $v0, $v1
/* EFF1B8 80083BF0 090022A6 */  sh         $v0, 0x9($s1)
/* EFF1BC 80083BF4 0B002296 */  lhu        $v0, 0xB($s1)
/* EFF1C0 80083BF8 3200A397 */  lhu        $v1, 0x32($sp)
/* EFF1C4 80083BFC 00000000 */  nop
/* EFF1C8 80083C00 21104300 */  addu       $v0, $v0, $v1
/* EFF1CC 80083C04 0D002396 */  lhu        $v1, 0xD($s1)
/* EFF1D0 80083C08 0B0022A6 */  sh         $v0, 0xB($s1)
/* EFF1D4 80083C0C 01002292 */  lbu        $v0, 0x1($s1)
/* EFF1D8 80083C10 3400A497 */  lhu        $a0, 0x34($sp)
/* EFF1DC 80083C14 01004224 */  addiu      $v0, $v0, 0x1
/* EFF1E0 80083C18 21186400 */  addu       $v1, $v1, $a0
/* EFF1E4 80083C1C 010022A2 */  sb         $v0, 0x1($s1)
/* EFF1E8 80083C20 FF004230 */  andi       $v0, $v0, 0xFF
/* EFF1EC 80083C24 2000422C */  sltiu      $v0, $v0, 0x20
/* EFF1F0 80083C28 07024010 */  beqz       $v0, .Llevel_12_80084448
/* EFF1F4 80083C2C 0D0023A6 */   sh        $v1, 0xD($s1)
/* EFF1F8 80083C30 02002292 */  lbu        $v0, 0x2($s1)
/* EFF1FC 80083C34 00000000 */  nop
/* EFF200 80083C38 03024010 */  beqz       $v0, .Llevel_12_80084448
/* EFF204 80083C3C 00000000 */   nop
/* EFF208 80083C40 0F002292 */  lbu        $v0, 0xF($s1)
/* EFF20C 80083C44 00000000 */  nop
/* EFF210 80083C48 FDFF4224 */  addiu      $v0, $v0, -0x3
/* EFF214 80083C4C 0F0022A2 */  sb         $v0, 0xF($s1)
/* EFF218 80083C50 FF004230 */  andi       $v0, $v0, 0xFF
/* EFF21C 80083C54 8000422C */  sltiu      $v0, $v0, 0x80
/* EFF220 80083C58 02004010 */  beqz       $v0, .Llevel_12_80083C64
/* EFF224 80083C5C 80000224 */   addiu     $v0, $zero, 0x80
/* EFF228 80083C60 0F0022A2 */  sb         $v0, 0xF($s1)
.Llevel_12_80083C64:
/* EFF22C 80083C64 10002292 */  lbu        $v0, 0x10($s1)
/* EFF230 80083C68 00000000 */  nop
/* EFF234 80083C6C FCFF4224 */  addiu      $v0, $v0, -0x4
/* EFF238 80083C70 100022A2 */  sb         $v0, 0x10($s1)
/* EFF23C 80083C74 FF004230 */  andi       $v0, $v0, 0xFF
/* EFF240 80083C78 6000422C */  sltiu      $v0, $v0, 0x60
/* EFF244 80083C7C 02004010 */  beqz       $v0, .Llevel_12_80083C88
/* EFF248 80083C80 60000224 */   addiu     $v0, $zero, 0x60
/* EFF24C 80083C84 100022A2 */  sb         $v0, 0x10($s1)
.Llevel_12_80083C88:
/* EFF250 80083C88 13002292 */  lbu        $v0, 0x13($s1)
/* EFF254 80083C8C 110020A2 */  sb         $zero, 0x11($s1)
/* EFF258 80083C90 FDFF4224 */  addiu      $v0, $v0, -0x3
/* EFF25C 80083C94 130022A2 */  sb         $v0, 0x13($s1)
/* EFF260 80083C98 FF004230 */  andi       $v0, $v0, 0xFF
/* EFF264 80083C9C C000422C */  sltiu      $v0, $v0, 0xC0
/* EFF268 80083CA0 02004010 */  beqz       $v0, .Llevel_12_80083CAC
/* EFF26C 80083CA4 C0000224 */   addiu     $v0, $zero, 0xC0
/* EFF270 80083CA8 130022A2 */  sb         $v0, 0x13($s1)
.Llevel_12_80083CAC:
/* EFF274 80083CAC 14002292 */  lbu        $v0, 0x14($s1)
/* EFF278 80083CB0 00000000 */  nop
/* EFF27C 80083CB4 FCFF4224 */  addiu      $v0, $v0, -0x4
/* EFF280 80083CB8 140022A2 */  sb         $v0, 0x14($s1)
/* EFF284 80083CBC FF004230 */  andi       $v0, $v0, 0xFF
/* EFF288 80083CC0 8000422C */  sltiu      $v0, $v0, 0x80
/* EFF28C 80083CC4 02004010 */  beqz       $v0, .Llevel_12_80083CD0
/* EFF290 80083CC8 80000224 */   addiu     $v0, $zero, 0x80
/* EFF294 80083CCC 140022A2 */  sb         $v0, 0x14($s1)
.Llevel_12_80083CD0:
/* EFF298 80083CD0 15002292 */  lbu        $v0, 0x15($s1)
/* EFF29C 80083CD4 00000000 */  nop
/* EFF2A0 80083CD8 FAFF4224 */  addiu      $v0, $v0, -0x6
/* EFF2A4 80083CDC 150022A2 */  sb         $v0, 0x15($s1)
/* EFF2A8 80083CE0 FF004230 */  andi       $v0, $v0, 0xFF
/* EFF2AC 80083CE4 2000422C */  sltiu      $v0, $v0, 0x20
/* EFF2B0 80083CE8 D9014010 */  beqz       $v0, .Llevel_12_80084450
/* EFF2B4 80083CEC 20000224 */   addiu     $v0, $zero, 0x20
/* EFF2B8 80083CF0 14110208 */  j          .Llevel_12_80084450
/* EFF2BC 80083CF4 150022A2 */   sb        $v0, 0x15($s1)
.L80083CF8_:
/* EFF2C0 80083CF8 01002292 */  lbu        $v0, 0x1($s1)
/* EFF2C4 80083CFC 00000000 */  nop
/* EFF2C8 80083D00 01004224 */  addiu      $v0, $v0, 0x1
/* EFF2CC 80083D04 010022A2 */  sb         $v0, 0x1($s1)
/* EFF2D0 80083D08 FF004230 */  andi       $v0, $v0, 0xFF
/* EFF2D4 80083D0C 2000422C */  sltiu      $v0, $v0, 0x20
/* EFF2D8 80083D10 CD014010 */  beqz       $v0, .Llevel_12_80084448
/* EFF2DC 80083D14 00000000 */   nop
/* EFF2E0 80083D18 02002292 */  lbu        $v0, 0x2($s1)
/* EFF2E4 80083D1C 00000000 */  nop
/* EFF2E8 80083D20 C9014010 */  beqz       $v0, .Llevel_12_80084448
/* EFF2EC 80083D24 00000000 */   nop
/* EFF2F0 80083D28 09002286 */  lh         $v0, 0x9($s1)
/* EFF2F4 80083D2C 03002386 */  lh         $v1, 0x3($s1)
/* EFF2F8 80083D30 00000000 */  nop
/* EFF2FC 80083D34 23104300 */  subu       $v0, $v0, $v1
/* EFF300 80083D38 3800A2AF */  sw         $v0, 0x38($sp)
/* EFF304 80083D3C 0B002286 */  lh         $v0, 0xB($s1)
/* EFF308 80083D40 05002386 */  lh         $v1, 0x5($s1)
/* EFF30C 80083D44 00000000 */  nop
/* EFF310 80083D48 23104300 */  subu       $v0, $v0, $v1
/* EFF314 80083D4C 3C00A2AF */  sw         $v0, 0x3C($sp)
/* EFF318 80083D50 0D002286 */  lh         $v0, 0xD($s1)
/* EFF31C 80083D54 07002386 */  lh         $v1, 0x7($s1)
/* EFF320 80083D58 00000000 */  nop
/* EFF324 80083D5C 23104300 */  subu       $v0, $v0, $v1
/* EFF328 80083D60 CB89010C */  jal        rand
/* EFF32C 80083D64 4000A2AF */   sw        $v0, 0x40($sp)
/* EFF330 80083D68 3800A38F */  lw         $v1, 0x38($sp)
/* EFF334 80083D6C 02004230 */  andi       $v0, $v0, 0x2
/* EFF338 80083D70 FFFF6324 */  addiu      $v1, $v1, -0x1
/* EFF33C 80083D74 21186200 */  addu       $v1, $v1, $v0
/* EFF340 80083D78 CB89010C */  jal        rand
/* EFF344 80083D7C 3800A3AF */   sw        $v1, 0x38($sp)
/* EFF348 80083D80 3C00A38F */  lw         $v1, 0x3C($sp)
/* EFF34C 80083D84 02004230 */  andi       $v0, $v0, 0x2
/* EFF350 80083D88 FFFF6324 */  addiu      $v1, $v1, -0x1
/* EFF354 80083D8C 21186200 */  addu       $v1, $v1, $v0
/* EFF358 80083D90 CB89010C */  jal        rand
/* EFF35C 80083D94 3C00A3AF */   sw        $v1, 0x3C($sp)
/* EFF360 80083D98 4000A38F */  lw         $v1, 0x40($sp)
/* EFF364 80083D9C 02004230 */  andi       $v0, $v0, 0x2
/* EFF368 80083DA0 FFFF6324 */  addiu      $v1, $v1, -0x1
/* EFF36C 80083DA4 21186200 */  addu       $v1, $v1, $v0
/* EFF370 80083DA8 4000A3AF */  sw         $v1, 0x40($sp)
/* EFF374 80083DAC 3800A38F */  lw         $v1, 0x38($sp)
/* EFF378 80083DB0 09002296 */  lhu        $v0, 0x9($s1)
/* EFF37C 80083DB4 00000000 */  nop
/* EFF380 80083DB8 21104300 */  addu       $v0, $v0, $v1
/* EFF384 80083DBC 090022A6 */  sh         $v0, 0x9($s1)
/* EFF388 80083DC0 3C00A38F */  lw         $v1, 0x3C($sp)
/* EFF38C 80083DC4 0B002296 */  lhu        $v0, 0xB($s1)
/* EFF390 80083DC8 00000000 */  nop
/* EFF394 80083DCC 21104300 */  addu       $v0, $v0, $v1
/* EFF398 80083DD0 0B0022A6 */  sh         $v0, 0xB($s1)
/* EFF39C 80083DD4 4000A38F */  lw         $v1, 0x40($sp)
/* EFF3A0 80083DD8 0D002296 */  lhu        $v0, 0xD($s1)
/* EFF3A4 80083DDC 00000000 */  nop
/* EFF3A8 80083DE0 21104300 */  addu       $v0, $v0, $v1
/* EFF3AC 80083DE4 0D0022A6 */  sh         $v0, 0xD($s1)
/* EFF3B0 80083DE8 3800A38F */  lw         $v1, 0x38($sp)
/* EFF3B4 80083DEC 09002296 */  lhu        $v0, 0x9($s1)
/* EFF3B8 80083DF0 00000000 */  nop
/* EFF3BC 80083DF4 23104300 */  subu       $v0, $v0, $v1
/* EFF3C0 80083DF8 030022A6 */  sh         $v0, 0x3($s1)
/* EFF3C4 80083DFC 3C00A38F */  lw         $v1, 0x3C($sp)
/* EFF3C8 80083E00 0B002296 */  lhu        $v0, 0xB($s1)
/* EFF3CC 80083E04 00000000 */  nop
/* EFF3D0 80083E08 23104300 */  subu       $v0, $v0, $v1
/* EFF3D4 80083E0C 050022A6 */  sh         $v0, 0x5($s1)
/* EFF3D8 80083E10 13002292 */  lbu        $v0, 0x13($s1)
/* EFF3DC 80083E14 4000A48F */  lw         $a0, 0x40($sp)
/* EFF3E0 80083E18 15002392 */  lbu        $v1, 0x15($s1)
/* EFF3E4 80083E1C FEFF4224 */  addiu      $v0, $v0, -0x2
/* EFF3E8 80083E20 130022A2 */  sb         $v0, 0x13($s1)
/* EFF3EC 80083E24 14002292 */  lbu        $v0, 0x14($s1)
/* EFF3F0 80083E28 FCFF6324 */  addiu      $v1, $v1, -0x4
/* EFF3F4 80083E2C 150023A2 */  sb         $v1, 0x15($s1)
/* EFF3F8 80083E30 10002392 */  lbu        $v1, 0x10($s1)
/* EFF3FC 80083E34 FEFF4224 */  addiu      $v0, $v0, -0x2
/* EFF400 80083E38 140022A2 */  sb         $v0, 0x14($s1)
/* EFF404 80083E3C 0F002292 */  lbu        $v0, 0xF($s1)
/* EFF408 80083E40 FDFF6324 */  addiu      $v1, $v1, -0x3
/* EFF40C 80083E44 100023A2 */  sb         $v1, 0x10($s1)
/* EFF410 80083E48 0D002396 */  lhu        $v1, 0xD($s1)
/* EFF414 80083E4C FDFF4224 */  addiu      $v0, $v0, -0x3
/* EFF418 80083E50 0F0022A2 */  sb         $v0, 0xF($s1)
/* EFF41C 80083E54 11002292 */  lbu        $v0, 0x11($s1)
/* EFF420 80083E58 23186400 */  subu       $v1, $v1, $a0
/* EFF424 80083E5C 070023A6 */  sh         $v1, 0x7($s1)
/* EFF428 80083E60 FDFF4224 */  addiu      $v0, $v0, -0x3
/* EFF42C 80083E64 14110208 */  j          .Llevel_12_80084450
/* EFF430 80083E68 110022A2 */   sb        $v0, 0x11($s1)
.L80083E6C_:
/* EFF434 80083E6C 01002292 */  lbu        $v0, 0x1($s1)
/* EFF438 80083E70 00000000 */  nop
/* EFF43C 80083E74 01004224 */  addiu      $v0, $v0, 0x1
/* EFF440 80083E78 010022A2 */  sb         $v0, 0x1($s1)
/* EFF444 80083E7C FF004230 */  andi       $v0, $v0, 0xFF
/* EFF448 80083E80 3000422C */  sltiu      $v0, $v0, 0x30
/* EFF44C 80083E84 70014010 */  beqz       $v0, .Llevel_12_80084448
/* EFF450 80083E88 00000000 */   nop
/* EFF454 80083E8C 02002292 */  lbu        $v0, 0x2($s1)
/* EFF458 80083E90 00000000 */  nop
/* EFF45C 80083E94 6C014010 */  beqz       $v0, .Llevel_12_80084448
/* EFF460 80083E98 00000000 */   nop
/* EFF464 80083E9C 03002286 */  lh         $v0, 0x3($s1)
/* EFF468 80083EA0 09002386 */  lh         $v1, 0x9($s1)
/* EFF46C 80083EA4 00000000 */  nop
/* EFF470 80083EA8 23104300 */  subu       $v0, $v0, $v1
/* EFF474 80083EAC 43100200 */  sra        $v0, $v0, 1
/* EFF478 80083EB0 3000A2AF */  sw         $v0, 0x30($sp)
/* EFF47C 80083EB4 05002286 */  lh         $v0, 0x5($s1)
/* EFF480 80083EB8 0B002386 */  lh         $v1, 0xB($s1)
/* EFF484 80083EBC 00000000 */  nop
/* EFF488 80083EC0 23104300 */  subu       $v0, $v0, $v1
/* EFF48C 80083EC4 43100200 */  sra        $v0, $v0, 1
/* EFF490 80083EC8 3400A2AF */  sw         $v0, 0x34($sp)
/* EFF494 80083ECC 07002286 */  lh         $v0, 0x7($s1)
/* EFF498 80083ED0 0D002386 */  lh         $v1, 0xD($s1)
/* EFF49C 80083ED4 00000000 */  nop
/* EFF4A0 80083ED8 23104300 */  subu       $v0, $v0, $v1
/* EFF4A4 80083EDC 43100200 */  sra        $v0, $v0, 1
/* EFF4A8 80083EE0 CB89010C */  jal        rand
/* EFF4AC 80083EE4 3800A2AF */   sw        $v0, 0x38($sp)
/* EFF4B0 80083EE8 3000A38F */  lw         $v1, 0x30($sp)
/* EFF4B4 80083EEC 04004230 */  andi       $v0, $v0, 0x4
/* EFF4B8 80083EF0 FEFF6324 */  addiu      $v1, $v1, -0x2
/* EFF4BC 80083EF4 21186200 */  addu       $v1, $v1, $v0
/* EFF4C0 80083EF8 CB89010C */  jal        rand
/* EFF4C4 80083EFC 3000A3AF */   sw        $v1, 0x30($sp)
/* EFF4C8 80083F00 3400A38F */  lw         $v1, 0x34($sp)
/* EFF4CC 80083F04 04004230 */  andi       $v0, $v0, 0x4
/* EFF4D0 80083F08 FEFF6324 */  addiu      $v1, $v1, -0x2
/* EFF4D4 80083F0C 21186200 */  addu       $v1, $v1, $v0
/* EFF4D8 80083F10 CB89010C */  jal        rand
/* EFF4DC 80083F14 3400A3AF */   sw        $v1, 0x34($sp)
/* EFF4E0 80083F18 3800A38F */  lw         $v1, 0x38($sp)
/* EFF4E4 80083F1C 02004230 */  andi       $v0, $v0, 0x2
/* EFF4E8 80083F20 FFFF6324 */  addiu      $v1, $v1, -0x1
/* EFF4EC 80083F24 21186200 */  addu       $v1, $v1, $v0
/* EFF4F0 80083F28 3800A3AF */  sw         $v1, 0x38($sp)
/* EFF4F4 80083F2C 3000A38F */  lw         $v1, 0x30($sp)
/* EFF4F8 80083F30 03002296 */  lhu        $v0, 0x3($s1)
/* EFF4FC 80083F34 00000000 */  nop
/* EFF500 80083F38 21104300 */  addu       $v0, $v0, $v1
/* EFF504 80083F3C 030022A6 */  sh         $v0, 0x3($s1)
/* EFF508 80083F40 3400A38F */  lw         $v1, 0x34($sp)
/* EFF50C 80083F44 05002296 */  lhu        $v0, 0x5($s1)
/* EFF510 80083F48 00000000 */  nop
/* EFF514 80083F4C 21104300 */  addu       $v0, $v0, $v1
/* EFF518 80083F50 050022A6 */  sh         $v0, 0x5($s1)
/* EFF51C 80083F54 3800A38F */  lw         $v1, 0x38($sp)
/* EFF520 80083F58 07002296 */  lhu        $v0, 0x7($s1)
/* EFF524 80083F5C 00000000 */  nop
/* EFF528 80083F60 21104300 */  addu       $v0, $v0, $v1
/* EFF52C 80083F64 070022A6 */  sh         $v0, 0x7($s1)
/* EFF530 80083F68 3000A28F */  lw         $v0, 0x30($sp)
/* EFF534 80083F6C 03002396 */  lhu        $v1, 0x3($s1)
/* EFF538 80083F70 40100200 */  sll        $v0, $v0, 1
/* EFF53C 80083F74 23186200 */  subu       $v1, $v1, $v0
/* EFF540 80083F78 090023A6 */  sh         $v1, 0x9($s1)
/* EFF544 80083F7C 3400A28F */  lw         $v0, 0x34($sp)
/* EFF548 80083F80 05002396 */  lhu        $v1, 0x5($s1)
/* EFF54C 80083F84 40100200 */  sll        $v0, $v0, 1
/* EFF550 80083F88 23186200 */  subu       $v1, $v1, $v0
/* EFF554 80083F8C 0B0023A6 */  sh         $v1, 0xB($s1)
/* EFF558 80083F90 3800A28F */  lw         $v0, 0x38($sp)
/* EFF55C 80083F94 07002396 */  lhu        $v1, 0x7($s1)
/* EFF560 80083F98 40100200 */  sll        $v0, $v0, 1
/* EFF564 80083F9C 23186200 */  subu       $v1, $v1, $v0
/* EFF568 80083FA0 14110208 */  j          .Llevel_12_80084450
/* EFF56C 80083FA4 0D0023A6 */   sh        $v1, 0xD($s1)
.L80083FA8_:
/* EFF570 80083FA8 0780023C */  lui        $v0, %hi(g_DeltaTime)
/* EFF574 80083FAC CC56428C */  lw         $v0, %lo(g_DeltaTime)($v0)
/* EFF578 80083FB0 17002392 */  lbu        $v1, 0x17($s1)
/* EFF57C 80083FB4 80100200 */  sll        $v0, $v0, 2
/* EFF580 80083FB8 21186200 */  addu       $v1, $v1, $v0
/* EFF584 80083FBC 170023A2 */  sb         $v1, 0x17($s1)
/* EFF588 80083FC0 0780043C */  lui        $a0, %hi(g_DeltaTime)
/* EFF58C 80083FC4 CC56848C */  lw         $a0, %lo(g_DeltaTime)($a0)
/* EFF590 80083FC8 18002292 */  lbu        $v0, 0x18($s1)
/* EFF594 80083FCC 17002392 */  lbu        $v1, 0x17($s1)
/* EFF598 80083FD0 21104400 */  addu       $v0, $v0, $a0
/* EFF59C 80083FD4 40180300 */  sll        $v1, $v1, 1
/* EFF5A0 80083FD8 180022A2 */  sb         $v0, 0x18($s1)
/* EFF5A4 80083FDC 0780013C */  lui        $at, %hi(D_8006CC78)
/* EFF5A8 80083FE0 21082300 */  addu       $at, $at, $v1
/* EFF5AC 80083FE4 78CC2384 */  lh         $v1, %lo(D_8006CC78)($at)
/* EFF5B0 80083FE8 FF004230 */  andi       $v0, $v0, 0xFF
/* EFF5B4 80083FEC 18006200 */  mult       $v1, $v0
/* EFF5B8 80083FF0 17002392 */  lbu        $v1, 0x17($s1)
/* EFF5BC 80083FF4 0F002296 */  lhu        $v0, 0xF($s1)
/* EFF5C0 80083FF8 40180300 */  sll        $v1, $v1, 1
/* EFF5C4 80083FFC 12380000 */  mflo       $a3
/* EFF5C8 80084000 03230700 */  sra        $a0, $a3, 12
/* EFF5CC 80084004 21104400 */  addu       $v0, $v0, $a0
/* EFF5D0 80084008 030022A6 */  sh         $v0, 0x3($s1)
/* EFF5D4 8008400C 0780013C */  lui        $at, %hi(D_8006CBF8)
/* EFF5D8 80084010 21082300 */  addu       $at, $at, $v1
/* EFF5DC 80084014 F8CB2384 */  lh         $v1, %lo(D_8006CBF8)($at)
/* EFF5E0 80084018 18002292 */  lbu        $v0, 0x18($s1)
/* EFF5E4 8008401C 00000000 */  nop
/* EFF5E8 80084020 18006200 */  mult       $v1, $v0
/* EFF5EC 80084024 0780033C */  lui        $v1, %hi(g_DeltaTime)
/* EFF5F0 80084028 CC56638C */  lw         $v1, %lo(g_DeltaTime)($v1)
/* EFF5F4 8008402C 00000000 */  nop
/* EFF5F8 80084030 40100300 */  sll        $v0, $v1, 1
/* EFF5FC 80084034 21104300 */  addu       $v0, $v0, $v1
/* EFF600 80084038 07002396 */  lhu        $v1, 0x7($s1)
/* EFF604 8008403C 40100200 */  sll        $v0, $v0, 1
/* EFF608 80084040 21186200 */  addu       $v1, $v1, $v0
/* EFF60C 80084044 070023A6 */  sh         $v1, 0x7($s1)
/* EFF610 80084048 18002392 */  lbu        $v1, 0x18($s1)
/* EFF614 8008404C 11002296 */  lhu        $v0, 0x11($s1)
/* EFF618 80084050 100E0208 */  j          .Llevel_12_80083840
/* EFF61C 80084054 C100632C */   sltiu     $v1, $v1, 0xC1
.L80084058_:
/* EFF620 80084058 09002486 */  lh         $a0, 0x9($s1)
/* EFF624 8008405C 03002286 */  lh         $v0, 0x3($s1)
/* EFF628 80084060 00000000 */  nop
/* EFF62C 80084064 23208200 */  subu       $a0, $a0, $v0
/* EFF630 80084068 43200400 */  sra        $a0, $a0, 1
/* EFF634 8008406C 3000A4A7 */  sh         $a0, 0x30($sp)
/* EFF638 80084070 0B002286 */  lh         $v0, 0xB($s1)
/* EFF63C 80084074 05002386 */  lh         $v1, 0x5($s1)
/* EFF640 80084078 00000000 */  nop
/* EFF644 8008407C 23104300 */  subu       $v0, $v0, $v1
/* EFF648 80084080 43100200 */  sra        $v0, $v0, 1
/* EFF64C 80084084 3200A2A7 */  sh         $v0, 0x32($sp)
/* EFF650 80084088 0D002286 */  lh         $v0, 0xD($s1)
/* EFF654 8008408C 07002386 */  lh         $v1, 0x7($s1)
/* EFF658 80084090 00000000 */  nop
/* EFF65C 80084094 23104300 */  subu       $v0, $v0, $v1
/* EFF660 80084098 43100200 */  sra        $v0, $v0, 1
/* EFF664 8008409C 3400A2A7 */  sh         $v0, 0x34($sp)
/* EFF668 800840A0 03002296 */  lhu        $v0, 0x3($s1)
/* EFF66C 800840A4 00000000 */  nop
/* EFF670 800840A8 21104400 */  addu       $v0, $v0, $a0
/* EFF674 800840AC 030022A6 */  sh         $v0, 0x3($s1)
/* EFF678 800840B0 05002296 */  lhu        $v0, 0x5($s1)
/* EFF67C 800840B4 3200A397 */  lhu        $v1, 0x32($sp)
/* EFF680 800840B8 00000000 */  nop
/* EFF684 800840BC 21104300 */  addu       $v0, $v0, $v1
/* EFF688 800840C0 050022A6 */  sh         $v0, 0x5($s1)
/* EFF68C 800840C4 07002296 */  lhu        $v0, 0x7($s1)
/* EFF690 800840C8 3400A397 */  lhu        $v1, 0x34($sp)
/* EFF694 800840CC 00000000 */  nop
/* EFF698 800840D0 21104300 */  addu       $v0, $v0, $v1
/* EFF69C 800840D4 070022A6 */  sh         $v0, 0x7($s1)
/* EFF6A0 800840D8 3200A297 */  lhu        $v0, 0x32($sp)
/* EFF6A4 800840DC 3000A397 */  lhu        $v1, 0x30($sp)
/* EFF6A8 800840E0 01004224 */  addiu      $v0, $v0, 0x1
/* EFF6AC 800840E4 3200A2A7 */  sh         $v0, 0x32($sp)
/* EFF6B0 800840E8 09002296 */  lhu        $v0, 0x9($s1)
/* EFF6B4 800840EC 00000000 */  nop
/* EFF6B8 800840F0 21104300 */  addu       $v0, $v0, $v1
/* EFF6BC 800840F4 090022A6 */  sh         $v0, 0x9($s1)
/* EFF6C0 800840F8 0B002296 */  lhu        $v0, 0xB($s1)
/* EFF6C4 800840FC 3200A397 */  lhu        $v1, 0x32($sp)
/* EFF6C8 80084100 00000000 */  nop
/* EFF6CC 80084104 21104300 */  addu       $v0, $v0, $v1
/* EFF6D0 80084108 0D002396 */  lhu        $v1, 0xD($s1)
/* EFF6D4 8008410C 0B0022A6 */  sh         $v0, 0xB($s1)
/* EFF6D8 80084110 01002292 */  lbu        $v0, 0x1($s1)
/* EFF6DC 80084114 3400A497 */  lhu        $a0, 0x34($sp)
/* EFF6E0 80084118 01004224 */  addiu      $v0, $v0, 0x1
/* EFF6E4 8008411C 21186400 */  addu       $v1, $v1, $a0
/* EFF6E8 80084120 010022A2 */  sb         $v0, 0x1($s1)
/* EFF6EC 80084124 FF004230 */  andi       $v0, $v0, 0xFF
/* EFF6F0 80084128 2000422C */  sltiu      $v0, $v0, 0x20
/* EFF6F4 8008412C C8004014 */  bnez       $v0, .Llevel_12_80084450
/* EFF6F8 80084130 0D0023A6 */   sh        $v1, 0xD($s1)
/* EFF6FC 80084134 12110208 */  j          .Llevel_12_80084448
/* EFF700 80084138 00000000 */   nop
.L8008413C_:
/* EFF704 8008413C 01002292 */  lbu        $v0, 0x1($s1)
/* EFF708 80084140 00000000 */  nop
/* EFF70C 80084144 01004224 */  addiu      $v0, $v0, 0x1
/* EFF710 80084148 010022A2 */  sb         $v0, 0x1($s1)
/* EFF714 8008414C FF004230 */  andi       $v0, $v0, 0xFF
/* EFF718 80084150 2800422C */  sltiu      $v0, $v0, 0x28
/* EFF71C 80084154 BC004010 */  beqz       $v0, .Llevel_12_80084448
/* EFF720 80084158 00000000 */   nop
/* EFF724 8008415C 02002292 */  lbu        $v0, 0x2($s1)
/* EFF728 80084160 00000000 */  nop
/* EFF72C 80084164 B8004010 */  beqz       $v0, .Llevel_12_80084448
/* EFF730 80084168 00000000 */   nop
/* EFF734 8008416C 03002296 */  lhu        $v0, 0x3($s1)
/* EFF738 80084170 0F002396 */  lhu        $v1, 0xF($s1)
/* EFF73C 80084174 11002496 */  lhu        $a0, 0x11($s1)
/* EFF740 80084178 13002596 */  lhu        $a1, 0x13($s1)
/* EFF744 8008417C 21104300 */  addu       $v0, $v0, $v1
/* EFF748 80084180 030022A6 */  sh         $v0, 0x3($s1)
/* EFF74C 80084184 05002296 */  lhu        $v0, 0x5($s1)
/* EFF750 80084188 07002396 */  lhu        $v1, 0x7($s1)
/* EFF754 8008418C 21104400 */  addu       $v0, $v0, $a0
/* EFF758 80084190 21186500 */  addu       $v1, $v1, $a1
/* EFF75C 80084194 050022A6 */  sh         $v0, 0x5($s1)
/* EFF760 80084198 CB89010C */  jal        rand
/* EFF764 8008419C 070023A6 */   sh        $v1, 0x7($s1)
/* EFF768 800841A0 0F002396 */  lhu        $v1, 0xF($s1)
/* EFF76C 800841A4 02004230 */  andi       $v0, $v0, 0x2
/* EFF770 800841A8 FFFF6324 */  addiu      $v1, $v1, -0x1
/* EFF774 800841AC 21186200 */  addu       $v1, $v1, $v0
/* EFF778 800841B0 CB89010C */  jal        rand
/* EFF77C 800841B4 0F0023A6 */   sh        $v1, 0xF($s1)
/* EFF780 800841B8 11002396 */  lhu        $v1, 0x11($s1)
/* EFF784 800841BC 02004230 */  andi       $v0, $v0, 0x2
/* EFF788 800841C0 FFFF6324 */  addiu      $v1, $v1, -0x1
/* EFF78C 800841C4 21186200 */  addu       $v1, $v1, $v0
/* EFF790 800841C8 CB89010C */  jal        rand
/* EFF794 800841CC 110023A6 */   sh        $v1, 0x11($s1)
/* EFF798 800841D0 13002396 */  lhu        $v1, 0x13($s1)
/* EFF79C 800841D4 02004230 */  andi       $v0, $v0, 0x2
/* EFF7A0 800841D8 FFFF6324 */  addiu      $v1, $v1, -0x1
/* EFF7A4 800841DC 21186200 */  addu       $v1, $v1, $v0
/* EFF7A8 800841E0 130023A6 */  sh         $v1, 0x13($s1)
/* EFF7AC 800841E4 001C0300 */  sll        $v1, $v1, 16
/* EFF7B0 800841E8 031C0300 */  sra        $v1, $v1, 16
/* EFF7B4 800841EC 03006328 */  slti       $v1, $v1, 0x3
/* EFF7B8 800841F0 02006014 */  bnez       $v1, .Llevel_12_800841FC
/* EFF7BC 800841F4 02000224 */   addiu     $v0, $zero, 0x2
/* EFF7C0 800841F8 130022A6 */  sh         $v0, 0x13($s1)
.Llevel_12_800841FC:
/* EFF7C4 800841FC 13002286 */  lh         $v0, 0x13($s1)
/* EFF7C8 80084200 00000000 */  nop
/* EFF7CC 80084204 FCFF4228 */  slti       $v0, $v0, -0x4
/* EFF7D0 80084208 02004010 */  beqz       $v0, .Llevel_12_80084214
/* EFF7D4 8008420C FCFF0224 */   addiu     $v0, $zero, -0x4
/* EFF7D8 80084210 130022A6 */  sh         $v0, 0x13($s1)
.Llevel_12_80084214:
/* EFF7DC 80084214 0B002292 */  lbu        $v0, 0xB($s1)
/* EFF7E0 80084218 0D002392 */  lbu        $v1, 0xD($s1)
/* EFF7E4 8008421C FEFF4224 */  addiu      $v0, $v0, -0x2
/* EFF7E8 80084220 0B0022A2 */  sb         $v0, 0xB($s1)
/* EFF7EC 80084224 0C002292 */  lbu        $v0, 0xC($s1)
/* EFF7F0 80084228 FFFF6324 */  addiu      $v1, $v1, -0x1
/* EFF7F4 8008422C 0D0023A2 */  sb         $v1, 0xD($s1)
/* EFF7F8 80084230 FEFF4224 */  addiu      $v0, $v0, -0x2
/* EFF7FC 80084234 14110208 */  j          .Llevel_12_80084450
/* EFF800 80084238 0C0022A2 */   sb        $v0, 0xC($s1)
.L8008423C_:
/* EFF804 8008423C 09002486 */  lh         $a0, 0x9($s1)
/* EFF808 80084240 03002286 */  lh         $v0, 0x3($s1)
/* EFF80C 80084244 00000000 */  nop
/* EFF810 80084248 23208200 */  subu       $a0, $a0, $v0
/* EFF814 8008424C 43200400 */  sra        $a0, $a0, 1
/* EFF818 80084250 3000A4A7 */  sh         $a0, 0x30($sp)
/* EFF81C 80084254 0B002286 */  lh         $v0, 0xB($s1)
/* EFF820 80084258 05002386 */  lh         $v1, 0x5($s1)
/* EFF824 8008425C 00000000 */  nop
/* EFF828 80084260 23104300 */  subu       $v0, $v0, $v1
/* EFF82C 80084264 43100200 */  sra        $v0, $v0, 1
/* EFF830 80084268 3200A2A7 */  sh         $v0, 0x32($sp)
/* EFF834 8008426C 0D002286 */  lh         $v0, 0xD($s1)
/* EFF838 80084270 07002386 */  lh         $v1, 0x7($s1)
/* EFF83C 80084274 00000000 */  nop
/* EFF840 80084278 23104300 */  subu       $v0, $v0, $v1
/* EFF844 8008427C 43100200 */  sra        $v0, $v0, 1
/* EFF848 80084280 3400A2A7 */  sh         $v0, 0x34($sp)
/* EFF84C 80084284 03002296 */  lhu        $v0, 0x3($s1)
/* EFF850 80084288 00000000 */  nop
/* EFF854 8008428C 21104400 */  addu       $v0, $v0, $a0
/* EFF858 80084290 030022A6 */  sh         $v0, 0x3($s1)
/* EFF85C 80084294 05002296 */  lhu        $v0, 0x5($s1)
/* EFF860 80084298 3200A397 */  lhu        $v1, 0x32($sp)
/* EFF864 8008429C 00000000 */  nop
/* EFF868 800842A0 21104300 */  addu       $v0, $v0, $v1
/* EFF86C 800842A4 050022A6 */  sh         $v0, 0x5($s1)
/* EFF870 800842A8 07002296 */  lhu        $v0, 0x7($s1)
/* EFF874 800842AC 3400A397 */  lhu        $v1, 0x34($sp)
/* EFF878 800842B0 00000000 */  nop
/* EFF87C 800842B4 21104300 */  addu       $v0, $v0, $v1
/* EFF880 800842B8 070022A6 */  sh         $v0, 0x7($s1)
/* EFF884 800842BC 09002296 */  lhu        $v0, 0x9($s1)
/* EFF888 800842C0 3000A397 */  lhu        $v1, 0x30($sp)
/* EFF88C 800842C4 00000000 */  nop
/* EFF890 800842C8 21104300 */  addu       $v0, $v0, $v1
/* EFF894 800842CC 090022A6 */  sh         $v0, 0x9($s1)
/* EFF898 800842D0 0B002296 */  lhu        $v0, 0xB($s1)
/* EFF89C 800842D4 3200A397 */  lhu        $v1, 0x32($sp)
/* EFF8A0 800842D8 00000000 */  nop
/* EFF8A4 800842DC 21104300 */  addu       $v0, $v0, $v1
/* EFF8A8 800842E0 0D002396 */  lhu        $v1, 0xD($s1)
/* EFF8AC 800842E4 0B0022A6 */  sh         $v0, 0xB($s1)
/* EFF8B0 800842E8 01002292 */  lbu        $v0, 0x1($s1)
/* EFF8B4 800842EC 3400A497 */  lhu        $a0, 0x34($sp)
/* EFF8B8 800842F0 01004224 */  addiu      $v0, $v0, 0x1
/* EFF8BC 800842F4 21186400 */  addu       $v1, $v1, $a0
/* EFF8C0 800842F8 010022A2 */  sb         $v0, 0x1($s1)
/* EFF8C4 800842FC FF004230 */  andi       $v0, $v0, 0xFF
/* EFF8C8 80084300 1800422C */  sltiu      $v0, $v0, 0x18
/* EFF8CC 80084304 50004010 */  beqz       $v0, .Llevel_12_80084448
/* EFF8D0 80084308 0D0023A6 */   sh        $v1, 0xD($s1)
/* EFF8D4 8008430C 02002292 */  lbu        $v0, 0x2($s1)
/* EFF8D8 80084310 00000000 */  nop
/* EFF8DC 80084314 4C004010 */  beqz       $v0, .Llevel_12_80084448
/* EFF8E0 80084318 00000000 */   nop
/* EFF8E4 8008431C 0F002292 */  lbu        $v0, 0xF($s1)
/* EFF8E8 80084320 13002392 */  lbu        $v1, 0x13($s1)
/* EFF8EC 80084324 FDFF4224 */  addiu      $v0, $v0, -0x3
/* EFF8F0 80084328 0F0022A2 */  sb         $v0, 0xF($s1)
/* EFF8F4 8008432C 10002292 */  lbu        $v0, 0x10($s1)
/* EFF8F8 80084330 FDFF6324 */  addiu      $v1, $v1, -0x3
/* EFF8FC 80084334 130023A2 */  sb         $v1, 0x13($s1)
/* EFF900 80084338 FCFF4224 */  addiu      $v0, $v0, -0x4
/* EFF904 8008433C 100022A2 */  sb         $v0, 0x10($s1)
/* EFF908 80084340 14002292 */  lbu        $v0, 0x14($s1)
/* EFF90C 80084344 15002392 */  lbu        $v1, 0x15($s1)
/* EFF910 80084348 FCFF4224 */  addiu      $v0, $v0, -0x4
/* EFF914 8008434C 140022A2 */  sb         $v0, 0x14($s1)
/* EFF918 80084350 0600622C */  sltiu      $v0, $v1, 0x6
/* EFF91C 80084354 3E004014 */  bnez       $v0, .Llevel_12_80084450
/* EFF920 80084358 FAFF6224 */   addiu     $v0, $v1, -0x6
/* EFF924 8008435C 14110208 */  j          .Llevel_12_80084450
/* EFF928 80084360 150022A2 */   sb        $v0, 0x15($s1)
.L80084364_:
/* EFF92C 80084364 09002496 */  lhu        $a0, 0x9($s1)
/* EFF930 80084368 03002296 */  lhu        $v0, 0x3($s1)
/* EFF934 8008436C 00000000 */  nop
/* EFF938 80084370 23208200 */  subu       $a0, $a0, $v0
/* EFF93C 80084374 3000A4A7 */  sh         $a0, 0x30($sp)
/* EFF940 80084378 0B002296 */  lhu        $v0, 0xB($s1)
/* EFF944 8008437C 05002396 */  lhu        $v1, 0x5($s1)
/* EFF948 80084380 00000000 */  nop
/* EFF94C 80084384 23104300 */  subu       $v0, $v0, $v1
/* EFF950 80084388 3200A2A7 */  sh         $v0, 0x32($sp)
/* EFF954 8008438C 0D002296 */  lhu        $v0, 0xD($s1)
/* EFF958 80084390 07002396 */  lhu        $v1, 0x7($s1)
/* EFF95C 80084394 00000000 */  nop
/* EFF960 80084398 23104300 */  subu       $v0, $v0, $v1
/* EFF964 8008439C 3400A2A7 */  sh         $v0, 0x34($sp)
/* EFF968 800843A0 03002296 */  lhu        $v0, 0x3($s1)
/* EFF96C 800843A4 00000000 */  nop
/* EFF970 800843A8 21104400 */  addu       $v0, $v0, $a0
/* EFF974 800843AC 030022A6 */  sh         $v0, 0x3($s1)
/* EFF978 800843B0 05002296 */  lhu        $v0, 0x5($s1)
/* EFF97C 800843B4 3200A397 */  lhu        $v1, 0x32($sp)
/* EFF980 800843B8 00000000 */  nop
/* EFF984 800843BC 21104300 */  addu       $v0, $v0, $v1
/* EFF988 800843C0 050022A6 */  sh         $v0, 0x5($s1)
/* EFF98C 800843C4 07002296 */  lhu        $v0, 0x7($s1)
/* EFF990 800843C8 3400A397 */  lhu        $v1, 0x34($sp)
/* EFF994 800843CC 00000000 */  nop
/* EFF998 800843D0 21104300 */  addu       $v0, $v0, $v1
/* EFF99C 800843D4 070022A6 */  sh         $v0, 0x7($s1)
/* EFF9A0 800843D8 3400A297 */  lhu        $v0, 0x34($sp)
/* EFF9A4 800843DC 3000A397 */  lhu        $v1, 0x30($sp)
/* EFF9A8 800843E0 FFFF4224 */  addiu      $v0, $v0, -0x1
/* EFF9AC 800843E4 3400A2A7 */  sh         $v0, 0x34($sp)
/* EFF9B0 800843E8 09002296 */  lhu        $v0, 0x9($s1)
/* EFF9B4 800843EC 00000000 */  nop
/* EFF9B8 800843F0 21104300 */  addu       $v0, $v0, $v1
/* EFF9BC 800843F4 090022A6 */  sh         $v0, 0x9($s1)
/* EFF9C0 800843F8 0B002296 */  lhu        $v0, 0xB($s1)
/* EFF9C4 800843FC 3200A397 */  lhu        $v1, 0x32($sp)
/* EFF9C8 80084400 00000000 */  nop
/* EFF9CC 80084404 21104300 */  addu       $v0, $v0, $v1
/* EFF9D0 80084408 0D002396 */  lhu        $v1, 0xD($s1)
/* EFF9D4 8008440C 0B0022A6 */  sh         $v0, 0xB($s1)
/* EFF9D8 80084410 01002292 */  lbu        $v0, 0x1($s1)
/* EFF9DC 80084414 3400A497 */  lhu        $a0, 0x34($sp)
/* EFF9E0 80084418 01004224 */  addiu      $v0, $v0, 0x1
/* EFF9E4 8008441C 21186400 */  addu       $v1, $v1, $a0
/* EFF9E8 80084420 010022A2 */  sb         $v0, 0x1($s1)
/* EFF9EC 80084424 FF004230 */  andi       $v0, $v0, 0xFF
/* EFF9F0 80084428 2000422C */  sltiu      $v0, $v0, 0x20
/* EFF9F4 8008442C 0D0023A6 */  sh         $v1, 0xD($s1)
.Llevel_12_80084430:
/* EFF9F8 80084430 05004010 */  beqz       $v0, .Llevel_12_80084448
/* EFF9FC 80084434 00000000 */   nop
.Llevel_12_80084438:
/* EFFA00 80084438 02002292 */  lbu        $v0, 0x2($s1)
/* EFFA04 8008443C 00000000 */  nop
/* EFFA08 80084440 03004014 */  bnez       $v0, .Llevel_12_80084450
/* EFFA0C 80084444 00000000 */   nop
.Llevel_12_80084448:
/* EFFA10 80084448 824D010C */  jal        func_80053608
/* EFFA14 8008444C 21208002 */   addu      $a0, $s4, $zero
.Llevel_12_80084450:
/* EFFA18 80084450 20003126 */  addiu      $s1, $s1, 0x20
/* EFFA1C 80084454 2000DE27 */  addiu      $fp, $fp, 0x20
/* EFFA20 80084458 2000B526 */  addiu      $s5, $s5, 0x20
/* EFFA24 8008445C 00002392 */  lbu        $v1, 0x0($s1)
/* EFFA28 80084460 FF000224 */  addiu      $v0, $zero, 0xFF
/* EFFA2C 80084464 98FB6214 */  bne        $v1, $v0, .Llevel_12_800832C8
/* EFFA30 80084468 20009426 */   addiu     $s4, $s4, 0x20
.Llevel_12_8008446C:
/* EFFA34 8008446C 7400BF8F */  lw         $ra, 0x74($sp)
/* EFFA38 80084470 7000BE8F */  lw         $fp, 0x70($sp)
/* EFFA3C 80084474 6C00B78F */  lw         $s7, 0x6C($sp)
/* EFFA40 80084478 6800B68F */  lw         $s6, 0x68($sp)
/* EFFA44 8008447C 6400B58F */  lw         $s5, 0x64($sp)
/* EFFA48 80084480 6000B48F */  lw         $s4, 0x60($sp)
/* EFFA4C 80084484 5C00B38F */  lw         $s3, 0x5C($sp)
/* EFFA50 80084488 5800B28F */  lw         $s2, 0x58($sp)
/* EFFA54 8008448C 5400B18F */  lw         $s1, 0x54($sp)
/* EFFA58 80084490 5000B08F */  lw         $s0, 0x50($sp)
/* EFFA5C 80084494 7800BD27 */  addiu      $sp, $sp, 0x78
/* EFFA60 80084498 0800E003 */  jr         $ra
/* EFFA64 8008449C 00000000 */   nop
.size func_level_12_80083274, . - func_level_12_80083274
