.set noat      /* allow manual use of $at */
.set noreorder /* don't insert nops after branches */

.section .rodata.jtbl
.align 3
dlabel jtbl_level_20_8007B5CC
/* 187EB94 8007B5CC A8AE0880 */ .word .L8008AEA8_
/* 187EB98 8007B5D0 30AF0880 */ .word .L8008AF30_
/* 187EB9C 8007B5D4 B8AF0880 */ .word .L8008AFB8_
/* 187EBA0 8007B5D8 A4BF0880 */ .word .Llevel_20_8008BFA4
/* 187EBA4 8007B5DC A4BF0880 */ .word .Llevel_20_8008BFA4
/* 187EBA8 8007B5E0 A4BF0880 */ .word .Llevel_20_8008BFA4
/* 187EBAC 8007B5E4 A4BF0880 */ .word .Llevel_20_8008BFA4
/* 187EBB0 8007B5E8 A4BF0880 */ .word .Llevel_20_8008BFA4
/* 187EBB4 8007B5EC A4BF0880 */ .word .Llevel_20_8008BFA4
/* 187EBB8 8007B5F0 40B00880 */ .word .L8008B040_
/* 187EBBC 8007B5F4 A4B00880 */ .word .L8008B0A4_
/* 187EBC0 8007B5F8 ACB10880 */ .word .L8008B1AC_
/* 187EBC4 8007B5FC F0B10880 */ .word .L8008B1F0_
/* 187EBC8 8007B600 64B20880 */ .word .L8008B264_
/* 187EBCC 8007B604 A4BF0880 */ .word .Llevel_20_8008BFA4
/* 187EBD0 8007B608 A4BF0880 */ .word .Llevel_20_8008BFA4
/* 187EBD4 8007B60C A4BF0880 */ .word .Llevel_20_8008BFA4
/* 187EBD8 8007B610 A4BF0880 */ .word .Llevel_20_8008BFA4
/* 187EBDC 8007B614 A4BF0880 */ .word .Llevel_20_8008BFA4
/* 187EBE0 8007B618 A4BF0880 */ .word .Llevel_20_8008BFA4
/* 187EBE4 8007B61C A4BF0880 */ .word .Llevel_20_8008BFA4
/* 187EBE8 8007B620 A4BF0880 */ .word .Llevel_20_8008BFA4
/* 187EBEC 8007B624 A4BF0880 */ .word .Llevel_20_8008BFA4
/* 187EBF0 8007B628 94B30880 */ .word .L8008B394_
/* 187EBF4 8007B62C FCB30880 */ .word .L8008B3FC_
/* 187EBF8 8007B630 A4BF0880 */ .word .Llevel_20_8008BFA4
/* 187EBFC 8007B634 A4BF0880 */ .word .Llevel_20_8008BFA4
/* 187EC00 8007B638 A4BF0880 */ .word .Llevel_20_8008BFA4
/* 187EC04 8007B63C A4BF0880 */ .word .Llevel_20_8008BFA4
/* 187EC08 8007B640 A4BF0880 */ .word .Llevel_20_8008BFA4
/* 187EC0C 8007B644 A4BF0880 */ .word .Llevel_20_8008BFA4
/* 187EC10 8007B648 A4BF0880 */ .word .Llevel_20_8008BFA4
/* 187EC14 8007B64C A4BF0880 */ .word .Llevel_20_8008BFA4
/* 187EC18 8007B650 34B50880 */ .word .L8008B534_
/* 187EC1C 8007B654 A4BF0880 */ .word .Llevel_20_8008BFA4
/* 187EC20 8007B658 A4BF0880 */ .word .Llevel_20_8008BFA4
/* 187EC24 8007B65C A4BF0880 */ .word .Llevel_20_8008BFA4
/* 187EC28 8007B660 A4BF0880 */ .word .Llevel_20_8008BFA4
/* 187EC2C 8007B664 A4BF0880 */ .word .Llevel_20_8008BFA4
/* 187EC30 8007B668 A4BF0880 */ .word .Llevel_20_8008BFA4
/* 187EC34 8007B66C A4BF0880 */ .word .Llevel_20_8008BFA4
/* 187EC38 8007B670 A4BF0880 */ .word .Llevel_20_8008BFA4
/* 187EC3C 8007B674 A4BF0880 */ .word .Llevel_20_8008BFA4
/* 187EC40 8007B678 A4BF0880 */ .word .Llevel_20_8008BFA4
/* 187EC44 8007B67C A4BF0880 */ .word .Llevel_20_8008BFA4
/* 187EC48 8007B680 A4BF0880 */ .word .Llevel_20_8008BFA4
/* 187EC4C 8007B684 A4BF0880 */ .word .Llevel_20_8008BFA4
/* 187EC50 8007B688 A4BF0880 */ .word .Llevel_20_8008BFA4
/* 187EC54 8007B68C A4BF0880 */ .word .Llevel_20_8008BFA4
/* 187EC58 8007B690 A4BF0880 */ .word .Llevel_20_8008BFA4
/* 187EC5C 8007B694 A4BF0880 */ .word .Llevel_20_8008BFA4
/* 187EC60 8007B698 A4BF0880 */ .word .Llevel_20_8008BFA4
/* 187EC64 8007B69C A4BF0880 */ .word .Llevel_20_8008BFA4
/* 187EC68 8007B6A0 A4BF0880 */ .word .Llevel_20_8008BFA4
/* 187EC6C 8007B6A4 A4BF0880 */ .word .Llevel_20_8008BFA4
/* 187EC70 8007B6A8 A4BF0880 */ .word .Llevel_20_8008BFA4
/* 187EC74 8007B6AC A4BF0880 */ .word .Llevel_20_8008BFA4
/* 187EC78 8007B6B0 A4BF0880 */ .word .Llevel_20_8008BFA4
/* 187EC7C 8007B6B4 A4BF0880 */ .word .Llevel_20_8008BFA4
/* 187EC80 8007B6B8 A4BF0880 */ .word .Llevel_20_8008BFA4
/* 187EC84 8007B6BC A4BF0880 */ .word .Llevel_20_8008BFA4
/* 187EC88 8007B6C0 A4BF0880 */ .word .Llevel_20_8008BFA4
/* 187EC8C 8007B6C4 A4BF0880 */ .word .Llevel_20_8008BFA4
/* 187EC90 8007B6C8 A4BF0880 */ .word .Llevel_20_8008BFA4
/* 187EC94 8007B6CC A4BF0880 */ .word .Llevel_20_8008BFA4
/* 187EC98 8007B6D0 A4BF0880 */ .word .Llevel_20_8008BFA4
/* 187EC9C 8007B6D4 DCB50880 */ .word .L8008B5DC_
/* 187ECA0 8007B6D8 A4BF0880 */ .word .Llevel_20_8008BFA4
/* 187ECA4 8007B6DC A4BF0880 */ .word .Llevel_20_8008BFA4
/* 187ECA8 8007B6E0 A4BF0880 */ .word .Llevel_20_8008BFA4
/* 187ECAC 8007B6E4 A8B60880 */ .word .L8008B6A8_
/* 187ECB0 8007B6E8 94B80880 */ .word .L8008B894_
/* 187ECB4 8007B6EC 08BA0880 */ .word .L8008BA08_
/* 187ECB8 8007B6F0 A4BF0880 */ .word .Llevel_20_8008BFA4
/* 187ECBC 8007B6F4 44BB0880 */ .word .L8008BB44_
/* 187ECC0 8007B6F8 A4BF0880 */ .word .Llevel_20_8008BFA4
/* 187ECC4 8007B6FC A4BF0880 */ .word .Llevel_20_8008BFA4
/* 187ECC8 8007B700 ACBB0880 */ .word .L8008BBAC_
/* 187ECCC 8007B704 90BC0880 */ .word .L8008BC90_
/* 187ECD0 8007B708 90BD0880 */ .word .L8008BD90_
/* 187ECD4 8007B70C B8BE0880 */ .word .L8008BEB8_
.size jtbl_level_20_8007B5CC, . - jtbl_level_20_8007B5CC


.section .text
/* Generated by spimdisasm 1.27.0 */

glabel func_level_20_8008AE28
/* 188E3F0 8008AE28 98FFBD27 */  addiu      $sp, $sp, -0x68
/* 188E3F4 8008AE2C 4800B2AF */  sw         $s2, 0x48($sp)
/* 188E3F8 8008AE30 0780123C */  lui        $s2, %hi(D_80075824)
/* 188E3FC 8008AE34 2458528E */  lw         $s2, %lo(D_80075824)($s2)
/* 188E400 8008AE38 5000B4AF */  sw         $s4, 0x50($sp)
/* 188E404 8008AE3C 6000BFAF */  sw         $ra, 0x60($sp)
/* 188E408 8008AE40 5C00B7AF */  sw         $s7, 0x5C($sp)
/* 188E40C 8008AE44 5800B6AF */  sw         $s6, 0x58($sp)
/* 188E410 8008AE48 5400B5AF */  sw         $s5, 0x54($sp)
/* 188E414 8008AE4C 4C00B3AF */  sw         $s3, 0x4C($sp)
/* 188E418 8008AE50 4400B1AF */  sw         $s1, 0x44($sp)
/* 188E41C 8008AE54 4000B0AF */  sw         $s0, 0x40($sp)
/* 188E420 8008AE58 01004392 */  lbu        $v1, 0x1($s2)
/* 188E424 8008AE5C FF000224 */  addiu      $v0, $zero, 0xFF
/* 188E428 8008AE60 57046210 */  beq        $v1, $v0, .Llevel_20_8008BFC0
/* 188E42C 8008AE64 21A08000 */   addu      $s4, $a0, $zero
/* 188E430 8008AE68 40B81400 */  sll        $s7, $s4, 1
/* 188E434 8008AE6C 80A81400 */  sll        $s5, $s4, 2
/* 188E438 8008AE70 01005026 */  addiu      $s0, $s2, 0x1
/* 188E43C 8008AE74 18005626 */  addiu      $s6, $s2, 0x18
/* 188E440 8008AE78 04005326 */  addiu      $s3, $s2, 0x4
.Llevel_20_8008AE7C:
/* 188E444 8008AE7C 00004392 */  lbu        $v1, 0x0($s2)
/* 188E448 8008AE80 00000000 */  nop
/* 188E44C 8008AE84 5100622C */  sltiu      $v0, $v1, 0x51
/* 188E450 8008AE88 46044010 */  beqz       $v0, .Llevel_20_8008BFA4
/* 188E454 8008AE8C 80100300 */   sll       $v0, $v1, 2
/* 188E458 8008AE90 0880013C */  lui        $at, %hi(jtbl_level_20_8007B5CC)
/* 188E45C 8008AE94 21082200 */  addu       $at, $at, $v0
/* 188E460 8008AE98 CCB5228C */  lw         $v0, %lo(jtbl_level_20_8007B5CC)($at)
/* 188E464 8008AE9C 00000000 */  nop
/* 188E468 8008AEA0 08004000 */  jr         $v0
/* 188E46C 8008AEA4 00000000 */   nop
.L8008AEA8_:
/* 188E470 8008AEA8 21206002 */  addu       $a0, $s3, $zero
/* 188E474 8008AEAC 21286002 */  addu       $a1, $s3, $zero
/* 188E478 8008AEB0 215F000C */  jal        func_80017C84
/* 188E47C 8008AEB4 2130C002 */   addu      $a2, $s6, $zero
/* 188E480 8008AEB8 1D000286 */  lh         $v0, 0x1D($s0)
/* 188E484 8008AEBC 00000000 */  nop
/* 188E488 8008AEC0 06004010 */  beqz       $v0, .Llevel_20_8008AEDC
/* 188E48C 8008AEC4 01000224 */   addiu     $v0, $zero, 0x1
/* 188E490 8008AEC8 1B000296 */  lhu        $v0, 0x1B($s0)
/* 188E494 8008AECC 00000000 */  nop
/* 188E498 8008AED0 01004224 */  addiu      $v0, $v0, 0x1
/* 188E49C 8008AED4 1B0002A6 */  sh         $v0, 0x1B($s0)
/* 188E4A0 8008AED8 01000224 */  addiu      $v0, $zero, 0x1
.Llevel_20_8008AEDC:
/* 188E4A4 8008AEDC 09000392 */  lbu        $v1, 0x9($s0)
/* 188E4A8 8008AEE0 1D000496 */  lhu        $a0, 0x1D($s0)
/* 188E4AC 8008AEE4 21187700 */  addu       $v1, $v1, $s7
/* 188E4B0 8008AEE8 090003A2 */  sb         $v1, 0x9($s0)
/* 188E4B4 8008AEEC 0C000392 */  lbu        $v1, 0xC($s0)
/* 188E4B8 8008AEF0 23104400 */  subu       $v0, $v0, $a0
/* 188E4BC 8008AEF4 1D0002A6 */  sh         $v0, 0x1D($s0)
/* 188E4C0 8008AEF8 0B000292 */  lbu        $v0, 0xB($s0)
/* 188E4C4 8008AEFC 23187500 */  subu       $v1, $v1, $s5
/* 188E4C8 8008AF00 0C0003A2 */  sb         $v1, 0xC($s0)
/* 188E4CC 8008AF04 0D000392 */  lbu        $v1, 0xD($s0)
/* 188E4D0 8008AF08 23105500 */  subu       $v0, $v0, $s5
/* 188E4D4 8008AF0C 0B0002A2 */  sb         $v0, 0xB($s0)
/* 188E4D8 8008AF10 01000292 */  lbu        $v0, 0x1($s0)
/* 188E4DC 8008AF14 23187500 */  subu       $v1, $v1, $s5
/* 188E4E0 8008AF18 21105400 */  addu       $v0, $v0, $s4
/* 188E4E4 8008AF1C 010002A2 */  sb         $v0, 0x1($s0)
/* 188E4E8 8008AF20 FF004230 */  andi       $v0, $v0, 0xFF
/* 188E4EC 8008AF24 2000422C */  sltiu      $v0, $v0, 0x20
/* 188E4F0 8008AF28 E12F0208 */  j          .Llevel_20_8008BF84
/* 188E4F4 8008AF2C 0D0003A2 */   sb        $v1, 0xD($s0)
.L8008AF30_:
/* 188E4F8 8008AF30 21206002 */  addu       $a0, $s3, $zero
/* 188E4FC 8008AF34 21286002 */  addu       $a1, $s3, $zero
/* 188E500 8008AF38 215F000C */  jal        func_80017C84
/* 188E504 8008AF3C 2130C002 */   addu      $a2, $s6, $zero
/* 188E508 8008AF40 1D000286 */  lh         $v0, 0x1D($s0)
/* 188E50C 8008AF44 00000000 */  nop
/* 188E510 8008AF48 06004010 */  beqz       $v0, .Llevel_20_8008AF64
/* 188E514 8008AF4C 01000224 */   addiu     $v0, $zero, 0x1
/* 188E518 8008AF50 1B000296 */  lhu        $v0, 0x1B($s0)
/* 188E51C 8008AF54 00000000 */  nop
/* 188E520 8008AF58 01004224 */  addiu      $v0, $v0, 0x1
/* 188E524 8008AF5C 1B0002A6 */  sh         $v0, 0x1B($s0)
/* 188E528 8008AF60 01000224 */  addiu      $v0, $zero, 0x1
.Llevel_20_8008AF64:
/* 188E52C 8008AF64 09000392 */  lbu        $v1, 0x9($s0)
/* 188E530 8008AF68 1D000496 */  lhu        $a0, 0x1D($s0)
/* 188E534 8008AF6C 21187500 */  addu       $v1, $v1, $s5
/* 188E538 8008AF70 090003A2 */  sb         $v1, 0x9($s0)
/* 188E53C 8008AF74 0C000392 */  lbu        $v1, 0xC($s0)
/* 188E540 8008AF78 23104400 */  subu       $v0, $v0, $a0
/* 188E544 8008AF7C 1D0002A6 */  sh         $v0, 0x1D($s0)
/* 188E548 8008AF80 0B000292 */  lbu        $v0, 0xB($s0)
/* 188E54C 8008AF84 23187500 */  subu       $v1, $v1, $s5
/* 188E550 8008AF88 0C0003A2 */  sb         $v1, 0xC($s0)
/* 188E554 8008AF8C 0D000392 */  lbu        $v1, 0xD($s0)
/* 188E558 8008AF90 23105500 */  subu       $v0, $v0, $s5
/* 188E55C 8008AF94 0B0002A2 */  sb         $v0, 0xB($s0)
/* 188E560 8008AF98 01000292 */  lbu        $v0, 0x1($s0)
/* 188E564 8008AF9C 23187500 */  subu       $v1, $v1, $s5
/* 188E568 8008AFA0 21105400 */  addu       $v0, $v0, $s4
/* 188E56C 8008AFA4 010002A2 */  sb         $v0, 0x1($s0)
/* 188E570 8008AFA8 FF004230 */  andi       $v0, $v0, 0xFF
/* 188E574 8008AFAC 1800422C */  sltiu      $v0, $v0, 0x18
/* 188E578 8008AFB0 E12F0208 */  j          .Llevel_20_8008BF84
/* 188E57C 8008AFB4 0D0003A2 */   sb        $v1, 0xD($s0)
.L8008AFB8_:
/* 188E580 8008AFB8 21206002 */  addu       $a0, $s3, $zero
/* 188E584 8008AFBC 21286002 */  addu       $a1, $s3, $zero
/* 188E588 8008AFC0 215F000C */  jal        func_80017C84
/* 188E58C 8008AFC4 2130C002 */   addu      $a2, $s6, $zero
/* 188E590 8008AFC8 1D000286 */  lh         $v0, 0x1D($s0)
/* 188E594 8008AFCC 00000000 */  nop
/* 188E598 8008AFD0 06004010 */  beqz       $v0, .Llevel_20_8008AFEC
/* 188E59C 8008AFD4 01000224 */   addiu     $v0, $zero, 0x1
/* 188E5A0 8008AFD8 1B000296 */  lhu        $v0, 0x1B($s0)
/* 188E5A4 8008AFDC 00000000 */  nop
/* 188E5A8 8008AFE0 01004224 */  addiu      $v0, $v0, 0x1
/* 188E5AC 8008AFE4 1B0002A6 */  sh         $v0, 0x1B($s0)
/* 188E5B0 8008AFE8 01000224 */  addiu      $v0, $zero, 0x1
.Llevel_20_8008AFEC:
/* 188E5B4 8008AFEC 09000392 */  lbu        $v1, 0x9($s0)
/* 188E5B8 8008AFF0 1D000496 */  lhu        $a0, 0x1D($s0)
/* 188E5BC 8008AFF4 21187500 */  addu       $v1, $v1, $s5
/* 188E5C0 8008AFF8 090003A2 */  sb         $v1, 0x9($s0)
/* 188E5C4 8008AFFC 0C000392 */  lbu        $v1, 0xC($s0)
/* 188E5C8 8008B000 23104400 */  subu       $v0, $v0, $a0
/* 188E5CC 8008B004 1D0002A6 */  sh         $v0, 0x1D($s0)
/* 188E5D0 8008B008 0B000292 */  lbu        $v0, 0xB($s0)
/* 188E5D4 8008B00C 23187500 */  subu       $v1, $v1, $s5
/* 188E5D8 8008B010 0C0003A2 */  sb         $v1, 0xC($s0)
/* 188E5DC 8008B014 0D000392 */  lbu        $v1, 0xD($s0)
/* 188E5E0 8008B018 23105500 */  subu       $v0, $v0, $s5
/* 188E5E4 8008B01C 0B0002A2 */  sb         $v0, 0xB($s0)
/* 188E5E8 8008B020 01000292 */  lbu        $v0, 0x1($s0)
/* 188E5EC 8008B024 23187500 */  subu       $v1, $v1, $s5
/* 188E5F0 8008B028 21105400 */  addu       $v0, $v0, $s4
/* 188E5F4 8008B02C 010002A2 */  sb         $v0, 0x1($s0)
/* 188E5F8 8008B030 FF004230 */  andi       $v0, $v0, 0xFF
/* 188E5FC 8008B034 2000422C */  sltiu      $v0, $v0, 0x20
/* 188E600 8008B038 E12F0208 */  j          .Llevel_20_8008BF84
/* 188E604 8008B03C 0D0003A2 */   sb        $v1, 0xD($s0)
.L8008B040_:
/* 188E608 8008B040 21206002 */  addu       $a0, $s3, $zero
/* 188E60C 8008B044 21286002 */  addu       $a1, $s3, $zero
/* 188E610 8008B048 215F000C */  jal        func_80017C84
/* 188E614 8008B04C 2130C002 */   addu      $a2, $s6, $zero
/* 188E618 8008B050 1D000286 */  lh         $v0, 0x1D($s0)
/* 188E61C 8008B054 00000000 */  nop
/* 188E620 8008B058 05004010 */  beqz       $v0, .Llevel_20_8008B070
/* 188E624 8008B05C 00000000 */   nop
/* 188E628 8008B060 1B000296 */  lhu        $v0, 0x1B($s0)
/* 188E62C 8008B064 00000000 */  nop
/* 188E630 8008B068 01004224 */  addiu      $v0, $v0, 0x1
/* 188E634 8008B06C 1B0002A6 */  sh         $v0, 0x1B($s0)
.Llevel_20_8008B070:
/* 188E638 8008B070 1D000396 */  lhu        $v1, 0x1D($s0)
/* 188E63C 8008B074 01000224 */  addiu      $v0, $zero, 0x1
/* 188E640 8008B078 23104300 */  subu       $v0, $v0, $v1
/* 188E644 8008B07C 09000392 */  lbu        $v1, 0x9($s0)
/* 188E648 8008B080 1D0002A6 */  sh         $v0, 0x1D($s0)
/* 188E64C 8008B084 01000292 */  lbu        $v0, 0x1($s0)
/* 188E650 8008B088 21187700 */  addu       $v1, $v1, $s7
/* 188E654 8008B08C 21105400 */  addu       $v0, $v0, $s4
/* 188E658 8008B090 010002A2 */  sb         $v0, 0x1($s0)
/* 188E65C 8008B094 FF004230 */  andi       $v0, $v0, 0xFF
/* 188E660 8008B098 2000422C */  sltiu      $v0, $v0, 0x20
/* 188E664 8008B09C E12F0208 */  j          .Llevel_20_8008BF84
/* 188E668 8008B0A0 090003A2 */   sb        $v1, 0x9($s0)
.L8008B0A4_:
/* 188E66C 8008B0A4 0880033C */  lui        $v1, %hi(g_Spyro + 0x78)
/* 188E670 8008B0A8 D08A638C */  lw         $v1, %lo(g_Spyro + 0x78)($v1)
/* 188E674 8008B0AC 1D000224 */  addiu      $v0, $zero, 0x1D
/* 188E678 8008B0B0 06006214 */  bne        $v1, $v0, .Llevel_20_8008B0CC
/* 188E67C 8008B0B4 00000000 */   nop
/* 188E680 8008B0B8 0880023C */  lui        $v0, %hi(g_Spyro + 0x164)
/* 188E684 8008B0BC BC8B428C */  lw         $v0, %lo(g_Spyro + 0x164)($v0)
/* 188E688 8008B0C0 00000000 */  nop
/* 188E68C 8008B0C4 B5034004 */  bltz       $v0, .Llevel_20_8008BF9C
/* 188E690 8008B0C8 00000000 */   nop
.Llevel_20_8008B0CC:
/* 188E694 8008B0CC 0780023C */  lui        $v0, %hi(g_IsSpyroHidden)
/* 188E698 8008B0D0 1458428C */  lw         $v0, %lo(g_IsSpyroHidden)($v0)
/* 188E69C 8008B0D4 00000000 */  nop
/* 188E6A0 8008B0D8 B0034014 */  bnez       $v0, .Llevel_20_8008BF9C
/* 188E6A4 8008B0DC 00000000 */   nop
/* 188E6A8 8008B0E0 0880053C */  lui        $a1, %hi(g_Spyro + 0x160)
/* 188E6AC 8008B0E4 B88BA524 */  addiu      $a1, $a1, %lo(g_Spyro + 0x160)
/* 188E6B0 8008B0E8 0000A28C */  lw         $v0, 0x0($a1)
/* 188E6B4 8008B0EC 00000000 */  nop
/* 188E6B8 8008B0F0 AA034018 */  blez       $v0, .Llevel_20_8008BF9C
/* 188E6BC 8008B0F4 1000A427 */   addiu     $a0, $sp, 0x10
/* 188E6C0 8008B0F8 C05D000C */  jal        VecCopy
/* 188E6C4 8008B0FC A0FEA524 */   addiu     $a1, $a1, -0x160
/* 188E6C8 8008B100 17000486 */  lh         $a0, 0x17($s0)
/* 188E6CC 8008B104 2C5B000C */  jal        Cos
/* 188E6D0 8008B108 00000000 */   nop
/* 188E6D4 8008B10C 1000A38F */  lw         $v1, 0x10($sp)
/* 188E6D8 8008B110 03110200 */  sra        $v0, $v0, 4
/* 188E6DC 8008B114 21186200 */  addu       $v1, $v1, $v0
/* 188E6E0 8008B118 1000A3AF */  sw         $v1, 0x10($sp)
/* 188E6E4 8008B11C 17000486 */  lh         $a0, 0x17($s0)
/* 188E6E8 8008B120 165B000C */  jal        Sin
/* 188E6EC 8008B124 00000000 */   nop
/* 188E6F0 8008B128 21206002 */  addu       $a0, $s3, $zero
/* 188E6F4 8008B12C 1000A527 */  addiu      $a1, $sp, 0x10
/* 188E6F8 8008B130 03110200 */  sra        $v0, $v0, 4
/* 188E6FC 8008B134 1400A38F */  lw         $v1, 0x14($sp)
/* 188E700 8008B138 1800A68F */  lw         $a2, 0x18($sp)
/* 188E704 8008B13C 21186200 */  addu       $v1, $v1, $v0
/* 188E708 8008B140 0001C624 */  addiu      $a2, $a2, 0x100
/* 188E70C 8008B144 1400A3AF */  sw         $v1, 0x14($sp)
/* 188E710 8008B148 FF5E000C */  jal        func_80017BFC
/* 188E714 8008B14C 1800A6AF */   sw        $a2, 0x18($sp)
/* 188E718 8008B150 17000496 */  lhu        $a0, 0x17($s0)
/* 188E71C 8008B154 00000000 */  nop
/* 188E720 8008B158 40008424 */  addiu      $a0, $a0, 0x40
/* 188E724 8008B15C 170004A6 */  sh         $a0, 0x17($s0)
/* 188E728 8008B160 00240400 */  sll        $a0, $a0, 16
/* 188E72C 8008B164 0780023C */  lui        $v0, %hi(g_Camera + 0x50)
/* 188E730 8008B168 206E4284 */  lh         $v0, %lo(g_Camera + 0x50)($v0)
/* 188E734 8008B16C 03240400 */  sra        $a0, $a0, 16
/* 188E738 8008B170 23208200 */  subu       $a0, $a0, $v0
/* 188E73C 8008B174 2C5B000C */  jal        Cos
/* 188E740 8008B178 FF0F8430 */   andi      $a0, $a0, 0xFFF
/* 188E744 8008B17C 6060033C */  lui        $v1, (0x60606061 >> 16)
/* 188E748 8008B180 61606334 */  ori        $v1, $v1, (0x60606061 & 0xFFFF)
/* 188E74C 8008B184 02004104 */  bgez       $v0, .Llevel_20_8008B190
/* 188E750 8008B188 00000000 */   nop
/* 188E754 8008B18C 23100200 */  negu       $v0, $v0
.Llevel_20_8008B190:
/* 188E758 8008B190 18004300 */  mult       $v0, $v1
/* 188E75C 8008B194 C3170200 */  sra        $v0, $v0, 31
/* 188E760 8008B198 10380000 */  mfhi       $a3
/* 188E764 8008B19C 83190700 */  sra        $v1, $a3, 6
/* 188E768 8008B1A0 23186200 */  subu       $v1, $v1, $v0
/* 188E76C 8008B1A4 E92F0208 */  j          .Llevel_20_8008BFA4
/* 188E770 8008B1A8 090003A2 */   sb        $v1, 0x9($s0)
.L8008B1AC_:
/* 188E774 8008B1AC 21206002 */  addu       $a0, $s3, $zero
/* 188E778 8008B1B0 21286002 */  addu       $a1, $s3, $zero
/* 188E77C 8008B1B4 215F000C */  jal        func_80017C84
/* 188E780 8008B1B8 12004626 */   addiu     $a2, $s2, 0x12
/* 188E784 8008B1BC 0B000292 */  lbu        $v0, 0xB($s0)
/* 188E788 8008B1C0 0C000392 */  lbu        $v1, 0xC($s0)
/* 188E78C 8008B1C4 F8FF4224 */  addiu      $v0, $v0, -0x8
/* 188E790 8008B1C8 0B0002A2 */  sb         $v0, 0xB($s0)
/* 188E794 8008B1CC 0D000292 */  lbu        $v0, 0xD($s0)
/* 188E798 8008B1D0 F8FF6324 */  addiu      $v1, $v1, -0x8
/* 188E79C 8008B1D4 0C0003A2 */  sb         $v1, 0xC($s0)
/* 188E7A0 8008B1D8 0B000392 */  lbu        $v1, 0xB($s0)
/* 188E7A4 8008B1DC F8FF4224 */  addiu      $v0, $v0, -0x8
/* 188E7A8 8008B1E0 6E036010 */  beqz       $v1, .Llevel_20_8008BF9C
/* 188E7AC 8008B1E4 0D0002A2 */   sb        $v0, 0xD($s0)
/* 188E7B0 8008B1E8 E32F0208 */  j          .Llevel_20_8008BF8C
/* 188E7B4 8008B1EC 00000000 */   nop
.L8008B1F0_:
/* 188E7B8 8008B1F0 0A000292 */  lbu        $v0, 0xA($s0)
/* 188E7BC 8008B1F4 00000000 */  nop
/* 188E7C0 8008B1F8 08004224 */  addiu      $v0, $v0, 0x8
/* 188E7C4 8008B1FC 0A0002A2 */  sb         $v0, 0xA($s0)
/* 188E7C8 8008B200 09000292 */  lbu        $v0, 0x9($s0)
/* 188E7CC 8008B204 0B000392 */  lbu        $v1, 0xB($s0)
/* 188E7D0 8008B208 02004224 */  addiu      $v0, $v0, 0x2
/* 188E7D4 8008B20C 03006010 */  beqz       $v1, .Llevel_20_8008B21C
/* 188E7D8 8008B210 090002A2 */   sb        $v0, 0x9($s0)
/* 188E7DC 8008B214 F8FF6224 */  addiu      $v0, $v1, -0x8
/* 188E7E0 8008B218 0B0002A2 */  sb         $v0, 0xB($s0)
.Llevel_20_8008B21C:
/* 188E7E4 8008B21C 0C000292 */  lbu        $v0, 0xC($s0)
/* 188E7E8 8008B220 00000000 */  nop
/* 188E7EC 8008B224 02004010 */  beqz       $v0, .Llevel_20_8008B230
/* 188E7F0 8008B228 F8FF4224 */   addiu     $v0, $v0, -0x8
/* 188E7F4 8008B22C 0C0002A2 */  sb         $v0, 0xC($s0)
.Llevel_20_8008B230:
/* 188E7F8 8008B230 0D000292 */  lbu        $v0, 0xD($s0)
/* 188E7FC 8008B234 00000000 */  nop
/* 188E800 8008B238 02004010 */  beqz       $v0, .Llevel_20_8008B244
/* 188E804 8008B23C F8FF4224 */   addiu     $v0, $v0, -0x8
/* 188E808 8008B240 0D0002A2 */  sb         $v0, 0xD($s0)
.Llevel_20_8008B244:
/* 188E80C 8008B244 FF00033C */  lui        $v1, (0xFFFFFF >> 16)
/* 188E810 8008B248 0B00028E */  lw         $v0, 0xB($s0)
/* 188E814 8008B24C FFFF6334 */  ori        $v1, $v1, (0xFFFFFF & 0xFFFF)
/* 188E818 8008B250 24104300 */  and        $v0, $v0, $v1
/* 188E81C 8008B254 51034010 */  beqz       $v0, .Llevel_20_8008BF9C
/* 188E820 8008B258 00000000 */   nop
/* 188E824 8008B25C E32F0208 */  j          .Llevel_20_8008BF8C
/* 188E828 8008B260 00000000 */   nop
.L8008B264_:
/* 188E82C 8008B264 01000292 */  lbu        $v0, 0x1($s0)
/* 188E830 8008B268 00000000 */  nop
/* 188E834 8008B26C 1C00422C */  sltiu      $v0, $v0, 0x1C
/* 188E838 8008B270 4A034010 */  beqz       $v0, .Llevel_20_8008BF9C
/* 188E83C 8008B274 00000000 */   nop
/* 188E840 8008B278 02000292 */  lbu        $v0, 0x2($s0)
/* 188E844 8008B27C 00000000 */  nop
/* 188E848 8008B280 46034010 */  beqz       $v0, .Llevel_20_8008BF9C
/* 188E84C 8008B284 21206002 */   addu      $a0, $s3, $zero
/* 188E850 8008B288 21286002 */  addu       $a1, $s3, $zero
/* 188E854 8008B28C 215F000C */  jal        func_80017C84
/* 188E858 8008B290 2130C002 */   addu      $a2, $s6, $zero
/* 188E85C 8008B294 1D000286 */  lh         $v0, 0x1D($s0)
/* 188E860 8008B298 00000000 */  nop
/* 188E864 8008B29C 05004010 */  beqz       $v0, .Llevel_20_8008B2B4
/* 188E868 8008B2A0 00000000 */   nop
/* 188E86C 8008B2A4 1B000296 */  lhu        $v0, 0x1B($s0)
/* 188E870 8008B2A8 00000000 */  nop
/* 188E874 8008B2AC 01004224 */  addiu      $v0, $v0, 0x1
/* 188E878 8008B2B0 1B0002A6 */  sh         $v0, 0x1B($s0)
.Llevel_20_8008B2B4:
/* 188E87C 8008B2B4 1D000396 */  lhu        $v1, 0x1D($s0)
/* 188E880 8008B2B8 01000224 */  addiu      $v0, $zero, 0x1
/* 188E884 8008B2BC 23104300 */  subu       $v0, $v0, $v1
/* 188E888 8008B2C0 1D0002A6 */  sh         $v0, 0x1D($s0)
/* 188E88C 8008B2C4 09000292 */  lbu        $v0, 0x9($s0)
/* 188E890 8008B2C8 01000392 */  lbu        $v1, 0x1($s0)
/* 188E894 8008B2CC 21105700 */  addu       $v0, $v0, $s7
/* 188E898 8008B2D0 090002A2 */  sb         $v0, 0x9($s0)
/* 188E89C 8008B2D4 0D00622C */  sltiu      $v0, $v1, 0xD
/* 188E8A0 8008B2D8 14004014 */  bnez       $v0, .Llevel_20_8008B32C
/* 188E8A4 8008B2DC 0500622C */   sltiu     $v0, $v1, 0x5
/* 188E8A8 8008B2E0 F4FF6224 */  addiu      $v0, $v1, -0xC
/* 188E8AC 8008B2E4 C0100200 */  sll        $v0, $v0, 3
/* 188E8B0 8008B2E8 80000324 */  addiu      $v1, $zero, 0x80
/* 188E8B4 8008B2EC 23106200 */  subu       $v0, $v1, $v0
/* 188E8B8 8008B2F0 02004104 */  bgez       $v0, .Llevel_20_8008B2FC
/* 188E8BC 8008B2F4 00000000 */   nop
/* 188E8C0 8008B2F8 21100000 */  addu       $v0, $zero, $zero
.Llevel_20_8008B2FC:
/* 188E8C4 8008B2FC 01000392 */  lbu        $v1, 0x1($s0)
/* 188E8C8 8008B300 0B0002A2 */  sb         $v0, 0xB($s0)
/* 188E8CC 8008B304 40000224 */  addiu      $v0, $zero, 0x40
/* 188E8D0 8008B308 F4FF6324 */  addiu      $v1, $v1, -0xC
/* 188E8D4 8008B30C 80180300 */  sll        $v1, $v1, 2
/* 188E8D8 8008B310 23104300 */  subu       $v0, $v0, $v1
/* 188E8DC 8008B314 02004104 */  bgez       $v0, .Llevel_20_8008B320
/* 188E8E0 8008B318 00000000 */   nop
/* 188E8E4 8008B31C 21100000 */  addu       $v0, $zero, $zero
.Llevel_20_8008B320:
/* 188E8E8 8008B320 0C0002A2 */  sb         $v0, 0xC($s0)
/* 188E8EC 8008B324 E02C0208 */  j          .Llevel_20_8008B380
/* 188E8F0 8008B328 0D0000A2 */   sb        $zero, 0xD($s0)
.Llevel_20_8008B32C:
/* 188E8F4 8008B32C 0A004014 */  bnez       $v0, .Llevel_20_8008B358
/* 188E8F8 8008B330 80000224 */   addiu     $v0, $zero, 0x80
/* 188E8FC 8008B334 01000392 */  lbu        $v1, 0x1($s0)
/* 188E900 8008B338 0B0002A2 */  sb         $v0, 0xB($s0)
/* 188E904 8008B33C 80FF0224 */  addiu      $v0, $zero, -0x80
/* 188E908 8008B340 0D0000A2 */  sb         $zero, 0xD($s0)
/* 188E90C 8008B344 FCFF6324 */  addiu      $v1, $v1, -0x4
/* 188E910 8008B348 C0180300 */  sll        $v1, $v1, 3
/* 188E914 8008B34C 23104300 */  subu       $v0, $v0, $v1
/* 188E918 8008B350 E02C0208 */  j          .Llevel_20_8008B380
/* 188E91C 8008B354 0C0002A2 */   sb        $v0, 0xC($s0)
.Llevel_20_8008B358:
/* 188E920 8008B358 01000392 */  lbu        $v1, 0x1($s0)
/* 188E924 8008B35C 0B0002A2 */  sb         $v0, 0xB($s0)
/* 188E928 8008B360 0C0002A2 */  sb         $v0, 0xC($s0)
/* 188E92C 8008B364 80000224 */  addiu      $v0, $zero, 0x80
/* 188E930 8008B368 40190300 */  sll        $v1, $v1, 5
/* 188E934 8008B36C 23104300 */  subu       $v0, $v0, $v1
/* 188E938 8008B370 02004104 */  bgez       $v0, .Llevel_20_8008B37C
/* 188E93C 8008B374 00000000 */   nop
/* 188E940 8008B378 21100000 */  addu       $v0, $zero, $zero
.Llevel_20_8008B37C:
/* 188E944 8008B37C 0D0002A2 */  sb         $v0, 0xD($s0)
.Llevel_20_8008B380:
/* 188E948 8008B380 01000292 */  lbu        $v0, 0x1($s0)
/* 188E94C 8008B384 00000000 */  nop
/* 188E950 8008B388 21105400 */  addu       $v0, $v0, $s4
/* 188E954 8008B38C E92F0208 */  j          .Llevel_20_8008BFA4
/* 188E958 8008B390 010002A2 */   sb        $v0, 0x1($s0)
.L8008B394_:
/* 188E95C 8008B394 21206002 */  addu       $a0, $s3, $zero
/* 188E960 8008B398 21286002 */  addu       $a1, $s3, $zero
/* 188E964 8008B39C 215F000C */  jal        func_80017C84
/* 188E968 8008B3A0 2130C002 */   addu      $a2, $s6, $zero
/* 188E96C 8008B3A4 0A000292 */  lbu        $v0, 0xA($s0)
/* 188E970 8008B3A8 09000392 */  lbu        $v1, 0x9($s0)
/* 188E974 8008B3AC 1D000492 */  lbu        $a0, 0x1D($s0)
/* 188E978 8008B3B0 21187700 */  addu       $v1, $v1, $s7
/* 188E97C 8008B3B4 090003A2 */  sb         $v1, 0x9($s0)
/* 188E980 8008B3B8 0C000392 */  lbu        $v1, 0xC($s0)
/* 188E984 8008B3BC 21104400 */  addu       $v0, $v0, $a0
/* 188E988 8008B3C0 0A0002A2 */  sb         $v0, 0xA($s0)
/* 188E98C 8008B3C4 0B000292 */  lbu        $v0, 0xB($s0)
/* 188E990 8008B3C8 23187700 */  subu       $v1, $v1, $s7
/* 188E994 8008B3CC 0C0003A2 */  sb         $v1, 0xC($s0)
/* 188E998 8008B3D0 0D000392 */  lbu        $v1, 0xD($s0)
/* 188E99C 8008B3D4 23105700 */  subu       $v0, $v0, $s7
/* 188E9A0 8008B3D8 0B0002A2 */  sb         $v0, 0xB($s0)
/* 188E9A4 8008B3DC 01000292 */  lbu        $v0, 0x1($s0)
/* 188E9A8 8008B3E0 23187700 */  subu       $v1, $v1, $s7
/* 188E9AC 8008B3E4 21105400 */  addu       $v0, $v0, $s4
/* 188E9B0 8008B3E8 010002A2 */  sb         $v0, 0x1($s0)
/* 188E9B4 8008B3EC FF004230 */  andi       $v0, $v0, 0xFF
/* 188E9B8 8008B3F0 3000422C */  sltiu      $v0, $v0, 0x30
/* 188E9BC 8008B3F4 E12F0208 */  j          .Llevel_20_8008BF84
/* 188E9C0 8008B3F8 0D0003A2 */   sb        $v1, 0xD($s0)
.L8008B3FC_:
/* 188E9C4 8008B3FC 0B000392 */  lbu        $v1, 0xB($s0)
/* 188E9C8 8008B400 00000000 */  nop
/* 188E9CC 8008B404 F000622C */  sltiu      $v0, $v1, 0xF0
/* 188E9D0 8008B408 02004010 */  beqz       $v0, .Llevel_20_8008B414
/* 188E9D4 8008B40C 04006224 */   addiu     $v0, $v1, 0x4
/* 188E9D8 8008B410 0B0002A2 */  sb         $v0, 0xB($s0)
.Llevel_20_8008B414:
/* 188E9DC 8008B414 0C000392 */  lbu        $v1, 0xC($s0)
/* 188E9E0 8008B418 00000000 */  nop
/* 188E9E4 8008B41C F000622C */  sltiu      $v0, $v1, 0xF0
/* 188E9E8 8008B420 02004010 */  beqz       $v0, .Llevel_20_8008B42C
/* 188E9EC 8008B424 04006224 */   addiu     $v0, $v1, 0x4
/* 188E9F0 8008B428 0C0002A2 */  sb         $v0, 0xC($s0)
.Llevel_20_8008B42C:
/* 188E9F4 8008B42C 0D000392 */  lbu        $v1, 0xD($s0)
/* 188E9F8 8008B430 00000000 */  nop
/* 188E9FC 8008B434 F000622C */  sltiu      $v0, $v1, 0xF0
/* 188EA00 8008B438 02004010 */  beqz       $v0, .Llevel_20_8008B444
/* 188EA04 8008B43C 04006224 */   addiu     $v0, $v1, 0x4
/* 188EA08 8008B440 0D0002A2 */  sb         $v0, 0xD($s0)
.Llevel_20_8008B444:
/* 188EA0C 8008B444 0780023C */  lui        $v0, %hi(g_DeltaTime)
/* 188EA10 8008B448 CC56428C */  lw         $v0, %lo(g_DeltaTime)($v0)
/* 188EA14 8008B44C 1B000392 */  lbu        $v1, 0x1B($s0)
/* 188EA18 8008B450 C0100200 */  sll        $v0, $v0, 3
/* 188EA1C 8008B454 21186200 */  addu       $v1, $v1, $v0
/* 188EA20 8008B458 1B0003A2 */  sb         $v1, 0x1B($s0)
/* 188EA24 8008B45C 0780033C */  lui        $v1, %hi(g_DragonCutscene + 0x3C)
/* 188EA28 8008B460 6C70638C */  lw         $v1, %lo(g_DragonCutscene + 0x3C)($v1)
/* 188EA2C 8008B464 00000000 */  nop
/* 188EA30 8008B468 40006228 */  slti       $v0, $v1, 0x40
/* 188EA34 8008B46C 02004010 */  beqz       $v0, .Llevel_20_8008B478
/* 188EA38 8008B470 3F000424 */   addiu     $a0, $zero, 0x3F
/* 188EA3C 8008B474 21206000 */  addu       $a0, $v1, $zero
.Llevel_20_8008B478:
/* 188EA40 8008B478 48000224 */  addiu      $v0, $zero, 0x48
/* 188EA44 8008B47C 1C000392 */  lbu        $v1, 0x1C($s0)
/* 188EA48 8008B480 23104400 */  subu       $v0, $v0, $a0
/* 188EA4C 8008B484 18006200 */  mult       $v1, $v0
/* 188EA50 8008B488 1C000392 */  lbu        $v1, 0x1C($s0)
/* 188EA54 8008B48C 12280000 */  mflo       $a1
/* 188EA58 8008B490 20000224 */  addiu      $v0, $zero, 0x20
/* 188EA5C 8008B494 23104300 */  subu       $v0, $v0, $v1
/* 188EA60 8008B498 18004400 */  mult       $v0, $a0
/* 188EA64 8008B49C C3100500 */  sra        $v0, $a1, 3
/* 188EA68 8008B4A0 170002A6 */  sh         $v0, 0x17($s0)
/* 188EA6C 8008B4A4 12180000 */  mflo       $v1
/* 188EA70 8008B4A8 03110300 */  sra        $v0, $v1, 4
/* 188EA74 8008B4AC 1B000392 */  lbu        $v1, 0x1B($s0)
/* 188EA78 8008B4B0 08004224 */  addiu      $v0, $v0, 0x8
/* 188EA7C 8008B4B4 190002A6 */  sh         $v0, 0x19($s0)
/* 188EA80 8008B4B8 00140200 */  sll        $v0, $v0, 16
/* 188EA84 8008B4BC 40180300 */  sll        $v1, $v1, 1
/* 188EA88 8008B4C0 0780013C */  lui        $at, %hi(D_8006CC78)
/* 188EA8C 8008B4C4 21082300 */  addu       $at, $at, $v1
/* 188EA90 8008B4C8 78CC2384 */  lh         $v1, %lo(D_8006CC78)($at)
/* 188EA94 8008B4CC 03140200 */  sra        $v0, $v0, 16
/* 188EA98 8008B4D0 18006200 */  mult       $v1, $v0
/* 188EA9C 8008B4D4 11000296 */  lhu        $v0, 0x11($s0)
/* 188EAA0 8008B4D8 12180000 */  mflo       $v1
/* 188EAA4 8008B4DC 03230300 */  sra        $a0, $v1, 12
/* 188EAA8 8008B4E0 1B000392 */  lbu        $v1, 0x1B($s0)
/* 188EAAC 8008B4E4 21104400 */  addu       $v0, $v0, $a0
/* 188EAB0 8008B4E8 030002A6 */  sh         $v0, 0x3($s0)
/* 188EAB4 8008B4EC 19000286 */  lh         $v0, 0x19($s0)
/* 188EAB8 8008B4F0 40180300 */  sll        $v1, $v1, 1
/* 188EABC 8008B4F4 0780013C */  lui        $at, %hi(D_8006CBF8)
/* 188EAC0 8008B4F8 21082300 */  addu       $at, $at, $v1
/* 188EAC4 8008B4FC F8CB2384 */  lh         $v1, %lo(D_8006CBF8)($at)
/* 188EAC8 8008B500 00000000 */  nop
/* 188EACC 8008B504 18006200 */  mult       $v1, $v0
/* 188EAD0 8008B508 17000296 */  lhu        $v0, 0x17($s0)
/* 188EAD4 8008B50C 15000396 */  lhu        $v1, 0x15($s0)
/* 188EAD8 8008B510 20004224 */  addiu      $v0, $v0, 0x20
/* 188EADC 8008B514 21186200 */  addu       $v1, $v1, $v0
/* 188EAE0 8008B518 13000296 */  lhu        $v0, 0x13($s0)
/* 188EAE4 8008B51C 070003A6 */  sh         $v1, 0x7($s0)
/* 188EAE8 8008B520 12400000 */  mflo       $t0
/* 188EAEC 8008B524 031B0800 */  sra        $v1, $t0, 12
/* 188EAF0 8008B528 21104300 */  addu       $v0, $v0, $v1
/* 188EAF4 8008B52C E92F0208 */  j          .Llevel_20_8008BFA4
/* 188EAF8 8008B530 050002A6 */   sh        $v0, 0x5($s0)
.L8008B534_:
/* 188EAFC 8008B534 21206002 */  addu       $a0, $s3, $zero
/* 188EB00 8008B538 21286002 */  addu       $a1, $s3, $zero
/* 188EB04 8008B53C 215F000C */  jal        func_80017C84
/* 188EB08 8008B540 2130C002 */   addu      $a2, $s6, $zero
/* 188EB0C 8008B544 1D000286 */  lh         $v0, 0x1D($s0)
/* 188EB10 8008B548 00000000 */  nop
/* 188EB14 8008B54C 05004010 */  beqz       $v0, .Llevel_20_8008B564
/* 188EB18 8008B550 00000000 */   nop
/* 188EB1C 8008B554 1B000296 */  lhu        $v0, 0x1B($s0)
/* 188EB20 8008B558 00000000 */  nop
/* 188EB24 8008B55C 01004224 */  addiu      $v0, $v0, 0x1
/* 188EB28 8008B560 1B0002A6 */  sh         $v0, 0x1B($s0)
.Llevel_20_8008B564:
/* 188EB2C 8008B564 0B000292 */  lbu        $v0, 0xB($s0)
/* 188EB30 8008B568 1D000496 */  lhu        $a0, 0x1D($s0)
/* 188EB34 8008B56C 09000392 */  lbu        $v1, 0x9($s0)
/* 188EB38 8008B570 23285400 */  subu       $a1, $v0, $s4
/* 188EB3C 8008B574 01000224 */  addiu      $v0, $zero, 0x1
/* 188EB40 8008B578 23104400 */  subu       $v0, $v0, $a0
/* 188EB44 8008B57C 21187700 */  addu       $v1, $v1, $s7
/* 188EB48 8008B580 1D0002A6 */  sh         $v0, 0x1D($s0)
/* 188EB4C 8008B584 0200A104 */  bgez       $a1, .Llevel_20_8008B590
/* 188EB50 8008B588 090003A2 */   sb        $v1, 0x9($s0)
/* 188EB54 8008B58C 21280000 */  addu       $a1, $zero, $zero
.Llevel_20_8008B590:
/* 188EB58 8008B590 0C000292 */  lbu        $v0, 0xC($s0)
/* 188EB5C 8008B594 0B0005A2 */  sb         $a1, 0xB($s0)
/* 188EB60 8008B598 23285400 */  subu       $a1, $v0, $s4
/* 188EB64 8008B59C 0200A104 */  bgez       $a1, .Llevel_20_8008B5A8
/* 188EB68 8008B5A0 00000000 */   nop
/* 188EB6C 8008B5A4 21280000 */  addu       $a1, $zero, $zero
.Llevel_20_8008B5A8:
/* 188EB70 8008B5A8 0D000292 */  lbu        $v0, 0xD($s0)
/* 188EB74 8008B5AC 0C0005A2 */  sb         $a1, 0xC($s0)
/* 188EB78 8008B5B0 23285400 */  subu       $a1, $v0, $s4
/* 188EB7C 8008B5B4 0200A104 */  bgez       $a1, .Llevel_20_8008B5C0
/* 188EB80 8008B5B8 00000000 */   nop
/* 188EB84 8008B5BC 21280000 */  addu       $a1, $zero, $zero
.Llevel_20_8008B5C0:
/* 188EB88 8008B5C0 01000292 */  lbu        $v0, 0x1($s0)
/* 188EB8C 8008B5C4 0D0005A2 */  sb         $a1, 0xD($s0)
/* 188EB90 8008B5C8 21105400 */  addu       $v0, $v0, $s4
/* 188EB94 8008B5CC 010002A2 */  sb         $v0, 0x1($s0)
/* 188EB98 8008B5D0 FF004230 */  andi       $v0, $v0, 0xFF
/* 188EB9C 8008B5D4 E12F0208 */  j          .Llevel_20_8008BF84
/* 188EBA0 8008B5D8 2000422C */   sltiu     $v0, $v0, 0x20
.L8008B5DC_:
/* 188EBA4 8008B5DC 2F00801A */  blez       $s4, .Llevel_20_8008B69C
/* 188EBA8 8008B5E0 21880000 */   addu      $s1, $zero, $zero
.Llevel_20_8008B5E4:
/* 188EBAC 8008B5E4 01000292 */  lbu        $v0, 0x1($s0)
/* 188EBB0 8008B5E8 00000000 */  nop
/* 188EBB4 8008B5EC 01004230 */  andi       $v0, $v0, 0x1
/* 188EBB8 8008B5F0 23004010 */  beqz       $v0, .Llevel_20_8008B680
/* 188EBBC 8008B5F4 00000000 */   nop
/* 188EBC0 8008B5F8 03000296 */  lhu        $v0, 0x3($s0)
/* 188EBC4 8008B5FC 0F000496 */  lhu        $a0, 0xF($s0)
/* 188EBC8 8008B600 05000396 */  lhu        $v1, 0x5($s0)
/* 188EBCC 8008B604 11000596 */  lhu        $a1, 0x11($s0)
/* 188EBD0 8008B608 21104400 */  addu       $v0, $v0, $a0
/* 188EBD4 8008B60C 030002A6 */  sh         $v0, 0x3($s0)
/* 188EBD8 8008B610 07000296 */  lhu        $v0, 0x7($s0)
/* 188EBDC 8008B614 13000496 */  lhu        $a0, 0x13($s0)
/* 188EBE0 8008B618 21186500 */  addu       $v1, $v1, $a1
/* 188EBE4 8008B61C 050003A6 */  sh         $v1, 0x5($s0)
/* 188EBE8 8008B620 01000392 */  lbu        $v1, 0x1($s0)
/* 188EBEC 8008B624 21104400 */  addu       $v0, $v0, $a0
/* 188EBF0 8008B628 02006330 */  andi       $v1, $v1, 0x2
/* 188EBF4 8008B62C 14006010 */  beqz       $v1, .Llevel_20_8008B680
/* 188EBF8 8008B630 070002A6 */   sh        $v0, 0x7($s0)
/* 188EBFC 8008B634 CB89010C */  jal        rand
/* 188EC00 8008B638 00000000 */   nop
/* 188EC04 8008B63C 0F000396 */  lhu        $v1, 0xF($s0)
/* 188EC08 8008B640 02004230 */  andi       $v0, $v0, 0x2
/* 188EC0C 8008B644 FFFF6324 */  addiu      $v1, $v1, -0x1
/* 188EC10 8008B648 21186200 */  addu       $v1, $v1, $v0
/* 188EC14 8008B64C CB89010C */  jal        rand
/* 188EC18 8008B650 0F0003A6 */   sh        $v1, 0xF($s0)
/* 188EC1C 8008B654 11000396 */  lhu        $v1, 0x11($s0)
/* 188EC20 8008B658 02004230 */  andi       $v0, $v0, 0x2
/* 188EC24 8008B65C FFFF6324 */  addiu      $v1, $v1, -0x1
/* 188EC28 8008B660 21186200 */  addu       $v1, $v1, $v0
/* 188EC2C 8008B664 CB89010C */  jal        rand
/* 188EC30 8008B668 110003A6 */   sh        $v1, 0x11($s0)
/* 188EC34 8008B66C 13000396 */  lhu        $v1, 0x13($s0)
/* 188EC38 8008B670 02004230 */  andi       $v0, $v0, 0x2
/* 188EC3C 8008B674 FFFF6324 */  addiu      $v1, $v1, -0x1
/* 188EC40 8008B678 21186200 */  addu       $v1, $v1, $v0
/* 188EC44 8008B67C 130003A6 */  sh         $v1, 0x13($s0)
.Llevel_20_8008B680:
/* 188EC48 8008B680 01000292 */  lbu        $v0, 0x1($s0)
/* 188EC4C 8008B684 01003126 */  addiu      $s1, $s1, 0x1
/* 188EC50 8008B688 01004224 */  addiu      $v0, $v0, 0x1
/* 188EC54 8008B68C 010002A2 */  sb         $v0, 0x1($s0)
/* 188EC58 8008B690 2A103402 */  slt        $v0, $s1, $s4
/* 188EC5C 8008B694 D3FF4014 */  bnez       $v0, .Llevel_20_8008B5E4
/* 188EC60 8008B698 00000000 */   nop
.Llevel_20_8008B69C:
/* 188EC64 8008B69C 01000292 */  lbu        $v0, 0x1($s0)
/* 188EC68 8008B6A0 E12F0208 */  j          .Llevel_20_8008BF84
/* 188EC6C 8008B6A4 1800422C */   sltiu     $v0, $v0, 0x18
.L8008B6A8_:
/* 188EC70 8008B6A8 09000486 */  lh         $a0, 0x9($s0)
/* 188EC74 8008B6AC 03000286 */  lh         $v0, 0x3($s0)
/* 188EC78 8008B6B0 00000000 */  nop
/* 188EC7C 8008B6B4 23208200 */  subu       $a0, $a0, $v0
/* 188EC80 8008B6B8 43200400 */  sra        $a0, $a0, 1
/* 188EC84 8008B6BC 2000A4A7 */  sh         $a0, 0x20($sp)
/* 188EC88 8008B6C0 0B000286 */  lh         $v0, 0xB($s0)
/* 188EC8C 8008B6C4 05000386 */  lh         $v1, 0x5($s0)
/* 188EC90 8008B6C8 00000000 */  nop
/* 188EC94 8008B6CC 23104300 */  subu       $v0, $v0, $v1
/* 188EC98 8008B6D0 43100200 */  sra        $v0, $v0, 1
/* 188EC9C 8008B6D4 2200A2A7 */  sh         $v0, 0x22($sp)
/* 188ECA0 8008B6D8 0D000286 */  lh         $v0, 0xD($s0)
/* 188ECA4 8008B6DC 07000386 */  lh         $v1, 0x7($s0)
/* 188ECA8 8008B6E0 00000000 */  nop
/* 188ECAC 8008B6E4 23104300 */  subu       $v0, $v0, $v1
/* 188ECB0 8008B6E8 43100200 */  sra        $v0, $v0, 1
/* 188ECB4 8008B6EC 2400A2A7 */  sh         $v0, 0x24($sp)
/* 188ECB8 8008B6F0 03000296 */  lhu        $v0, 0x3($s0)
/* 188ECBC 8008B6F4 00000000 */  nop
/* 188ECC0 8008B6F8 21104400 */  addu       $v0, $v0, $a0
/* 188ECC4 8008B6FC 030002A6 */  sh         $v0, 0x3($s0)
/* 188ECC8 8008B700 05000296 */  lhu        $v0, 0x5($s0)
/* 188ECCC 8008B704 2200A397 */  lhu        $v1, 0x22($sp)
/* 188ECD0 8008B708 00000000 */  nop
/* 188ECD4 8008B70C 21104300 */  addu       $v0, $v0, $v1
/* 188ECD8 8008B710 050002A6 */  sh         $v0, 0x5($s0)
/* 188ECDC 8008B714 07000296 */  lhu        $v0, 0x7($s0)
/* 188ECE0 8008B718 2400A397 */  lhu        $v1, 0x24($sp)
/* 188ECE4 8008B71C 00000000 */  nop
/* 188ECE8 8008B720 21104300 */  addu       $v0, $v0, $v1
/* 188ECEC 8008B724 CB89010C */  jal        rand
/* 188ECF0 8008B728 070002A6 */   sh        $v0, 0x7($s0)
/* 188ECF4 8008B72C 2000A397 */  lhu        $v1, 0x20($sp)
/* 188ECF8 8008B730 02004230 */  andi       $v0, $v0, 0x2
/* 188ECFC 8008B734 FFFF6324 */  addiu      $v1, $v1, -0x1
/* 188ED00 8008B738 21186200 */  addu       $v1, $v1, $v0
/* 188ED04 8008B73C CB89010C */  jal        rand
/* 188ED08 8008B740 2000A3A7 */   sh        $v1, 0x20($sp)
/* 188ED0C 8008B744 2200A397 */  lhu        $v1, 0x22($sp)
/* 188ED10 8008B748 02004230 */  andi       $v0, $v0, 0x2
/* 188ED14 8008B74C FFFF6324 */  addiu      $v1, $v1, -0x1
/* 188ED18 8008B750 21186200 */  addu       $v1, $v1, $v0
/* 188ED1C 8008B754 2200A3A7 */  sh         $v1, 0x22($sp)
/* 188ED20 8008B758 01000292 */  lbu        $v0, 0x1($s0)
/* 188ED24 8008B75C 00000000 */  nop
/* 188ED28 8008B760 01004230 */  andi       $v0, $v0, 0x1
/* 188ED2C 8008B764 05004010 */  beqz       $v0, .Llevel_20_8008B77C
/* 188ED30 8008B768 00000000 */   nop
/* 188ED34 8008B76C 2400A297 */  lhu        $v0, 0x24($sp)
/* 188ED38 8008B770 00000000 */  nop
/* 188ED3C 8008B774 FFFF4224 */  addiu      $v0, $v0, -0x1
/* 188ED40 8008B778 2400A2A7 */  sh         $v0, 0x24($sp)
.Llevel_20_8008B77C:
/* 188ED44 8008B77C 09000296 */  lhu        $v0, 0x9($s0)
/* 188ED48 8008B780 2000A397 */  lhu        $v1, 0x20($sp)
/* 188ED4C 8008B784 00000000 */  nop
/* 188ED50 8008B788 21104300 */  addu       $v0, $v0, $v1
/* 188ED54 8008B78C 090002A6 */  sh         $v0, 0x9($s0)
/* 188ED58 8008B790 0B000296 */  lhu        $v0, 0xB($s0)
/* 188ED5C 8008B794 2200A397 */  lhu        $v1, 0x22($sp)
/* 188ED60 8008B798 00000000 */  nop
/* 188ED64 8008B79C 21104300 */  addu       $v0, $v0, $v1
/* 188ED68 8008B7A0 0D000396 */  lhu        $v1, 0xD($s0)
/* 188ED6C 8008B7A4 0B0002A6 */  sh         $v0, 0xB($s0)
/* 188ED70 8008B7A8 01000292 */  lbu        $v0, 0x1($s0)
/* 188ED74 8008B7AC 2400A497 */  lhu        $a0, 0x24($sp)
/* 188ED78 8008B7B0 01004224 */  addiu      $v0, $v0, 0x1
/* 188ED7C 8008B7B4 21186400 */  addu       $v1, $v1, $a0
/* 188ED80 8008B7B8 010002A2 */  sb         $v0, 0x1($s0)
/* 188ED84 8008B7BC FF004230 */  andi       $v0, $v0, 0xFF
/* 188ED88 8008B7C0 2000422C */  sltiu      $v0, $v0, 0x20
/* 188ED8C 8008B7C4 F5014010 */  beqz       $v0, .Llevel_20_8008BF9C
/* 188ED90 8008B7C8 0D0003A6 */   sh        $v1, 0xD($s0)
/* 188ED94 8008B7CC 02000292 */  lbu        $v0, 0x2($s0)
/* 188ED98 8008B7D0 00000000 */  nop
/* 188ED9C 8008B7D4 F1014010 */  beqz       $v0, .Llevel_20_8008BF9C
/* 188EDA0 8008B7D8 00000000 */   nop
/* 188EDA4 8008B7DC 0F000292 */  lbu        $v0, 0xF($s0)
/* 188EDA8 8008B7E0 00000000 */  nop
/* 188EDAC 8008B7E4 FDFF4224 */  addiu      $v0, $v0, -0x3
/* 188EDB0 8008B7E8 0F0002A2 */  sb         $v0, 0xF($s0)
/* 188EDB4 8008B7EC FF004230 */  andi       $v0, $v0, 0xFF
/* 188EDB8 8008B7F0 8000422C */  sltiu      $v0, $v0, 0x80
/* 188EDBC 8008B7F4 02004010 */  beqz       $v0, .Llevel_20_8008B800
/* 188EDC0 8008B7F8 80000224 */   addiu     $v0, $zero, 0x80
/* 188EDC4 8008B7FC 0F0002A2 */  sb         $v0, 0xF($s0)
.Llevel_20_8008B800:
/* 188EDC8 8008B800 10000292 */  lbu        $v0, 0x10($s0)
/* 188EDCC 8008B804 00000000 */  nop
/* 188EDD0 8008B808 FCFF4224 */  addiu      $v0, $v0, -0x4
/* 188EDD4 8008B80C 100002A2 */  sb         $v0, 0x10($s0)
/* 188EDD8 8008B810 FF004230 */  andi       $v0, $v0, 0xFF
/* 188EDDC 8008B814 6000422C */  sltiu      $v0, $v0, 0x60
/* 188EDE0 8008B818 02004010 */  beqz       $v0, .Llevel_20_8008B824
/* 188EDE4 8008B81C 60000224 */   addiu     $v0, $zero, 0x60
/* 188EDE8 8008B820 100002A2 */  sb         $v0, 0x10($s0)
.Llevel_20_8008B824:
/* 188EDEC 8008B824 13000292 */  lbu        $v0, 0x13($s0)
/* 188EDF0 8008B828 110000A2 */  sb         $zero, 0x11($s0)
/* 188EDF4 8008B82C FDFF4224 */  addiu      $v0, $v0, -0x3
/* 188EDF8 8008B830 130002A2 */  sb         $v0, 0x13($s0)
/* 188EDFC 8008B834 FF004230 */  andi       $v0, $v0, 0xFF
/* 188EE00 8008B838 C000422C */  sltiu      $v0, $v0, 0xC0
/* 188EE04 8008B83C 02004010 */  beqz       $v0, .Llevel_20_8008B848
/* 188EE08 8008B840 C0000224 */   addiu     $v0, $zero, 0xC0
/* 188EE0C 8008B844 130002A2 */  sb         $v0, 0x13($s0)
.Llevel_20_8008B848:
/* 188EE10 8008B848 14000292 */  lbu        $v0, 0x14($s0)
/* 188EE14 8008B84C 00000000 */  nop
/* 188EE18 8008B850 FCFF4224 */  addiu      $v0, $v0, -0x4
/* 188EE1C 8008B854 140002A2 */  sb         $v0, 0x14($s0)
/* 188EE20 8008B858 FF004230 */  andi       $v0, $v0, 0xFF
/* 188EE24 8008B85C 8000422C */  sltiu      $v0, $v0, 0x80
/* 188EE28 8008B860 02004010 */  beqz       $v0, .Llevel_20_8008B86C
/* 188EE2C 8008B864 80000224 */   addiu     $v0, $zero, 0x80
/* 188EE30 8008B868 140002A2 */  sb         $v0, 0x14($s0)
.Llevel_20_8008B86C:
/* 188EE34 8008B86C 15000292 */  lbu        $v0, 0x15($s0)
/* 188EE38 8008B870 00000000 */  nop
/* 188EE3C 8008B874 FAFF4224 */  addiu      $v0, $v0, -0x6
/* 188EE40 8008B878 150002A2 */  sb         $v0, 0x15($s0)
/* 188EE44 8008B87C FF004230 */  andi       $v0, $v0, 0xFF
/* 188EE48 8008B880 2000422C */  sltiu      $v0, $v0, 0x20
/* 188EE4C 8008B884 C7014010 */  beqz       $v0, .Llevel_20_8008BFA4
/* 188EE50 8008B888 20000224 */   addiu     $v0, $zero, 0x20
/* 188EE54 8008B88C E92F0208 */  j          .Llevel_20_8008BFA4
/* 188EE58 8008B890 150002A2 */   sb        $v0, 0x15($s0)
.L8008B894_:
/* 188EE5C 8008B894 01000292 */  lbu        $v0, 0x1($s0)
/* 188EE60 8008B898 00000000 */  nop
/* 188EE64 8008B89C 01004224 */  addiu      $v0, $v0, 0x1
/* 188EE68 8008B8A0 010002A2 */  sb         $v0, 0x1($s0)
/* 188EE6C 8008B8A4 FF004230 */  andi       $v0, $v0, 0xFF
/* 188EE70 8008B8A8 2000422C */  sltiu      $v0, $v0, 0x20
/* 188EE74 8008B8AC BB014010 */  beqz       $v0, .Llevel_20_8008BF9C
/* 188EE78 8008B8B0 00000000 */   nop
/* 188EE7C 8008B8B4 02000292 */  lbu        $v0, 0x2($s0)
/* 188EE80 8008B8B8 00000000 */  nop
/* 188EE84 8008B8BC B7014010 */  beqz       $v0, .Llevel_20_8008BF9C
/* 188EE88 8008B8C0 00000000 */   nop
/* 188EE8C 8008B8C4 09000286 */  lh         $v0, 0x9($s0)
/* 188EE90 8008B8C8 03000386 */  lh         $v1, 0x3($s0)
/* 188EE94 8008B8CC 00000000 */  nop
/* 188EE98 8008B8D0 23104300 */  subu       $v0, $v0, $v1
/* 188EE9C 8008B8D4 2800A2AF */  sw         $v0, 0x28($sp)
/* 188EEA0 8008B8D8 0B000286 */  lh         $v0, 0xB($s0)
/* 188EEA4 8008B8DC 05000386 */  lh         $v1, 0x5($s0)
/* 188EEA8 8008B8E0 00000000 */  nop
/* 188EEAC 8008B8E4 23104300 */  subu       $v0, $v0, $v1
/* 188EEB0 8008B8E8 2C00A2AF */  sw         $v0, 0x2C($sp)
/* 188EEB4 8008B8EC 0D000286 */  lh         $v0, 0xD($s0)
/* 188EEB8 8008B8F0 07000386 */  lh         $v1, 0x7($s0)
/* 188EEBC 8008B8F4 00000000 */  nop
/* 188EEC0 8008B8F8 23104300 */  subu       $v0, $v0, $v1
/* 188EEC4 8008B8FC CB89010C */  jal        rand
/* 188EEC8 8008B900 3000A2AF */   sw        $v0, 0x30($sp)
/* 188EECC 8008B904 2800A38F */  lw         $v1, 0x28($sp)
/* 188EED0 8008B908 02004230 */  andi       $v0, $v0, 0x2
/* 188EED4 8008B90C FFFF6324 */  addiu      $v1, $v1, -0x1
/* 188EED8 8008B910 21186200 */  addu       $v1, $v1, $v0
/* 188EEDC 8008B914 CB89010C */  jal        rand
/* 188EEE0 8008B918 2800A3AF */   sw        $v1, 0x28($sp)
/* 188EEE4 8008B91C 2C00A38F */  lw         $v1, 0x2C($sp)
/* 188EEE8 8008B920 02004230 */  andi       $v0, $v0, 0x2
/* 188EEEC 8008B924 FFFF6324 */  addiu      $v1, $v1, -0x1
/* 188EEF0 8008B928 21186200 */  addu       $v1, $v1, $v0
/* 188EEF4 8008B92C CB89010C */  jal        rand
/* 188EEF8 8008B930 2C00A3AF */   sw        $v1, 0x2C($sp)
/* 188EEFC 8008B934 3000A38F */  lw         $v1, 0x30($sp)
/* 188EF00 8008B938 02004230 */  andi       $v0, $v0, 0x2
/* 188EF04 8008B93C FFFF6324 */  addiu      $v1, $v1, -0x1
/* 188EF08 8008B940 21186200 */  addu       $v1, $v1, $v0
/* 188EF0C 8008B944 3000A3AF */  sw         $v1, 0x30($sp)
/* 188EF10 8008B948 2800A38F */  lw         $v1, 0x28($sp)
/* 188EF14 8008B94C 09000296 */  lhu        $v0, 0x9($s0)
/* 188EF18 8008B950 00000000 */  nop
/* 188EF1C 8008B954 21104300 */  addu       $v0, $v0, $v1
/* 188EF20 8008B958 090002A6 */  sh         $v0, 0x9($s0)
/* 188EF24 8008B95C 2C00A38F */  lw         $v1, 0x2C($sp)
/* 188EF28 8008B960 0B000296 */  lhu        $v0, 0xB($s0)
/* 188EF2C 8008B964 00000000 */  nop
/* 188EF30 8008B968 21104300 */  addu       $v0, $v0, $v1
/* 188EF34 8008B96C 0B0002A6 */  sh         $v0, 0xB($s0)
/* 188EF38 8008B970 3000A38F */  lw         $v1, 0x30($sp)
/* 188EF3C 8008B974 0D000296 */  lhu        $v0, 0xD($s0)
/* 188EF40 8008B978 00000000 */  nop
/* 188EF44 8008B97C 21104300 */  addu       $v0, $v0, $v1
/* 188EF48 8008B980 0D0002A6 */  sh         $v0, 0xD($s0)
/* 188EF4C 8008B984 2800A38F */  lw         $v1, 0x28($sp)
/* 188EF50 8008B988 09000296 */  lhu        $v0, 0x9($s0)
/* 188EF54 8008B98C 00000000 */  nop
/* 188EF58 8008B990 23104300 */  subu       $v0, $v0, $v1
/* 188EF5C 8008B994 030002A6 */  sh         $v0, 0x3($s0)
/* 188EF60 8008B998 2C00A38F */  lw         $v1, 0x2C($sp)
/* 188EF64 8008B99C 0B000296 */  lhu        $v0, 0xB($s0)
/* 188EF68 8008B9A0 00000000 */  nop
/* 188EF6C 8008B9A4 23104300 */  subu       $v0, $v0, $v1
/* 188EF70 8008B9A8 050002A6 */  sh         $v0, 0x5($s0)
/* 188EF74 8008B9AC 13000292 */  lbu        $v0, 0x13($s0)
/* 188EF78 8008B9B0 3000A48F */  lw         $a0, 0x30($sp)
/* 188EF7C 8008B9B4 15000392 */  lbu        $v1, 0x15($s0)
/* 188EF80 8008B9B8 FEFF4224 */  addiu      $v0, $v0, -0x2
/* 188EF84 8008B9BC 130002A2 */  sb         $v0, 0x13($s0)
/* 188EF88 8008B9C0 14000292 */  lbu        $v0, 0x14($s0)
/* 188EF8C 8008B9C4 FCFF6324 */  addiu      $v1, $v1, -0x4
/* 188EF90 8008B9C8 150003A2 */  sb         $v1, 0x15($s0)
/* 188EF94 8008B9CC 10000392 */  lbu        $v1, 0x10($s0)
/* 188EF98 8008B9D0 FEFF4224 */  addiu      $v0, $v0, -0x2
/* 188EF9C 8008B9D4 140002A2 */  sb         $v0, 0x14($s0)
/* 188EFA0 8008B9D8 0F000292 */  lbu        $v0, 0xF($s0)
/* 188EFA4 8008B9DC FDFF6324 */  addiu      $v1, $v1, -0x3
/* 188EFA8 8008B9E0 100003A2 */  sb         $v1, 0x10($s0)
/* 188EFAC 8008B9E4 0D000396 */  lhu        $v1, 0xD($s0)
/* 188EFB0 8008B9E8 FDFF4224 */  addiu      $v0, $v0, -0x3
/* 188EFB4 8008B9EC 0F0002A2 */  sb         $v0, 0xF($s0)
/* 188EFB8 8008B9F0 11000292 */  lbu        $v0, 0x11($s0)
/* 188EFBC 8008B9F4 23186400 */  subu       $v1, $v1, $a0
/* 188EFC0 8008B9F8 070003A6 */  sh         $v1, 0x7($s0)
/* 188EFC4 8008B9FC FDFF4224 */  addiu      $v0, $v0, -0x3
/* 188EFC8 8008BA00 E92F0208 */  j          .Llevel_20_8008BFA4
/* 188EFCC 8008BA04 110002A2 */   sb        $v0, 0x11($s0)
.L8008BA08_:
/* 188EFD0 8008BA08 01000292 */  lbu        $v0, 0x1($s0)
/* 188EFD4 8008BA0C 00000000 */  nop
/* 188EFD8 8008BA10 01004224 */  addiu      $v0, $v0, 0x1
/* 188EFDC 8008BA14 010002A2 */  sb         $v0, 0x1($s0)
/* 188EFE0 8008BA18 FF004230 */  andi       $v0, $v0, 0xFF
/* 188EFE4 8008BA1C 3000422C */  sltiu      $v0, $v0, 0x30
/* 188EFE8 8008BA20 5E014010 */  beqz       $v0, .Llevel_20_8008BF9C
/* 188EFEC 8008BA24 00000000 */   nop
/* 188EFF0 8008BA28 02000292 */  lbu        $v0, 0x2($s0)
/* 188EFF4 8008BA2C 00000000 */  nop
/* 188EFF8 8008BA30 5A014010 */  beqz       $v0, .Llevel_20_8008BF9C
/* 188EFFC 8008BA34 00000000 */   nop
/* 188F000 8008BA38 03000286 */  lh         $v0, 0x3($s0)
/* 188F004 8008BA3C 09000386 */  lh         $v1, 0x9($s0)
/* 188F008 8008BA40 00000000 */  nop
/* 188F00C 8008BA44 23104300 */  subu       $v0, $v0, $v1
/* 188F010 8008BA48 43100200 */  sra        $v0, $v0, 1
/* 188F014 8008BA4C 2000A2AF */  sw         $v0, 0x20($sp)
/* 188F018 8008BA50 05000286 */  lh         $v0, 0x5($s0)
/* 188F01C 8008BA54 0B000386 */  lh         $v1, 0xB($s0)
/* 188F020 8008BA58 00000000 */  nop
/* 188F024 8008BA5C 23104300 */  subu       $v0, $v0, $v1
/* 188F028 8008BA60 43100200 */  sra        $v0, $v0, 1
/* 188F02C 8008BA64 2400A2AF */  sw         $v0, 0x24($sp)
/* 188F030 8008BA68 07000286 */  lh         $v0, 0x7($s0)
/* 188F034 8008BA6C 0D000386 */  lh         $v1, 0xD($s0)
/* 188F038 8008BA70 00000000 */  nop
/* 188F03C 8008BA74 23104300 */  subu       $v0, $v0, $v1
/* 188F040 8008BA78 43100200 */  sra        $v0, $v0, 1
/* 188F044 8008BA7C CB89010C */  jal        rand
/* 188F048 8008BA80 2800A2AF */   sw        $v0, 0x28($sp)
/* 188F04C 8008BA84 2000A38F */  lw         $v1, 0x20($sp)
/* 188F050 8008BA88 04004230 */  andi       $v0, $v0, 0x4
/* 188F054 8008BA8C FEFF6324 */  addiu      $v1, $v1, -0x2
/* 188F058 8008BA90 21186200 */  addu       $v1, $v1, $v0
/* 188F05C 8008BA94 CB89010C */  jal        rand
/* 188F060 8008BA98 2000A3AF */   sw        $v1, 0x20($sp)
/* 188F064 8008BA9C 2400A38F */  lw         $v1, 0x24($sp)
/* 188F068 8008BAA0 04004230 */  andi       $v0, $v0, 0x4
/* 188F06C 8008BAA4 FEFF6324 */  addiu      $v1, $v1, -0x2
/* 188F070 8008BAA8 21186200 */  addu       $v1, $v1, $v0
/* 188F074 8008BAAC CB89010C */  jal        rand
/* 188F078 8008BAB0 2400A3AF */   sw        $v1, 0x24($sp)
/* 188F07C 8008BAB4 2800A38F */  lw         $v1, 0x28($sp)
/* 188F080 8008BAB8 02004230 */  andi       $v0, $v0, 0x2
/* 188F084 8008BABC FFFF6324 */  addiu      $v1, $v1, -0x1
/* 188F088 8008BAC0 21186200 */  addu       $v1, $v1, $v0
/* 188F08C 8008BAC4 2800A3AF */  sw         $v1, 0x28($sp)
/* 188F090 8008BAC8 2000A38F */  lw         $v1, 0x20($sp)
/* 188F094 8008BACC 03000296 */  lhu        $v0, 0x3($s0)
/* 188F098 8008BAD0 00000000 */  nop
/* 188F09C 8008BAD4 21104300 */  addu       $v0, $v0, $v1
/* 188F0A0 8008BAD8 030002A6 */  sh         $v0, 0x3($s0)
/* 188F0A4 8008BADC 2400A38F */  lw         $v1, 0x24($sp)
/* 188F0A8 8008BAE0 05000296 */  lhu        $v0, 0x5($s0)
/* 188F0AC 8008BAE4 00000000 */  nop
/* 188F0B0 8008BAE8 21104300 */  addu       $v0, $v0, $v1
/* 188F0B4 8008BAEC 050002A6 */  sh         $v0, 0x5($s0)
/* 188F0B8 8008BAF0 2800A38F */  lw         $v1, 0x28($sp)
/* 188F0BC 8008BAF4 07000296 */  lhu        $v0, 0x7($s0)
/* 188F0C0 8008BAF8 00000000 */  nop
/* 188F0C4 8008BAFC 21104300 */  addu       $v0, $v0, $v1
/* 188F0C8 8008BB00 070002A6 */  sh         $v0, 0x7($s0)
/* 188F0CC 8008BB04 2000A28F */  lw         $v0, 0x20($sp)
/* 188F0D0 8008BB08 03000396 */  lhu        $v1, 0x3($s0)
/* 188F0D4 8008BB0C 40100200 */  sll        $v0, $v0, 1
/* 188F0D8 8008BB10 23186200 */  subu       $v1, $v1, $v0
/* 188F0DC 8008BB14 090003A6 */  sh         $v1, 0x9($s0)
/* 188F0E0 8008BB18 2400A28F */  lw         $v0, 0x24($sp)
/* 188F0E4 8008BB1C 05000396 */  lhu        $v1, 0x5($s0)
/* 188F0E8 8008BB20 40100200 */  sll        $v0, $v0, 1
/* 188F0EC 8008BB24 23186200 */  subu       $v1, $v1, $v0
/* 188F0F0 8008BB28 0B0003A6 */  sh         $v1, 0xB($s0)
/* 188F0F4 8008BB2C 2800A28F */  lw         $v0, 0x28($sp)
/* 188F0F8 8008BB30 07000396 */  lhu        $v1, 0x7($s0)
/* 188F0FC 8008BB34 40100200 */  sll        $v0, $v0, 1
/* 188F100 8008BB38 23186200 */  subu       $v1, $v1, $v0
/* 188F104 8008BB3C E92F0208 */  j          .Llevel_20_8008BFA4
/* 188F108 8008BB40 0D0003A6 */   sh        $v1, 0xD($s0)
.L8008BB44_:
/* 188F10C 8008BB44 03000296 */  lhu        $v0, 0x3($s0)
/* 188F110 8008BB48 01000392 */  lbu        $v1, 0x1($s0)
/* 188F114 8008BB4C 0F000496 */  lhu        $a0, 0xF($s0)
/* 188F118 8008BB50 13000596 */  lhu        $a1, 0x13($s0)
/* 188F11C 8008BB54 01006624 */  addiu      $a2, $v1, 0x1
/* 188F120 8008BB58 21104400 */  addu       $v0, $v0, $a0
/* 188F124 8008BB5C 030002A6 */  sh         $v0, 0x3($s0)
/* 188F128 8008BB60 05000296 */  lhu        $v0, 0x5($s0)
/* 188F12C 8008BB64 11000496 */  lhu        $a0, 0x11($s0)
/* 188F130 8008BB68 07000396 */  lhu        $v1, 0x7($s0)
/* 188F134 8008BB6C 010006A2 */  sb         $a2, 0x1($s0)
/* 188F138 8008BB70 21104400 */  addu       $v0, $v0, $a0
/* 188F13C 8008BB74 050002A6 */  sh         $v0, 0x5($s0)
/* 188F140 8008BB78 0C000292 */  lbu        $v0, 0xC($s0)
/* 188F144 8008BB7C 21186500 */  addu       $v1, $v1, $a1
/* 188F148 8008BB80 070003A6 */  sh         $v1, 0x7($s0)
/* 188F14C 8008BB84 02000392 */  lbu        $v1, 0x2($s0)
/* 188F150 8008BB88 F1FF4224 */  addiu      $v0, $v0, -0xF
/* 188F154 8008BB8C 03016010 */  beqz       $v1, .Llevel_20_8008BF9C
/* 188F158 8008BB90 0C0002A2 */   sb        $v0, 0xC($s0)
/* 188F15C 8008BB94 FF00C230 */  andi       $v0, $a2, 0xFF
/* 188F160 8008BB98 1100422C */  sltiu      $v0, $v0, 0x11
/* 188F164 8008BB9C FF004010 */  beqz       $v0, .Llevel_20_8008BF9C
/* 188F168 8008BBA0 00000000 */   nop
/* 188F16C 8008BBA4 EA2F0208 */  j          .Llevel_20_8008BFA8
/* 188F170 8008BBA8 20001026 */   addiu     $s0, $s0, 0x20
.L8008BBAC_:
/* 188F174 8008BBAC 09000486 */  lh         $a0, 0x9($s0)
/* 188F178 8008BBB0 03000286 */  lh         $v0, 0x3($s0)
/* 188F17C 8008BBB4 00000000 */  nop
/* 188F180 8008BBB8 23208200 */  subu       $a0, $a0, $v0
/* 188F184 8008BBBC 43200400 */  sra        $a0, $a0, 1
/* 188F188 8008BBC0 2000A4A7 */  sh         $a0, 0x20($sp)
/* 188F18C 8008BBC4 0B000286 */  lh         $v0, 0xB($s0)
/* 188F190 8008BBC8 05000386 */  lh         $v1, 0x5($s0)
/* 188F194 8008BBCC 00000000 */  nop
/* 188F198 8008BBD0 23104300 */  subu       $v0, $v0, $v1
/* 188F19C 8008BBD4 43100200 */  sra        $v0, $v0, 1
/* 188F1A0 8008BBD8 2200A2A7 */  sh         $v0, 0x22($sp)
/* 188F1A4 8008BBDC 0D000286 */  lh         $v0, 0xD($s0)
/* 188F1A8 8008BBE0 07000386 */  lh         $v1, 0x7($s0)
/* 188F1AC 8008BBE4 00000000 */  nop
/* 188F1B0 8008BBE8 23104300 */  subu       $v0, $v0, $v1
/* 188F1B4 8008BBEC 43100200 */  sra        $v0, $v0, 1
/* 188F1B8 8008BBF0 2400A2A7 */  sh         $v0, 0x24($sp)
/* 188F1BC 8008BBF4 03000296 */  lhu        $v0, 0x3($s0)
/* 188F1C0 8008BBF8 00000000 */  nop
/* 188F1C4 8008BBFC 21104400 */  addu       $v0, $v0, $a0
/* 188F1C8 8008BC00 030002A6 */  sh         $v0, 0x3($s0)
/* 188F1CC 8008BC04 05000296 */  lhu        $v0, 0x5($s0)
/* 188F1D0 8008BC08 2200A397 */  lhu        $v1, 0x22($sp)
/* 188F1D4 8008BC0C 00000000 */  nop
/* 188F1D8 8008BC10 21104300 */  addu       $v0, $v0, $v1
/* 188F1DC 8008BC14 050002A6 */  sh         $v0, 0x5($s0)
/* 188F1E0 8008BC18 07000296 */  lhu        $v0, 0x7($s0)
/* 188F1E4 8008BC1C 2400A397 */  lhu        $v1, 0x24($sp)
/* 188F1E8 8008BC20 00000000 */  nop
/* 188F1EC 8008BC24 21104300 */  addu       $v0, $v0, $v1
/* 188F1F0 8008BC28 070002A6 */  sh         $v0, 0x7($s0)
/* 188F1F4 8008BC2C 2200A297 */  lhu        $v0, 0x22($sp)
/* 188F1F8 8008BC30 2000A397 */  lhu        $v1, 0x20($sp)
/* 188F1FC 8008BC34 01004224 */  addiu      $v0, $v0, 0x1
/* 188F200 8008BC38 2200A2A7 */  sh         $v0, 0x22($sp)
/* 188F204 8008BC3C 09000296 */  lhu        $v0, 0x9($s0)
/* 188F208 8008BC40 00000000 */  nop
/* 188F20C 8008BC44 21104300 */  addu       $v0, $v0, $v1
/* 188F210 8008BC48 090002A6 */  sh         $v0, 0x9($s0)
/* 188F214 8008BC4C 0B000296 */  lhu        $v0, 0xB($s0)
/* 188F218 8008BC50 2200A397 */  lhu        $v1, 0x22($sp)
/* 188F21C 8008BC54 00000000 */  nop
/* 188F220 8008BC58 21104300 */  addu       $v0, $v0, $v1
/* 188F224 8008BC5C 0D000396 */  lhu        $v1, 0xD($s0)
/* 188F228 8008BC60 0B0002A6 */  sh         $v0, 0xB($s0)
/* 188F22C 8008BC64 01000292 */  lbu        $v0, 0x1($s0)
/* 188F230 8008BC68 2400A497 */  lhu        $a0, 0x24($sp)
/* 188F234 8008BC6C 01004224 */  addiu      $v0, $v0, 0x1
/* 188F238 8008BC70 21186400 */  addu       $v1, $v1, $a0
/* 188F23C 8008BC74 010002A2 */  sb         $v0, 0x1($s0)
/* 188F240 8008BC78 FF004230 */  andi       $v0, $v0, 0xFF
/* 188F244 8008BC7C 2000422C */  sltiu      $v0, $v0, 0x20
/* 188F248 8008BC80 C8004014 */  bnez       $v0, .Llevel_20_8008BFA4
/* 188F24C 8008BC84 0D0003A6 */   sh        $v1, 0xD($s0)
/* 188F250 8008BC88 E72F0208 */  j          .Llevel_20_8008BF9C
/* 188F254 8008BC8C 00000000 */   nop
.L8008BC90_:
/* 188F258 8008BC90 01000292 */  lbu        $v0, 0x1($s0)
/* 188F25C 8008BC94 00000000 */  nop
/* 188F260 8008BC98 01004224 */  addiu      $v0, $v0, 0x1
/* 188F264 8008BC9C 010002A2 */  sb         $v0, 0x1($s0)
/* 188F268 8008BCA0 FF004230 */  andi       $v0, $v0, 0xFF
/* 188F26C 8008BCA4 2800422C */  sltiu      $v0, $v0, 0x28
/* 188F270 8008BCA8 BC004010 */  beqz       $v0, .Llevel_20_8008BF9C
/* 188F274 8008BCAC 00000000 */   nop
/* 188F278 8008BCB0 02000292 */  lbu        $v0, 0x2($s0)
/* 188F27C 8008BCB4 00000000 */  nop
/* 188F280 8008BCB8 B8004010 */  beqz       $v0, .Llevel_20_8008BF9C
/* 188F284 8008BCBC 00000000 */   nop
/* 188F288 8008BCC0 03000296 */  lhu        $v0, 0x3($s0)
/* 188F28C 8008BCC4 0F000396 */  lhu        $v1, 0xF($s0)
/* 188F290 8008BCC8 11000496 */  lhu        $a0, 0x11($s0)
/* 188F294 8008BCCC 13000596 */  lhu        $a1, 0x13($s0)
/* 188F298 8008BCD0 21104300 */  addu       $v0, $v0, $v1
/* 188F29C 8008BCD4 030002A6 */  sh         $v0, 0x3($s0)
/* 188F2A0 8008BCD8 05000296 */  lhu        $v0, 0x5($s0)
/* 188F2A4 8008BCDC 07000396 */  lhu        $v1, 0x7($s0)
/* 188F2A8 8008BCE0 21104400 */  addu       $v0, $v0, $a0
/* 188F2AC 8008BCE4 21186500 */  addu       $v1, $v1, $a1
/* 188F2B0 8008BCE8 050002A6 */  sh         $v0, 0x5($s0)
/* 188F2B4 8008BCEC CB89010C */  jal        rand
/* 188F2B8 8008BCF0 070003A6 */   sh        $v1, 0x7($s0)
/* 188F2BC 8008BCF4 0F000396 */  lhu        $v1, 0xF($s0)
/* 188F2C0 8008BCF8 02004230 */  andi       $v0, $v0, 0x2
/* 188F2C4 8008BCFC FFFF6324 */  addiu      $v1, $v1, -0x1
/* 188F2C8 8008BD00 21186200 */  addu       $v1, $v1, $v0
/* 188F2CC 8008BD04 CB89010C */  jal        rand
/* 188F2D0 8008BD08 0F0003A6 */   sh        $v1, 0xF($s0)
/* 188F2D4 8008BD0C 11000396 */  lhu        $v1, 0x11($s0)
/* 188F2D8 8008BD10 02004230 */  andi       $v0, $v0, 0x2
/* 188F2DC 8008BD14 FFFF6324 */  addiu      $v1, $v1, -0x1
/* 188F2E0 8008BD18 21186200 */  addu       $v1, $v1, $v0
/* 188F2E4 8008BD1C CB89010C */  jal        rand
/* 188F2E8 8008BD20 110003A6 */   sh        $v1, 0x11($s0)
/* 188F2EC 8008BD24 13000396 */  lhu        $v1, 0x13($s0)
/* 188F2F0 8008BD28 02004230 */  andi       $v0, $v0, 0x2
/* 188F2F4 8008BD2C FFFF6324 */  addiu      $v1, $v1, -0x1
/* 188F2F8 8008BD30 21186200 */  addu       $v1, $v1, $v0
/* 188F2FC 8008BD34 130003A6 */  sh         $v1, 0x13($s0)
/* 188F300 8008BD38 001C0300 */  sll        $v1, $v1, 16
/* 188F304 8008BD3C 031C0300 */  sra        $v1, $v1, 16
/* 188F308 8008BD40 03006328 */  slti       $v1, $v1, 0x3
/* 188F30C 8008BD44 02006014 */  bnez       $v1, .Llevel_20_8008BD50
/* 188F310 8008BD48 02000224 */   addiu     $v0, $zero, 0x2
/* 188F314 8008BD4C 130002A6 */  sh         $v0, 0x13($s0)
.Llevel_20_8008BD50:
/* 188F318 8008BD50 13000286 */  lh         $v0, 0x13($s0)
/* 188F31C 8008BD54 00000000 */  nop
/* 188F320 8008BD58 FCFF4228 */  slti       $v0, $v0, -0x4
/* 188F324 8008BD5C 02004010 */  beqz       $v0, .Llevel_20_8008BD68
/* 188F328 8008BD60 FCFF0224 */   addiu     $v0, $zero, -0x4
/* 188F32C 8008BD64 130002A6 */  sh         $v0, 0x13($s0)
.Llevel_20_8008BD68:
/* 188F330 8008BD68 0B000292 */  lbu        $v0, 0xB($s0)
/* 188F334 8008BD6C 0D000392 */  lbu        $v1, 0xD($s0)
/* 188F338 8008BD70 FEFF4224 */  addiu      $v0, $v0, -0x2
/* 188F33C 8008BD74 0B0002A2 */  sb         $v0, 0xB($s0)
/* 188F340 8008BD78 0C000292 */  lbu        $v0, 0xC($s0)
/* 188F344 8008BD7C FFFF6324 */  addiu      $v1, $v1, -0x1
/* 188F348 8008BD80 0D0003A2 */  sb         $v1, 0xD($s0)
/* 188F34C 8008BD84 FEFF4224 */  addiu      $v0, $v0, -0x2
/* 188F350 8008BD88 E92F0208 */  j          .Llevel_20_8008BFA4
/* 188F354 8008BD8C 0C0002A2 */   sb        $v0, 0xC($s0)
.L8008BD90_:
/* 188F358 8008BD90 09000486 */  lh         $a0, 0x9($s0)
/* 188F35C 8008BD94 03000286 */  lh         $v0, 0x3($s0)
/* 188F360 8008BD98 00000000 */  nop
/* 188F364 8008BD9C 23208200 */  subu       $a0, $a0, $v0
/* 188F368 8008BDA0 43200400 */  sra        $a0, $a0, 1
/* 188F36C 8008BDA4 2000A4A7 */  sh         $a0, 0x20($sp)
/* 188F370 8008BDA8 0B000286 */  lh         $v0, 0xB($s0)
/* 188F374 8008BDAC 05000386 */  lh         $v1, 0x5($s0)
/* 188F378 8008BDB0 00000000 */  nop
/* 188F37C 8008BDB4 23104300 */  subu       $v0, $v0, $v1
/* 188F380 8008BDB8 43100200 */  sra        $v0, $v0, 1
/* 188F384 8008BDBC 2200A2A7 */  sh         $v0, 0x22($sp)
/* 188F388 8008BDC0 0D000286 */  lh         $v0, 0xD($s0)
/* 188F38C 8008BDC4 07000386 */  lh         $v1, 0x7($s0)
/* 188F390 8008BDC8 00000000 */  nop
/* 188F394 8008BDCC 23104300 */  subu       $v0, $v0, $v1
/* 188F398 8008BDD0 43100200 */  sra        $v0, $v0, 1
/* 188F39C 8008BDD4 2400A2A7 */  sh         $v0, 0x24($sp)
/* 188F3A0 8008BDD8 03000296 */  lhu        $v0, 0x3($s0)
/* 188F3A4 8008BDDC 00000000 */  nop
/* 188F3A8 8008BDE0 21104400 */  addu       $v0, $v0, $a0
/* 188F3AC 8008BDE4 030002A6 */  sh         $v0, 0x3($s0)
/* 188F3B0 8008BDE8 05000296 */  lhu        $v0, 0x5($s0)
/* 188F3B4 8008BDEC 2200A397 */  lhu        $v1, 0x22($sp)
/* 188F3B8 8008BDF0 00000000 */  nop
/* 188F3BC 8008BDF4 21104300 */  addu       $v0, $v0, $v1
/* 188F3C0 8008BDF8 050002A6 */  sh         $v0, 0x5($s0)
/* 188F3C4 8008BDFC 07000296 */  lhu        $v0, 0x7($s0)
/* 188F3C8 8008BE00 2400A397 */  lhu        $v1, 0x24($sp)
/* 188F3CC 8008BE04 00000000 */  nop
/* 188F3D0 8008BE08 21104300 */  addu       $v0, $v0, $v1
/* 188F3D4 8008BE0C 070002A6 */  sh         $v0, 0x7($s0)
/* 188F3D8 8008BE10 09000296 */  lhu        $v0, 0x9($s0)
/* 188F3DC 8008BE14 2000A397 */  lhu        $v1, 0x20($sp)
/* 188F3E0 8008BE18 00000000 */  nop
/* 188F3E4 8008BE1C 21104300 */  addu       $v0, $v0, $v1
/* 188F3E8 8008BE20 090002A6 */  sh         $v0, 0x9($s0)
/* 188F3EC 8008BE24 0B000296 */  lhu        $v0, 0xB($s0)
/* 188F3F0 8008BE28 2200A397 */  lhu        $v1, 0x22($sp)
/* 188F3F4 8008BE2C 00000000 */  nop
/* 188F3F8 8008BE30 21104300 */  addu       $v0, $v0, $v1
/* 188F3FC 8008BE34 0D000396 */  lhu        $v1, 0xD($s0)
/* 188F400 8008BE38 0B0002A6 */  sh         $v0, 0xB($s0)
/* 188F404 8008BE3C 01000292 */  lbu        $v0, 0x1($s0)
/* 188F408 8008BE40 2400A497 */  lhu        $a0, 0x24($sp)
/* 188F40C 8008BE44 01004224 */  addiu      $v0, $v0, 0x1
/* 188F410 8008BE48 21186400 */  addu       $v1, $v1, $a0
/* 188F414 8008BE4C 010002A2 */  sb         $v0, 0x1($s0)
/* 188F418 8008BE50 FF004230 */  andi       $v0, $v0, 0xFF
/* 188F41C 8008BE54 1800422C */  sltiu      $v0, $v0, 0x18
/* 188F420 8008BE58 50004010 */  beqz       $v0, .Llevel_20_8008BF9C
/* 188F424 8008BE5C 0D0003A6 */   sh        $v1, 0xD($s0)
/* 188F428 8008BE60 02000292 */  lbu        $v0, 0x2($s0)
/* 188F42C 8008BE64 00000000 */  nop
/* 188F430 8008BE68 4C004010 */  beqz       $v0, .Llevel_20_8008BF9C
/* 188F434 8008BE6C 00000000 */   nop
/* 188F438 8008BE70 0F000292 */  lbu        $v0, 0xF($s0)
/* 188F43C 8008BE74 13000392 */  lbu        $v1, 0x13($s0)
/* 188F440 8008BE78 FDFF4224 */  addiu      $v0, $v0, -0x3
/* 188F444 8008BE7C 0F0002A2 */  sb         $v0, 0xF($s0)
/* 188F448 8008BE80 10000292 */  lbu        $v0, 0x10($s0)
/* 188F44C 8008BE84 FDFF6324 */  addiu      $v1, $v1, -0x3
/* 188F450 8008BE88 130003A2 */  sb         $v1, 0x13($s0)
/* 188F454 8008BE8C FCFF4224 */  addiu      $v0, $v0, -0x4
/* 188F458 8008BE90 100002A2 */  sb         $v0, 0x10($s0)
/* 188F45C 8008BE94 14000292 */  lbu        $v0, 0x14($s0)
/* 188F460 8008BE98 15000392 */  lbu        $v1, 0x15($s0)
/* 188F464 8008BE9C FCFF4224 */  addiu      $v0, $v0, -0x4
/* 188F468 8008BEA0 140002A2 */  sb         $v0, 0x14($s0)
/* 188F46C 8008BEA4 0600622C */  sltiu      $v0, $v1, 0x6
/* 188F470 8008BEA8 3E004014 */  bnez       $v0, .Llevel_20_8008BFA4
/* 188F474 8008BEAC FAFF6224 */   addiu     $v0, $v1, -0x6
/* 188F478 8008BEB0 E92F0208 */  j          .Llevel_20_8008BFA4
/* 188F47C 8008BEB4 150002A2 */   sb        $v0, 0x15($s0)
.L8008BEB8_:
/* 188F480 8008BEB8 09000496 */  lhu        $a0, 0x9($s0)
/* 188F484 8008BEBC 03000296 */  lhu        $v0, 0x3($s0)
/* 188F488 8008BEC0 00000000 */  nop
/* 188F48C 8008BEC4 23208200 */  subu       $a0, $a0, $v0
/* 188F490 8008BEC8 2000A4A7 */  sh         $a0, 0x20($sp)
/* 188F494 8008BECC 0B000296 */  lhu        $v0, 0xB($s0)
/* 188F498 8008BED0 05000396 */  lhu        $v1, 0x5($s0)
/* 188F49C 8008BED4 00000000 */  nop
/* 188F4A0 8008BED8 23104300 */  subu       $v0, $v0, $v1
/* 188F4A4 8008BEDC 2200A2A7 */  sh         $v0, 0x22($sp)
/* 188F4A8 8008BEE0 0D000296 */  lhu        $v0, 0xD($s0)
/* 188F4AC 8008BEE4 07000396 */  lhu        $v1, 0x7($s0)
/* 188F4B0 8008BEE8 00000000 */  nop
/* 188F4B4 8008BEEC 23104300 */  subu       $v0, $v0, $v1
/* 188F4B8 8008BEF0 2400A2A7 */  sh         $v0, 0x24($sp)
/* 188F4BC 8008BEF4 03000296 */  lhu        $v0, 0x3($s0)
/* 188F4C0 8008BEF8 00000000 */  nop
/* 188F4C4 8008BEFC 21104400 */  addu       $v0, $v0, $a0
/* 188F4C8 8008BF00 030002A6 */  sh         $v0, 0x3($s0)
/* 188F4CC 8008BF04 05000296 */  lhu        $v0, 0x5($s0)
/* 188F4D0 8008BF08 2200A397 */  lhu        $v1, 0x22($sp)
/* 188F4D4 8008BF0C 00000000 */  nop
/* 188F4D8 8008BF10 21104300 */  addu       $v0, $v0, $v1
/* 188F4DC 8008BF14 050002A6 */  sh         $v0, 0x5($s0)
/* 188F4E0 8008BF18 07000296 */  lhu        $v0, 0x7($s0)
/* 188F4E4 8008BF1C 2400A397 */  lhu        $v1, 0x24($sp)
/* 188F4E8 8008BF20 00000000 */  nop
/* 188F4EC 8008BF24 21104300 */  addu       $v0, $v0, $v1
/* 188F4F0 8008BF28 070002A6 */  sh         $v0, 0x7($s0)
/* 188F4F4 8008BF2C 2400A297 */  lhu        $v0, 0x24($sp)
/* 188F4F8 8008BF30 2000A397 */  lhu        $v1, 0x20($sp)
/* 188F4FC 8008BF34 FFFF4224 */  addiu      $v0, $v0, -0x1
/* 188F500 8008BF38 2400A2A7 */  sh         $v0, 0x24($sp)
/* 188F504 8008BF3C 09000296 */  lhu        $v0, 0x9($s0)
/* 188F508 8008BF40 00000000 */  nop
/* 188F50C 8008BF44 21104300 */  addu       $v0, $v0, $v1
/* 188F510 8008BF48 090002A6 */  sh         $v0, 0x9($s0)
/* 188F514 8008BF4C 0B000296 */  lhu        $v0, 0xB($s0)
/* 188F518 8008BF50 2200A397 */  lhu        $v1, 0x22($sp)
/* 188F51C 8008BF54 00000000 */  nop
/* 188F520 8008BF58 21104300 */  addu       $v0, $v0, $v1
/* 188F524 8008BF5C 0D000396 */  lhu        $v1, 0xD($s0)
/* 188F528 8008BF60 0B0002A6 */  sh         $v0, 0xB($s0)
/* 188F52C 8008BF64 01000292 */  lbu        $v0, 0x1($s0)
/* 188F530 8008BF68 2400A497 */  lhu        $a0, 0x24($sp)
/* 188F534 8008BF6C 01004224 */  addiu      $v0, $v0, 0x1
/* 188F538 8008BF70 21186400 */  addu       $v1, $v1, $a0
/* 188F53C 8008BF74 010002A2 */  sb         $v0, 0x1($s0)
/* 188F540 8008BF78 FF004230 */  andi       $v0, $v0, 0xFF
/* 188F544 8008BF7C 2000422C */  sltiu      $v0, $v0, 0x20
/* 188F548 8008BF80 0D0003A6 */  sh         $v1, 0xD($s0)
.Llevel_20_8008BF84:
/* 188F54C 8008BF84 05004010 */  beqz       $v0, .Llevel_20_8008BF9C
/* 188F550 8008BF88 00000000 */   nop
.Llevel_20_8008BF8C:
/* 188F554 8008BF8C 02000292 */  lbu        $v0, 0x2($s0)
/* 188F558 8008BF90 00000000 */  nop
/* 188F55C 8008BF94 03004014 */  bnez       $v0, .Llevel_20_8008BFA4
/* 188F560 8008BF98 00000000 */   nop
.Llevel_20_8008BF9C:
/* 188F564 8008BF9C 824D010C */  jal        func_80053608
/* 188F568 8008BFA0 21204002 */   addu      $a0, $s2, $zero
.Llevel_20_8008BFA4:
/* 188F56C 8008BFA4 20001026 */  addiu      $s0, $s0, 0x20
.Llevel_20_8008BFA8:
/* 188F570 8008BFA8 2000D626 */  addiu      $s6, $s6, 0x20
/* 188F574 8008BFAC 20007326 */  addiu      $s3, $s3, 0x20
/* 188F578 8008BFB0 00000392 */  lbu        $v1, 0x0($s0)
/* 188F57C 8008BFB4 FF000224 */  addiu      $v0, $zero, 0xFF
/* 188F580 8008BFB8 B0FB6214 */  bne        $v1, $v0, .Llevel_20_8008AE7C
/* 188F584 8008BFBC 20005226 */   addiu     $s2, $s2, 0x20
.Llevel_20_8008BFC0:
/* 188F588 8008BFC0 6000BF8F */  lw         $ra, 0x60($sp)
/* 188F58C 8008BFC4 5C00B78F */  lw         $s7, 0x5C($sp)
/* 188F590 8008BFC8 5800B68F */  lw         $s6, 0x58($sp)
/* 188F594 8008BFCC 5400B58F */  lw         $s5, 0x54($sp)
/* 188F598 8008BFD0 5000B48F */  lw         $s4, 0x50($sp)
/* 188F59C 8008BFD4 4C00B38F */  lw         $s3, 0x4C($sp)
/* 188F5A0 8008BFD8 4800B28F */  lw         $s2, 0x48($sp)
/* 188F5A4 8008BFDC 4400B18F */  lw         $s1, 0x44($sp)
/* 188F5A8 8008BFE0 4000B08F */  lw         $s0, 0x40($sp)
/* 188F5AC 8008BFE4 6800BD27 */  addiu      $sp, $sp, 0x68
/* 188F5B0 8008BFE8 0800E003 */  jr         $ra
/* 188F5B4 8008BFEC 00000000 */   nop
.size func_level_20_8008AE28, . - func_level_20_8008AE28
